### ISSUE TITLE
Remove `.localized` in `focus_area.html`

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10009]
## Description
Try to remove all uses of `.localized` from this template. `.localized` is not a cached property and can trigger one or more database queries. This is especially problematic when used in a loop, where this is triggered for each item in the iterable. 

Instead, try to move this logic to the page’s `get_context` or other method to make sure that the template already receives the items of the correct locale. 

Pretty much the same thing applies for `.specific`.

See the epic for some more context: https://github.com/mozilla/foundation.mozilla.org/issues/9882

## Acceptance criteria 
* [ ] Number of `.localized` usages in this template is reduced.
* [ ] The template renders the same information and links to the same places as before.

## Notes
Usages of `.localized` in the template:

```
network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/focus_area.html
11:            <a href="{{ area.page.localized.url }}" aria-label="{% blocktrans with name=area.name %}Learn more about: {{ name }}{% endblocktrans %}">{% trans "Learn more →" %}</a>

```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-102)

**Comment by data-sync-user** [comment]
➤ diego commented:

Simon Acosta Torres 

It seems that this template focus_area.html was modified and the whole <a href> tag was removed so .localized is not anymore in the template.

  * Link  ( https://github.com/MozillaFoundation/foundation.mozilla.org/blob/961cf1679630d343f0282136a14fb7c1e0f59386/network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/focus_area.html#L7 )for reference.

We can safely abandond this ticket.
