### ISSUE TITLE
[PNI] Show featured CTA when navigating from landing to category page

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10046]
## Description

This is a follow up to #9853. 

When navigating from the PNI landing page to a category page (the category has the "show CTA" flag set to "True") the CTA is not displayed in the product grid. 

## Steps to reproduce

1. Create a Buyer's Guide CTA: https://foundation.mofostaging.net/cms/snippets/wagtailpages/buyersguidecalltoaction/
2. Set the created CTA as the featured CTA on the PNI landing page: https://foundation.mofostaging.net/cms/pages/1444/edit/
3. Set the show CTA flag on a product category to "True" (checked): https://foundation.mofostaging.net/cms/snippets/wagtailpages/buyersguideproductcategory/edit/2/
4. Visit the PNI landing page: https://foundation.mofostaging.net/en/privacynotincluded/
5. Click the menu entry for the category where you have set "show CTA" to "True" above, e.g. "Smart Home". 
6. See the product grid update, but the CTA does not show.

## Acceptance criteria

Given that a Buyer's Guide CTA exists and that CTA is set as the featured CTA on the PNI landing page:

- [x] As a page visitor, when I load the PNI landing page the featured CTA is not displayed inside the product grid.
- [x] As a page visitor, when I load the PNI landing page and then click the menu entry for a category I see the product grid update and the CTA is displayed inside the product grid. 
- [x] As a page visitor, when I navigate to a new category page that has the CTA flag set to false, the CTA gets cleared.
- [x] As a page visitor, when I navigate to a new category page that has the CTA flag set to true, the CTA remains visible.

**Comment by kristinashu** [comment]
@mtdenton flagging that Kevin has recently also asked for this feature so that we can have a donation CTA on PNI

**Comment by Gbaldassano** [comment]
@mtdenton Kevin asked if it would it be possible to have this tested and live before the mental health app marketing promotion begins on May 2nd? Since our current sprint ends 4/28, I doubt that's possible. 

Has this been groomed/do we have a rough sizing for this?

**Comment by Gbaldassano** [comment]
@mmmavis can we incorporate this into support duty for this Sprint? Stakeholder has been asking for an update and we're hoping this ticket is relatively straight forward (and not requiring a Spike)?

**Comment by kristinashu** [comment]
I've added the CTA to https://foundation.mofostaging.net/en/privacynotincluded/categories/mental-health-apps/ so you should be able to see the bug there if you navigate to the homepage and then back to Mental Health Apps.

**Comment by mmmavis** [comment]
@Gbaldassano @kristinashu thanks for flagging it. I will get to this ticket this sprint. As for estimates, any PNI bugs fixes are hard to give estimates due to the current state of the PNI codebase but I'm hoping it is a 2 for this ticket.

**Comment by mmmavis** [comment]
Hi @kristinashu , can you help QA this on staging? https://foundation.mofostaging.net/en/privacynotincluded/ Thanks!

**Comment by kristinashu** [comment]
Looks good! I've checked off the ACs.

**Comment by danielfmiranda** [comment]
This has been pushed to prod. Closing!
