### ISSUE TITLE
[PNI] Related articles on product pages not synchronized on translated pages

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#10048]
Related articles have been added to existing translated products, but syncing translations doesn’t add the related articles to the translated pages.

Notice the missing articles on the right:
English: https://foundation.mozilla.org/en/privacynotincluded/whatsapp/
French: https://foundation.mozilla.org/fr/privacynotincluded/whatsapp/

<img width="296" alt="Capture d’écran 2023-01-24 à 11 55 25" src="https://user-images.githubusercontent.com/1294206/214273815-726a5d5e-7838-44d0-b2e5-0d5c556a19b1.png">

### Dev Tasks
 - [ ] Add related articles to synchronized fields
 - [ ] Render localized version of related article
 
### Acceptance Criteria
 - [ ] Related Articles from the English version of a product page are shown on a translation of the same page.
 - [ ] Related Article link text is in the locale of the page being shown.

**Comment by mtdenton** [comment]
@TheoChevalier Looking to get this into the next sprint. Thanks for the bug report!

**Comment by danielfmiranda** [comment]
Hi @TheoChevalier ! 

This update is now on staging and ready for QA. Can you please take a look whenever you find a free moment? 

Thanks!

**Comment by TheoChevalier** [comment]
Many thanks @danielfmiranda, I was able to verify it on staging here! https://foundation.mofostaging.net/fr/privacynotincluded/amazon-echo-dot/
Would it be possible to ping me when this hits prod so I can sync the relevant product pages?

I’ve also noticed we have a similar issue on category pages, so I’ll file another ticket for it.

Thanks!

(Assuming this is when tickets get closed, please reopen if I’m mistaken)

**Comment by danielfmiranda** [comment]
Thanks @TheoChevalier! 
I will be sure to reach out as soon as this hits prod. Also, thanks for creating that ticket!

I will re-open this ticket and close it once it reaches prod.
