### ISSUE TITLE
[PNI] Consider hiding speech bubble and creep-o-meter if products are sorted alphabetically

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10056]
Speech bubble and creep-o-meter change their content based on the creepiness score of the products visible on screen. This works great when products are sorted by creepiness. However, when products are sorted in alphabetically order, creepiness score can jump up and down product by product. This can make speech bubble and creep-o-meter change quite abruptly as users scroll. They don't always show the correct indicator either. (Think about a scenario where one super creepy product is on the same row of not creepy products. What should the speech bubble say?) We should consider hiding them if products are sorted alphabetically so they don't look wonky.

### Production/Desktop Screen Recording
https://user-images.githubusercontent.com/2896608/214915588-94a42f7d-47bb-4417-ae46-5bf8f8557b45.mov

### Mobile Screen Recording
**Note: Speech bubble and creep-o-meter currently don't update on smaller screens (bug #9942). This recording is taken locally from my machine with a potential fix to that.**

https://user-images.githubusercontent.com/2896608/214917727-cc2911ea-6791-4927-a859-d2423d498ee6.mov

**Comment by simont-cr** [comment]
Closed per 2024 ticket purge.
