### ISSUE TITLE
[PNI] Search - sorting dropdown does not reflect the order products are in

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10055]
### Describe the bug
PNI Search - sorting dropdown does not reflect the order products are in

### To Reproduce

1. Go to https://foundation.mozilla.org/en/privacynotincluded
1. Verify products are listed in the order of 'Creepiness: Least - Most' (Tips: you can use dev tool inspector to inspect the `data-creepiness` value of `.product-box`) 
![](https://user-images.githubusercontent.com/2896608/214911016-5a26b23a-1e89-4241-98bf-999e72326b1a.png)
1. Verify sorting dropdown shows 'Creepiness: Least - Most' 
1. Enter a search term. e.g., fitbit
1. Search results are ordered in 'Alphabetical' order while sorting dropdown displays 'Creepiness: Least - Most'

### Expected behavior
Sorting dropdown should correctly reflect the order of the products shown on page.
Need to check with design team what order the products should be in for search results.

### Screenshots
For demo purpose I have added a red text label to show creepiness score of each product.

https://user-images.githubusercontent.com/2896608/214909252-d8605c10-7296-4236-ac0e-115606fc2a2d.mov

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-115)

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

We’ve learned that PNI tickets often ended up taking a lot longer time than anticipated to complete. It’s safe to overestimate the work needed for this ticket than underestimated 😅

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

For this ticket, we should also add Playwright tests for the expected behaviours.
