### ISSUE TITLE
Make heading anchors accessible

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10052]
## Description 
We have two locations where we make headings in the page content available as anchor link targets (we can link to them with an element identifier like `#my-heading-id` in the URL). 

One location is the image teaser block, the other is the richtext filer customization in https://github.com/mozilla/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailcustomization/templatetags/wagtailcustom_tags.py#L33 that adds an anchor element to the headings.

These anchor elements look something like this: `<h2>Mozone<a href="#mozone"></a></h2>`. 

There are two issue with this:

1. The anchor element appears in the tabbing order and is being focused but has no content. This is not good for accessibility/screen reader users
1. The anchors elements can not be discovered. Staff need to know these anchors exist and use the Browser dev tools to pull the relevant ID out of the markup and add that to the URL manually. 

Goals for this ticket:

1. Ensure that the anchor had sensible content for screen reader users
1. Make it easier for users to get the full URL to a heading, e.g. by clicking on it.

See also:

* An example for discoverable headings can be found on MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#all_headings
* This article contains some accessibility considerations: https://amberwilson.co.uk/blog/are-your-anchor-links-accessible/

The solution used on MDN wraps the whole heading content in an anchor. This makes the heading content also the screen reader content. `<h2 id="#mozone"><a href="#mozone">Mozone</a></h2>`. This might have some styling implications due to styles that are added automatically to links and heading. 

We still need to figure out what the heading anchor should look like:

* Should the heading be underlined on hover? 
* Should the an indicator show up on hover?
* E.g. is the `#` after the heading a good indicator? 

Related issues: #9902 

## Acceptance criteria
* [ ] As a screen reader user, when I tab to a heading with an anchor link, the link is announced with sensible content. 

Follow-up: make another ticket for the "discoverable" portion of this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-114)

**Comment by tbrlpld** [comment]
cc @kristinashu Do you have input regarding the open questions above?

**Comment by tbrlpld** [comment]
cc @mmmavis

**Comment by kristinashu** [comment]
Thank you for opening this Tibor! I need to think about it, look into it more, and perhaps discus with the team. I know that staff use these links but I'm just not sure how much our average user (external audience) would usesthese anchors.

Note that we have something to this on our style guide e.g. https://foundation.mozilla.org/style-guide/#site-palette where hovering over the heading reveals the `#` anchor link, and in this use case it is very handy.

**Comment by tbrlpld** [comment]
Thanks @kristinashu. The pattern in the style guide is very similar to the accessible version out lined in https://amberwilson.co.uk/blog/are-your-anchor-links-accessible/#accessibility-check. If if that is acceptable from a design perspective, we could use that.

**Comment by kristinashu** [comment]
I talked to the design team about this and here is what we think:
- For visitors, we are hesitant to make all our headings anchor links since this could become distracting and even cumbersome. 
- For editors, we would still like to make the anchor links easier to use add in the cms. Does Wagtail offer something simpler (I couldn't find anything - anchors do appear as an option but editors need to copy the heading and then replace the spaces with `-`)? We feel the ideal flow for editors would be to do something like add "Bookmark" in Google Docs does. 
<img width="235" alt="image" src="https://user-images.githubusercontent.com/1068783/217104423-b38c91f8-5a50-4f5f-8f89-08e2ef80740a.png">

  Perhaps in those instances, the link icon could be visible like in the example above 
<img width="214" alt="image" src="https://user-images.githubusercontent.com/1068783/217104039-ea93fc3c-4d62-482d-a97c-eec8b15da1ab.png">

**Comment by mtdenton** [comment]
Sorry, this one flew right under my radar.

What's the issue with using something like:

`<h2 id="link-target">Header Text</h2>`

and then linking to:

`https://www.example.com/page#link-target`

With a field in the CMS that allows the editor to set the `id`?

Example: https://www.techradar.com/news/bing-is-microsofts-chance-to-win-the-search-battle-if-bing-doesnt-screw-it-up#better-search-for-everybody

Historically, that's been accessible and is a pattern in a lot of other CMS. The other thing you see often is the HTML5 route of wrapping that content in a `<section id="link-target">`

Apologies in advance if I'm misunderstanding the issue.

**Comment by mtdenton** [comment]
We need to determine how to adjust the functionality already built by Pomax to grab these headers and assign an id, the above won't apply because of the open-ended Rich Text functionality won't have the inbuilt capabilities of, say, a header block.
