### ISSUE TITLE
Redirect deprecated category links into topic links

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#10060]
We'd like to automatically send users who enter through these old `/category/` links to their `/topic/` equivalent. We also need to maintain l10n functionality for routing users to the correct language.

For instance:
`https://foundation.mozilla.org/blog/category/moz-news-beat/`

should route to

`https://foundation.mozilla.org/en/blog/topic/moz-news-beat/`

if the user should go to an `/en/` view

## Dev notes

@tbrlpld identified that the work would need to happen in these places:
https://github.com/mozilla/foundation.mozilla.org/blob/e03f22a51ae3bdc8faa75c7c9140030d25f429cf/network-api/networkapi/wagtailpages/pagemodels/blog/blog_index.py#L91
https://github.com/mozilla/foundation.mozilla.org/blob/e03f22a51ae3bdc8faa75c7c9140030d25f429cf/network-api/networkapi/wagtailpages/pagemodels/blog/blog_index.py#L348-L361

## Acceptance Criteria

- [x] As a site visitor, when I open a URL to filter for blog "categories"  I should be redirected to the equivalent topic filter URL:
  - From: `https://foundation.mozilla.org/en/blog/category/moz-news-beat/`   
  - To `https://foundation.mozilla.org/en/blog/topic/moz-news-beat/`.
- [x] As a site visitor, when I open a blog category URL without a language code in it, I am redirected to the blog topic URL on the default locale: 
  - From `https://foundation.mozilla.org/blog/category/moz-news-beat/` 
  - To `https://foundation.mozilla.org/en/blog/topic/moz-news-beat/`
- [x] As a site visitor, when I have visited the foundation site and changed my locale to something other than the default (e.g. `de`), redirects from URLs without language code will redirect to URLs for my previously selected locale. 
  - From `https://foundation.mozilla.org/blog/category/moz-news-beat/` 
  - To `https://foundation.mozilla.org/de/blog/topic/moz-news-beat/`
- [x] If the origin URL contains a language code, the redirect target should keep the same locale as the origin. 
- [x] This should be a permanent redirect.

**Comment by tbrlpld** [comment]
@mtdenton Was it intentional that the origin URL does not contain the language code? 

`https://foundation.mozilla.org/blog/category/moz-news-beat/`
instead of 
`https://foundation.mozilla.org/en/blog/category/moz-news-beat/`

**Comment by cdanfon** [comment]
This is likely to be fixed by the redirects issue Kev has been working on

**Comment by tbrlpld** [comment]
@cdanfon I don't think the redirects issue @kevinhowbrook is working on has anything to do with this one. For context, @kevinhowbrook is working on what happens when page instances are moved or have their slug changed through the Wagtail admin. 

This issue here is dealing with additional "routes" on a page. These "routes" are defined in code and can not be changed in the admin. Also, there is no "page" in the Wagtail page tree for these "routes".

**Comment by danielfmiranda** [comment]
Hi @mmmavis!

When you have a free moment, I was wondering if you could please do the staging QA for this ticket?

I would visit these links, and if they redirect to the appropriate /topic/ URL then we are good to go.

- https://foundation.mofostaging.net/en/blog/category/advocacy/
- https://foundation.mofostaging.net/fr/blog/category/advocacy/
- https://foundation.mofostaging.net/en/blog/category/advocacy/?test=test
- https://foundation.mofostaging.net/fr/blog/category/advocacy/?test=test

Thanks!

**Comment by mmmavis** [comment]
@danielfmiranda everything works as expected! Thanks for the awesome work and instructions on how to QA!
