### ISSUE TITLE
Fix T001 template linting errors

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10095]
## Description

```
T001	Variables should be wrapped in a single whitespace. Ex: {{ this }}
```

This should be possible with the following replacement:

```
sed -i.bak "s|{{\([A-z0-9._]*\)}}|{{ \1 }}|g" **/*.html
```

Delete the `.bak` backup files afterwards.

See: https://djlint.com/docs/linter/

**Comment by danielfmiranda** [comment]
Hi @tbrlpld this PR has now been merged into main and is ready for testing if you would like to give the linter a try. 

Thanks!

**Comment by tbrlpld** [comment]
Thanks for fixing this @danielfmiranda. 

Testing this I notice that I messed up the CI apparently. The lint checks are all passing silently 🤦‍♂️

**Comment by tbrlpld** [comment]
My PR to activate linting in CI is merged too. So I think we are good to go on this.
