### ISSUE TITLE
Fix template linting errors

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10094]
## Description
This is a follow up to #9034. 

As part of #9034, template linting was set up and activate in CI. 

But, due to the high number of issue (1700+) it was not possible to fix all those issues in as part of that ticket and we probably will need an epic to track that work. 

When the template linting was activated a list of per-file error ignores was added. That means the for every template, the existing errors are ignored. This was done to make it possible to activate the linting in CI without it failing because of the 1700+ errors. 

While we are ignoring a big chunk of errors due to the per-file ignores, there is still value in having the linting running in CI. It does prevent new error types to be introduced into each file and also makes sure that new files don't violate any linting rule. 

The purpose of this epic is to fix all the existing linting errors that are currently ignored on a per-file basis (see `pyproject.toml` for the list). 
There are basically two ways to address these errors:

* Fix per file. Remove a file from the per-file ignore list, run the linter to see all errors, fix all errors. 
* Fix per error type. This will not be possible for all error types, but for some. If you find a clever way (e.g. regex) to fix a specific type of error, remove the error code from the the `pyproject.toml` and then run you fix / regex-replace over all template files. 

This epic is related to but a bit different from #9875. #9875 deals with HTML validation error on the rendered pages. This epic is dealing with template linting. They are connected, because the final HTML is rendered from the templates, but also different, because certain HTML errors can not be checked in templates and vice versa. If we discover certain recurring HTML errors in #9875 that are not covered by the template linting rules so far, we can try to create a custom `djlint` rule that would avoid that error from creeping up in the future. 

See also: 

* Linter rules documentation: https://djlint.com/docs/linter/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-121)

**Comment by mtdenton** [comment]
Via @jhonatan-lopes let's see if `djlint` will work for this, if not, we need to find an alternative. See #10947

**Comment by mtdenton** [comment]
Very much need to see if we can split this, so we can assign priority

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Jhonatan Lopes This was an EPIC as you can see on https://app.zenhub.com/workspaces/mofo-web-platforms-team-585335eab729771d0736378d/issues/gh/mozillafoundation/foundation.mozilla.org/10094 ( https://app.zenhub.com/workspaces/mofo-web-platforms-team-585335eab729771d0736378d/issues/gh/mozillafoundation/foundation.mozilla.org/10094|smart-link )  but the only ticket included as part of the EPIC is closed already. Would you say this should be closed as well or should we keep open and add more tickets?

**Comment by jhonatan-lopes** [comment]
Hi Simon! This is an epic to hold all the work that should go into fixing those errors. They are still there but the issues haven't been created yet. There's two things that need to happen:
* First, we need to fix all linting issues in here: https://github.com/MozillaFoundation/foundation.mozilla.org/blob/fcb5f0327e9252fbb9e22230f94394b548e7dd06/pyproject.toml#L16-L233
* Second, we need to add `djlint` (or any other django linter) to make sure that those errors do not happen again.

It might be that more errors were introduced to that list while `djlint` was disabled (it is currently disabled), so there's still that as well.
