### ISSUE TITLE
Use consistent string formatting in JS

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10092]
## Description 
Based on https://github.com/mozilla/foundation.mozilla.org/pull/10053#discussion_r1093784778

The code base uses a mix of backticks <code>`</code> and quotes <code>"</code> for string formatting in JS. 

It would be nice to find a consistent standard and have the linting piont out when we are inconsistent. 

Which one we go with should be decided by the team. 

## Acceptance criteria
* [ ] The code base uses consistent string formatting. 
* [ ] Running `inv lint-js` shows errors when we use inconsistent formatting.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-120)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Tyler Denton A good candidate for removal. While we know there are inconsistencies in the codebase, it might be better to re-evaluate the full code on a later time.
