### ISSUE TITLE
Make Accordion block on Article pages the same width as the Content block

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#10102]
We have a request from Eeva to make Accordions narrower on Article pages so they are the same width as the Content block so that she can use headings above the accordions without it looking broken. 

Screen cap showing the issue on Article and Publication pages:

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/1068783/216437744-6678414c-0051-49a1-a146-9a0531f60cb4.png">

Screen cap showing how Accordions are the same width as Paragraph block on other page types:
<img width="922" alt="image" src="https://user-images.githubusercontent.com/1068783/216437188-6f30d040-95ed-4965-8e51-69ffe55f1442.png">

## AC
- [x] As a visitor, the Accordion block is the same narrower width as the Content block on Article pages

@mtdenton @cdanfon does this need further grooming?

**Comment by cdanfon** [comment]
Hey @kristinashu are we meant to decrease the with of the _Accordion_ or increase the width of the _Content block_?

**Comment by kristinashu** [comment]
Ah good point Claudia! I've update the copy to make it clear that the Accordion width should be decreased the match the Content block. Ty!

**Comment by mmmavis** [comment]
Hi @kristinashu are we making this change for Article Pages only? It looks like accordion block is also available on other page types like PNI article page, blog page, campaign page, primary page etc)

**Comment by kristinashu** [comment]
I believe it is only necessary on the Articles pages because the other Accordion block instances are all already narrow (same width as the paragraph text). But please let me know if you notice any that are wider.

**Comment by mmmavis** [comment]
Hi @kristinashu , this is ready for QA on staging. I've included some links for testing.

### Article Page (accordion should be narrower on staging)

- PR: https://foundation.mofostaging.net/en/research/library/is-that-even-legal/builders-guide/
- Production: [https://foundation.mozilla.org/en/research/library/is-that-even-legal/builders-guide/](https://foundation.mozilla.org/en/research/library/is-that-even-legal/builders-guide/)

### Default Page (both should look the same)

- PR: https://foundation.mofostaging.net/en/docs/how-do-i-wagtail/streamfield-blocks/#accordion
- Production: [https://foundation.mozilla.org/en/docs/how-do-i-wagtail/streamfield-blocks/#accordion](https://foundation.mozilla.org/en/docs/how-do-i-wagtail/streamfield-blocks/#accordion)

### Banner Page (both should look the same)

- PR: https://foundation.mofostaging.net/en/youtube/regretsreporter-dataset/ (find password on [edit page](https://foundation.mofostaging.net/cms/pages/21685/edit))
- Production: [https://foundation.mozilla.org/en/youtube/regretsreporter-dataset/](https://foundation.mozilla.org/en/youtube/regretsreporter-dataset/) (same password from above)

**Comment by kristinashu** [comment]
Thank you @mmmavis!

Accordions on Article pages look really good at wider browser widths. 

 <img width="999" alt="image" src="https://user-images.githubusercontent.com/1068783/228975378-6d4945db-ae63-441a-8969-afdfe99e9b29.png">

But at narrower widths, the accordions start to become too narrow (they look narrower than the paragraph text when I would expect it to remain the same width).

<img width="944" alt="image" src="https://user-images.githubusercontent.com/1068783/228975428-dd8a68ff-e92c-4ef4-ad0c-075b9f476ad5.png">

<img width="447" alt="image" src="https://user-images.githubusercontent.com/1068783/228975324-d30e8a15-2fd7-4cce-83ca-de8f9cda4d4d.png">

The accordions on Default and Banner pages look as expected (accordion width aligns with paragraph width even at narrower browser widths)

<img width="447" alt="image" src="https://user-images.githubusercontent.com/1068783/228975233-767b130c-9b46-44bb-8788-72472776874d.png">

Is it possible for Accordions on Article pages to be the same width as the content block at all browser widths?

**Comment by mmmavis** [comment]
> Is it possible for Accordions on Article pages to be the same width as the content block at all browser widths?

@kristinashu Thanks for the QA. Yes! Will file a follow-up PR to fix the width issue on narrower screens!

**Comment by kristinashu** [comment]
Thank you Mavis!

**Comment by mmmavis** [comment]
@kristinashu fix is on staging! The article page link I included above doesn't seem to work on staging anymore. I've found another article page with accordion block for QA

- Staging: https://foundation.mofostaging.net/en/research/library/user-controls/report/meager-and-inadequate-a-quantitative-analysis-of-youtubes-user-controls/ (Search for "Terms used in the study" to go to the accordion block)
- Production: https://foundation.mozilla.org/en/research/library/user-controls/report/meager-and-inadequate-a-quantitative-analysis-of-youtubes-user-controls/

**Comment by kristinashu** [comment]
Accordions look excellent! 

(https://foundation.mofostaging.net/en/research/library/is-that-even-legal/builders-guide/ should work again, I had unpublished it when testing a different ticket)
