### ISSUE TITLE
Add the footnote functionality to Accordions

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#10103]
We have a request from Eeva to add footnote functionality to Accordions on Article and Publication page types. 

### Dev Tasks
 - [ ] Update accordion block to use rich text with footnotes block
 - [ ] Implement JS to automatically open accordion item if the footnote reference links to a closed item.
 
### Acceptance Criteria
TODO: add link for testing
- [ ] As an editor, I can add footnotes within an Accordion's Rich text field on Article and Publication pages
- [ ] As a visitor, I can click on a footnote within an accordion and it will bring me down the page to the appropriate footnote
- [ ] As a visitor, I can click on a footnote at the bottom of a page and it will bring me up the page to the appropriate footnote (if the accordion is closed then the accordion is automatically opened so I can see the footnote)

**Comment by cdanfon** [comment]
Hey @kristinashu thanks for this. The team can have a look in the next grooming meeting. 

Ahead of it, @mmmavis @danielfmiranda would the above description make sense to you or would you need further info to be able to define Dev tasks in a grooming session?

**Comment by mtdenton** [comment]
Updated ticket, ready for 2/20 sprint

**Comment by simont-cr** [comment]
Closed per 2024 ticket purge.
