### ISSUE TITLE
[MAIT Report] Add content into Publication

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#10116]
[Assets Folder](https://drive.google.com/drive/u/0/folders/1ZjW8eWnULgpROINGcczRvP1Itet6j4I7)
[MAIT report draft](https://docs.google.com/document/d/18KyJzLZvIBq0TlHm59NZMbNVEhfprnWrYmreEb-rnbA/edit?usp=sharing) 
[Illustrations](https://drive.google.com/drive/folders/1mWs2SFu3eHZb6aZuuhJ8rKOHS1Q2VRHD?usp=sharing)

Todo
- [x] Layout content in publications template
- [x] Add Illustrations and graphs
- [x] Share with Ramy for review
- [ ] Explore how we can add a more "accessible section" to the publication potentially using assets created from https://github.com/mozilla/foundation.mozilla.org/issues/9990

**Comment by kristinashu** [comment]
Time box to a 4

**Comment by nancyt1** [comment]
Did a first pass of content entry, https://foundation.mozilla.org/en/research/library/ai-transparency-in-practice/ai-transparency-in-practice/

**Comment by nancyt1** [comment]
Also created a [version](https://foundation.mozilla.org/en/research/library/ai-transparency-in-practice/ai-transparency-article-test/) using just the article template at Ramy's request to see which version might be better.

**Comment by nancyt1** [comment]
Ramy likes the article version best so I've added everything I can already and when draft is finalized, I'll go in made the necessary changes.
