### ISSUE TITLE
Add Spacer block to Article page type

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#10121]
Add `Spacer` block to `Article` page type 

## AC
- [ ] As an editor, I can add a Spacer block on a page
- [ ] As a visitor, I can see vertical space between blocks where a Spacer has been added
- [ ] As a staff member, I can see [this spreadshee](https://docs.google.com/spreadsheets/d/1AwLF6dw05Jn2WZu-xvxUgm8VQ4udriZW6d_NfdVI9ns/edit#gid=1064282995)t is up-to-date (aka please add a checkmark to the sheet when this is live)

cc @nancyt1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-124)

**Comment by simont-cr** [comment]
@kristinashu Is this something that the team still needs for Articles?

**Comment by kristinashu** [comment]
Yes, this is still wanted!
