### ISSUE TITLE
Hide protected research hub detail pages from listings

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#10128]
### Description

Follow up from https://github.com/mozilla/foundation.mozilla.org/issues/10081

We now hide protected pages on https://foundation.mozilla.org/research/library/ but a protected page will still appear on an author page e.g 
https://foundation.mozilla.org/en/research/browse-authors/180/maximilian-gahntz/

This also seems to be an issue on the landing page, where the latest research might show protected pages: https://foundation.mozilla.org/en/research/

### Dev notes

- [ ] Search codebase for locations where we surface detail pages in a list (off the top of my head: landing page, library page, author page)
- [ ] Ensure all these locations only show live and public pages. Make sure the queryset uses `.live().public()`.

### Acceptance criteria

- [x] As an editor, I can safely publish a report landing page with a password or only available to logged-in users and know that the thumbnail will not be visible to the public
- [x] As a visitor, I only see report detail pages listed that I can click on and view 
- [x] No protected detail pages are listed on an author page.
- [x] No protected detail pages are listed in the "latest" section on the research hub landing page. 

cc @tbrlpld @kevinhowbrook

**Comment by mtdenton** [comment]
Sending this to grooming

**Comment by tbrlpld** [comment]
@kristinashu This is ready for testing on staging: https://foundation.mofostaging.net/en/research/browse-authors/180/maximilian-gahntz/

**Comment by kristinashu** [comment]
This is working well!
