### ISSUE TITLE
Images in the Slider block are overly compressed

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#10130]
### Describe the bug
The images shown in the foundation carousel on the following page are showing artifacting from being compressed:
https://foundation.mozilla.org/en/research/library/is-that-even-legal/germany/#additional-resources

### To Reproduce
Navigate to the link and scroll down to see the slider block in comparison to the card grid underneath it. You should see the difference in image quality even though they're both using the same image source.

### Expected behavior
Images displayed should not present artifacting.

### Screenshots
![imageartifacting](https://user-images.githubusercontent.com/41487159/217960044-d351d9cc-e5c5-4775-a780-084bd76079da.JPG)

**Comment by mtdenton** [comment]
@fessehaye passing this to you for support duty

**Comment by kristinashu** [comment]
Thank you Tyler and Simon! This is related to this broader issue https://github.com/mozilla/foundation.mozilla.org/issues/9918 but this particular block is need for a report launching soon.

**Comment by fessehaye** [comment]
@mtdenton  can you check on staging if this is resolved? thx!

**Comment by kristinashu** [comment]
Design-wise, this looks much better to me! Thank you Simon!
