### ISSUE TITLE
Missing Profile bios lead to inconsistent design

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10147]
## Description

Reported by @gutermul on [Slack](https://mozilla.slack.com/archives/C98GW3P7X/p1676290434520839). 

> Hi! I am noticing something that I think will continue to be an issue with different streamfield blocks and other elements drawing on "Profile snippets:" Profile snippets are used across the website in many different contexts (sometimes they're just an icon on a blog, on the [research hub](https://foundation.mozilla.org/en/research/browse-authors/28/kasia-odrozek/) they're drawn on, and on the new [DFL "about" page](https://foundation.mozilla.org/en/data-futures-lab/draftabout/) they're drawn on in a [profiles streamfield block](https://foundation.mozilla.org/en/docs/how-do-i-wagtail/streamfield-blocks/#profiles)).
The issue is: they will continue to be changed at the source and that can make them inconsistent in the other contexts in which they're placed (see Kasia's bio that was created at the bottom of the about page, where no one else has one).
Suggested solution: this might not cover all cases, but for the Profiles streamfield block that we're using, having a tick-box option of whether we want to include the bio or not would work.

**Comment by simont-cr** [comment]
Closed per 2024 ticket purge.
