### ISSUE TITLE
[EPIC] PNI Refactoring Stage 1

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10159]
As discussed in the [spike ticket](https://github.com/mozilla/foundation.mozilla.org/issues/9948), let's start the refactoring work with low-risk tasks. I've broken them down into three categories and will be filing tickets for individual tasks.

1. Extract code dupes and turn them into functions. This will reduce the code by hundreds+ lines. **[Tickets filed under this Stage 1 Epic]**
2. Use JSDoc style to document every functions and modules. We have quite a bit of functions with long implementation. Many functions look like they have gone through rounds of quick patches and now their function names don’t represent what they do anymore. Ideally, we would want to break the long implementation into smaller functions to make sure each function has one sole purpose. To do so, we will first need to know what the current functions do, which we can achieve by adding documentations to existing functions and modules. **[Tickets filed under this Stage 1 Epic]**
3. Update function names. There are some functions with very similar names but have quite different purposes. We should update them to make them more distinguishable. **[Tickets to be filed after Step 1 and 2 tickets are done]**
4. Audit to see if JS files need to be moved to a diff directory (for better file organization)
5. Change [utils.js](https://github.com/mozilla/foundation.mozilla.org/blob/1b0298d1a23c78f9696fc5e315627cb90f041c35/source/js/buyers-guide/search/utils.js#L15) so functions are not wrapped in a class. **[Mavis to file ticket]**

**Comment by tbrlpld** [comment]
@mmmavis I have also notices in the JS that some util modules group all their functions on a single object the is imported. If this is a style we want to keep, can we add some description as to what is supposed to be useful about this? I don't quite understand it. If we want it for namespacing, I feel like `import "module-name"` or `import * as newName from "module-name"` provides the same benefits.

**Comment by mmmavis** [comment]
@tbrlpld Thanks for raising this issue. I haven't paid much attention to that front and I'm unable to give opinions until the codebase is more readable and digestable lol 😅 Do you think we can revisit this at a later stage? I can make a note in the epic so it doesn't get lost.

**Comment by tbrlpld** [comment]
@mmmavis Sure, we can revisit this. I was mostly wondering if this is something that has an obvious reason to a more seasoned JS dev that I am missing. If this does not sound like the natural thing to do to you too, yea, adding it to / noting it in the epic would be great.

**Comment by mmmavis** [comment]
Note added to epic description.

@tbrlpld I don't have a huge pref about which to use between `import * as newName from "module-name"` and `import obj from "module-name"`. To me it's also depending on how the module itself is implemented. If anything, personally I like to avoid using alias to avoid naming inconsistency when importing a module. I'm curious about what @fessehaye @danielfmiranda think.

**Comment by tbrlpld** [comment]
@mmmavis I am not concerned with the import style. I am questioning if we should use "classes" for namespacing. A class in OOP should really be a thing that stores data with operations that work on or with that data. 

I wonder what the point of a class is in grouping unrelated functionality, like in [this `Utils` class](https://github.com/mozilla/foundation.mozilla.org/blob/1b0298d1a23c78f9696fc5e315627cb90f041c35/source/js/buyers-guide/search/utils.js#L15).

**Comment by mmmavis** [comment]
@tbrlpld ah got it. I totally missed that line `export class Utils {`. Thanks for pointing it out. And yes I agree that shouldn't be a class.

**Comment by mmmavis** [comment]
From the performance point of view - I agree with @jhonatan-lopes with his list of backend P1s. Front-end code def needs to be refactored / rewritten as it has become wonky over the years. A good chunk of the frontend code can be simplified if we decide and have the bandwidth to move searching/filtering logics to backend. Currently it's done via frontend and it's error prone.

**Comment by Gbaldassano** [comment]
@mmmavis @jhonatan-lopes sounds good, thanks! @jhonatan-lopes could you also link here any remaining work you identified around PNI improvements (even bandaid solutions) that still need to be done?
