### ISSUE TITLE
Accordion shows detail triangles on Safari

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10155]
### Description

The default toggle indicator triangles of the `details` element are showing on Safari. This is redundant with the +/- icon on the right and does not happen in other browsers.

On iOS the triangles are even smushed. 

### To Reproduce

1. Go to https://foundation.mozilla.org/en/research/library/is-that-even-legal/builders-guide/
2. Scroll down to the accordion section

### Expected behavior

The triangles are not shown. 

### Screenshots

<img width="300" alt="Screenshot 2023-02-15 at 07 49 37" src="https://user-images.githubusercontent.com/24797493/219080930-b0b63fae-2edc-4d7b-93fd-8a0832b81601.png">

<img width="300" src="https://user-images.githubusercontent.com/24797493/219080948-3f090a43-bddf-4756-bcf8-c5c85ec87dc0.jpeg">

### Desktop

 - OS: macOS
 - Browser: Safari
 - Version: 16.3

### Smartphone

 - Device: iPhone 14 Pro
 - OS: iOS 16.3.1
 - Browser: Safari

**Comment by danielfmiranda** [comment]
Hi @tbrlpld this is now on staging and ready to be QA'd whenever you get a free moment. Thanks!

**Comment by danielfmiranda** [comment]
Hi @mmmavis! 

Thanks for volunteering to do QA for this ticket. 


Here are the steps to test: 

- Using Safari, Go to https://foundation.mofostaging.net/en/research/library/is-that-even-legal/builders-guide/
- Scroll down to the accordion section
- Check if triangles are still showing on the left side of items, shown in the screenshot above.
- If the triangles are no longer there, testing is complete!

**Comment by tbrlpld** [comment]
Thanks @danielfmiranda I can confirm this is fixed now 👍

**Comment by mmmavis** [comment]
Oops, sorry just saw this. This is working great on prod as well. Closing!
