### ISSUE TITLE
Add tests for existing index page functionality

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10152]
## Description

This issue is just in preparation of the actual refactoring of the index page in #9080. 

Before we can confidently start refactoring, it would be good to have some tests for the existing index functionality in place that we want to keep. These tests should preferable be black box tests that are not tied to implementation details. 

### Index page

- [x]  List all child pages
    - [x]  Child pages are of the same locale as the parent
    - [x]  Can list children of different types?
- ~~Cache all entries for a configureable amount of time.~~
    - The cache was added to fix n+1 issues… but it’s not really fixing the underlying issue. It still has n+1 calls but saves the result. See: https://github.com/mozilla/foundation.mozilla.org/issues/6463
    - So if I can return the entries without the n+1 issue, I should be able to not need the cache.
    - Yup… the `localized` and `specific` calls are hidden in the templates (`blog_card` and `generic_card`. This should not be the case.
- [x]  Filter by tag (although this is really only used on the blog)
- ~~Filter for multiple tags~~
    → No body is using that. I have checked the logs. If this causes issues, I can just remove this. 
- [x]  Load more pagination.
- [ ]  Load more pagination when filtering for tag.

### Campaign index page

- [ ]  Exclude publication pages from items

### Blog index page

- [ ]  Reduce initial number of items by one if the featured topics box is displayed.
    - There are some tests… but not for the following pages. Only for the initial page.
    - These tests would need to be overhauled and the followup responses (for the load more function) need to be tested. We need to check that the originally excluded is added back. It works but there is no test.
- [x]  Don’t included featured items in normal listing (to avoid duplication).
- [ ]  Topic filter route
    - [ ]  Topic filtering
    - [ ]  Hide results count “x results for y”
    - ~~Hide classifiers ? This is supposed to hide something in the template but is never checked in the template code. This can go.~~
    - [ ]  Set index title and intro based on topic
    - [ ]  Set SEO fields on page based on topic filter
- [x]  Author index route. This is pretty uncoupled from the rest of the page and uses its own template.
- [x]  Author detail route. Same, but also not really showing much.
- [x]  Search filter route. Results list also has the load more functionality.

## Acceptance criteria

- [ ] Tests exist for all the existing features of the index pages.

**Comment by mtdenton** [comment]
Closing, identified as completed during 5/30 sprint planning
