### ISSUE TITLE
Long topic titles lead to overflow and horizontal scrolling

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10154]
### Describe the bug

Long words in the research topics lead to overflow and horizontal scrolling. 

### To Reproduce
1. Go to https://foundation.mofostaging.net/cms/snippets/wagtailpages/researchtopic/
2. Change the title of an existing and used research topic to have a very long single word in the title. E.g. `Electionsectionsectionsectionsections`
3. Go to https://foundation.mofostaging.net/en/research/library/
4. See how the long word leads to overflow and horizontal scrolling in the filter box.

### Expected behavior

The words should be broken into multiple lines and hyphenated. 

(Or we use ellipsis for overflow, but this means that we are also not breaking on white space for multi word titles.)

### Screenshots

<img width="300" alt="Screenshot 2023-02-15 at 07 13 36" src="https://user-images.githubusercontent.com/24797493/219069749-4294dc6d-4f86-490c-b0ff-1fe9e622f632.png">

### Additional context

We might want to check other locations where the research topic titles are used and apply similar solutions.

## Acceptance Criteria

- [ ] As a user, words in the left-hand menu should split to a new line when it would cause overflow in the container.

**Comment by beccaklam** [comment]
Good catch @tbrlpld though I'm not sure of any word in topic titles that are _that_ long so perhaps this isn't an immediate problem? I think breaking on white space is important to show the whole topic name. Does this error only occur when a word is so long it takes up the entire width of the filter box? Otherwise it would break on the second line?

**Comment by tbrlpld** [comment]
On multi word titles it does break on white space to multiple lines. 

<img width="300" alt="Screenshot 2023-02-15 at 07 10 38" src="https://user-images.githubusercontent.com/24797493/219153307-3b9f39a9-3af5-4984-a6ea-033c3aac34f6.png">


So, yes, this starts happening when works do take the whole width of the box. 

I would like to caution that other languages might tend to longer words more frequently than english. E.g. "internet health report" in German is one word "Internetgesundheitsbericht". Which is very close to breaking the layout: https://foundation.mofostaging.net/de/research/library/

**Comment by mtdenton** [comment]
@jhonatan-lopes this one may have slipped through the cracks, let me know what you think

**Comment by mtdenton** [comment]
Related: #10093

It's too much trouble and involves too many hacky things to get that hyphen in, I'd say let's skip the hyphenation.
