### ISSUE TITLE
PNI - Uncaught TypeError on product review pages

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10158]
### Describe the bug
`Uncaught TypeError: i.addedNodes[0].firstChild is null` on PNI product review pages.

### To Reproduce
1. Go to https://foundation.mozilla.org/en/privacynotincluded/euki/
2. Open dev tool console
3. See error

### Expected behavior
No `Uncaught TypeError`

### Screenshots
<img width="768" alt="image" src="https://user-images.githubusercontent.com/2896608/219180070-0470a267-9885-480e-b8eb-5f533ccb0fe3.png">

### Acceptance Criteria
- [ ] No `Uncaught TypeError` on dev tool's console
- [ ] (TBD. Unsure if this bug is breaking other things. Will need further investigation)

**Comment by fessehaye** [comment]
@mmmavis can you check if this is still happening on staging?

**Comment by mmmavis** [comment]
@fessehaye I'm still seeing the same error on staging 😬

**Comment by mmmavis** [comment]
@danielfmiranda do you mind help QAing this on staging? https://foundation.mofostaging.net/en/privacynotincluded/euki/

**Comment by danielfmiranda** [comment]
No problem Mavis! just tested this out and everything looks good to me. One thing I did notice was that a font-src for commento was being blocked so I updated that CSP setting for the staging site.

Moving to ready for prod!

**Comment by mmmavis** [comment]
Awesome! Thanks for QAing this and updating CSP!
