### ISSUE TITLE
SPIKE | User Account settings don't appear in the Wagtail dashboard

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#10151]
For some reason, we don't have the ability to set things like time zones in our account views:

![nosettings](https://user-images.githubusercontent.com/41487159/218824976-95a160ee-2582-4894-9511-ef2f16808bb1.jpg)

@bheasman sent a video of the settings that are typically available from this view.

https://user-images.githubusercontent.com/41487159/218824809-e403561d-2670-4f9b-8134-00dd6da98b00.mov

One theory is that the SSO plugin we're using (found [here](https://github.com/python-social-auth/social-app-django)) is disabling this functionality behind the scenes. After looking through the wagtail database, I also found that none of these user accounts have this field set:
![pgadmin3](https://user-images.githubusercontent.com/41487159/218825314-53edb526-d675-4ef6-9c0f-276f4f13eef5.JPG)

Goal: Investigate why we don't have these settings and create follow-up tickets if it's possible for us to gain this functionality.

**Comment by bheasman** [comment]
Thanks Tyler! This may be helpful from the Wagtail docs:
https://docs.wagtail.org/en/stable/extending/custom_account_settings.html#customising-the-user-account-settings-form

**Comment by laymonage** [comment]
Hi, I'm just chiming in, but it's likely the template override here is overriding the whole view:

https://github.com/mozilla/foundation.mozilla.org/blob/1b0298d1a23c78f9696fc5e315627cb90f041c35/network-api/networkapi/wagtailcustomization/templates/wagtailadmin/account/account.html

**Comment by tbrlpld** [comment]
How did I miss that one 🤦‍♂️ Thanks @laymonage that's a fantastic pointer

**Comment by tbrlpld** [comment]
@laymonage Thanks again for the pointer and pointing out the customization docs. 

Having looked into this, I am assuming the this was originally overridden to avoid users from trying to manage their password, because we use Google for SSO. Is there a good way to remove existing panels from the accounts settings while keeping others? E.g. having the locale and notification settings in place would be great, while we would want to remove the name/email and password panels.

**Comment by tbrlpld** [comment]
Actually... does not look like that was the intent... https://github.com/mozilla/foundation.mozilla.org/pull/1261

They are just showing some groups... which I don't think is very useful for normal users. Admins can look up a user's class on in the Users list.

**Comment by tbrlpld** [comment]
@cdanfon @mtdenton This is now ready for QA on staging: https://foundation.mofostaging.net/cms/account/

**Comment by cdanfon** [comment]
Thanks @tbrlpld I've tested and LGTM - I've updated my preferred language and timezone. Moving this to 'ready for prod'
