### ISSUE TITLE
Schedule.mozillafestival GA4 Setup

### ISSUE THREAD

**Issue by phoang0** [MozillaFoundation/foundation.mozilla.org#10150]
We've created a GTM container for the schedule.mozillafestival now however the snippet below needs to be added to the site before we can proceed any further. 

A GA4 property has also been setup (property ID: 353721369) but we need the snippet to be added before any GA4 tags can be published.

Copy the code below and paste it on to every page of your website.
Paste this code as high in the <head> of the page as possible:

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PB5FRTL');</script>
<!-- End Google Tag Manager -->
```

Additionally, paste this code immediately after the opening <body> tag:

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PB5FRTL"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by marcwalsh** [comment]
Adding @robb-j here who is the developer from Open Lab - he'll be able to support this.

**Comment by robb-j** [comment]
Should I also take out the existing GA tracking code?

**Comment by robb-j** [comment]
I've deployed a version to the staging/development site which you can use to test it is integrated properly?
https://mozfest.openlab.dev/plaza

**Comment by marcwalsh** [comment]
Hey @phoang0 - we've decided to make this change after the festival to avoid any potential data loss for the live event.

**Comment by phoang0** [comment]
Hi both, apologies if I'm misreading your messages but I can't seem to find the GTM snippet on the staging site? Thanks

**Comment by simont-cr** [comment]
Closed per 2024 ticket purge.
