### ISSUE TITLE
[PNI] Use database to sort products by creepiness

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10168]
The creepiness of a product is currently a property/method: https://github.com/mozilla/foundation.mozilla.org/blob/1b0298d1a23c78f9696fc5e315627cb90f041c35/network-api/networkapi/wagtailpages/pagemodels/buyersguide/products.py#L655-L663

If we want to sort by it, we need to do it in Python: https://github.com/mozilla/foundation.mozilla.org/blob/1b0298d1a23c78f9696fc5e315627cb90f041c35/network-api/networkapi/wagtailpages/pagemodels/buyersguide/utils.py#L41-L45

This is inefficient. The sorting should happen in the database. 

The original reason was that the votes are only stored on the default locale product.

**We should find a way to pull the products from the database sorted by creepiness.** 

We might want to update how creepiness is saved. Or, explore annotations to add the creepiness value from the default locale to the other locales.

**Comment by kristinashu** [comment]
@jhonatan-lopes has done this as part of his wider PNI performance work. His updates should land later this week! Closing this ticket.
