### ISSUE TITLE
Dropdown button styles broken in Wagtail Dashboard

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#10194]
### Describe the bug
A button has some bad styles in the Wagtail dashboard after the Wagtail 3.0 Update (affecting all browsers):

![bustedbutton](https://user-images.githubusercontent.com/41487159/220427002-42f8e6b4-4803-40f1-8a3f-249456ca3f93.JPG)

### To Reproduce
Go to https://foundation.mozilla.org/cms/snippets/wagtailpages/update/ as an example link. The button in the top right has the broken styles

**Comment by mmmavis** [comment]
This bug comes from Wagtail again. I will add styling overrides on our end to fix this.

**Comment by mmmavis** [comment]
@mtdenton this is ready for QA on staging: https://foundation.mofostaging.net/cms/snippets/wagtailpages/update/

**Comment by mtdenton** [comment]
@mmmavis Good to go!

**Comment by mmmavis** [comment]
Done!
