### ISSUE TITLE
Wagtail CMS Dashboard icon is oversized

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#10192]
### Describe the bug
The "right arrow" icon being used in the menus on the Wagtail dashboard seems to have inadvertently changed.

I'm seeing several tailwind classes added to this, so maybe that's the reason?

![menutailwind](https://user-images.githubusercontent.com/41487159/220406367-671521d0-7317-48da-8c84-5d0e3f7d080f.JPG)

### To Reproduce
1. In the CMS dashboard, go to Pages > Homepage > Blog, the arrow is seen at the bottom of the screen

### Expected behavior
The icon should be reduced in size so that the link to go to the blog view (https://foundation.mozilla.org/cms/pages/789/) isn't clipping out of the bottom of the page.

**Comment by mmmavis** [comment]
@cdanfon do you mind sharing a screenshot of another Wagtail 3.0 site? I'm wondering how the arrow is supposed to look like.

**Comment by mmmavis** [comment]
@cdanfon do you mind sharing a screenshot of another Wagtail 3.0 site? I'm wondering how the arrow is supposed to look like.

**Comment by mmmavis** [comment]
I set up a fresh Wagtail site locally that runs on Wagtail v3.0 and confirmed that the issue came from Wagtail.

Should I use my best judgement to come up with CSS override to fix this bug?

**Comment by mtdenton** [comment]
Ha, interesting. @cdanfon @tbrlpld I doubt it's a ticket-worthy bug for y'all but FYI.

+1 on the best judgement route @mmmavis . Thanks for looking into this!

**Comment by tbrlpld** [comment]
If this is fixed in Wagtail 4 and this is not preventing editors from any important work, I would just wait. You can always opt to navigate the page tree with the list view (main page content) instead of the sidebar.

**Comment by mmmavis** [comment]
I've filed a bug ticket on Wagtail's repo as I was able to reproduce this from Wagtail v3 to v4.2.
I will have a PR on our foundation site repo to address this issue.

**Comment by mmmavis** [comment]
@mtdenton this is ready for QA on staging!

**Comment by mtdenton** [comment]
@mmmavis looks good from here!

**Comment by mmmavis** [comment]
Done!
