### ISSUE TITLE
Attribution report for donations - TBX Analytics

### ISSUE THREAD

**Issue by cdanfon** [MozillaFoundation/foundation.mozilla.org#10203]
Attribution report for donations (like the [newsletter one](https://analytics.google.com/analytics/web/?authuser=0&pli=1#/analysis/p321347134/edit/x0YQzCR6Rea1wOhx04t3GQ)) - to cover getting source/medium and page attributed to donation conversions 

Estimation: 0.5 days

**Comment by bheasman** [comment]
[Here's the explorations report](https://analytics.google.com/analytics/web/#/analysis/p321328061/edit/tIIi5UnbRoywFP50teMxNw) for donate.mozilla.org: 

The 2 tabs in the report relate to the initial landing page on the site where the user started their journey (this doesn't feel so useful for donate.mozilla as there's only one page! But it does give a sense of where users came in via a campaign with present amounts, for example).

The other tab relates to the source for referral. 

We're currently blocked on creating a similar report for the FRU modal (pending GA4 setup off the back of conversations with FRU)- but as we discussed, it may be good to wait until we know the approach in terms of landing page vs modal. If we go for the latter and replace the existing donate.mozilla landing page - we can easily update this report with the new path. 

In the meantime, [here's a report ](https://analytics.google.com/analytics/web/#/my-reports/grB8m6LjS_Oz0mO7_dRWBw/a87658599w211260246p202905341/) for the FRU modal Universal Analytics.

**Comment by bheasman** [comment]
Quick reminder that in GA4, to edit the parameters of a report, you have to make a copy of the report for yourself first!

**Comment by simont-cr** [comment]
@cdanfon Could you please let us know if this ticket is still something the team should be focusing on this year or it is considered outdated?

**Comment by cdanfon** [comment]
Hi @simont-cr, looping @bheasman in as he might have more context

**Comment by simont-cr** [comment]
Sounds good, thanks for the confirmation Shing!
