### ISSUE TITLE
TabbedProfileDirectory stream block is giving error to published page

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10205]
### Describe the bug
`TabbedProfileDirectory` stream block is giving error. If you publish a page that uses a `TabbedProfileDirectory` stream block, the published page gets an `IndexError`.

### To Reproduce

1. Edit a MozFest page. e.g., https://mozillafestival.mofostaging.net/cms/pages/415/edit/
1. Add a `TabbedProfileDirectory` stream block in. e.g.,
![](https://user-images.githubusercontent.com/2896608/221054312-a638ae5d-65cf-4db0-a8de-0a91e5e99584.png)
1. Publish the page & see errors

![](https://user-images.githubusercontent.com/2896608/221054418-60016449-bf85-491b-a768-45181d79c1bf.png)

### Expected behavior
Published page should render without errors.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-132)

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

TabbedProfileDirectory has already been removed from MozfestPrimaryPage in PR #3602 ( https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11629 ) . We are good here!
