### ISSUE TITLE
Video background not working on hero images

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#10219]
From Sabrina:

I've followed the instructions on https://foundation.mozilla.org/en/docs/how-do-i-wagtail/how-to-embed-video/ for trying to place a video in the hero area on https://foundation.mozilla.org/en/research/library/user-controls/report/ but appears black.

V

## Dev Tasks
 - [ ] Update the help text to further clarify the settings needed here to make the video hero display, specifically that "Full Screen", "Left", or "Right" should be selected in order for the video background to work.
 - [ ] Investigate CSP directives to make sure that the source of the video background is allowed to be loaded on the site.

**Comment by kristinashu** [comment]
@danielfmiranda fix this and it's looking amazing on https://foundation.mozilla.org/en/research/library/ai-transparency-in-practice/ai-transparency-article-test/, thank you Daniel!
