### ISSUE TITLE
[PNI] Active category nav links don't get properly reset

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10220]
### Describe the bug
Active category nav links don't get properly reset when navigating between webpages using browser's back/forward buttons.

### To Reproduce

1. Go to https://foundation.mozilla.org/en/privacynotincluded/
1. Click on any category nav link. e.g., `Smart Home`
1. Click on any subcategory nav link. e.g., `Robot Vacuums`
1. Click on a different category nav link. e.g., `Entertainment`
1. Click on any subcategory nav link. e.g., `eReaders`
1. Using browser's back button to go back to previous pages. 
1. Notice at some point the two category nav links `Smart Home`and  `Entertainment` are both highlighted. 
1. Navigate between pages using browser's back and forward buttons. Observe errors.

### Screenshots
https://user-images.githubusercontent.com/2896608/221270980-772d8357-e6c1-40aa-a04b-4778336e67b8.mov

### Acceptance Criteria
* [ ] There should be only one active category nav link at any given time
* [ ] Active category nav link should be highlighted
* [ ] Active category nav link should correctly reflect what category of products users are viewing on the page

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-133)

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

Simon Acosta Torres I think it might be better to tackle this one after other PNI refactor tickets are done first. Right now PNI JS code is very tangled together and buggy 😅  It’s safer that we don’t work on PNI code in parallel lol
