### ISSUE TITLE
Add query string field to append to petition donation modal CTA link

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#10238]
Stakeholder: Kevin Hill

We would like to add a field that allows us to append a query string to the CTA button `href` found here:

![petitioncta](https://user-images.githubusercontent.com/41487159/222195167-a6060721-5631-4c03-b83d-aee3877e6c85.JPG)

So if we had a field in the Donation Modal block that was similar to

CTA Query Parameters: `sfid=2342324&utm_campagin=things&etc=stuff`

We could append that string to here:
https://github.com/MozillaFoundation/foundation.mozilla.org/blob/3e43dafbd9da44646496762d631fbcd9d5f56ecd/source/js/components/petition/donation-modal.jsx#L74 

Not sure if Wagtail/Django could validate whether or not the string fits the pattern of a query string or if we need to use a regular expression, but it should ideally validate.

## Dev Tasks:
* [ ] Add a new "Donation Link Query String" field to `donate_modal.py` with appropriate help text (need to groom this, also talk about some sort of validation). Field should not be required. If left blank, the field adds nothing to the CTA URL. Validation is done on the string to make sure it fits the pattern of a query string.
* [ ] Append the string to `this.donateUrl` in `donation-modal.jsx`. Connect these strings with `&`. If the CMS field is blank, the `&` should not be added. If the CMS field starts wtih `&`, that character should be removed.

## Acceptance Criteria:
* [ ] If the "Donation Link Query String" field is blank, nothing changes and the user is taken to `?form=donate`
* [ ] Validation prevents page save if the string doesn't fit the format of a query string. 
* [ ] If a valid query string is added, a user is taken to the combined link with the new query string when they click the blue "Yes, I'll Chip In" CTA button after signing a petition 
* [ ] If an `&` is added to the front of the "Donation Link Query String" field in the CMS, it is discarded to prevent two `&`'s being added and causing an invalid link

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-135)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Tyler Denton Do you think this stakeholder request is still valid or we can get away with removing as it’s from early 2023?
