### ISSUE TITLE
Remove custom GitHub CI action

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10230]
From Slack,
> Once we reactivate the integration between Heroku and Github and activate automatic deployment to staging, we can remove the custom GitHub continuous deployment action (https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/.github/workflows/continuous-deployment.yaml)

Slack thread: https://mozilla.slack.com/archives/C04DYP6T6VD/p1677249499546539

**Comment by mmmavis** [comment]
@jzinner I would like to double check with you to see if it's okay to remove this GitHub action. To my understanding integration between Heroku and GitHub has been set up without the use of this `.yaml` file. How about automatic deployment to staging? Does it still require GitHub action to do that?

**Comment by jzinner** [comment]
Hi @mmmavis, you should can review this yourself in the `Deploy` tab of the `foundation-mofostaging` Heroku app.  It says "Automatic Deploys from main are enabled" 
So we do not require this Github action now to deploy to staging.

**Comment by mmmavis** [comment]
@jzinner got it. Thanks!
