### ISSUE TITLE
SPIKE | Assess viability and steps to adapt a donate-wagtail landing page template into foundation

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#10234]
The purpose of this spike is to assess effort and feasibility of adapting a template from donate-wagtail for use on the foundation stack. We should also determine what it would take to multi-site donate.mozilla.org onto foundation, similar to how we handle mozillafestival.org.

A possible template in question:
https://github.com/MozillaFoundation/donate-wagtail/blob/6c44bbaf15ab6875d405dbba9a2a7b5395123759/donate/templates/pages/core/landing_page_master.html

Pages we want to emulate:
https://donate.mozilla.org
https://donate.mozilla.org/happy-holidays-from-mozilla/

The purpose of this is to give us a good starting point for future incremental changes to our donate landing pages by ensuring that the structure of the page doesn't affect how we measure outcomes.

Wishlist:

- [ ] Page header container should be very plain (no navigation) and emulate the current donate landing pages
- [ ] In order to create variants, we would be able to add a hero image to donation landing pages similar to what is being done [here](https://donate.mozilla.org/en-US/happy-holidays-from-mozilla/)
- [ ] Fundraise Up embedded elements would replace everything in `#anchor-donate`
- [ ] Everything in `.introduction__container` and `.donate-form__footer` is CMS-editable
- [ ] CSS is largely if not exactly 1:1 on the new adaptation (meaning layout, colors, etc)
- [ ] Localization capabilities. While Pontoon might be off the table initially, we should still be able to accommodate multiple languages here.

EDIT: After discussion, this should focus on mapping redirects for legacy languages that are no longer supported and determining the behavior when one of these languages is encountered. Locales should also be considered here (en-us vs en-gb) and making sure we're robust on the FRU side to determine currency to display.

**Comment by kristinashu** [comment]
Noting that we still need a decision from Kevin on if we should use donate.mozilla.org or foundation.mozilla.org/donate (aka a new site or a just new page type).

**Comment by mtdenton** [comment]
After discussion, a spike item isn't needed. Daniel has created an epic for this work
