### ISSUE TITLE
[Wagtail Bug] Pages aren't loaded/rendered properly on Firefox

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10239]
### Describe the bug
Staff reported on Slack. (I'm unable to reproduce this issue)

> Hi, I am having issues accessing wagtail. Whenever I try to edit a page the screen does not load fully (I can only see the title of the page and no menus. Would love some help with this, thanks!

> I just scrolled on this page using the touchscreen on my laptop and it worked. There is still a grey bar at the bottom, but it let's me scroll down. The scroll bar itself still doesn't work.

Full thread [here](https://mozilla.slack.com/archives/C98GW3P7X/p1677675490600199)

### To Reproduce
1. Go to /cms and edit any page
2. See error

### Expected behavior
All pages should fully load for users.

### Desktop (please complete the following information):
 - Browser Firefox
 - Version 110.0 (64-bit)

### Additional context
This could be related to [the double scroll bar bug on FF](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10193)

**Comment by tbrlpld** [comment]
Has this been reproduced in Wagtail bakery? If so, we should report it to the Wagtail repo.

**Comment by mmmavis** [comment]
So far only one user reported this to us. I wasn't able to reproduce bug myself.

**Comment by tbrlpld** [comment]
Oh ok. Sorry I thought you had been able to reproduce this.

**Comment by mmmavis** [comment]
No problem! I updated the ticket description so it's clearer.
