### ISSUE TITLE
Strange horizontal panning allowed on iOS Safari

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10232]
Use an iPhone (iOS 16) and visit the Foundation website (e.g. the [homepage](https://foundation.mozilla.org/en/), but it happens on other pages too) slide your finger horizontally on the screen as if scrolling. See how the content pans. 

https://user-images.githubusercontent.com/24797493/221705404-d087bbb4-4860-4fea-b029-d6a1440178bd.MP4

This is a strange experience also happens when you just try to scroll vertically when your finger/thumb motion is a bit sloppy. 

This does not happen on other websites (e.g. [GitHub](https://github.com))

**Comment by mmmavis** [comment]
Hi @danielfmiranda , Could you help QAing this on staging?

To QA, please load the following links on your iPhone Safari

### Homepage
  - staging: https://foundation.mofostaging.net
 
### Primary page

Narrow layout
  - staging: https://foundation.mofostaging.net/who-we-are/

Wide layout
  - staging: https://foundation.mofostaging.net/advocacy/

### Article page

  - staging: https://foundation.mofostaging.net/docs/how-do-i-wagtail/grimms-fairy-tales-demo/wolf-and-seven-little-kids/

### Opportunity page 
  - staging: https://foundation.mofostaging.net/initiatives/web-literacy/core-curriculum/participate/

**Comment by mtdenton** [comment]
Moving this along with the caveat that we need to fix this on the opportunity pages, I'd say we create a new ticket to fix that specifically @mmmavis

**Comment by mmmavis** [comment]
Yup, here's the new ticket https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10801
