### ISSUE TITLE
[FRU] - Donate Stack Migration

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#10259]
This Epic has been made to house all of the work required for the migration of "donate" pages from the [old donate stack ](https://github.com/MozillaFoundation/donate-wagtail) to the foundation site, updated to use FundraiseUp.

**At the moment, there are 3 main tasks that would deliver the MVP:**

1. Update the original donate stack to use FRU
1. Copy over the donate stack to the foundation site, using FRU components, under a "donate" sub-site (similar to mozfest).
1. Ensure that existing recurring donation subscriptions from braintree/stripe persist after the move

After that we can focus on other projects such as updating these pages to be more customizable and AB testing.

### Update original donate site to use FRU:
1. [https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10249](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10249) (design)
1. [https://github.com/mozillafoundation/foundation.mozilla.org/issues/10261](https://github.com/mozillafoundation/foundation.mozilla.org/issues/10261)
1. [https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10364](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10364)
1. [https://github.com/mozillafoundation/foundation.mozilla.org/issues/10262](https://github.com/mozillafoundation/foundation.mozilla.org/issues/10262)
1. [https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10263](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10263)
 
### Copy donate site to foundation.mozilla.org
1. [https://github.com/mozillafoundation/foundation.mozilla.org/issues/10265](https://github.com/mozillafoundation/foundation.mozilla.org/issues/10265)
1. [https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10266](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10266)
1. [https://github.com/mozillafoundation/foundation.mozilla.org/issues/10267](https://github.com/mozillafoundation/foundation.mozilla.org/issues/10267)
1. [https://github.com/mozillafoundation/foundation.mozilla.org/issues/10268](https://github.com/mozillafoundation/foundation.mozilla.org/issues/10268)
1. [https://github.com/mozillafoundation/foundation.mozilla.org/issues/10269](https://github.com/mozillafoundation/foundation.mozilla.org/issues/10269)
1. [https://github.com/mozillafoundation/foundation.mozilla.org/issues/10271](https://github.com/mozillafoundation/foundation.mozilla.org/issues/10271)
1. [https://github.com/mozillafoundation/foundation.mozilla.org/issues/10272](https://github.com/mozillafoundation/foundation.mozilla.org/issues/10272)
1. [https://github.com/mozillafoundation/foundation.mozilla.org/issues/10270](https://github.com/mozillafoundation/foundation.mozilla.org/issues/10270)
1. https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11736
1. [https://github.com/mozillafoundation/foundation.mozilla.org/issues/10309](https://github.com/mozillafoundation/foundation.mozilla.org/issues/10309)
1. https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10327
1. https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10510
1. https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11737
1. https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11738
1. https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11739
1. https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11740

### Ensure existing braintree/stripe recurring donations continue to work as expected:
1. [https://github.com/mozillafoundation/foundation.mozilla.org/issues/10264](https://github.com/mozillafoundation/foundation.mozilla.org/issues/10264)

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/TP1-138)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Closed per Daniel Miranda confirmation.
