### ISSUE TITLE
Update Heroku resource naming in app.json to enable review app

### ISSUE THREAD

**Issue by jzinner** [MozillaFoundation/foundation.mozilla.org#10256]
in [app.json](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/app.json)
 Need to update the line: 
    "heroku-postgresql:hobby-dev" ->
    "heroku-postgresql:mini"

**Comment by tbrlpld** [comment]
Can we add some more context for future reference why this change is needed?

**Comment by jzinner** [comment]
For context please reference:

- [Removal of Heroku Free Product Plans FAQ](https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq) 
    - _Removal of free dynos, free Heroku Postgres and free Heroku Data for Redis plans starting November 28, 2022_ 
- [Heroku Article: Introducing Our New Low-Cost Plans](https://blog.heroku.com/new-low-cost-plans),

**Comment by mmmavis** [comment]
Done!
