### ISSUE TITLE
[FRU] - Campaign Page Template

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#10269]
Create a `campaign_page.html` template based on Donate's [`campaign_page_master.html`](https://github.com/MozillaFoundation/donate-wagtail/blob/main/donate/templates/pages/core/campaign_page_master.html) and [`campaign_page.html`](https://github.com/MozillaFoundation/donate-wagtail/blob/main/donate/templates/pages/core/campaign_page.html). Since there will only be one version of campaign template (because we are not moving Thunderbird portion of code over), we can just merge the two template files mentioned above into one. The template is to be used for the Campaign model (see #10268 )

### Dev Tasks
- [ ] Create a new `campaign_page.html` template mimicking Donate's [`campaign_page_master.html`](https://github.com/MozillaFoundation/donate-wagtail/blob/main/donate/templates/pages/core/campaign_page_master.html) and [`campaign_page.html`](https://github.com/MozillaFoundation/donate-wagtail/blob/main/donate/templates/pages/core/campaign_page.html)
- [ ] Style the page using Tailwind classes only
- [ ] Template should display field content from ContentPage model
- [ ] (TBD) is there a design file we can reference to?
- [ ] Make sure rendered page doesn't have HTML validation errors
- [ ] Add this page template to Percy

### Acceptance Criteria
- [ ] As a user, when I publish a content page, the published page should have the same design and functionality as what we have on the donate site (e.g., https://donate.mozilla.org/happy-holidays-from-mozilla/). This should be checked across small, medium, and large screen sizes.
- [ ] As a user, when I publish a content page, the published page should display content from CMS.

**Comment by mmmavis** [comment]
Ticket updated and ready for our team to review during the next grooming meeting!

**Comment by cdanfon** [comment]
@mmmavis please refine ACs with further detail/content for testers

**Comment by mmmavis** [comment]
ACs updated! Let me know if they need to be improved further.

**Comment by danielfmiranda** [comment]
As mentioned in #10268, we are no longer moving forward with transferring the `CampaignPage` model to the foundation site. Closing!
