### ISSUE TITLE
[FRU] - [Donate] Add Apple Pay Verification Files

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#10262]
## Description

For FRU elements to be able to accept apple pay , we need to add a Apple Pay Verification file to the /.well-known directory in order to enable Apple Pay for donate.mozilla.org.

We can accomplish this by taking the contents of the files provided by Fundraise Up and saving them as environment variables in Heroku, we can then add a view to serve the contents of the file when Apple Pay visits `.well-known/apple-developer-merchantid-domain-association`

Notes: 
- This work will need to be done in the [donate repo](https://github.com/MozillaFoundation/donate-wagtail), not the foundations
- For reference, you can use #9747 and its accompanying PR #9779, where we implemented this for the foundation site.

## Dev Tasks
- [ ] Create an environment variables that store the file's contents (A string).
- [ ] Write logic to serve the contents of these files when Apple Pay checks `/.well-known/apple-developer-merchantid-domain-association`

## Acceptance Criteria
- [ ] As Apple, I can navigate to donate.mozilla.org/.well-known/apple-developer-merchantid-domain-association and see the verification code

**Comment by danielfmiranda** [comment]
Hi @cdanfon!

This has been merged into main and ready for QA testing. Can you please visit https://donate-wagtail.mofostaging.net/.well-known/apple-developer-merchantid-domain-association to verify that its working correctly?

The page should return the string "hello_world". 

Thanks in advance!

**Comment by cdanfon** [comment]
Hey @danielfmiranda LGTM, moving this to ready for prod!
