### ISSUE TITLE
[FRU] - [Donate] Update original donate site to use FRU form

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#10261]
## Description

**Notes**: 
- This work is going to have to take place in the original [donate repo](https://github.com/MozillaFoundation/donate-wagtail) 

It has been requested by stakeholders that we replace the donate repo's original form:

![Screenshot 2023-03-05 at 16-07-14 Donate now Donate to Mozilla](https://user-images.githubusercontent.com/18314510/222994070-0f8eea0f-c6ba-4079-8a50-844c8ab5b61f.png)

With a FRU rendered form, similar to what is being done on the Thunderbird donate site:
![Screenshot 2023-03-05 at 16-03-58 Give to Thunderbird](https://user-images.githubusercontent.com/18314510/222993996-b1268615-93a4-4bcb-8c7c-35d87cfcd21a.png)

## Dev Tasks
- [x] Work with design to create a FundraiseUp "Donation Form" element (this is done within the FundraiseUp admin site and we are going to need access)
- [x] In `donate/templates/base.html`, add the following code:

```

{% block fundraiseup_script %}
  <!-- Fundraise Up: the new standard for online giving -->
  <script nonce="{{request.csp_nonce}}">(function(w,d,s,n,a){if(!w[n]){var l='call,catch,on,once,set,then,track'
  .split(','),i,o=function(n){return'function'==typeof n?o.l.push([arguments])&&o
  :function(){return o.l.push([n,arguments])&&o}},t=d.getElementsByTagName(s)[0],
  j=d.createElement(s);j.async=!0;j.src='https://cdn.fundraiseup.com/widget/'+a;
  t.parentNode.insertBefore(j,t);o.s=Date.now();o.v=4;o.h=w.location.href;o.l=[];
  for(i=0;i<7;i++)o[l[i]]=o(l[i]);w[n]=o}
  })(window,document,'script','FundraiseUp','ADCYPWMX');</script>
  <!-- End Fundraise Up -->
{% endblock %}

```

- [x] Update our CSP directives in `donate/settings/defaults.py` to include the following URLs found [here](https://fundraiseup.com/support/content-security-policy/)
- [ ] Override these sections in [landing_page_master.html](https://github.com/MozillaFoundation/donate-wagtail/blob/91ccbcb015ce74b6f56e792d9932e045c16262fd/donate/templates/pages/core/landing_page_master.html#L46-L74) and [campaign_page_master.html](https://github.com/MozillaFoundation/donate-wagtail/blob/91ccbcb015ce74b6f56e792d9932e045c16262fd/donate/templates/pages/core/campaign_page_master.html#L70-L98) in order to add new elements, following the format in Figma from #10249 
- [ ] Update the copy at the bottom of the donate form to match the comment below.

Note: The new FRU component should be rendered like so:
```
<a href="#{{campaign_id}}" style="display: none"></a>
```

**Comment by danielfmiranda** [comment]
Question: Should we update the copy below the form that references Braintree?

**Comment by danielfmiranda** [comment]
After reaching out to donate team, they let me know that the copy below the form:
![Screenshot 2023-03-10 at 10-51-26 Donate now Donate to Mozilla](https://user-images.githubusercontent.com/18314510/224447623-67b4cb53-445f-4afe-a25a-69a88ca535a2.png)


Should be updated to the following: 


Mozilla is committed to your privacy; please read our [privacy policy here](https://www.mozilla.org/privacy/websites/). Your payment details will be processed by [Stripe](https://stripe.com/en-ca/legal/privacy-center), or [PayPal](https://www.paypal.com/us/webapps/mpp/ua/privacy-full), and a record of your donation will be stored by Mozilla.
Other ways to give: [Check](https://donate.mozilla.org/ways-to-give#check)
Question donating? Visit our [FAQ](https://donate.mozilla.org/faq) for answers to most common questions.
Need to reach us about your donation? [Contact us](https://donate.mozilla.org/help/)
Contributions go to the [Mozilla Foundation](https://foundation.mozilla.org/who-we-are/), a 501(c)(3) organization based in San Francisco, California, to be used in its discretion for its charitable purposes. They are tax-deductible in the U.S. to the fullest extent permitted by law.

**Comment by danielfmiranda** [comment]
Hi @beccaklam! 

While working on this ticket, I found that the FRU form looks a little out of place in the breakpoint between 480px and 768px. When the screen width is below 768px, the page elements stack on top of one another. This looked OK with our original form, because it would stretch to fill its space.

Unfortunately, FundraiseUp forces their element to have a max width of 376px **and** a padding of 20px, meaning that when the elements stack on top of one another, the form looks misaligned to the left.

Here are some screenshots of what they look like:
| Landing Page |  Campaign Page |
|--------|---|
| ![Screenshot 2023-03-14 at 10-03-38 Donate today Donate to Mozilla](https://user-images.githubusercontent.com/18314510/225083528-5b3d3431-6147-4543-991b-c59770025c4f.png) | ![Screenshot 2023-03-14 at 10-09-47 It's Pi Day! Donate to Mozilla](https://user-images.githubusercontent.com/18314510/225084099-c01d49bc-af82-46a9-b1d1-334d8c7be943.png)




I was wondering if this was OK with design, or if you would like me to implement something else for this breakpoint. 

One possible solution is having the elements remain side by side until the page width is < 480px. 

Here is a rough idea of what that would look like:

| Landing Page |  Campaign Page |
|--------|---|
| ![Screenshot 2023-03-14 at 10-21-56 Donate today Donate to Mozilla](https://user-images.githubusercontent.com/18314510/225091394-736464b0-a128-4f02-94bd-a435d5ab99e5.png) | ![Screenshot 2023-03-14 at 10-23-13 It's Pi Day! Donate to Mozilla](https://user-images.githubusercontent.com/18314510/225091500-af0024c8-7629-4b19-a16a-9197f86d3197.png) |



Thanks for your help!

**Comment by danielfmiranda** [comment]
Hi @beccaklam the reason for the gap between the top of the page and the landing page content is because the gap was also found in the [figma file](https://www.figma.com/file/pJMns4BCi7sJPT4VTWJY4U/FRU-Update?node-id=0%3A1&t=z5DZTACpfX9oai1t-0)


Also regarding the campaign page, I forgot to mention that the top/bottom padding of the hero image will be reduced quite a bit per figma designs:


<img width="300px" src="https://user-images.githubusercontent.com/18314510/225102458-73ac9816-a308-4f23-a1b0-762777008282.png"/>



Does this look better to you?

**Comment by beccaklam** [comment]
Ah I see, thank you for sharing the figma file! And according the figma file the campaign page above 👆  is just the MVP and in the future we'll implement this design?
<img width="400" alt="image" src="https://user-images.githubusercontent.com/20977376/225104218-87ad2ded-b0f8-40e9-8f00-a5776c198667.png">

**Comment by danielfmiranda** [comment]
Hi @beccaklam! Thats correct 👍

**Comment by beccaklam** [comment]
@danielfmiranda Okay in that case I'm good with moving forward with your proposal (having the elements remain side by side until the page width is < 480px). Thank you!

**Comment by kristinashu** [comment]
Looks good, thank you both!

**Comment by danielfmiranda** [comment]
Hi @mtdenton @kristinashu this ticket is now on staging and ready for QA

https://donate-wagtail.mofostaging.net/en-US/?fundraiseupLivemode=no

I was wondering if one of you could please take a look whenever you find a free moment and let me know if everything is looking alright? 

Thanks!

**Comment by kristinashu** [comment]
Thank you Daniel, this is looking good! Do you have a link to a campaign page example as well? Or can you please remind me how to sign into the donate staging cms?

I'm not sure if it's just because it's a demo page or not but when switching languages, the FRU modal text doesn't seem the change: 
<img width="1069" alt="Screenshot 2023-03-21 at 8 08 32 AM" src="https://user-images.githubusercontent.com/1068783/226650241-c844a6e6-7a71-4dd3-8638-573192bd16bf.png">

**Comment by kristinashu** [comment]
When you're ready, also please share this in the project slack channel for Kevin to approve!

**Comment by TheoChevalier** [comment]
> I'm not sure if it's just because it's a demo page or not but when switching languages, the FRU modal text doesn't seem the change:

I think I’ve fixed this, the locales needed to be enabled on Fundraise up for the embed form.
That being said, the form localization is based on the browser language settings, so you would need to set a different language there first

<img width="569" alt="Capture d’écran 2023-03-21 à 17 58 19" src="https://user-images.githubusercontent.com/1294206/226685064-83ac4869-d36f-427f-8f89-5e51e3d6e0f4.png">

**Comment by danielfmiranda** [comment]
Thanks for taking a look @kristinashu! 

Here is a link to a test campaign page: https://donate-wagtail.mofostaging.net/en-US/its-pi-day/?fundraiseupLivemode=no

Also, @TheoChevalier is correct that the localizations have to be enabled on the form and work on a browser language basis. Thanks for the update Theo! 

I would say that the estimate of 1 still feels right.

I have reached out in the fundraise-up slack channel to ask Kevin to take a look, and if approved I can push this to prod.

**Comment by kristinashu** [comment]
Perfect, thank you Daniel!

**Comment by danielfmiranda** [comment]
This has been pushed to prod per request of the donate team. Moving to closed!
