### ISSUE TITLE
[FRU] - Campaign Page model

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#10268]
## Description:

Now that we have created the donation site and the landing page, we need to copy over the `CampaignPage` model from the donate stack as well as its factories.

## Dev Tasks:

- [ ] Copy over the Donate Stack's `CampaignPage` Model with all of its fields. Since we are now letting FRU handle all the donation work, we can leave the models custom methods behind
- [ ] Copy over the `CampaignPage` related factories from `core_pages.py`
- [ ] Create a placeholder template `campaign_page.html` that renders the page name
- [ ] Create a simple test suite: testing creation and 200 status is received with minimal data in the model

## Acceptance Criteria:
- [ ] As a dev, I can run `inv new-db` and a donate site will  be created alongside Mozfest and the Foundation Site. This site should include a Landing Page, and a Campaign Page titled "Its Pi Day!"
- [ ] As a user, I can log into the CMS and create a custom campaign page with the same fields as the original donate site.

**Comment by mtdenton** [comment]
Need to verify if this is obsolete via Michael Whitney @Gbaldassano @danielfmiranda

**Comment by danielfmiranda** [comment]
Per [this discussion in slack](https://mozilla.slack.com/archives/C065XEHSNMC/p1705453197138939) we have verbal confirmation that this page type is no longer in use from Michael Whitney.

Going to close this ticket as well as its corresponding front end ticket, https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10269
