### ISSUE TITLE
[FRU] - Contributor Support Page

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#10270]
## Description:

Now that we have created the donation site and the landing page, we need to copy over the `ContributorSupport` model from the donate stack, and also create a factory to create a page when someone runs `inv new-db`.

**Note:** This page houses a form with ReCaptcha validation, as well as some Salesforce keys being used in the pages `get_context` method. We should figure out whether or not we are going to need to use salesforce.

## Dev Tasks:

- [ ] Understand the implication of removing reCaptcha as part of the form and add any extra required dev tasks to the list based on findings
- [ ] Copy over the Donate Stack's `ContributorSupportPage` Model with all of its fields.
- [ ] Copy over the contents of the donate stacks template `contributor_support_page_master.html`, into a new template titled `contributor_support_page`.
- [ ] Create a factory for the page, which creates a new `ContributorSupportPage` titled `Donor Help`.
- [ ] Create a simple test suite: testing creation, test 200 status is received with minimal data in the model

## Acceptance Criteria:
- [ ] As a dev, I can run `inv new-db` and a donate site will  be created alongside Mozfest and the Foundation Site. This site should include a Landing Page, and a `ContributorSupportPage` titled "Donor Help"
- [ ] This new page should render a template that is the same in copy/design/functionality as donate.mozilla.org/help.
- [ ] As a user, I can log into the CMS and create a `ContributorSupportPage` with the same fields as the original donate site.

**Comment by mtdenton** [comment]
Closing as obsolete

**Comment by danielfmiranda** [comment]
As @mtdenton mentioned above, this ticket is no longer needed. 

We were able to create a "help" AKA "contributor support page" through the work found [here](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11359).

The updated help/contributor support page can be found here: https://foundation.mozilla.org/en/donate/help/

Closing!
