### ISSUE TITLE
[FRU] - ContentPage Template

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#10272]
Create a `content_page.html` template mimicking donate repo's [`content_page.html`](https://github.com/MozillaFoundation/donate-wagtail/blob/main/donate/templates/pages/core/content_page.html). This template is to be used for the ContentPage model (see #10271)

### Dev Tasks
- [ ] Create a new `content_page.html` template mimicking donate repo's [`content_page.html`](https://github.com/MozillaFoundation/donate-wagtail/blob/main/donate/templates/pages/core/content_page.html).
- [ ] Style the page using Tailwind classes only
- [ ] Template should display field content from ContentPage model
- [ ] (TBD) is there a design file we can reference to?
- [ ] Make sure rendered page doesn't have HTML validation errors
- [ ] Set up this page on Percy 

### Acceptance Criteria
- [ ] As a user, when I publish a content page, the published page should have the same design and functionality as what we have on the donate site (e.g., https://donate.mozilla.org/faq/). This should be checked across small, medium, and large screen sizes.
- [ ] As a user, when I publish a content page, the published page should display content from CMS.

**Comment by mmmavis** [comment]
Ticket updated and ready for our next team grooming meeting!

**Comment by cdanfon** [comment]
@mmmavis please refine the ACs

**Comment by mmmavis** [comment]
ACs updated! Let me know if they need to be improved further.

**Comment by danielfmiranda** [comment]
As mentioned in #10271, we are no longer moving forward with transferring the `ContentPage` model to the foundation site. Closing!
