### ISSUE TITLE
[PNI] Related articles on category pages not synchronized on translated pages

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#10304]
Similar to the issue on product pages (#10048), related articles are not showing up on translated category pages

<img width="1182" alt="Capture d’écran 2023-03-07 à 17 05 32" src="https://user-images.githubusercontent.com/1294206/223479725-a20ee8d5-66c2-4ea0-93ee-0a22f8bd1177.png">

https://foundation.mozilla.org/en/privacynotincluded/categories/smart-home/
https://foundation.mozilla.org/fr/privacynotincluded/categories/smart-home/

**Comment by simont-cr** [comment]
Closed per 2024 ticket purge.
