### ISSUE TITLE
Donate Page Analytics

### ISSUE THREAD

**Issue by cdanfon** [MozillaFoundation/foundation.mozilla.org#10303]
# Goal:

- A clear and easy-to-read summary of what we’ve already learnt about how [donate.mozilla.org](http://donate.mozilla.org/) vs our campaign pages like[ https://donate.mozilla.org/happy-holidays-from-mozilla/](https://donate.mozilla.org/happy-holidays-from-mozilla/) vs lightbox[ https://foundation.mozilla.org/?form=donate](https://foundation.mozilla.org/?form=donate) compare to each other in terms of key metrics (e.g. conversion rates and total donations received), and broken down by factors (e.g. traffic source).

- Confirmation that the data is significantly significant enough that we can make conclusions and if so, the perhaps some baselines that we can then use to easily compare future landing page changes.

- A few questions we would like to be informed by analytics on are:

  - Does the url matter?
  - Does the FRU form perform better?
  - Can we retire the layout seen on [donate.mozilla.org](http://donate.mozilla.org/) and just use our campaign pages and the lightbox?

# Context

Details from the Slack convo: 

Shing: Could Peter help us look into the analytics around our donate pages and look at conversion metrics?

Kristina: I'm curious to find out more about our donation conversion rates and how they compare between [donate.mozilla.org/](http://donate.mozilla.org/) vs our campaign pages like https://donate.mozilla.org/happy-holidays-from-mozilla/ vs https://foundation.mozilla.org/en/?form=donate?
Also wondering how the traffic source affects these rates?

Kevin: I'm also interested in going deeper on this, it's not clear to me if each Wagtail donation form is tracked separately, or altogether. In terms of source of traffic, it looks like for Wagtail in FY22, it varies greatly, and if these numbers are correct, there's a lot of room for improvement—especially for referral traffic (3% conversion rate overall). In comparison, email traffic is at 18%.

Kevin: It doesn't appear that conversion tracking has been set up for FRU yet, but it looks like since launch we've had 28,975 page views / 15,506 unique page views of the FRU form (at least by searching for "form=donate" in 'Mozilla Foundation Site 360>Behavior>Site Content>All Pages').
We've had 8604 donations (One-time + 1st recurring) via FRU (which would mean a 29.6% conversion rate).
If someone more familiar with the GA account set up could assist in pulling these numbers, I'd be very grateful!

Shing: [@kevinhill](https://mozilla.slack.com/team/U040XGSR8NS)
 out of curiosity, what is the date you're using to defining "Since Launch"?
Tyler reminded me that we are able to see check out open, checkout close, and checkout complete through this report - [https://analytics.google.com/analytics/web/?pli=1&authuser=1#/report/content-event-events/a87658599w138[…]t%20Events&explorer-table.plotKeys=%5B%5D/](https://analytics.google.com/analytics/web/?pli=1&authuser=1#/report/content-event-events/a87658599w138395144p162890438/_u.date00=20230101&_u.date01=20230301&explorer-segmentExplorer.segmentId=analytics.eventAction&_r.drilldown=analytics.eventCategory:Fundraise%20Up%20Checkout%20Events&explorer-table.plotKeys=%5B%5D/)
We probably want to pull these into a more consolidated dashboard, with the above request from Kristina as well to make it more accessible

Kevin: Thank you, Shing! I had used Dec 1, 2022, though Dec 14 was the first public-facing test date.
It's interesting to note that in this report GA shows fewer Checkout Completes than FRU shows transactions. I guess it's possible that people donate but abandon before triggering that event action. Would love to explore alignment here.

**Comment by bheasman** [comment]
Update from Slack from Kristina: Hey, chiming in to expand on what I am hoping for here. I'm trying to be open enough to get input from the expects but also be clear on what we are trying to achieve:
A clear and easy-to-read summary of what we’ve already learnt about how [donate.mozilla.org](http://donate.mozilla.org/) vs our campaign pages like[ https://donate.mozilla.org/happy-holidays-from-mozilla/](https://donate.mozilla.org/happy-holidays-from-mozilla/) vs lightbox[ https://foundation.mozilla.org/?form=donate](https://foundation.mozilla.org/?form=donate) compare to each other in terms of key metrics (e.g. conversion rates and total donations received), and broken down by factors (e.g. traffic source).
Confirmation that the data is significantly significant enough that we can make conclusions and if so, the perhaps some baselines that we can then use to easily compare future landing page changes.
A few questions we would like to be informed by analytics on are:
Does the url matter?
Does the FRU form perform better?
Can we retire the layout seen on [donate.mozilla.org](http://donate.mozilla.org/) and just use our campaign pages and the lightbox?
These are some initial thoughts and questions but I would love to get input from a data person on the types of questions we should be asking and what is the best (aka the most accurate, simplest to read and interpret) way to present this information?

**Comment by cdanfon** [comment]
It would be great if answers could be provided by end of the week about: 

- Does the url matter?
- Does the FRU form perform better?
- Can we retire the layout seen on [donate.mozilla.org](http://donate.mozilla.org/) and just use our campaign pages and the lightbox?

**Comment by cdanfon** [comment]
@kristinashu @mtdenton Any progress on the above? Please let me know so that can Peter (unfortunately he still doesn't have access to the tickets/board) can start the work on this.

**Comment by kristinashu** [comment]
Thank you @phoang0! @mtdenton does this make sense to you? Are we still not able to answer the initial questions of:
- Does the url matter?
- Does the FRU form perform better?
- Can we retire the layout seen on [donate.mozilla.org](http://donate.mozilla.org/) and just use our campaign pages and the lightbox?

**Comment by phoang0** [comment]
Hey Kristina, 

Sorry I wasn't clear on the answers above. 

On the first and second questions however, I've had a look in the UA roll-up property which shows that there are more users donating through foundation.mozilla.org as opposed to donate.mozilla.org with roughly 80% of the purchases coming from the foundation site which suggests that this does perform better compared to the donate site. (see [here](https://analytics.google.com/analytics/web/#/my-reports/0wJ_Ue3HS_2aqjSfQpABww/a87658599w211260246p202905341/_u.dateOption=last30days/))

Please note that this analysis only looks at purchases specifically rather then begin checkouts as we don't have a full ecommerce setup but I think this analysis still helps answer the first two questions. 

Based on the previous analysis, it looks like the majority of donations for the [donate.mozilla.org/](http://donate.mozilla.org/) site still come directly to the homepage with the existing layout as opposed to a campaign pages however it would be difficult to investigate this any further without any campaign codes or list of campaigns. Despite this, we would suggest to keep the layout seen on [donate.mozilla.org](http://donate.mozilla.org/) for the time being. 

Thanks, hope this helps.

Peter

**Comment by phoang0** [comment]
Hey Kristina,

Can you try using the link below instead? You'll need to select 'UA-87658599-19' as the main property and click on 'Foundation Sites - Primary Reporting' as the main view. 

https://analytics.google.com/analytics/web/template?uid=rXX_QIvdT0WLGx9UcDRWjA

Thanks,

Peter

**Comment by cdanfon** [comment]
Ben to add a report for Kevin Hill to make a decision.

**Comment by bheasman** [comment]
I've caught up with one of our SEO team to get his thoughts on URL question. The bottom line is that either option (donate.mozilla.org or foundation.mozilla.org/donate) is fine from a visibility point of view - it won't impact it's organic visibility (and therefore donations).

However - strategically, there's a small advantage of the donate page sitting on the foundation site. Mainly because the main site will get the slight SEO benefit of any backlinks to the donate page from other sites (this wouldn't be the case on the donate.mozilla domain, as for one, Google sees subdomains as separate sites).

So that's our slight leaning in terms of a recommendation - but as it's marginal, it's worth considering this alongside other factors (like the pain/cost of moving from donate.mozilla.org).

Hope that helps!

**Comment by kristinashu** [comment]
Using foundation.mozilla.org/donate sounds good to me! It will be nice to, right away, be able to use some of our existing pages and blocks. And now that donate.mozilla.org has FRU on it it seems like we could test the two against each other. I believe Kevin is the ultimate decider tho.

**Comment by kristinashu** [comment]
Awesome, thank you for the update!
