### ISSUE TITLE
Footnote link does not bring you to the right page location

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10310]
### Describe the bug
nancyt1 reported via [Slack](https://mozilla.slack.com/archives/C98GW3P7X/p1678204402784689)

> https://foundation.mozilla.org/en/research/library/ai-transparency-in-practice/ai-transparency-in-practice-test/
> If you click on footnote 2, it will take you to footnote 3 in the footnotes section instead.

Not confirmed yet but this maybe be solved by setting scroll-padding? We'll need to take the sticky article nav bar into account.

### To Reproduce

1. Go to https://foundation.mozilla.org/en/research/library/ai-transparency-in-practice/ai-transparency-in-practice-test/ OR https://foundation.mozilla.org/en/research/library/is-that-even-legal/germany
1. Click on any footnote link e.g., [1]
1. Page takes you to the 2nd item in the footnotes section instead of the 1st item
1. This is reproduceable for all footnote links

### Expected behavior
Clicking on a footnote link in the article should bring you to the corresponding item in the Footnotes section.

### Screenshots
URL has hash `#footnote-1` but footnote 1 isn't visible in viewport.
![](https://user-images.githubusercontent.com/2896608/224409676-75ad2275-1438-462b-b89f-aad4ab179c03.png)

### Desktop (please complete the following information):
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-140)

**Comment by kristinashu** [comment]
Might be related to https://github.com/MozillaFoundation/foundation.mozilla.org/issues/5788?

**Comment by simont-cr** [comment]
@mmmavis Can you confirm if the work done on #5788 also applied to this ticket?

**Comment by mmmavis** [comment]
Unfortunately, this bug is still present.
