### ISSUE TITLE
[FRU] - Analytics

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10327]
This is part of the "Donate Stack Migration" work.

[GTM tags](https://tagmanager.google.com/#/container/accounts/6002697367/containers/70597222/workspaces/5/tags) need to be moved over as well as other measurement tool implementations outside of GTM (gtag.js, etc).

In order to do so, we need to first
- [ ] Create a GA4 property for donate
- [ ] Create a new UA code for donate
- [ ] Make sure the Foundation UA code is not activated on the donate pages

More details to come.

**Comment by danielfmiranda** [comment]
After taking a look through the donate code and through google tag manager, I no longer think this work is needed.

Donate pages live under the foundation.mozilla.org domain and are all being tracked the same as the other pages on the foundation stack.

When comparing FRU events between the two sites, I see that they both have the same events in place:

- FRU checkout open
- FRU checkout closed
- FRU checkout complete


GTM instance of donate (note that the FRU triggers are not even set up with tags):
![Screenshot 2024-01-19 at 15-07-21 Google Tag Manager](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/18314510/a4a8d8c3-b8fa-46d5-a32e-cc05cbf873e8)

GTM instance of FoMo (note that these FRU tags are set to fire with FRU triggers):
![Screenshot 2024-01-19 at 15-06-54 Google Tag Manager](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/18314510/cf50850b-73e0-49aa-91d2-b7d902d3a0ab)




Any other events that I found in the donate stack appear to be related to the old donation form that is now deprecated.


Closing!
