### ISSUE TITLE
Profile - Use fallback image on profile card for profiles without image

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10326]
### Describe the bug

When a profile does not have an image set, there is a weird gap between the parent container and the name. 

<img width="284" alt="Screenshot 2023-03-13 at 07 05 08" src="https://user-images.githubusercontent.com/24797493/224725797-4365d2d9-e05b-436d-a43a-128a552d185a.png">

We should make this look nicer. 

We need to consider that there can be mixed cases where one profile has an image and another does not. 

The simplest solution I can think of is a fallback image. I think on other places we use that black image with the wavy dots. 

### To Reproduce
1. Go to https://foundation.mozilla.org/en/research/library/creating-community-driven-datasets-insights-from-mozilla-common-voice-activities-in-east-africa/
2. Scroll down to the project leads section

**Comment by tbrlpld** [comment]
cc @beccaklam

**Comment by danielfmiranda** [comment]
Hi @sabrinang!

I was wondering if you could please help me decide what image to use as a "fallback" image when a RCC research author does not have a profile picture set in the CMS. 

I noticed in other sections of our site, we have this black/white/grey placeholder image:

![Screenshot 2023-05-31 at 11-49-17 Blog - Mozilla Foundation](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/18314510/7b0fea35-fd3a-4f3f-9ed5-48e5468a609f)


Should this be what the research author profile image should fall back to? 

Thanks in advance!

**Comment by sabrinang** [comment]
@danielfmiranda Yes you can use that same fallback image for authors we currently have on the site and it will solve having none/mixed cases.
