### ISSUE TITLE
[FRU] - Base Template + Nav + Footer

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#10330]
## Description:
Once we complete creating the Landing Page model + Factory, we should then do the following:
-  create a base template for all of the donate pages to share
- This template should include two more new templates: 
  - One for the navigation bar
  - One for the footer
- These templates should be styled, using tailwind classes as much as possible

## Screenshots:
(Header and footer highlighted in red)
![Screenshot 2023-03-28 at 10-51-55 It's Pi Day! Donate to Mozilla](https://user-images.githubusercontent.com/18314510/228325824-197175f5-97e2-493b-8b22-a03e90cf1d40.png)

## Acceptance Criteria:
- [ ] There is a new template in the code base, which the `LandingPage` model template from #10265 now inherits from. 
- [ ] There is a new template for the Navbar that is being rendered in the base template. This navbar should be styled using tailwind classes to match the design from the original donate stack
- [ ] There is a new template for the Footer that is being rendered in the base template. This Footer should be styled using tailwind classes to match the design from the original donate stack

**Comment by mmmavis** [comment]
Didn't have enough time this sprint to properly wrap my assigned tickets for donate. The groundwork is done. I have the landing page built but there are still some remaining tasks

- work with design team to finalize design details
- simplify HTML a bit especially for the nav and footer. I mocked the DOM node structure with fo.mo existing code for now. If we are keeping the nav and footer on Donate pages simple, then there's no need for us to over complicate HTML code just so it matches the rest of the codebase.
- turn more SCSS code into Tailwind

**Comment by mmmavis** [comment]
My progress this sprint for this ticket:

Most of the work for this ticket is being tackled as part of [the landing page work](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10266#issuecomment-1527954701). Once that ticket is done, we'll only need to extract the code into base template and landing page.

**Comment by mmmavis** [comment]
Hey @danielfmiranda , can you advice how we QA this work on staging?
