### ISSUE TITLE
Add "wide" option to article TableBlock

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#10332]
### Describe the feature request
Currently article page TableBlocks break out the bounds of the content and it would be great to have a checkbox like the one in the image block to display the table at wide or narrow widths. By default, it should align with the content block.

**AC**

* [ ] As an editor, I'm able to check a box to have my table block wider than the content.
* [ ] As a reader, I'm able to see tables the same width as the content block if "wide" box is unchecked.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-144)

**Comment by simont-cr** [comment]
@danielfmiranda Can this ticket be closed per the merged issue #10163?
