### ISSUE TITLE
Move code related to the Research Hub from the `wagtailpages` app to a `libraries` app.

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10340]
You probably want a models directory in there with a research_hub directory. (For the playbook you could then add another responsible_computing_challenge_playbook directory). I would call the app “libraries” because that is the focus of these site sections. The models in the two library instances will still need name prefixes, because of the model registry. I guess you could move research hub and playbook to their own apps… but that feels too far away, given how related they are… hmm…

**Comment by danielfmiranda** [comment]
Re-estimating this as a 2, as after some discussion with Jhonatan we decided to move the models and other code into /research_hub/ directories within wagtailpages instead of creating a new app, custom migrations so we dont lose the data, etc.
