### ISSUE TITLE
Language switcher is not stylized anymore

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#10347]
There’s a recent visual regression on the language switcher:

<img width="564" alt="Capture d’écran 2023-03-16 à 15 49 23" src="https://user-images.githubusercontent.com/1294206/225851551-f8aa3ae5-c259-455e-8677-fc3cd5d8c05f.png">

**Comment by mmmavis** [comment]
Thanks for reporting! I'm surprised our visual regression test didn't catch this. Will have a fix soon.

**Comment by mmmavis** [comment]
@TheoChevalier When you get a chance, do you mind checking the staging to verify the styling for the footer language dropdown is back? No rush at all. Thanks!

https://foundation.mofostaging.net/en/

**Comment by TheoChevalier** [comment]
Thanks @mmmavis, looks great!
