### ISSUE TITLE
Newsletter signup box on Mozfest pages on mobile

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10351]
### Describe the bug

The box is full width on mobile, which is breaking the border design.

![image](https://user-images.githubusercontent.com/24797493/226085129-8f741523-6009-4226-901e-1c4b357926ee.png)

### To Reproduce
1. Go to https://www.mozillafestival.org/en/issues-and-spaces/data-stewardship/
3. Scroll down to the newsletter box
A

### Device 

iPhone 14 Pro

**Comment by mmmavis** [comment]
Cannot reproduce the issue. Page doesn't have such element anymore.
