### ISSUE TITLE
[FRU] - [Donate] - Update mobile spacing for between Page title and hero section

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#10364]
## Description: 

Once we re-add the changes that were reverted in https://github.com/MozillaFoundation/donate-wagtail/pull/1744, it has been requested by design to update the spacing (on mobile) between the page title and the hero section:

![image](https://user-images.githubusercontent.com/18314510/227063499-f9ae56b5-11d2-4108-9fbf-629572ed9132.png)

**Comment by danielfmiranda** [comment]
After looking into this ticket further, I can see that this issue was made in reference to the original donate stack at https://donate.mozilla.org

Since we are working on decommissioning that stack, I believe that this ticket can be closed if we get design approval on the mobile spacing found on the new donate page at https://foundation.mozilla.org/donate

@nancyt1 could you please help me by taking a look at the mobile spacing on https://foundation.mozilla.org/donate whenever you find a free moment, and let me know if everything looks OK? 

Thanks in advance! 🙌

**Comment by nancyt1** [comment]
@danielfmiranda I can't tell exactly what the spacing is but if you can make sure the spacing between the image and title is 32px then it's good! Here's the updated [mockup](https://www.figma.com/file/rK4Nt5dtxizgv4HTOGrlK2/%5BWIP%5D-Templates?type=design&node-id=1%3A1583&mode=design&t=RJyBnq75RH4EwAdP-1) for reference. The spacing in the screenshot is with a full header banner which we don't currently have so we can make updates to that later! Thanks Daniel!

**Comment by danielfmiranda** [comment]
Thanks @nancyt1! I have created PR #11707 which updates the spacing to follow the mockup, and have tagged you as a reviewer for whenever you have a moment. :+1:

**Comment by danielfmiranda** [comment]
Just double checked this on staging and can confirm that everything is looking as expected. Moving to ready for prod!

**Comment by danielfmiranda** [comment]
Live on prod. Closing!
