### ISSUE TITLE
Wagtail Upgrade | Unable to create page alias for MozFest

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10384]
### Describe the bug
Server error hit when trying to create a page alias for MozFest.

### To Reproduce
1. Go to any page on MozFest CMS . e.g., https://mozillafestival.mofostaging.net/cms/pages/397/
2. Hover over "Supporters" -> "More" -> "Copy" 
3. Fill out the form as the 1st screenshot below and click on "Copy this page"
4. 500 error encountered. See 2nd screenshot below.

### Expected behavior
Page alias is created without errors.

### Screenshots
![image](https://user-images.githubusercontent.com/2896608/228039016-809b396b-db71-432f-9b81-8e1cc7e77440.png)
![image](https://user-images.githubusercontent.com/2896608/228039175-0d617233-f71d-4ea8-8e54-db662c3ba7f1.png)

**Comment by tbrlpld** [comment]
Is it confirmed that this did not happen before the upgrade?

**Comment by tbrlpld** [comment]
Also, are the pages that are being copied valid? Can they be saved/published (without creating an alias/copy)? I am wondering if a field was changed after the pages already existed and trying to save the page is now failing because it is being run checked with the changed field for the first time.

**Comment by mtdenton** [comment]
git reset to [a commit before 3.0.3](https://github.com/MozillaFoundation/foundation.mozilla.org/commit/76635cc9a2aa8b61dec884be0c6885e05e135710) shows a successful copy, so this seems like a new bug:

![copied](https://user-images.githubusercontent.com/41487159/228311011-56d4f347-bb98-45a6-9304-951362cd59c9.JPG)

**Comment by tbrlpld** [comment]
Also, to judge how much effort we should be putting into this: how often are alias pages created? Is this something we are likely to run into in production before we get time to investigate? Does this happen on every alias creation, or just this particular page? 

If this is an error only for a particular page and not likely to pop-up often, I would just earmark this to fix after the deployment and not hold up all other work because of it.

**Comment by mtdenton** [comment]
This is definitely not a Wagtail 4.1 deployment blocker.

> how often are alias pages created? Is this something we are likely to run into in production before we get time to investigate?
Probably not often

>Does this happen on every alias creation, or just this particular page?
Seems like it's isolated to a specific page.

**Comment by simont-cr** [comment]
Closed per 2024 ticket purge.
