### ISSUE TITLE
Verify if custom CSS fixes for Wagtail v3 are still needed for v4

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10382]
(This is not a prod push blocker)

We added [custom-fix.css](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailcustomization/static/wagtailadmin/css/custom-fix.css) to address styling issues found on Wagtail v3. Once v4 is on prod, we should verify if these custom fixes are still needed and update the code/file accordingly.

## Dev Task
- [x] Remove custom CSS fixes that are no longer needed

## Acceptance Criteria 
- [x] As a staff, when I visit CMS, I don't see bugs mentioned in 
    -  (Note: we still need the custom fix for #10192 for v4)
    - [x] #10193 
    - [x] #10194

**Comment by mmmavis** [comment]
Hi @danielfmiranda , could you please QA this on staging? Thanks!

**Comment by danielfmiranda** [comment]
Can confirm that this is working great. Thanks @mmmavis
