### ISSUE TITLE
Preview isn't working on /how-do-i-wagtail/streamfield-blocks/

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#10396]
### Describe the bug
Preview says validation error on this page https://foundation.mozilla.org/cms/pages/14737/edit/ but I can't find any errors. I am still able to publish, just not preview. Note that preview does work on staging https://foundation.mofostaging.net/cms/pages/14737/edit/

### To Reproduce
1. Go to https://foundation.mozilla.org/cms/pages/14737/edit/
2. See preview error 
3. Or click on external preview icon and see error

### Expected behavior
Should be able to see the preview (or the cause the validation error)

### Screenshots

https://foundation.mofostaging.net/cms/pages/14737/edit/
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/1068783/228607624-3acfd6bc-fa99-469a-8e2c-b942b6e9b21c.png">

https://foundation.mozilla.org/cms/pages/14737/edit/
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/1068783/228607750-af9beda6-5f08-4328-a023-9fab4c06a6b7.png">

<img width="870" alt="image" src="https://user-images.githubusercontent.com/1068783/228608392-db2ba5c5-2c53-449a-8758-0cb4a4f3841a.png">

**Comment by mtdenton** [comment]
I'm betting that this also has something to do with our CSP headers

Staging dev console (Firefox):
![stagingcsp](https://user-images.githubusercontent.com/41487159/228626085-38895da7-4e1e-43d6-8c83-279c1e03353b.JPG)

Prod dev console (also Firefox):
![prodcsp](https://user-images.githubusercontent.com/41487159/228626318-da1b33e4-815a-48c8-b596-60451e7f6d3e.JPG)


@danielfmiranda , maybe we missed something on the environment variable updates?

**Comment by beccaklam** [comment]
Adding that this is happening on Article pages too @danielfmiranda 
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/20977376/228984276-3ee30411-3d3b-4eb6-b3de-8ad5f5ecd278.png">

**Comment by beccaklam** [comment]
The strange thing is that it's working on some article pages and not others 🤔 For example, under 
[Does This Button Work? Investigating YouTube's ineffective user controls](https://foundation.mozilla.org/cms/pages/19247/edit/), [Executive Summary's ](https://foundation.mozilla.org/cms/pages/19364/edit/)preview works but not 
[Meager and inadequate: A quantitative analysis of YouTube’s user controls](https://foundation.mozilla.org/cms/pages/19391/edit/) or 
[‘Nothing changed’: A qualitative analysis of YouTube’s user controls](https://foundation.mozilla.org/cms/pages/19382/edit/) for example.

**Comment by beccaklam** [comment]
Though I wonder if I'm just seeing a loading issue, it seems shorter pages preview faster and perhaps long ones take longer?
