### ISSUE TITLE
Move all Research Hub related templates into grouping directories

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10393]
## Description

Currently, the Research Hub templates used namespaced filenames but reside in the same directory with a bunch of templates from different site sections. This is true for page templates in `network-api/networkapi/wagtailpages/templates/wagtailpages` as well as template fragments in `network-api/networkapi/wagtailpages/templates/wagtailpages/fragments`. 

We can probably make this a bit cleaner by using a directory for the namespacing and remove the prefix from the filenames. 

Also, to prepare for the setup of a design system and pattern library (e.g. with `django-pattern-library`), we might want to consider moving the templates into a more central template directory, like `network-api/networkapi/templates`. See also #9665

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

- [ ] As a developer, I can confirm that all Research Hub related templates are grouped in a directory that clarifies their association with the Research Hub.

**Comment by danielfmiranda** [comment]
Hi @kristinashu! If you have time I was wondering if you could please help me QA this whenever you have a free moment? 

This ticket just involved moving the templates to a different directory, so I think just clicking through the research hub and making sure everything looks as expected is all the testing that is needed

**Comment by kristinashu** [comment]
Hey @danielfmiranda, just to confirm, to QA this should I just make sure that everything related to the research hub in the cms is working the same on staging and production?

**Comment by danielfmiranda** [comment]
Hi @kristinashu yep! Since we just moved templates around there should be no changes, just needed to double check that everything was working as it should. 

Thanks!
