### ISSUE TITLE
Implement security relevant upgrades

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10398]
## Description

See this list of security relevant upgraded: https://github.com/MozillaFoundation/foundation.mozilla.org/security/dependabot

## Acceptance criteria

- [ ] All security relevant upgrades have been implemented.

**Comment by tbrlpld** [comment]
cc @mtdenton for planning on Monday

**Comment by danielfmiranda** [comment]
Since this is just a security update ticket, the only thing to check was that nothing has broken. 
I can confirm that everything is working as it should and that this ticket is ready for prod!
