### ISSUE TITLE
Draft an onboarding doc for devs

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10394]
Draft a doc for us to record things we want to include in the dev onboarding doc.

More details to come. 

WIP doc can be found [here](https://docs.google.com/document/d/1QeSPH9-osNT9Rc-tbQH-6ikvma6N07jlOan-qLkgeLo/edit)

**Comment by simont-cr** [comment]
The WIP document was actually used for this year onboarding, but we're also in the process of revamping the onboarding process for new hires. Will close this ticket for the time.
