### ISSUE TITLE
Detail page - Author links using english locale

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10405]
### Describe the bug

When visiting a detail page in a non-default locale (e.g. `/fr/`) the links to the author pages are going to the default locale `/en/`

### To Reproduce

1. Go to https://foundation.mofostaging.net/fr/research/library/ai-transparency-in-practice/
2. Click on one of the author ("project lead") links
4. See that you navigate to the english locale, e.g. https://foundation.mofostaging.net/en/research/browse-authors/483/ramak-molavi-vassei/ 

### Expected behavior

You should navigate to the authors page in the same locale that you viewed the detail page in. I.e. https://foundation.mofostaging.net/fr/research/browse-authors/483/ramak-molavi-vassei/

### Screenshots

<img width="300" alt="Screenshot 2023-03-30 at 14 54 26" src="https://user-images.githubusercontent.com/24797493/228972975-ecf13575-b0ee-4fd5-9788-08618dc87b07.png">

### Additional context

This can probably be solved by making sure that the author index page that is passed to the template context (for URL generation) uses the same locale as the detail page that is being viewed. 

Similar fix: https://github.com/MozillaFoundation/foundation.mozilla.org/issues/8932

**Comment by Gbaldassano** [comment]
@jhonatan-lopes is this related to the bug you fixed?

**Comment by kevinhowbrook** [comment]
I think the main issue causing this is that it's a snippet and a link is generated via routablepageurl (rather than localising the queryset), I think we need both but there should be some additional context when generating the page part of the URL (like the author index page).

PR above should resolve this.

**Comment by danielfmiranda** [comment]
Tested and can confirm that its working! Moving to ready for prod
