### ISSUE TITLE
Factory generates weird text for `article_listing_what_to_read_next.html`

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10400]
I happened to spot a weird `A / ABLE` label show up on Percy's snapshot. We should investigate where it is coming from and why.

* [Full page snapshot](https://images.percy.io/0812bfe2823ed1de99f94d9a0b5d66452ff1d6bf6710779a29bc4f55edbaaad9)
* Label in question (cropped screenshot from above): 
![0812bfe2823ed1de99f94d9a0b5d66452ff1d6bf6710779a29bc4f55edbaaad9](https://user-images.githubusercontent.com/2896608/228945249-ee82abc8-8cd1-4e4b-aaaf-17dd994a889c.png)

Not sure if it's coincidental but it seems to match where the date related regression that Percy always nags about.

![Screenshot 2023-03-30 at 12 38 01 PM](https://user-images.githubusercontent.com/2896608/228946468-d5282cec-25df-45f1-a57f-7b6dc543f74d.png)

- - -
Related ticket: https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10328

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-147)

**Comment by tbrlpld** [comment]
That's just a weird one word category name. You change the seed number of the type of faker that is used for the category names. 

It has been bugging me too, but I don't think this is a bug.

**Comment by mtdenton** [comment]
Via SD work week, timebox this, see if it's still even an issue.

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Tyler Denton Feel we could close this ticket for the time being if it hasn’t appear again.
