### ISSUE TITLE
Author detail route - Remove IDs from author detail page URLs

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10413]
This was added to get around the issue of people having the same name and issues with setting a slug field to be unique per locale. Unique per locale slug has been solved and we can leave it up to the editors to fix slug clashes between profiles.

Refer to the [`BuyersGudieContentCategory`](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/pagemodels/buyersguide/taxonomies.py#L31-L45) model for a reference implementation of unique-per-locale slugs.

**Comment by jhonatan-lopes** [comment]
Might need to fix #10509 first before fixing this one, as slugs are not unique right now.
