### ISSUE TITLE
Utility to filter a queryset based on localized related object

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10417]
## Description

Extract a utility function to “filter a queryset based on this related object that may or may not be translated into the locale that we want the queryset for”. 

The above functionality is needed in the library site section several times when listing detail pages. It is likely to also come up in other section of the site, because it happens when listing any kind of model that is related to a translatable model. 

In particular, this happens because pages are automatically copied to all locales (tree sync). Taxonomies and other related models like profiles are **not** automatically copied into all locales. That means these alias pages remain associated with the default locales objects. 

Now, the related object may be translated or not into a locale, but the page alias will still be related to the object from the default locale. 

When filtering for pages by the related object, a page should be included, regardless of the locale of the object that it associated with. E.g. a french page should be included if I filter for the french author object or the english author object. 

This is relatively straight forward by means of the `translation_key` of translatable models. But, since this pattern shows up quite frequently, it might be nice to give it a utility function with a name that can be unit tested. 

The `AuthorIndexPage.get_author_research` method is a specialized version of such a function. This pattern is also used on the library page multiple times. 

(Filtering of the page's own locale is independent of the filtering by the related object.)

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

- [ ] As a developer, I can confirm that there is utility function that allows me to filter a queryset based on a localized related object.
- [ ] As a developer, I can confirm that the filtered queryset result is the same, regardless of the locale of the related objects used for filtering. 

***

Does anybody understand this ticket? Please let me know if you have questions... it's really hard to express this...

**Comment by jhonatan-lopes** [comment]
I have taken a look at this but haven't found a straightforward way to proceed with the refactoring. I'll postpone this work until the RCC implementation so that it is clearer where the patterns are repeated.

**Comment by jhonatan-lopes** [comment]
Handled by #10769
