### ISSUE TITLE
Remove main site navigation data from the Research Hub base page

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10415]
## Description

Currently, the Research Hub base page `get_context` method is used to add the main site navigation data to the template context.

The individual page is not needed as input to the util, thus it could be a `staticmethod` for sure. 

Additionally, it seems like a strange level to introduce a method to add the global nav data in the Research Hub base page, instead of, say, a base page model that used as a base for every single page model across the site. 

Furthermore, the additional of the data to the context is reusing an already existing utility method that does the main work of retrieving the necessary data. 

It is currently planned for the Research Hub base page to be removed in #10416. For more context, see [this section](https://docs.google.com/document/d/1DtBZvmd3Dpx6ssXWnXd8jk0jPLwfU9FGjnC9rl_CTfg/edit#heading=h.9up1lm4bofmx) in the tech spec. 

I think there are two potential approaches to solved this moving forward: 

1. Introduce an abstract base page model or a mixin that can be used site wide. This base page/mixin could be used on every page model on the site. We are already using a [mixin for metadata](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/pagemodels/mixin/foundation_metadata.py#L11) in a similar way. The difference is that the metadata mixin adds methods that actually need data from specific page instance. That would not be the case with the global navigation data. Also, all caveats about inheritance outlined in the [tech spec](https://docs.google.com/document/d/1DtBZvmd3Dpx6ssXWnXd8jk0jPLwfU9FGjnC9rl_CTfg/edit#heading=h.p3e43tb95jwu) still apply. 
2. Add a template tag that renders the main site navigation. This template tag could be used on all page templates (or base templates) that need to render the main site navigation. 

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

- [ ] As a developer, I can confirm that the main site navigation data is not added to the template context in the `get_context` method of the Research Hub base page anymore. 
- [ ] As a site visitor, I see the main site navigation on all pages (including all pages of the Research Hub) as before.

**Comment by mtdenton** [comment]
Questions:
How heavy will the logic be here? Too heavy for a template?


Decision to make:
Which of the approaches from above do we want to take?

**Comment by tbrlpld** [comment]
My recommendation would be to **never** to data retrieval in a template. Templates should be as dumb as possible. 

_Everything is relative, including "never", but it is a very strong recommendation._

**Comment by danielfmiranda** [comment]
Since this is more of a back-end change, there is not much to test besides making sure that everything is working/looking the same as before.

I have given the site and CMS a test and everything is looking good to me. Ready for prod!
