### ISSUE TITLE
Remove the Research Hub base page class 

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10416]
## Description

Depends on #10414 #10415 

As outlined in the [tech spec](https://docs.google.com/document/d/1DtBZvmd3Dpx6ssXWnXd8jk0jPLwfU9FGjnC9rl_CTfg/edit#heading=h.9up1lm4bofmx), experiences with base page structures in this and other repositories have proven to lead to quite hard to reason about logic flows. 

Additionally, the previously existing functionality for main site navigation and breadcrumbs maybe better suited to be implemented in different ways (see the related issues #10414 and #10415). This points out that the existence of the base page may suggest non-optimal design patterns to be used in the code base. 

It was therefore proposed in the tech spec to remove the Research Hub base page. The necessary replacement functionality should have implemented in #10414 and #10415. The only goal of this ticket is to finally remove the base page class. 

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

- [ ] As a developer, I can confirm that the Research Hub base class has been removed from the code base.

**Comment by danielfmiranda** [comment]
Since this is more of a back-end change, there is not much to test besides making sure that everything is working/looking the same as before.

I have given the site and CMS a test and everything is looking good to me. Ready for prod!
