### ISSUE TITLE
Profile - Util function to retrieve research author profiles

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10419]
## Description

Currently, there is a convenience method `filter_research_authors` on the `ProfileQuerySet` 
class. 

Having this as a method on the `ProfileQuerySet` feels a bit weird. There is not really a reason why the profile or it's queryset should "know" anything about the existence of the research detail pages. 

This pattern of the convenience has now been replicated for blog authors too. I am not sure this is a good pattern. The more relations we have to the profile the more of these convenience methods we will have... 

I don't know. Maybe it's ok. Maybe it would be cleaner to have utility functions in the sections that need it. E.g. utility method to retrieve research authors in the Research Hub. That feels fine, because the Research Hub code already knows about profiles to create the relation. I am not sure. I am just doubting my original implementation now. 

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

- [ ] As a developer, I can confirm that the `filter_..._authors` methods have been removed from the `ProfileQuerySet`. 
- [ ] As a developer, I can confirm that the `profiles` module does not reference Research Hub or Blog code.
- [ ] As a developer, I can confirm that where necessary replacement method have been defined in the sections that need them.
- [ ] As a site visitor, I can visit a research author's detail page and see the research detail pages of the author listed.
- [ ] As a site visitor, when I visit an author's detail page, the research detail pages listed use the same locale as the author detail page (this should be tested in a non-default locale).

**Comment by Gbaldassano** [comment]
@danielfmiranda is it OK if I move this back to the all products backlog so we have it ready to review for the next sprint?

**Comment by danielfmiranda** [comment]
Everything is looking as expected. Ready for prod!
