### ISSUE TITLE
Create taxonomy classes

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10425]
## Description

⚠️ **NOTE:** Please check with the RCC Stakeholder Joycelyn Streator to confirm taxonomy names before beginning this work.

Create the taxonomies for Responsible Computing Challenge Playbook. We will need the following taxonomy snippets: 

* Content Type (**Attention** this is not the [Django contenttypes framework](https://docs.djangoproject.com/en/4.2/ref/contrib/contenttypes/) and associated models!)
* Topic
* Curricular Area

![image](https://user-images.githubusercontent.com/20977376/231253857-deb74b2e-be4b-4730-bdb5-8d35812bba58.png)

Try to use class naming that signifies the connection to the Responsible Computing Challenge Playbook. "Playbook" may be an acceptable shorthand. Also consider using [verbose name](https://docs.djangoproject.com/en/4.1/ref/models/options/#verbose-name).

Depending on the implementation of #10422 they may derive from a common base class.

Don't yet create relations to the pages. That will be part of #10426. 

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

In the Wagtail CMS, as an editor of the Responsible Computing Challenge team, …

- [x] I can create multiple instances of the “content type” taxonomy. 
- [x] I can create multiple instances of the “topic” taxonomy. 
- [x] I can create multiple instances of the “curricular area” taxonomy. 

As a developer, ...

- [ ]  I can confirm that, when I run `inv new-db`, multiple instances of each Responsible Computing Challenge Playbook taxonomy are created.

**Comment by beccaklam** [comment]
@tbrlpld Are these taxonomy names final or can they be changed in the future? If they are final I will confirm with Joycelyn that these are indeed the final names she wants to go with.

**Comment by tbrlpld** [comment]
@beccaklam They can be changed in the future, at least the editor and user facing bits, but to avoid confusion it would be nice to also have the proper names in code. So it would be good to get these clarified before work starts.

**Comment by jhonatan-lopes** [comment]
Confirmed taxonomy names with Joycelyn today

**Comment by danielfmiranda** [comment]
Un-assigning this ticket in place of #10340 for the sprint
