### ISSUE TITLE
Library page - Filter by taxonomy

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10428]
## Description

Enable the filtering of the displayed detail pages by their associated taxonomies. 

Each taxonomy should have its own section in the filter form. All instances for each taxonomy are listed as options in the respective section. 

## Acceptance criteria

On the library page,  as a visitor, … 

- [x] I can see filter options for all available "content type" instances.
- [x] I can filter the detail pages by one or more instances of the “content type” taxonomy.
- [x] I can see filter options for all available "topic" instances.
- [x] I can filter the detail pages by one or more instances of the “topic” taxonomy.
- [x] I can see filter options for all available "curricular area" instances.
- [x] I can filter the detail pages by one or more instances of the “curricular area” taxonomy.
- [x] *I create a more specific filter by selecting more options. A more specific filter will typically lead to fewer results.*
- [x] I can see the total number of results available, based on the filter I have selected.

**Comment by beccaklam** [comment]
This looks fine to me ✅
