### ISSUE TITLE
Copy page types

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10424]
## Description

This is the first real implementation step from a single library site section (Research Hub) to [two independent library site sections build from shared components](https://docs.google.com/document/d/1DtBZvmd3Dpx6ssXWnXd8jk0jPLwfU9FGjnC9rl_CTfg/edit#heading=h.p3e43tb95jwu) as described in the tech spec.

The point of the ticket is to create duplicates of all page types that already exist for the Research Hub, but for the Responsible Computing Challenge Playbook. "Playbook" may be an acceptable shorthand, but that should be discussed with other devs and possibly design.

As a first step we only want to be able to create the page tree structure. All filtering, listing and other custom functionality should be deactivated by commenting it out (having this active now would require too many changes at once). 

Also leave out relation ships to other models, in particular when they need through models (think authors, taxonomies, etc.). This will be dealt with in #10426 after the taxonomies are created in #10425.

Do update the page relation definitions and keep the field and panel definitions. 

Page level templates should also be duplicated. The page level templates should not be shared to allow customization, the fragments from which the page level templates are build, however, should be reused between the two libraries as much as possible though.

Update the fake data generation to also set up the Playbook library site section (in addition to the existing Research Hub library site section). This will not be used in production, but will be useful during testing. 

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

* In the Wagtail CMS, as an editor of the Responsible Computing Challenge team, …
	- [ ] I can create an instance of a library landing page for the Responsible Computing Challenge Playbook.
	- [ ] I can create a library page under the library landing page I have created for the Responsible Computing Challenge Playbook.
	- [x] I can create many library detail pages under the library page for the Responsible Computing Challenge Playbook.
	- [ ] I can create an author index page under the library landing page for the Responsible Computing Challenge Playbook.

* As a developer, ...
	- [ ] I can confirm that when I run inv new-db, a site section for the Responsible Computing Challenge Playbook is generated.

* On the landing page…
	* as a visitor …
		- [x] I can read the title and introduction to the playbook.
		- [x] I can navigate to the library page via more than one link. 
	* as an editor …
		- [x] I can edit the page title and introduction text. 
		- [x] I can set a banner image. 
* On a detail page … 
	* as a visitor … 
		- [x] *I can see the introduction and overview of the course material.*
	* as an editor … 
		- [x] I can manually specify a publication date for the resource that is different from the actual publication of the detail page.

**Comment by beccaklam** [comment]
This looks fine to me!

**Comment by beccaklam** [comment]
Hi @jhonatan-lopes, as an editor I am unable to complete some of the ACs in the first bullet point, but I think that's okay? We can discuss more tomorrow at stand. I think it makes sense that our team sets up the RCC team for those pages and that staff can't just create another library instance without notifying the web platforms team first?

**Comment by jhonatan-lopes** [comment]
Yep, in this case they have been created already in the review app with fake data. Since there can be only one of those pages, you should not be able to create another. I think the equivalent criteria here could be if you can see and edit those pages in the review app's admin interface. We can discuss that at stand up as well
