### ISSUE TITLE
Library page - Filter by "collaborator" profile

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10429]
## Description

Enable filtering of the listed detail pages by their associated profile. 

<img width="256" alt="230465798-72273de5-c39d-4d75-9057-117fde7d089c" src="https://user-images.githubusercontent.com/24797493/230921107-2842fae4-2244-4dad-b677-1219a97141fc.png">

## Acceptance criteria

* On the library page, as a visitor, … 
	- [x] I can see filter options for all profile that are associated with any detail pages in the Responsible Computing Challenge Playbook library.
	- [x] I can filter the detail pages by one or more profiles.
	- [x] *I create a more specific filter by selecting more options.*
	- [x] I can see the total number of results available, based on the filter I have selected.
	~- [ ] I can see filter options for all profile that are associated with any detail pages in the Responsible Computing Challenge Playbook library.~ Duplicate of first AC? -RL
	- [x] I can see the profile filter section has a heading reading "contributor". (TODO: double check this with design, because this might change)

**Comment by beccaklam** [comment]
I think we decided the name will be "Contributors" not "Collaborator".
