### ISSUE TITLE
SPIKE - Identify recurring and sharable patterns in existing templates

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10421]
## Description

This spike is a main task to enable the creation of [two independent implementations of a library site sections from shared components](https://docs.google.com/document/d/1DtBZvmd3Dpx6ssXWnXd8jk0jPLwfU9FGjnC9rl_CTfg/edit#heading=h.p3e43tb95jwu) as is proposed in the tech spec.

The goal of this spike is to identify as many recurring and sharable patterns in existing templates as possible. 

"Recurring" in this case means if there are already multiple templates that do similar things but potentially with different specific values (strings) or variable names. It may be possible in that case to extract a fragment that defines the majority of that functionality and may only need to take the different specific values and maybe some additional variables as inputs. 

"Sharable" in this case means templates that may only exist once so far, but we will need a very similar template on the page in second library site section. Again, the variation will likely include different specific values (strings) but the functionality could be extracted into fragment that takes the different specific values as inputs. 

Whenever possible, try to remove Research Hub terminology from the templates and make these strings configurable through parameters. The parameters can be passed into the template when they are [included](https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#include). 

Also, try to remove "research" from file names as much as possible, unless the template is absolutely research related. When trying to express a design variation try to prefer use the design description for differentiation (e.g. `search_bar_square`) instead of the usage location (e.g. `research_search_bar`) -- usage dependent names tend to get out of date and become misleading quickly. 

For small patterns, you could consider to implement the extraction as part of this work, but the actual extraction work might be better suited to be done in dedicated tickets. Do create the tickets as part of this spike.

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

There are no hard and fast acceptance criteria for this issue because it is a spike issue. 

The goal would be to have to have follow-up tickets created that handle the actual extraction of the identified patterns into template fragments.

**Comment by tbrlpld** [comment]
Here are some example I have not had time to fully groom:

- [ ]  Extract profile stack fragment (used for “project leads” on research detail page)
- [ ]  Extract page header fragment. All the headers look quite similar, but they are build differently between the page type templates.
- [ ]  Turn `research_author_card.html` into `profile_card.html`. There is nothing research specific to this. If there will be something research specific at some point, you might create `profile_card_reserach.html` that passes specific values to the `profile_card.html`.

**Comment by Gbaldassano** [comment]
@danielfmiranda  Time box 2 hours for Spike investigation

**Comment by mtdenton** [comment]
@jhonatan-lopes when you get back, can you review the above comment from Daniel to see if you agree here? He may be going into a bit more detail as well.

**Comment by jhonatan-lopes** [comment]
@mtdenton @danielfmiranda That seems very reasonable. There might be other patterns that emerge once we start copying the templates, but that's ok.

**Comment by mtdenton** [comment]
Per Daniel, this is ready to close!

**Comment by jhonatan-lopes** [comment]
Ultimately, I've decided to go with the following templates:
- "pages/libraries/base.html" -> base libraries page, inheriting from "wagtailpages/modular_page.html"
- "pages/libraries/detail_page.html" -> an abstract detail page for the library
- "pages/libraries/landing_page.html" -> an abstract landing page
- "pages/libraries/library_page.html" -> an abstract library page
- "pages/libraries/authors_index_page.html" -> an abstract authors index page
- "pages/libraries/profile_page.html" -> an abstract author detail page

Concrete implementation of these templates by the RCC and Research Hub libraries were defined by extending the templates and implementing the relevant blocks.

The following fragments were implemented:
- "fragments/libraries/author_card.html"
- "fragments/libraries/detail_card.html" -> abstract (to be extended by each concrete implementation)
- "fragments/libraries/filter_button.html"
- "fragments/libraries/filter_form.html"
- "fragments/libraries/hero_guts.html"
