### ISSUE TITLE
Refactor `routableprofileurl` template tag

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10423]
## Description

The [`routableprofileurl` tag](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/templatetags/profile_tags.py) is weirdly specific and flexible at the same time. Its purpose is to generate the URLs of "author detail pages". These are not really pages in the CMS, but rather they are [routes on the author index page](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/pagemodels/research_hub/authors_index.py#L61-L78) which render a profile's information as a page. The tag takes the author index page, the route name and the profile as input to calculate the URL. The `routableprofileurl` is a wrapper around Wagtail's `routablepageurl` tag which does the actual URL computation.

I guess the existence of Wagtail's `routablepageurl` template tag must have inspired the original creation of the `routableprofileurl`. But, looking back this does not seem to make all that much sense anymore. It is not really that flexible because it is already tied to the signature the the profile route on the index page can have. 

Also, there are not going to be that many author (or rather profile) index pages that we need this flexibility. 

Additionally, since the tag already needs the index page as an input and is also tied to the signature of the route on the index, it might be better to add the URL generation to the index page itself (because wherever we might use the template tag, we need to retrieve the index already to be able to pass it to the tag).

Another strange decision was to use `profile_tags` as the module to house this tag. It's strange because it creates a sort of two way dependency. Instead of having the index page point to all things "profile", we now have a module about profiles that needs to know about "index pages". 

I can see two approaches that how the `routableprofilepage` tag could be refactored / replaces:

1. Add a method to reverse its own routes to the author index page. Use that method to compute the profile URL in the `get_context` method of the pages that previously used the template tag (I think so far that is only the detail page). Pass the URL with all other profile data into the template and render that. 
2. Create a very specific template tag that is tied directly to the author index page and only works with that page. The module should be named accordingly. 

I think the first solution may be cleaner because it keeps all logic related to the profile/author detail page closer together (it's basically all on the author index page). It should also be easier to deal with localization questions when working on page methods than it is in template code.

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

- [ ] As a developer, I can confirm that the `routableprofileurl` template tag has been removed (an alternative solution is used to generate the profile urls on a author index). 
- [ ] As a site visitor, I see profiles listed as before on the author index and I can click a profile to go to the associated "author detail page". 
- [ ] As a site visitor, I see profiles listed as before in the "project leads" section of any detail page and I can click a profile to go to the associated "author detail page". 
- [ ] As a site visitor, when navigating to a "author detail page" I remain in the same locale as the page on which I found the link to the "author detail page" (this should be verified with a non-default locale).

**Comment by danielfmiranda** [comment]
Tested on staging and can confirm its working as expected. Moving to ready for prod!

**Comment by danielfmiranda** [comment]
This has been pushed to prod. Closing!
