### ISSUE TITLE
Taxonomies - Add abstract taxonomy base class

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10422]
All taxonomies, regardless of their specific relationships and associations are very similar. They are usually a simple model with a single name field. We could consider adding an abstract base taxonomy and have all taxonomies be based on that abstract base. This could even be broader than just the library site section. The abstract taxonomy could be used site wide. The abstract functionality for taxonomies is fairly well known (a name field). What we could save by adding an abstract base is the duplicate field, panel and translation specification.

See also [this section](https://docs.google.com/document/d/1DtBZvmd3Dpx6ssXWnXd8jk0jPLwfU9FGjnC9rl_CTfg/edit#heading=h.gf42qxkn6q78) of the tech spec. 

I am not 100% sure if this is needed as this introduces again the option to add features to the base class that are not really needed across the instances... 

Having an abstract base to share functionality will make more sense when we want to share some more complex configuration across all child classes, i.e. #10442.

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

**Comment by Gbaldassano** [comment]
@jhonatan-lopes to confirm if this still needs grooming after RCC meeting 5/3

**Comment by jhonatan-lopes** [comment]
Yep, still needed and good to go

**Comment by kevinhowbrook** [comment]
This can be reviewed here https://github.com/MozillaFoundation/foundation.mozilla.org/pull/10582
Not entirely sure if it's what we need but I think it's in the ball park...

**Comment by danielfmiranda** [comment]
Since this is more of a back-end change, there is not much to test besides making sure that everything is working/looking the same as before.

I have given the site and CMS a test and everything is looking good to me. Ready for prod!
