### ISSUE TITLE
SPIKE - Identify recurring and sharable patterns in existing methods and classes 

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10420]
## Description

This spike is a main task to enable the creation of [two independent implementations of a library site sections from shared components](https://docs.google.com/document/d/1DtBZvmd3Dpx6ssXWnXd8jk0jPLwfU9FGjnC9rl_CTfg/edit#heading=h.p3e43tb95jwu) as is proposed in the tech spec.

The goal of this spike is to identify as many recurring and sharable patterns in existing methods and classes as possible. 

"Recurring" in this case means if there are already multiple methods that do similar things but potentially with different specific classes or property names. It may be possible in that case to extract a utility function that defined the majority of that functionality and may only need to take the classes and property names are parameters. 

"Sharable" in this case means methods that may only exist once so far, but we will need a very similar method on the respective class in second library site section. Again, the variation will likely include different class and property names but the functionality could be extracted into utility function that takes the differing names and classes as inputs. 

For small patterns, you could consider to implement the extraction as part of this work, but the actual extraction work might be better suited to be done in dedicated tickets. Do create the tickets as part of this spike.

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

There are no hard and fast acceptance criteria for this issue because it is a spike issue. 

The goal would be to have to have follow-up tickets created that handle the actual extraction of the identified patterns into utilities.

**Comment by jhonatan-lopes** [comment]
The pages in the libraries were re-written to have an abstract base which is made concrete by each concrete implementation (RCC and Research Hub):

- `libraries/authors_index.py`
  - `BaseAuthorsIndexPage`
    - `author_profiles` -> prop
    - `library_page` -> prop
    - `article_detail_pages` -> prop
    - `get_author_detail_context`
    - `get_latest_author_articles`
    - `get_author_articles_count`
    - `get_author_articles`
    - `get_banner`
- `libraries/constants.py`
- `libraries/detail_page.py`
  - `LibraryDetailPage`
    - `localized_authors` -> prop
    -  `authors_index_page` -> prop
    - `authors_detail_url_name` -> prop
    - `author_names` -> prop
    - `get_banner`
- `libraries/landing_page.py`
  - `BaseLandingPage`
    - `library_page` -> prop
    - `detail_pages` -> prop
    - `latest_detail_pages` -> prop
- `libraries/library_page.py`
  - `BaseLibraryPage`
    - `filter_form` -> prop
    - `detail_pages` -> prop
    - `filter_detail_pages`
    - `get_sorted_filtered_detail_pages`
    - `get_context`
    - `get_banner`

During the refactoring, an effort was made to replace `get_` methods with properties, as most of them don't change often and, as such, can safely be cached between requests to improve performance.
