### ISSUE TITLE
Library page - Child page listing, sorting and pagination

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10427]
## Description

Start adding functionality to the library page of the Responsible Computing Challenge Playbook site section. This functionality had been commented out when the library page type was first copied from the Research Hub. 

As a first step, add back the listing of the child detail pages, sorting and pagination. 

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

* On the library page, as a visitor, … 
	- [x] *I see the detail pages listed in reverse chronological order of their publication.*
	- [x] I can select the ordering of the detail page listing to follow chronological or alphabetical order, or the reverse of either.
	- [x] I can navigate to the detail page of one of the listed results by clicking on the listing item. 
	- [x] I can see the total number of results available.
	- [x] I can use the breadcrumb navigation to get back to the landing page. 
	- [x] *I see only the first 10 detail pages listed when there are more.* 
	- [x] *I can use page navigation to see the next set of detail pages (or back if I am not on the first page).*
	- [x] I see that, when I visit the library page for a non-default locale, the detail pages use the same locale as the library. I.e. if I visited the library page with `/fr/` the links to the detail pages also use `/fr/`.

**Comment by beccaklam** [comment]
To clarify, what is the purpose of the last checkbox "I see that, when I visit the library page for a non-default locale, the detail pages use the same locale as the library."? If I visited the library page with /fr/ for example, would the detail page also be /fr/ or would it be /en/?

**Comment by tbrlpld** [comment]
@beccaklam The purpose is to make sure we check the locale issue that we have been discovering all over the Research Hub. We do want `/fr/` to link to `/fr/` always! What we have seen in many places is the `/fr/` links to `/en/`, which is not what we want. Hence, the acceptance criterion.

**Comment by beccaklam** [comment]
@tbrlpld Thank you for explaining!
