### ISSUE TITLE
Create relationships between the classes

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10426]
## Description

After the page types and taxonomy models have been created in #10424 and #10425 respectively, we can now create the relation ships between the models. 

As a reference for the class relationships see the [class diagram in the tech spec](https://docs.google.com/document/d/1DtBZvmd3Dpx6ssXWnXd8jk0jPLwfU9FGjnC9rl_CTfg/edit#heading=h.4017gldnffhu). 

Mainly, the taxonomies need to be connected to the detail pages. Also, it should be possible to feature instances of the "content type" taxonomy on the landing page. 

The user/editor facing names for relation between detail page and profile model have been changing in the past. It probably makes most sense to use "profile" in code, but set the user/editor facing name to what is desired. Last change was to "Contributors". 

Also make sure that these desired connections are made in the fake data generation.

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

- [ ] As a developer, I can confirm that when I run `inv new-db`, a site section for the Responsible Computing Challenge Playbook is generated and that detail pages have relationships to the taxonomies and profiles models.
- [x] On the landing page as an editor  I can select multiple instances of the “content type” taxonomy that should be featured on the landing page.
* On a detail page, as an editor … 
	- [x] I can manually specify a publication date for the resource that is different from the actual publication of the detail page.
	- [x] I can select multiple instances of the “content type” taxonomy that the detail page should be related to. 
	- [x] I can select multiple instances of the “topic” taxonomy that the detail page should be related to. 
	- [x] I can select multiple instances of the “body of knowledge” taxonomy that the detail page should be related to. 
	- [x] I can select multiple instances of the “profile” model, in a section labelled "Contributors", that the detail page should be related to.

**Comment by beccaklam** [comment]
This looks fine to me. I'm assume we don't need to create new relationships for the "Contributor" taxonomy, correct? That will be inherited from the Research Hub?

**Comment by tbrlpld** [comment]
@beccaklam Thanks for the catch! I have expanded a bit on the he relation to the "profile" model and added an acceptance criterion.
