### ISSUE TITLE
Profile detail route - Show profile data

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10435]
## Description

Enable the profile detail route to display the basic profile information (name, image, tagline and introduction).

<img width="256" alt="image" src="https://user-images.githubusercontent.com/24797493/230472939-0223cb8b-d707-4b39-9f61-9f6ddebf0bb5.png">

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

* On a profile detail page …
	* as a visitor …
		- [x] I can see the profile’s name, image, tagline and introduction
		- [x] *when I visit the profile detail page with a non-default locale, I see the localized profile data*
		- [x] *I can navigate to the profile index page and the landing page via the breadcrumbs.*
		- [x] *when I visit the with a non-default locale the breadcrumbs navigation links use the same non-default locale.*

**Comment by beccaklam** [comment]
This looks fine to me ✅
