### ISSUE TITLE
Landing page - Search library page

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10433]
## Description

Enable the search bar on the landing page that uses the search functionality of the library page. 

Submitting a search term in the search bar will navigate to the library page filtered by the search term entered on the library page. 

<img width="356" alt="Screenshot 2023-04-05 at 16 11 36" src="https://user-images.githubusercontent.com/24797493/230231724-ba27b778-6623-4f9b-b8ef-b5423bc883ed.png">

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Design](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?node-id=489-17173&t=oQKTRRJG5GzUEDGM-4)

## Acceptance criteria

* On the landing page…
	* as a visitor …
		- [x] I can see a search bar with the placeholder text “Search”
		- [x] I can enter a search query in a search bar and, upon submission of the search, am taken to the library page which displays the search results for the term I have entered in the search bar. 
		- [x] when landed on the library page after submitting a search term on the landing page, the search term is displayed in the search bar on the library page.

**Comment by beccaklam** [comment]
This looks fine to me ✅

**Comment by beccaklam** [comment]
@jhonatan-lopes we should confirm with Joycelyn the search phrase the RCC team wants is "Search our Curriculum", not sure if Curriculum needs to be capitalized either
