### ISSUE TITLE
Landing page - Link to library pre-filtered by featured "content type"

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10432]
## Description

Enable the navigation to the library page, pre-filtered for a "content type". 

The content types which should be available in this filter link section are defined by editors on the library page as featured content types. 

<img width="256" alt="image" src="https://user-images.githubusercontent.com/24797493/230231161-497d01fb-f5c7-4f57-a460-ddcfa334d707.png">

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Design](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?node-id=489-17173&t=oQKTRRJG5GzUEDGM-4)

## Acceptance criteria

* On the landing page…
	* as a visitor …
		- [x] I see a list of content types that are available in the library and can click the name of a content type to navigate to the library page that is pre-filtered by the content type that I have clicked.
	* as an editor …
		- [x] I can select multiple instances of the “content type” taxonomy that should be featured on the page.

**Comment by beccaklam** [comment]
This looks fine to me ✅
