### ISSUE TITLE
Profile index - List profiles

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10434]
## Description

Enable the basic listing functionality of the profile index.

<img width="256" alt="image" src="https://user-images.githubusercontent.com/24797493/230471055-786a94f9-4f9f-48b7-84e4-f5e8f0c5837b.png">

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

* On the profile index page …
	* as a visitor …
		- [x] I can see all profiles that are related to any detail page in the for the Responsible Computing Challenge Playbook library.
		- [ ] I can see the profile listed in alphabetical order.
		- [x] *I can click on the listed profiles and am taken to the profile page for that profile.*
		- [x] *when I visit the profile index with a non-default locale (i.e. `/fr/`), the profile page I am navigating to is also of the same non-default locale  (i.e. `/fr/`) as the index page.*

**Comment by beccaklam** [comment]
Aside from again asking for clarification of what the final checkbox means, this looks fine to me ✅

**Comment by beccaklam** [comment]
@jhonatan-lopes @danielfmiranda Just noticed that the names are not listed alphabetically on the profile index page:
![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/20977376/5789d298-c28d-459b-88aa-a8502735d27f)

**Comment by jhonatan-lopes** [comment]
Yes, that will be fixed post-MVP by #8813
