### ISSUE TITLE
Profile detail route - List latest related detail pages

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10436]
## Description

Enable the listing of the latest related detail pages on the profile detail route. 

<img width="256" alt="Screenshot 2023-04-06 at 12 14 20" src="https://user-images.githubusercontent.com/24797493/230473708-6d746c09-c83e-41f8-918b-af4ad7351064.png">

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

* On a profile detail page …
	* as a visitor …
		- [x] I can see the latest **three** detail pages published, that are related to the profile, and can navigate to the detail pages by clicking on the listing items.
		- [x] *when I visit the profile detail page with a non-default locale, the links to the detail pages use the same non-default locale as the profile detail page*

**Comment by beccaklam** [comment]
This looks fine to me ✅
