### ISSUE TITLE
Profile detail route - Link to profile pre-filtered library page

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10437]
## Description

Enable the button that links to the library page. 

When following the link the library page is filtered for the profile from which's detail route we just came. I.e. when I view the profile detail route for "Harvard University" and then follow the link to the library page, the library page is filtered for "Harvard University" (with the profile/collaborators filter).

<img width="256" alt="Screenshot 2023-04-06 at 12 19 03" src="https://user-images.githubusercontent.com/24797493/230474648-cb9f7c59-327a-4ee4-83ad-db86ca65da20.png">

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

* On a profile detail page …
	* as a visitor …
		- [x] *I can see a button-style link that navigates to the library page.*
		- [x] *when I follow the link to the library page, the library page is filtered for detail pages related to the profile which’s profile page I came from (with the profile/collaborators filter).*
		- [x] *when I visit the profile detail page in a non-default locale, the link to the library page uses the same non-default locale.*

**Comment by beccaklam** [comment]
This looks fine to me ✅
