### ISSUE TITLE
Landing page - Latest detail pages

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10431]
## Description

List the 3 latest detail pages on the landing page. 

<img width="256" alt="image" src="https://user-images.githubusercontent.com/24797493/230230742-e37f6ed2-a4d9-4828-bca7-e17e00fbeff8.png">

[Design](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?node-id=489-17173&t=oQKTRRJG5GzUEDGM-4)

## Acceptance criteria

* On the landing page…
	* as a visitor …
		- [x] I can see cards for three most recent entries in the library and can click the card title to get to the detail page for that content.

**Comment by beccaklam** [comment]
Just confirming that editors can 'hack' this feature by editing the publication date, correct? Otherwise this looks fine to me ✅

**Comment by tbrlpld** [comment]
@beccaklam Yes. That is set on the detail page itself and not on the landing page.

**Comment by Gbaldassano** [comment]
The figma labels this as 'Featured articles' but we don't have that ability currently and won't for MVP  - the ability to pull in featured articles will be post MVP

**Comment by jhonatan-lopes** [comment]
The feature articles discussion might be related to #8810

**Comment by beccaklam** [comment]
@jhonatan-lopes @Gbaldassano The MVP should have the ability to feature the three most recent articles. The 'hack' for "Featured Articles" is for editors to change the publication dates of the articles they want to feature so that they can choose which articles shows up on the home page.
