### ISSUE TITLE
Detail page - Link to profile pages

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10439]
## Description

The related profiles are listed and link to their profile detail routes.

<img width="256" alt="Screenshot 2023-04-06 at 12 37 21" src="https://user-images.githubusercontent.com/24797493/230477960-d77da1f5-7e5b-4889-976d-adc20850cf46.png">

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

* On a detail page … 
	* as a visitor … 
		- [x] I can see the related profile’s listed. 
		- [x] I can navigate to the related profile’s page (lower priority). 
		- [x] *when I visit the detail page in a non-default locale, the link to the profile page uses the same non-default locale.*

**Comment by beccaklam** [comment]
This looks good to me ✅
