### ISSUE TITLE
Library page - Search

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10441]
## Description

Enable searching of detail pages by keyword. When a search term is submitted, the list of detail pages is only showing those that contain the search term in one or more fields. 

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria

As a visitor, on the library page, ...

- [x] I can search the detail pages by keyword. 
- [x] when I submit a search term, the listing of detail pages is filtered for items that contain the keyword in the title, introduction, overview or in one of the associated taxonomy instances.
- [x] I can see the total number of results available, based on the filter I have selected.

**Comment by beccaklam** [comment]
This looks fine to me.
