### ISSUE TITLE
Taxonomies - Unique-per-locale slugs

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10442]
Add unique-per-locale slugs and use slug to filter by taxonomy instead of ID. 

Currently, the taxonomies (`ResearchRegion` and `ResearchTopic`) are filtered for by ID. For one, it looks a bit odd in the query parameters. Worse though, this is wrong when dealing with localization. E.g. you filter for region with `id=2`, but then you want to filter the detail pages for the equivalent region of a different locale. So really you would be filtering for two different ids (the default locale one and the active locale one).

Refer to the [BuyersGudieContentCategory](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/pagemodels/buyersguide/taxonomies.py#L31-L45) model for a reference implementation of unique-per-locale slugs.

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

**Comment by Gbaldassano** [comment]
@kevinhowbrook are you able to pick this ticket up? @jhonatan-lopes - could you let me know if this still needs grooming?

**Comment by kevinhowbrook** [comment]
@jhonatan-lopes what's the actual plan here?
Since these taxonomies inherit from a new abstract BaseTaxonomy which doesn't have a slug field.

**Comment by jhonatan-lopes** [comment]
We need to add a slug field to the `BaseTaxonomy` class and then enforce uniqueness of the slug field together with locale, as was done [in here](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/pagemodels/buyersguide/taxonomies.py#L35).

We need to expose the `slug` field to editors and make it auto-generated from the taxonomy's name, just as we do in the [BuyersGuideContentCategory](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/pagemodels/buyersguide/taxonomies.py#L9).

**Comment by tbrlpld** [comment]
@kevinhowbrook @jhonatan-lopes Just want to flag that you also need to override `validate_unique` to allow the unique-together constraint of slug and locale (because locale is a non-editable field and those are usually in the "exclude" list which means it's ignored during validation)

https://github.com/MozillaFoundation/foundation.mozilla.org/blob/295fe9f53f9bc7e5f916d43cfb171c4d2adb515a/network-api/networkapi/wagtailpages/pagemodels/buyersguide/taxonomies.py#L42C16-L45

**Comment by kevinhowbrook** [comment]
This is ready to review here https://github.com/MozillaFoundation/foundation.mozilla.org/pull/10643
