### ISSUE TITLE
Allow long words in breadcrumbs sections to be truncated

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10440]
The titles in the playbook tend to get long (e.g. the landing page will be “Responsible Computing Challenge Playbook”). We want to handle that somehow. I don’t know how we currently handle that. See [this comment](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb?node-id=326:16188#368579662) in Figma

**Comment by jhonatan-lopes** [comment]
Design comments on breadcrumbs truncating:

![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/61277874/7fe9332e-d1c4-444d-bab2-5f9019f17117)

**Comment by danielfmiranda** [comment]
Hi @beccaklam!

This update has been merged into main and is now ready for QA testing on staging. I was wondering if you could please take a look whenever you have a free moment and let me know if everything is looking as expected? 

Thanks!

**Comment by beccaklam** [comment]
Hi @danielfmiranda is there an instance of the RCC Playbook on staging now? I'm not clear on where I can test this on staging?

**Comment by danielfmiranda** [comment]
Hi @beccaklam! Apologies for the confusion, at the moment there is no instance of the RCC playbook on staging, however, this can be tested using the Research hub as they share the same template for breadcrumbs! Alternatively, you can wait until the RCC Feature branch is merged into main this coming Wednesday 06/28/23

**Comment by beccaklam** [comment]
Hi @danielfmiranda no worries I can now test it in the RCC playbook review app. Just confirming am I testing the line breaks for the breadcrumbs when words get long?

**Comment by danielfmiranda** [comment]
Hi @beccaklam, that is correct! The QA for this ticket would just be double checking that the breadcrumbs wrap as expected. Some screenshots for reference can be found in the PR here: https://github.com/MozillaFoundation/foundation.mozilla.org/pull/10766


Thanks!

**Comment by beccaklam** [comment]
Hi @danielfmiranda thank you for clarifying, everything is looking as expected! ✅
