### ISSUE TITLE
Detail page - Full resource link

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#10466]
## Description

Enable linking to the full resource. The full resource can be a document, a page or an external URL. Often this is going to link to a child page of the detail page itself, but the page could be  somewhere else on the site.

<img width="256" alt="Screenshot 2023-04-06 at 12 41 16" src="https://user-images.githubusercontent.com/24797493/230479464-31d72de3-0ad6-468f-8cc6-dbb9927f3d7d.png">

<img width="256" alt="image" src="https://user-images.githubusercontent.com/24797493/230480006-a862235c-ac09-4960-8f75-1fa64e4a6494.png">

[Epic](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339) | [Designs](https://www.figma.com/file/dPGD3acNbT75dvEGzNaGUb/Responsible-Computing?t=zoMb9zxg25R0T6yt-6)

## Acceptance criteria 

* On a detail page … 
	* as a visitor … 
		- [x] I can navigate to the full course material resources. 
	* as an editor … 
		- [x] I can specify the label and the target for a link to the full course material resource. The target can be a document, page or external URL.
		- [x] I can create more than one such link.

**Comment by beccaklam** [comment]
This looks good to me ✅

**Comment by beccaklam** [comment]
cc: @jhonatan-lopes @danielfmiranda @mmmavis @sabrinang @nancyt1 This is working but we're getting some strange styling when we have three buttons squished. Not exactly sure what we should do about this yet:
![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/20977376/7de04ce9-0e27-49a5-8abd-6869b63ac1a1)
