### ISSUE TITLE
Wagtail-localize language switcher partially hidden

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#10464]
One issue I didn’t catch during the Wagtail 4.1.3 QA session, is the drop-down menu from the language switcher on translated pages is partially hidden behind the .po file download button and the promote tab.

Steps to reproduce:
- Edit any page translation, e.g https://foundation.mozilla.org/cms/pages/20995/edit/
- Try to switch to another language using the drop-down menu at the top

<img width="340" alt="Capture d’écran 2023-04-05 à 14 37 46" src="https://user-images.githubusercontent.com/1294206/230082825-cad45443-0ca1-4ae8-9e76-890e8e5002e8.png">

Note: We’re not using the latest wagtail-localize build, this issue may have been fixed in the latest release (currently 1.5)

**Comment by tbrlpld** [comment]
@TheoChevalier Has this be reported to the Wagtail and/or Wagtail Localize repos?

**Comment by TheoChevalier** [comment]
@tbrlpld I haven’t, but I’m happy to report to either

**Comment by TheoChevalier** [comment]
I’ve filed https://github.com/wagtail/wagtail-localize/issues/688

**Comment by jhonatan-lopes** [comment]
Fixed by #11443
