### ISSUE TITLE
[Epic] Replace petition form functionality with a FormAssembly equivalent

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#10460]
Since Cinchy is being decommissioned in May, we will be replacing the current functionality of our petitions by utilizing a FormAssembly form in place of the current form.

[Petition example](https://foundation.mozilla.org/en/campaigns/youtube-user-controls/):

![petition.JPG](https://images.zenhubusercontent.com/62b26ef0ef391812192d0391/a6870c9e-06dd-4cd9-b86d-adfd80cdef3d)

The goal of this is for FormAssembly to be a 1:1 replacement and maintain all functionality of the current petition pages, which includes:

- Validation of form fields (might already be included with FormAssembly head code)
- Autopopulated hidden field that sends the form ID along to FormAssembly (probably best inserted back-end)
- Localization of the form
- Sticky scrolling
- Modal pop-up after a successful submission
- ShareProgress DOM rewrite that displays the four share buttons
- Correct ARIA labels for the forms

Some things we might fix while we're in there:
- The form header skips several heading levels and goes straight to h5
- Auditing the page for accessibility with WAVE shows that the Share Progress implementation throws a couple of accessibility errors for empty links, we could look into those.

And of course responsiveness to different screen sizes but that's always a given.

The head and body code for the form can be found [here at FormAssembly](https://mozillafoundation.tfaforms.net/forms/builder/5.0.0/5)

Stakeholder note:
The engagement team has expressed interest in 'resurrecting' these two existing petitions in an April timeframe: 
Petition: [Mozilla Foundation - Tell Amazon Ring: stop sharing information with police](https://foundation.mozilla.org/en/campaigns/tell-amazon-ring-stop-sharing-information-police-services/)
Petition: [Tell Slack: #BlockAbuse](https://foundation.mozilla.org/en/campaigns/petition-slack-block-abuse/)

As the new petition system is getting set up, please list any potential flags we should take into account when it comes to reusing existing petitions between tech stack transitions. (For example, is data formatting 1:1? What is the workflow for reusing existing petitions?, etc)

**Comment by Gbaldassano** [comment]
@mmmavis @mtdenton I added some questions around what reusing existing petitions will look like in regards to this work in the body of this ticket - can we look into this?

**Comment by mmmavis** [comment]
@Gbaldassano Thanks for passing the info from stakeholders! 

Related to that - 
@mtdenton  I'm wondering how we want to roll out this Cinchy-to-FormAssembly transition on fo.mo website. Originally I was thinking to have the new implementation live on a feature branch until we are ready to make the switch (i.e., have it merged into `main` branch). However, this could be risky as we have so many active campaign/petition pages and we probably want to test the work on production before applying the new flow to all the existing forms. Will testing on staging be sufficient enough? If not, how do we low-key roll out the new flow to production for testing purpose first?

**Comment by Gbaldassano** [comment]
@mmmavis @mtdenton do we know how we plan to handle existing petitions in terms of switching over to form assembly? Asking because stakeholders are interested in setting up a petition in mid May - does it make sense to ask them to wait until FA is up and running or can they launch with existing tools and migrate after?

**Comment by mtdenton** [comment]
We've got testing to do to make sure that everything is sending client-side into FormAssembly on our staging environment, but since nothing is stored on our side, cutting over to the new form for all petitions should be pretty seamless once we're ready for prod. If everything is good to go on that FA/Salesforce side and our code is posting submissions as intended with all of the correct fields filled out then worst case scenario is that they'll be in the same boat as all of the other petitions if we have hiccups along the way.

**Comment by simont-cr** [comment]
Closed per 2024 ticket purge.
