### ISSUE TITLE
SPIKE - FormAssembly publishing options

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10468]
FormAssembly has [a few ways for publishing their forms.](https://help.formassembly.com/help/publishing-options) Let's figure out which option fits our needs the most.

Things to evaluate:
- localization
- form validation
- styling
- after submission screen (we want our Share modal to show up)
- analytics
- flexibility with the markup code (e.g., are we able to modify their code snippets? )

**Comment by mtdenton** [comment]
I'm heavily recommending "Embed HTML".

- FA hosted form won't go into the page.
- Iframe would restrict analytics measurement and styling and JS event detection will be far more difficult
- Server-side pulling will restrict our ability to use Wagtail localization since the form is pulled directly from FA on user request. If the form ever changes on the FormAssembly side, it will cause big problems in either the Embedded or API situation for us.

We need to stress the importance that this form should never change on the FA side unless there's a concerted effort between CRM and Web Platforms to replace the existing form (in which case I'd recommend creating a brand new form instead). Doing so would break this form in production.

**Comment by mmmavis** [comment]
Agreed what you said, @mtdenton . I was debating what's more suitable between "Embed HTML" and server-side pulling. I was favoring server-side pulling because I assumed the form on FormAssembly side would get changed often. With your explanation above, it makes sense to go with the "Embed HTML" option.

**Comment by mmmavis** [comment]
Two things i need to look into more before we come to a conclusion:

- FormAssembly’s form validation logic & if error messages can be localized
- FormAssembly script auto redirects users after form submission. I need to make sure that can be turned off somehow

**Comment by mmmavis** [comment]
Hi @mtdenton @Gbaldassano ,

I dived into the `HTML embed approach` yesterday by testing it out locally and going through their docs. Please see below for my findings. (Note: I haven't had time to look into the `Server-Side Script (API)` embed option we were also considering. I don't have anything to share on that front yet.)

- **Draft PR for my quick test: https://github.com/MozillaFoundation/foundation.mozilla.org/pull/10487**
- **Review app for demoing purpose:** [https://foundation-s-mavis-form-byaons.mofostaging.net/en/campaigns/exist-a-key/](https://foundation-s-mavis-form-byaons.mofostaging.net/en/campaigns/exist-a-key/)

## Security Concern

- This one is the most concerning to me. In order for the FormAssembly script to work, we’ll need to update a few CSP configs including allowing `unsafe-eval` for `script-src`. This opens up the possibilities for attackers to inject scripts to our site and services. [[Fo.mo](http://fo.mo/)](http://Fo.mo) site relies on many other external scripts, though the sources of them are probably trustworthy, we still have no control / can’t monitor how the scripts are written.

## After Submission Screen - Page will be redirected

- I reached out to FormAssembly support because I couldn’t figure how to turn off the redirect. They responded and said the HTML embed method **will redirect users** to a thank you page of our choice. We can redirect users to the same URL that user is currently on and pops up the Share modal so it feels like they are not being sent away. However, the UX is not ideal for users as the page will be reloaded completely.

## Localization / UX Issues

- Form labels (`First Name`, `Email`, `I'm okay with Mozilla handling my info as explained in this Privacy Notice.` etc) can be localized and pulled into site via Pontoon.
- **Error messages are controlled by FormAssembly script**. We can show localized error messages by loading the corresponding FormAssembly JS file (think about it like loading `en.js` vs `fr.js` vs `pl.js`). See my quick test [[here](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/10487/commits/99df1c15172282ddf4b1b4e5a728d6de32924452#diff-c11823fcd21296d4abee8619b69d658871938b73cfd496b308fd4593e5369f6c)](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/10487/commits/99df1c15172282ddf4b1b4e5a728d6de32924452#diff-c11823fcd21296d4abee8619b69d658871938b73cfd496b308fd4593e5369f6c).
    - Out of all languages we support on [fo.mo](http://fo.mo/), `Frisian` and `Swahili` are currently not supported by FormAssembly. We can [[submit localized Frisian/Swahili strings to FormAssembly](https://app.formassembly.com/translate)](https://app.formassembly.com/translate) and ask them to make it available.
- Although we can have localized error messages, the text itself is defined by FormAssembly. For example, we can’t change the FormAssembly defined standard `This field is required` text into something more relevant to the field like `Please enter your email`. You can see list of predefined text strings on [[FormAssembly translate page](https://app.formassembly.com/translate)](https://app.formassembly.com/translate) (click on any “translate” link).
- Form error alert popup cannot be turned off. In fact the whole validation flow doesn’t seem good or modern to me.  

https://user-images.githubusercontent.com/2896608/231276948-b93d08f5-822a-492a-8137-ab09b13190f1.mov

**Comment by Gbaldassano** [comment]
Thanks @mmmavis - from my POV the security concern seems the most troubling, did FormAssembly support have any comments or thoughts on how to mitigate that risk?
cc: @mtdenton

**Comment by mmmavis** [comment]
I will reach out to support today and see what they suggest.

**Comment by mtdenton** [comment]
Weird that they would need `unsafe-eval`. I'm interested to know what part of their script actually requires this expression, @mmmavis is this something you encountered yourself or is this in their docs somewhere?

**Comment by mmmavis** [comment]
Hi @mtdenton these are the errors I'm getting without allowing `unsafe-eval`

![image](https://user-images.githubusercontent.com/2896608/231556995-337511b0-8098-46b6-8027-d54e0ded5759.png)

The prettified version of the [original FormAssembly script](https://mozillafoundation.tfaforms.net/wForms/3.11/js/wforms.js) can be found [here](https://gist.github.com/mmmavis/5941813a43d0d4f6304e9e67aaed618e). Searching for `eval(` in the code gives me 7 results.

---

I reached out to FormAssembly support this morning using the live chat and the rep kept suggesting me to go with iFrame embed 😵‍💫 I told the rep iFrame wasn't an ideal solution for our needs and asked them to forward my q to the engineering team. They'll e-mail me back once they have an update.

**Comment by shing-mofo** [comment]
@mmmavis @mtdenton Have you reached out to our account rep directly? In the contracting process, we had redlines to the standard contract - the rep may be able to get better support or connect you to someone who may be able to provide you with a level of support beyond their standard disclaimer.

**Comment by Gbaldassano** [comment]
@mmmavis & @mtdenton to look into 'Plan B' for iFrame.

**Comment by Gbaldassano** [comment]
Tagging @maryhelenyj for visibility - @mtdenton  @mmmavis When you have a chance please let us know if the feedback from Jeremiah helps clear things up or if we should start looking into Plan B?

**Comment by Gbaldassano** [comment]
@mmmavis confirming as decided on Friday 4/21 the plan is to move forward with FA as is.
cc: @mtdenton

**Comment by mmmavis** [comment]
As discussed on Slack - we've decided to go ahead with the HTML embed option with two additional action items

1. follow up with FA to see if they are closing the security gap on their end (there's an email thread for this already)
2. in 4-6 months, checking in and evaluating the security concerns then (ticket filed #10535)

**Comment by mmmavis** [comment]
Closing this SPIKE ticket!
