### ISSUE TITLE
Fix `#mofo-ra-foundation` slack bot

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#10494]
## Description
In the past, the slack channel `#mofo-ra-foundation` had a slack bot called "HerokuReviewAppBot" that would post the following every time a new review app was created:

```
Login: admin
Password: <randomly_generated_password>
```

However, the bot seems to be disconnected/broken as when we create review apps, the messages are no longer sent. 

This means that we have to workaround this by logging into the review app on heroku, opening a bash terminal for the app, and then running python commands to either change the password or create a new user.

We should fix this functionality so devs and stakeholders can easily log into the CMS on review apps in order to test them out.

Most likely, the error has to do with the environment variables `GITHUB_TOKEN` which is used for github API authentication, or `SLACK_WEBHOOK_RA` which is the webhook to the `mofo-ra-foundation` channel. 

## Related tickets

**Here are some related tickets that we can use for reference:**
- [https://github.com/MozillaFoundation/mofo-devops/issues/598](https://github.com/MozillaFoundation/mofo-devops/issues/598)
- [https://github.com/MozillaFoundation/foundation.mozilla.org/pull/1646](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/1646)

## Acceptance Criteria

- [ ] As a dev, I can create a new review app on heroku and the admin credentials will successfully be posted in the slack channel `#mofo-ra-foundation`.

**Comment by mmmavis** [comment]
Thanks for creating this epic @danielfmiranda !

**Comment by danielfmiranda** [comment]
Thanks @mmmavis! I actually added the [epic] label by mistake, I have removed it from the title of this ticket and groomed the description/acceptance criteria as well!

**Comment by jhonatan-lopes** [comment]
I think the bot is working now. @mtdenton can we close this one?

**Comment by mtdenton** [comment]
Yep we're good here, closing ticket
