### ISSUE TITLE
[EPIC] Refactor templates to work with `django-pattern-library`

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#10492]
This epic is used to group the work related to updating our html template directory structure in order to work with the package [django-pattern-library](https://torchbox.github.io/django-pattern-library/).

### Setup:
- [ ] [https://github.com/MozillaFoundation/foundation.mozilla.org/issues/9665](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/9665)

### Template Updates:
- [x] [https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10393](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10393)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-148)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Per https://app.zenhub.com/workspaces/mofo-web-platforms-team-585335eab729771d0736378d/issues/gh/mozillafoundation/foundation.mozilla.org/10492 ( https://app.zenhub.com/workspaces/mofo-web-platforms-team-585335eab729771d0736378d/issues/gh/mozillafoundation/foundation.mozilla.org/10492|smart-link ) , this EPIC currently has no tickets associated. Also, the only two tickets included as part of the description are already closed. Abandoning this ticket for the time being.
