### ISSUE TITLE
Profile slug tries to access id before it is set

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#10509]
### Describe the bug
The `Profile` model tries to auto set-up slugs based on the `name` and `id` by overriding its `save` method. However, the `id` is not set yet, since the instance has not been saved to the database yet. Hence, you end up with slugs that contain `None` for the `id`.

### To Reproduce
1. Go to 'cms/snippets/wagtailpages/profile/', create a new `Profile`
2. On a Django shell, inspect the created profile and check the `slug`
3. See that the `slug` is set to `{profile_name}-none`

### Expected behavior
The function expected to set the `slug` to `{profile_name}-{id}` where `{id}` is the database id (an integer).

However, I believe that a better behaviour would be to expose `slug` field to CMS editors and pre-populate it with a slugified `profile_name`. This way we can let editors deal with conflicts and remove the `id`s from the routes (as specified in #10413)

**Comment by danielfmiranda** [comment]
Just tested this out and looks good to me! Moving to ready for prod
