### ISSUE TITLE
Empty dropdown state on research hub library

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/foundation.mozilla.org#10511]
### Describe the bug
The dropdown in the upper right on the /research/library/ page doesn't have options when selected:

### To Reproduce
1. Go to https://foundation.mozilla.org/en/research/library/
2. Click on down caret icon in the upper right
4. See error / empty state

### Expected behavior
- options should appear for selection

### Screenshots
![Screenshot 2023-04-18 at 12-20-51 Library](https://user-images.githubusercontent.com/2492510/232883872-386bcf7c-b917-4d32-9f15-f69411b47be6.png)

### Desktop (please complete the following information):
 - OS: MacOS 13.2.1
 - Browser Firefox 111.0.1

**Comment by mtdenton** [comment]
@sabrinang this and #10595 somehow got messed up on Zenhub, you probably already know but they're both resolved
