### ISSUE TITLE
Changing the order of a highlight on What You Can Do doesn't change the order

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#10515]
### Describe the bug
https://foundation.mozilla.org/en/what-you-can-do/ has highlight sections that can be updated in the CMS. The CMS has up/down arrows to change the order of the highlights but the change in order are not reflected on users viewing the page.

### To Reproduce
1. Go to https://foundation.mozilla.org/cms/pages/168/edit/ 
1. Click on an arrow to move a highlight up or down
1. See the highlight move in the CMS
1. See error: the highlight does not change in the page preview

### Expected behavior
The order of the highlights in the CMS should be the same as on the front-end

### Screenshots
![](https://user-images.githubusercontent.com/1068783/233733697-c2d5332c-f473-4087-8266-fb1a4d209eb1.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-150)

**Comment by simont-cr** [comment]
@kristinashu Could you please confirm if this is still a bug in need for fixing? If it is, I would say we could have it as a P1 to get it resolved soon.

**Comment by kristinashu** [comment]
This is still an issue and is related to https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11919

**Comment by robdivincenzo** [comment]
A solution involves undoing work done in #11493, so this needs discussion.
