### ISSUE TITLE
Newsletter Bug - Fix null value for the source value that feeds into Acoustic

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10538]
This is a request from Slack. Full thread can be found [here](https://mozilla.slack.com/archives/C98GW3P7X/p1682437114403409).

Currently the majority of our Newsletter forms have a null value for the source value that feeds into acoustic.

A working example of the source value being returned is on any of the sign up forms via the common voice webpage. The data being returned is:

```json
"newsletters": [
  {
    "name": "common-voice",
    "subscribed": true,
    "format": "H",
    "lang": "en",
    "source": "https://commonvoice.mozilla.org/en",
    "unsub_reason": null
  },
  {
    "name": "mozilla-technology",
    "subscribed": true,
    "format": "H",
    "lang": "en",
    "source": "https://commonvoice.mozilla.org/en",
    "unsub_reason": null
  }
]
```

An example of it not working is on the Foundation home page. Data being returned is:

```json
"newsletters": [
  {
    "name": "mozilla-foundation",
    "subscribed": true,
    "format": "H",
    "lang": "en",
    "source": null,
    "unsub_reason": null
  }
]
```

**Comment by mmmavis** [comment]
Did some investigation and found out the code used to include "source url" somehow got lost when we were doing the Cinchy/SQS to Basket transition in April 2021 😬 . I'll submit a fix soon. I will also file a new ticket to revisits tests for newsletter signup. We'll need to set up tests if we haven't done so already. More details in the to-be-filed ticket.

**Comment by mtdenton** [comment]
@danielfmiranda this is clear to be pushed without stakeholder QA, they will test tomorrow.

**Comment by danielfmiranda** [comment]
Got the OK from Tyler to push this to prod in the engineering slack channel. Moving to ready for prod!
