### ISSUE TITLE
Re-evaluate concerns with FormAssembly in Q3/Q4 2023

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10535]
Context: https://github.com/mozillafoundation/foundation.mozilla.org/issues/10468

Revisit our current concerns with FormAssembly in Q3/Q4 2023. See if there are improvements or additional security measures we can put in.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-151)

**Comment by mtdenton** [comment]
@mmmavis @Gbaldassano we're a bit late on this one but worth throwing into some discussions on how we make this more sustainable for stack.

Adding this to our maintenance roadmap project.

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Tyler Denton Do you still feel that we need to have some discussions on this regard, once Genevieve is back?
