### ISSUE TITLE
Update GitHub ticket templates

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10546]
## Tasks

- [ ] Disable "blank" ticket by setting `blank_issues_enabled` to `false` (see [doc](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser))
- [ ] Update [all ticket templates](https://github.com/MozillaFoundation/foundation.mozilla.org/tree/main/.github/ISSUE_TEMPLATE) to include stakeholder info. Something like `Who should be informed when this work is done: (stakeholder name or github handle)`

**Comment by simont-cr** [comment]
Closed per 2024 ticket purge.
