### ISSUE TITLE
[PNI] Dashboard check-in

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#10553]
To do:
- [x] Check in on PNI dashboard and see if there's enough data to draw some conclusions on how our designs have affected our metrics
- [x] ~Add notes to the dashboard on progress~ Unable to add notes, notes can be found in this [doc](https://docs.google.com/document/d/1sMUmNo2_vn5mCzEWWgGg82JuQoQQMZHkMRmXCWs2W9g/edit?usp=sharing)

**Comment by beccaklam** [comment]
Made some notes in this [doc](https://docs.google.com/document/d/1sMUmNo2_vn5mCzEWWgGg82JuQoQQMZHkMRmXCWs2W9g/edit?usp=sharing). Trying to see if I can add notes to lookerstudio or if that can only be done in analytics.

**Comment by nancyt1** [comment]
I added my comments! There wasn't a lot that I could pick out and a lot of metrics still feel the same.
