### ISSUE TITLE
[FA] Newsletter signup

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10560]
FormAssembly cannot handle newsletter signup. We’ll need to rely on Basket API to subscribe petitioners to newsletter.

Note so that the current form should still work during the transition/QA period, we should *not* modify the existing backend code. If anything we should create new function for that.

Details TBD. 

## Dev Tasks

- [ ] find out if we need a default value for newsletter. Currently `mozilla-foundation` is the default (set in petition.jsx)

## Acceptance Criteria

- [ ] TBD

**Comment by mtdenton** [comment]
Making a new repo for this lambda function, this will be a separate ticket over there for us to track. I'll add that repo to Zenhub so we can have it on this board.
