### ISSUE TITLE
Newsletter signup should send country info to Basket

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10575]
Related to #3481

Stakeholders: Brandon and Dan

Feedback from Brandon and Dan that country info should be included in newsletter signup. Full thread about the tests they did today is [here](https://mozilla.slack.com/archives/C98GW3P7X/p1683047646309579?thread_ts=1682437114.403409&cid=C98GW3P7X)

## Dev Tasks
- [x] include country in `basket.subscribe`

**Comment by danielfmiranda** [comment]
Discussed with Tyler, this is good to go on prod
