### ISSUE TITLE
[FA] [Post-Launch]  campaign_id should be a required field

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10579]
Ticket will need to be groomed.

In [campaigns.py](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/pagemodels/campaigns.py), `campaign_id` isn't a required field on various classes. I'm not sure if somewhere in the old pipeline we had a default value set up for campaign id, but it seems like we'll need turn it into a required field. 

From Mary Helen,
>  The campaign id needs to be sent to Salesforce because without that, Salesforce won't have a way to match to an existing Campaign and then create the corresponding Campaign member record for the person filling out the petition. 

## Dev Task
- [ ] find out what petition/signup/callpower snippets have an empty `campaign_id` and decide what to do with them
- [ ] turn `campaign_id` into a required field

**Comment by mtdenton** [comment]
@mmmavis Wow, super surprised that it isn't already a required field. Thanks for calling this out! I'd say let's try to make this change as the very last step before we launch if possible (if we have time, we may not have that luxury). Otherwise, we can launch without making this a required field and this needs to be the very next ticket that we work after launch and we'd need to get this change to prod ASAP or we risk losing signatures on any new petitions that might get created.

@Gbaldassano I don't know if there's any petitions planned for late May/early June, but we will want to send out a PSA about this if there's not time to fix this before we're forced to cut over to FA. Basically, in the week following the switch, stakeholders *must* fill out the Campaign ID field when they're making a petition in the Wagtail dashboard or they will lose signs on their petitions. If we can't squeeze this in, a fix will come ASAP after launch making it where the user will get an error if they try to save the petition without filling out the Campaign ID field.

**Comment by Gbaldassano** [comment]
Thank you for flagging @mtdenton & @mmmavis: a few clarifying questions before we give stakeholders a heads up:

- Has not having the campaign ID field filled out not been an issue in the past? Is this a new requirement that FA is adding to the equation, or have we always needed to fill out the campaign ID field and just haven't? 
- How has SF been tracking Campaign ID for petitions in their current state?
- How will this switch over affect existing petitions that don't have the campaign ID filled out? Will we need to go back and ask the team to fill out this field for pre-existing petitions?

@maryhelenyj FYI

**Comment by maryhelenyj** [comment]
@Gbaldassano I can't speak to how it's being done now but the Campaign Id is a Salesforce requirement not a Form Assembly requirement. Without the Id, Salesforce won't be able to assign the individual to a campaign which is the way we are recording that they signed the petition. It could be that Cinchy was somehow adding the Id at some point but I'm not sure.

**Comment by Gbaldassano** [comment]
@maryhelenyj gotcha - so the requirement is on Salesforce's side, not Form Assembly's - good to know! Def something I want to include in the next comms that go out.

@mtdenton @mmmavis following up on the last question, do we happen to know how, if at all, this switch over affect existing petitions that don't have the campaign ID filled out?

**Comment by mmmavis** [comment]
@mtdenton I'm not comfortable running db query to find out Petition snippets that are missing campaign id. Maybe this is something Daniel or Jhonatan can help?

**Comment by mmmavis** [comment]
@mtdenton probably safer to ask a second dev to double check 😅  - I ran the query and this is the only [petition snippet](https://foundation.mozilla.org/cms/snippets/wagtailpages/petition/edit/34/) has doesn't have campaign id.

**Comment by danielfmiranda** [comment]
Hi @mtdenton @Gbaldassano @maryhelenyj!

I was wondering if anyone knew how the Salesforce campaign ID UTM parameter should be named in the URL.

I cant seem to remember if it was `campaign_id` or `c_id` 😅 

Thanks!

**Comment by maryhelenyj** [comment]
Hi Daniel,

I sent you a very long explanation via slack (sorry!) which I am hoping
answers this (or at least part of it) but let me know if you have more
questions. There's one part specifically I called out that I think @Mavis Ou
***@***.***> or @Tyler Denton ***@***.***>
will have more clarity on than I do. Happy to answer any additional
questions!

Best,
MH

**Comment by danielfmiranda** [comment]
Hi @mtdenton @Gbaldassano!

This has now been merged into main and is live on staging. I was wondering if one of you can please take a look and help QA? 

To do so:

1. Visit https://foundation.mofostaging.net/cms/snippets/wagtailpages/petition/edit/306/
2. Confirm that the campaign ID is required
3. Visit https://foundation.mofostaging.net/en/campaigns/tell-slack-make-dms-safe/?thank_you=true
4. Hover over the purple "Yes, Ill chip in" button and confirm that the campaign ID is part of the URL preview at the bottom left corner of the screen.

Thanks in advance!

**Comment by Gbaldassano** [comment]
@danielfmiranda just checked, confirming campaign ID is required and I see it when hovering over the CTA!

**Comment by mtdenton** [comment]
Reminder that we need to update docs after prod push to reflect that campaign ID is now a required field!
