### ISSUE TITLE
Can't access redirect page in the CMS

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#10584]
### Describe the bug
Can't access redirect page in the CMS https://foundation.mozilla.org/cms/redirects/

### To Reproduce
1. Go to https://foundation.mozilla.org/cms/redirects/
2. See 500 error

<img width="636" alt="image" src="https://user-images.githubusercontent.com/1068783/236291744-7334c45c-7758-485b-914a-4982f47eb759.png">

### Expected behavior
Page should load and I should be able to see existing redirects and create new ones

**Comment by kristinashu** [comment]
cc @kevinhowbrook in case you have any insights

**Comment by jzinner** [comment]
### Server error logs: `Missing staticfiles manifest entry for 'wagtailredirects/css/index.css'`

> May 04 18:47:36 foundation-mozilla-org app/web.6 Traceback (most recent call last):
> ...
> May 04 18:47:36 foundation-mozilla-org app/web.6  File "/app/.heroku/python/lib/python3.9/site-packages/django/contrib/staticfiles/storage.py", line 417, in stored_name
>  May 04 18:47:36 foundation-mozilla-org app/web.6  raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
>  May 04 18:47:36 foundation-mozilla-org app/web.6 ValueError: Missing staticfiles manifest entry for 'wagtailredirects/css/index.css'
>  May 04 18:47:36 foundation-mozilla-org heroku/router at=info method=GET path="/cms/redirects/" host=[foundation.mozilla.org](http://foundation.mozilla.org/) request_id=...." dyno=web.6 connect=0ms service=111ms status=500 bytes=3070 protocol=https

**Comment by kristinashu** [comment]
cc @mtdenton @Gbaldassano for triage

**Comment by mtdenton** [comment]
@kevinhowbrook @jhonatan-lopes @danielfmiranda There's a [custom template](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailcustomization/templates/wagtailredirects/index.html) with an extra explanation at the bottom of this page back from when we were on Wagtail 2.



I'm assuming that this page has been broken ever since the upgrade. Is there any harm in just removing this template?

**Comment by jhonatan-lopes** [comment]
@mtdenton What the template is doing is adding some extra text to the redirects page to explain to editors how to setup the redirects. If this template is deleted, I think the redirects page will still work (at least it does locally for me) but without the extra explanation.

The error above suggests a missing css file when we call `<link rel="stylesheet" type="text/css" href="{% static 'wagtailredirects/css/index.css' %}">` on the template. The [static css file](https://github.com/wagtail/wagtail/blob/stable/2.16.x/wagtail/contrib/redirects/static/wagtailredirects/css/index.css) was present at version 2.X but has been deleted/incorporated into SASS in version 4.X.

To solve this issue, we can either update the template to work with version 4.X or remove the custom template.

**Comment by mtdenton** [comment]
I'm nixing it for now so that everything works, we can come back and deal with customization later if needed

**Comment by danielfmiranda** [comment]
Tested on staging, moving to ready for prod!

![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/18314510/cbd2878c-ae90-426b-9c95-86f45104949f)
