### ISSUE TITLE
[SPIKE] Review app gets wiped out on every git push to PR

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10588]
Review app gets wiped out on every git push to PR. After a git push, a new app is created with a new URL. The old review app still lives but gets detached from our repo (see first screencap below).

![image](https://user-images.githubusercontent.com/2896608/236540874-90d3f312-cf12-402b-b6f5-f9c8de62af3f.png)

<img width=600 src="https://user-images.githubusercontent.com/2896608/236541080-620995af-1fa9-4fc3-8999-cb6b4ae6f046.png">

**Comment by mtdenton** [comment]
Timebox to 2 hrs via SD workweek discussion.

**Comment by robdivincenzo** [comment]
Closing as heroku no longer appears to destroy/create new review apps on each commit.

Recent PR's for reference:

https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11864

https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11844
