### ISSUE TITLE
Destroy Review App once Github PR is merged

### ISSUE THREAD

**Issue by jzinner** [MozillaFoundation/foundation.mozilla.org#10585]
## Background 
@mmmavis requested to increase the length of time stale review apps are kept before being destroyed from `5 days` to `30 days`, which has already been updated. 

Per the [Review App docs on pr-predestroy script](https://devcenter.heroku.com/articles/github-integration-review-apps#pr-predestroy-script),

> You can optionally specify a pr-predestroy script on your app.json file. This script runs when review apps are destroyed once the associated pull request is merged or closed.

This needs to be added to this file: https://github.com/MozillaFoundation/foundation.mozilla.org/blob/65882e98d9a40bb073b46f4791c5a9c09fce57b5/app.json#L50

`"pr-predestroy": "python network-api/manage.py review_app_setup teardown"`
to 
`"pr-predestroy": "bin/teardown && python network-api/manage.py review_app_setup teardown"`

## Testing
This will need to be developed, but basically, open PR, create Review App, merge PR then see if the Review App was auto-destroyed when the PR was merged. 
If not, then revert the PR and try again.

**Comment by mmmavis** [comment]
I wonder if the issue I encounter isn't related to the lifespan we set for review apps. Even though we updated the lifespan to 30 days, I'm still seeing multiple reviews being created (and destroyed) in the same PR. It seems like every commit will trigger the app creation/deletion process.

![image](https://user-images.githubusercontent.com/2896608/236517971-a3e8d4b9-bed6-43c1-9a41-d89b5a07d563.png)

**Comment by jzinner** [comment]
One of the side effects of "keeping stale Review Apps for 30 days" seems to be that we are getting these Heroku emails RE: `[warning] Database disruption imminent`... for Review Apps.
I implemented keep for 30 days change on May 4th.  Then we started receiving these emails until May 10.

So far we have recieved 22x Heroku emails `[warning] Database disruption imminent`... for an identified Review App

My understanding is that the configuration change to increase the time we keep stale review apps did not fix the original problem - which is described by @mmmavis in the comment above: _every git push will trigger the app creation/deletion process_

So I reduced the time we keep stale review apps back to `Destroy stale review apps automatically: After 5 days`


Because we will only be keeping Review Apps for 5 days, we have no urgency to complete this `Destroy Review App once Github PR is merged`
