### ISSUE TITLE
Block with Aside 

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/foundation.mozilla.org#10583]
### Describe the bug
Using the Block with Aside works on the MozFest page templates, however once rendered it appears at full page width. 

### To Reproduce
1. Create a page using Mozfest primary page
2. Add a Block with Aside
3. Enter copy
4. Preview and see bug

### Expected behavior
The block is contained to the content width.

### Screenshots
<img width="1840" alt="Screenshot 2023-05-04 at 17 50 34" src="https://user-images.githubusercontent.com/30226684/236273228-f5024cfa-b8b0-4b2a-b1d2-a5872a9c7815.png">

**Comment by mtdenton** [comment]
Let's loop in a designer here to make sure that we're hitting the desired functionality. cc @kristinashu

**Comment by kristinashu** [comment]
It should look and function the same as it does on our main site e.g. https://foundation.mozilla.org/en/data-futures-lab/

<img width="1259" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/c8a9f640-0e7b-4d8a-9b2e-0eee6256ef34">

**Comment by marcwalsh** [comment]
This was fixed previously, I think we're okay to close it.

https://www.mozillafestival.org/house

**Comment by mtdenton** [comment]
Thanks both!
