### ISSUE TITLE
CMS Clean Up Work

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#10605]
Body of work related to streamlining the Foundation's current CMS system.

**Related documents:**
[Product Requirements Document](https://docs.google.com/document/d/16Aw2J26JlSBCsw1XO-PGXQ2OWULD4zyifWANqigyZ-Q/edit?usp=sharing)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-154)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Per https://app.zenhub.com/workspaces/mofo-web-platforms-team-585335eab729771d0736378d/issues/gh/mozillafoundation/foundation.mozilla.org/10605 ( https://app.zenhub.com/workspaces/mofo-web-platforms-team-585335eab729771d0736378d/issues/gh/mozillafoundation/foundation.mozilla.org/10605|smart-link ) , this EPIC has all associated tickets as completed so will be marked as Abandoned.
