### ISSUE TITLE
[CMS Clean Up] Research Planning

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#10611]
- [x] Plan user research to surface pain points in the current CMS
- [x] Gather feedback on research plan
- [x] Start recruiting participants (3-5)

**Comment by beccaklam** [comment]
Started a planning doc [here](https://docs.google.com/document/d/1c3xh9ZMhseysTekaoB_MbrkmNdds04aRkf4f8RIRaZg/edit?usp=sharing) since I had some time this sprint!

**Comment by kristinashu** [comment]
Good planning! Is this ticket ready to close?

**Comment by kristinashu** [comment]
oops wrong ticket! please ignore

**Comment by beccaklam** [comment]
Sent out emails to potential participants outlined in this [doc](https://docs.google.com/document/d/1c3xh9ZMhseysTekaoB_MbrkmNdds04aRkf4f8RIRaZg/edit?usp=sharing) :)
