### ISSUE TITLE
[FA] Make FormAssembly hosted page more branded

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10625]
FormAssembly script can handle field validation inline on our campaign pages (see 1st screenshot). However, for certain types of errors, users will be redirected to a FA hosted page (see 2nd screenshot). FA form builder allows us to add header to the form as well as some basic styling customization. We should utilize the features to make the FA hosted page more branded.

Note that I asked FA support if they could give me a list of errors that would send users to a FA hosted page. They told me 
> Unfortunately, we do not offer that kind of reporting

> The only way to know which forms will redirect is to go through them one at a time

😓 😓 😓 

![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/19cff011-e73b-495c-af35-3b32ea6cedb1)

![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/183bb618-d353-4d61-89f7-f5fba7423f50)

**Comment by kristinashu** [comment]
cc @nancyt1 since this will need design input

**Comment by mmmavis** [comment]
@nancyt1 This is how the FA hosted form page currently looks like: https://mozillafoundation.tfaforms.net/9

We are using this form for all petitions created on CMS. Data used to distinguish petition from one another (like campaign id, source URL etc) is included as hidden field. Since the header is predefined before campaign id etc are set, we won't be able to add petition specific header to that page and will need something generic. For styling - FA lets us add custom CSS to style the page but in a way that's hard to track code changes. Because of this, I'm hoping we can come up with simple design tweaks to make this page more branded.

**Comment by mmmavis** [comment]
Some updates - 

We've turned off a config on FA/Salesforce so that Salesforce errors like signing up with dupe emails etc won't be visible to users (i.e., won't redirect users to the FA hosted page mentioned in the ticket description).

I'm gonna close this ticket. If anything comes out from QA that requires us to continue this work, I'll revive this ticket then.

Thanks all!
