### ISSUE TITLE
[Research hub] Hide the taxonomy title from filters if there is nothing in it

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#10620]
The filters on https://foundation.mozilla.org/research/library/ shows "Regions" even though no regions have been set. Showing this even when it isn't relevant could be confusing and distracting to people visiting the site. Could we hide the section if it is empty? 

I'm am not sure if this is a new issue or if it has always been there.

Screen cap from prod showing the 
<img width="1201" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/95555519-e675-4132-88b9-09291f184226">

**Comment by beccaklam** [comment]
I think this was hidden before!

**Comment by kristinashu** [comment]
cc @jhonatan-lopes @danielfmiranda I don't think it's a high priority to fix this but want you to be aware.

**Comment by jhonatan-lopes** [comment]
@kristinashu it's a new issue but will be picked up as part of the RCC work. Thanks for flagging this up.
