### ISSUE TITLE
[PNI] Increase the maximum allowed number of privacy policy links on PNI product pages

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#10648]
Stakeholder: Jen Caltrider

From the Airtable request:
"On the PNI product pages, it would be so helpful to be able to include links to more than 3 privacy policies under the Links to Privacy Information section. This will be particularly important for our Cars & Privacy guide coming in July 2023."

Block in question:
![frontendprivacylink](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/41487159/abb83dfd-1c7c-4d44-b7c5-58d825426c9e)
![privacylinks](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/41487159/f5aa5c77-fde2-42fa-a920-a47481bc2647)

It might be best to just uncap the max on this or just set it very high, this limit doesn't seem to contribute anything.

Per @kristinashu below, setting max to 25

### Dev Tasks:

- [x] Increase the `max_num` argument to 25 from the `InlinePanel` constructor with the `relation_name` of `privacy_policy_links`, located in `network-api/networkapi/wagtailpages/pagemodels/buyersguide/products.py`

### Acceptance Criteria:

- [x] As a dashboard user, I cannot leave the privacy policy fields blank on the dashboard product page
- [x] As a dashboard user, I can add at least one up to 25 privacy policy links to the field in the dashboard product page while still maintaining the integrity of the styles on a product page
- [x] As a site visitor, I can see links for all the privacy policies that were added

**Comment by kristinashu** [comment]
Thank you Tyler! 

Jen says the most she has ever wanted to add was 14, the average for "a lot" is 5-6. I think a **max of 25** would be good. I don't think 25 will ever be needed. More than that would make the layout pretty crazy.

Should on of the AC reflect the front-end - something like "As a site visitor, I can see links for all the privacy policies that were added"

**Comment by mtdenton** [comment]
Updated!

**Comment by mtdenton** [comment]
@kristinashu ready for QA

https://foundation.mofostaging.net/cms/pages/1447/edit/

**Comment by kristinashu** [comment]
Perfect!
