### ISSUE TITLE
[CMS Clean Up] Deprecate Redirecting page

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#10675]
_From the Page Types audit work (#10606):_

**Task:** We now have wagtail redirects and no longer need these redirecting pages.

**Acceptance Criteria**
- [x] As an editor, there is no option for me to create a redirecting page
- [ ] As an editor, I should find that previous redirecting pages do not exist anymore

**Comment by beccaklam** [comment]
@kristinashu I'm actually not clear on what exactly this work entails, would you be able to give me some more details?

**Comment by kristinashu** [comment]
When going to create a new page, I often see an option to add a "Redirecting page". We shouldn't show this as an option to users since it isn't good UX to use one of these "pages" and staff don't use it since it's not needed. It just adds confusion and clutter when trying to create a new page. 

<img width="1440" alt="Screenshot 2023-05-29 at 5 14 46 PM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/45098935-c977-4953-8711-0a4597ef207c">

**Comment by mtdenton** [comment]
Question for @kristinashu: Are we keeping all past instances of redirecting pages or are we deleting all of the old ones with this change? That will affect feasibility and approach. Thanks!

**Comment by kristinashu** [comment]
@mtdenton ideally we remove all the past instances. Do we know of any case of this being used currently? I don't know of any but if there are then please let me know and I update them.

**Comment by mtdenton** [comment]
Thank you! @jhonatan-lopes to follow up in grooming

**Comment by victoriachan** [comment]
To view the list of existing pages, you can go to https://foundation.mozilla.org/cms/pages/usage/wagtailpages/redirectingpage/

**Comment by jhonatan-lopes** [comment]
Yes, I can confirm that there are 18 Redirecting Pages. I've sent you some instructions to work with this locally.

**Comment by victoriachan** [comment]
Sorry, didn't realise I should delete the old pages too. Will create a new PR.

**Comment by cdanfon** [comment]
@victoriachan to add link to new PR

**Comment by cdanfon** [comment]
It's been code reviewed and approved. Currently with editors to test. TBX work is completed on this apart from feedback from the testing if any.

**Comment by kristinashu** [comment]
Thank you @victoriachan @jhonatan-lopes for working on this! 

I have checked a few pages on staging and can confirm the redirect option is no longer available! 
But I am not sure how to test that the old redirects no longer exist. 

<img width="780" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/fb069811-ac80-4529-942e-dce6db90f275">
