### ISSUE TITLE
[CMS Clean Up] Deprecate Old YouTube Regrets Extension Landing Page

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#10707]
Task: Investigate whether or not we can deprecate the [old YouTube Regrets extension landing page](https://foundation.mozilla.org/cms/pages/1174/edit/).

To Do:
- [ ] Identify appropriate stakeholders for the website
- [ ] Inquire whether the page can be deprecated
- [ ] Deprecate page or decide what the long term solution will be for the page

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-164)

**Comment by data-sync-user** [comment]
➤ Rebecca Lam commented:

Adding a note here to say this work is still relevant any future website work re: clean up or tech debt.
