### ISSUE TITLE
Rework the PNI Creep-o-Meter to use an average instead of highest count vote bucket

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#10737]
Stakeholder: Misha

PNI folks have requested a rework of how PNI scores the creep-o-meeter. Currently, the option with the highest number of votes is selected without taking into account the distribution of votes across the options. We want to convert to finding the "average" rating instead.

We've got our five buckets of votes, from "not creepy" to "super creepy" left to right. Let's say we've got this many votes in each bucket:

`[10, 5, 1, 5, 10]`
Total votes =  31

To get the average, we can multiply each of these buckets by their position in the list, so "not creepy" would be 1, all the way up to "super creepy" with a value of 5:

`[10, 10, 3, 20, 50]`
Weighted votes = 93

Then we average that and that's the bucket that gets picked, like so
average bucket = floor( weighted votes / total votes ) = 3

`round()` should be used, confirmed by Misha

Subtract 1 because arrays start at 0, and your array position is now 2

So the average position is the third in the lists above, which would be "Somewhat creepy"

Misha also asked if this would affect the order of the product catalog. This code is separate from that sorting, so the answer is no.

### Dev Tasks

- [ ] Refactor `get_most_voted()` in `products.py` to fit the logic described above

### Acceptance Criteria

- [ ] As a user, I am displayed an average position of the votes given on a product page instead of the highest voted bucket.

**Comment by kristinashu** [comment]
@mtdenton @Gbaldassano any update on this? I suspect this info might be relevant for the Privacy Index landing page

**Comment by mtdenton** [comment]
We had some open questions and a need for an overhaul on this but I'm pushing it forward in its current state to get it out the door. PR is up for review

**Comment by kristinashu** [comment]
This ticket is blocked by the optimization work Jhonatan recently worked on. @jhonatan-lopes can you please link to that ticket? 

cc @mmmavis

**Comment by kristinashu** [comment]
Here's the ticket https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10159

**Comment by jhonatan-lopes** [comment]
Hi @kristinashu, for this one @mtdenton has a PR in the works: https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11048. This should be able to get merged before we do the optimisations. I can then refactor around it

**Comment by kristinashu** [comment]
Whatever is easiest for you, thank you @jhonatan-lopes!
