### ISSUE TITLE
Break-up large metadata on RCC detail page

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#10740]
RCC Detail page metadata is too long and overflows.

![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/61277874/c4b2f211-2af5-48b1-9027-56e9d008e358)

**Comment by beccaklam** [comment]
@jhonatan-lopes For the detail page, the RCC playbook design and Research Hub shows that the meta deta shouldn't show the author names and only list the publish date and one taxonomy. 
![Screenshot 2023-06-19 at 12 15 17 PM](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/20977376/859ab37a-cb50-4aad-8db1-2f2cc7292967)

It should also truncate after a certain length (here's an [example page](https://foundation.mozilla.org/en/research/library/creating-community-driven-datasets-insights-from-mozilla-common-voice-activities-in-east-africa/) from the Research Hub). Those fixes should fix the large amount of meta data causing this issue?

![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/20977376/52429004-5cbc-4a9e-8870-3db2795d2b66)

**Comment by jhonatan-lopes** [comment]
This was partially solved by removing the author names from the metadata.
