### ISSUE TITLE
Strange horizontal panning on Opportunity Pages on iOS Safari

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10801]
This is a follow-up for https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10232 as my original PR didn't seem to fix the issue on certain Opportunity Pages.

For example, 

* works fine: https://foundation.mozilla.org/initiatives/web-literacy/core-curriculum
* has panning issue: https://foundation.mozilla.org/initiatives/web-literacy/core-curriculum/participate/

There's some overflowing element on the page which causes the strange horizontal panning. See recording below.

I suspect the problem to be mismatched layout classes between Bootstrap and Tailwind. e.g., using `.container` from Bootstrap with `.tw-row` from Tailwind. Since the issues don't occur on all Opportunity Pages, I'm guessing the underlying problem may be due to specific type of streamblock.

https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/b535a612-03b6-4e8d-b0dc-6c0ed01f2033

## Dev Task
* [ ] Find out what's causing the overflow issue
* [ ] Update this ticket with findings
* [ ] If the underlying issue is coming from specific type of streamblock, ensure the fix doesn't create regression for other page types.

## Acceptance Criteria
* [ ] As an user, when I navigate [this page](https://foundation.mozilla.org/initiatives/web-literacy/core-curriculum/participate/) on iOS Safari, I don't get any strange panning issue.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-168)

**Comment by mtdenton** [comment]
@mmmavis to groom here

**Comment by data-sync-user** [comment]
➤ Ramon Ramos commented:

The horizontal scrolling is caused by a margin mismatch between bootstrap and tailwind row container inside specific content blocks: `.tw-container.image_text-block .streamfield-content .tw-row` being the main offender.

Solution proposed involves targeting said elements and applying a calc() to trim  1px from right margin.

Seems to be working fine in iOS v17.5.1.
