### ISSUE TITLE
Add Percy tests on RCC

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#10822]
### Describe the feature request
Add Percy tests to RCC.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-171)

**Comment by jhonatan-lopes** [comment]
@mtdenton to review whether or not we still want to include RCC pages on Percy testing due to the limited number of screenshots we get in a month

**Comment by simont-cr** [comment]
@jhonatan-lopes Is this something that we would prefer to wait for Tyler to come back and evaluate or can we close for the time being and reopen if necessary?

**Comment by jhonatan-lopes** [comment]
The PR is up (https://github.com/MozillaFoundation/foundation.mozilla.org/pull/10825), but Tyler was supposed to decide whether or not it to actually add those pages to Percy because of the limited number of screenshots that we get in a month

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Tyler Denton Jhonatan had mention that the decision on keeping this issue would be up to you, if we would actually want to add those pages to Percy. This also relates to https://mozilla-hub.atlassian.net/browse/TP1-172 ( https://mozilla-hub.atlassian.net/browse/TP1-172|smart-link ), so we might be able to either change our priorities or just remove these two tickets. Thank you!

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Due to priorities alignment, closing this ticket and related RCC ticket as well.
