### ISSUE TITLE
Update "About Blocks" image to always have 16:9 dimensions

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#10827]
# Description
There has been a request from design to update the image featured in the Libraries (RCC/Research Hub) landing page's "About Block" to always be rendered in 16:9 dimensions instead of allowing the height of the container to grow/shrink as needed. 

For reference, the design team has asked that it follows the same dimensions as this image found on the foundation site's home page:

![Screenshot 2023-07-20 at 21-13-41 Mozilla Foundation](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/18314510/e3b4cf15-6a7c-4839-b1a8-a91f43a0bd7c)

## Dev Tasks

- [ ] Update the image dimensions so that they follow the 16:9 format

## Acceptance Criteria

- [ ] The image size is updated to fit a 16:9 aspect ratio
- [ ] If the image is too large/small, it does not stretch/squish to fit the container but instead gets cropped in the center to fit whatever it can in the 16:9 format.

**Comment by kristinashu** [comment]
Closing this since it's low priority.
