### ISSUE TITLE
[Epic] PNI Privacy Index Landing Page

### ISSUE THREAD

**Issue by Gbaldassano** [MozillaFoundation/foundation.mozilla.org#10839]
### Context
The PNI team is requesting a landing page for a new initiative that recaps/outlines how creepy consumer tech is getting.

### GOALS (from https://docs.google.com/document/d/1uBidJZZYMjKbHWMUt6x498uobrnQoSSoXheDUFKmcB0/edit)

- Create a yearly announcement from Mozilla/PNI similar to the Doomsday Clock announcements that outlines how creepy (and harmful) we think our consumer tech is getting — but also bright spots
- Drive the conversation at a higher level than product reviews/buyer’s guides on what is happening to privacy/safety of our consumer tech in a way the media can easily cover and consumers can easily understand.
- Set Mozilla/PNI up as a trusted source for expertise and information on privacy in consumer technology. 

### Notes
As of right now the intent is to reuse this page on a yearly basis so should be built with scalability in mind.
The desired timeline for launch is early - Mid-October

### Acceptance Criteria
Landing page is designed and built that meets goals specified above, medium level of support (not too custom, but slightly more than a basic landing page)

### Helpful Documentation
https://docs.google.com/document/d/1uBidJZZYMjKbHWMUt6x498uobrnQoSSoXheDUFKmcB0/edit
https://docs.google.com/document/d/1dg13B3PNrugzp6cGPBBEnwZAE0MRyBLKTbW4uiavBiI/edit

**Comment by kristinashu** [comment]
[Meeting notes are here!](https://docs.google.com/document/d/1onymhqSU_l10weY1rpc5hshSbi8ws1XO_4Uyjchv8i4/edit#heading=h.1wjf2z6z6zqz)

**Comment by mtdenton** [comment]
Assuming we have all pieces in place, that sounds good to me!

**Comment by mmmavis** [comment]
I'll be OOO from Thursday (10/12) to the following Monday (inclusive) but I will make sure I hand off things properly before I go on PTO.

**Comment by kristinashu** [comment]
This is live and amazing https://foundation.mozilla.org/privacynotincluded/articles/annual-creep-o-meter/!

[We're tracking metrics here. ](https://lookerstudio.google.com/reporting/23d9e362-4fef-4c35-8a2f-82e297247832/page/ffkfD)
