### ISSUE TITLE
Set Up Basket/FRU Connection Via Zapier

### ISSUE THREAD

**Issue by Gbaldassano** [MozillaFoundation/foundation.mozilla.org#10838]
### Context
In Fundraise Up, there is a built-in option on Campaigns that allows you to ask donors to subscribe to your mailing list (basically a check box under the Campaign > Checkout > Mailing List that can be turned on to track a donor’s interest in subscribing.) If this box is checked, it will map the checked value to the “FRU Mailing List Subscription” field on the donor’s Contact record in Salesforce (visible under the Donations tab).

The Engagement Team is interested in asking donors to subscribe to our newsletter using this built in FRU functionality.

### Request
Though we can collect this information now, we are still missing the connection between the Fundraise Up flow and Basket, which is needed to trigger the double opt-in process. Based on the investigation from this SPIKE Ticket: https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10738 it seems we can set up this connection via Zapier.

We should already have a Zapier login accessible in the Mozfest vault (we should probably move this) under "Devopszapier@mozillafoundation.org"

The goal of this ticket is to set up/implement/test the connection to ensure users who donate and sign up to our mailing list via FRU are entered into the normal mailing list flow (receiving double opt in, etc). There may already be users who have checked this box before the connection was set up, so we should ensure they too get sent the correct opt in flows.

### Acceptance Criteria

- [ ] After donating, user selects 'subscribe to our mailing list' in FRU form (already set up)
- [ ] Selection is recorded and mapped to the “FRU Mailing List Subscription” field on the donor’s Contact record in Salesforce (visible under the Donations tab) (already set up)
- [ ] Connection between the Fundraise Up flow and Basket triggers the double opt-in process (do we need to FRU API and Zapier for this?)

Helpful documentation

- https://docs.google.com/document/d/1RXZFAJFTN9U_ukGxgkJmwOonesd4eGCxM7j3h6VSIg0/edit
- https://fundraiseup.com/docs/javascript-api/

**Comment by Gbaldassano** [comment]
@mtdenton could you add an estimate for this when you have a chance?

**Comment by mtdenton** [comment]
Made a new repo for any zap scripts we make. This specific one can be found [here](https://github.com/MozillaFoundation/mofo-zapier/blob/main/fundraise-up-to-basket-newsletter-signup.py)

**Comment by mtdenton** [comment]
Zapier dashboard test submission was successful, response from Basket:

`{
    "status": "ok"
}`

**Comment by mtdenton** [comment]
Zapier plan upgraded to Starter (750 zaps per month). Zap is published, monitoring activity before we close this ticket. (cc @Gbaldassano )

**Comment by mtdenton** [comment]
Zap can be found [here](https://zapier.com/editor/200918622/published/200918623/setup), under Zapier DevOps account in 1Password
