### ISSUE TITLE
Make petition modal CTA URL editable

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#10846]
We want to be able to update the URL for the purple "Yes, I'll Chip In" button in the CMS

![donatemodal](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/41487159/7a0433be-61fe-4465-a93b-6da9e092cec8)

**Comment by Gbaldassano** [comment]
Based on discussion of #10905, we should move forward and merge this when ready but not release to users until we have more information about how best to set up.

**Comment by Gbaldassano** [comment]
Based on discussion of #10905, we should move forward and merge this when ready but not release to users until we have more information about how best to set up.
