### ISSUE TITLE
[Design Updates] Secondary menu cuts off if there's too many nav items or long titles

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#10858]
Currently on desktop sizes, it seems the secondary menu will decrease column size on smaller screens and this makes long titles stack a little weirdly ([example on what we fund page.](https://foundation.mozilla.org/en/what-we-fund/)) Then if there's too many items, it will get cut off. There's not a live example of this cut off but it's an edge case that I think we should address. 

My initial idea was to allow the secondary menu to grow and scroll horizontally but open to any suggestions on how to make this more accessible.

**Example page:**

<img width="812" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/74557207/1a6be36a-5bc9-4498-9abf-1af47598350e">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-175)

**Comment by mmmavis** [comment]
Somewhat related: [PNI - Product Review - Tabs not accessible for certain locales](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10101)

**Comment by nancyt1** [comment]
Yes i think this is still needed!

**Comment by simont-cr** [comment]
Thanks Nancy! I will leave this as a P2 for the time being, so we can focus on the new nav and we can then revisit this issue.

**Comment by data-sync-user** [comment]
➤ Rob DiVincenzo commented:

Agree with Nancy’s suggestion! 

I think here’s a start for acceptance criteria:

The overflowing secondary menu should be handled by a horizontal scroll below the element. Ideally, add a slight fade to the text as it tapers off-screen. On browsers/systems where scrollbars are hidden until used, it would help indicate to the user there are more links and to scroll. The links should also be keyboard navigable for accessibility. And as you tab through the links, the links should become visible on the screen as if horizontally scrolling.
