### ISSUE TITLE
[Design Updates] Increase spacing between nav links for secondary mobile menu

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#10857]
Spacing is a little tight on this menu on mobile screens which can make it difficult for users to click on. I'd like to increase the tap area and have spacing between nav links be at least 1rem or 1.5rem.

[Who we are page link](https://foundation.mozilla.org/en/who-we-are/)
[Design component in figma](https://www.figma.com/file/sOxNGYMzwZT0B9Fal2D4WT/%5BWIP%5D-Component-Library?type=design&node-id=1173%3A7262&mode=design&t=BDaxvyEVVY7wlXU2-1)

<img width="380" alt="Screenshot 2023-07-11 at 10 39 08 AM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/74557207/80f1ff07-c55e-46fe-8c74-ce4369d1d5e4">

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-85)

**Comment by mmmavis** [comment]
Done!
