### ISSUE TITLE
Add Mozilla logo to donate footer on tablet and mobile sizes

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#10859]
Currently on the [Donate site](https://donate.mozilla.org/en-US/) the Mozilla logo shows up in the footer on desktop sizes but doesn't appear on tablet and mobile. I'm not sure what the reasoning was for this but it would be great if we can add it back.

[Mockup in Figma](https://www.figma.com/file/sOxNGYMzwZT0B9Fal2D4WT/%5BWIP%5D-Component-Library?type=design&node-id=1691%3A22334&mode=design&t=BDaxvyEVVY7wlXU2-1)

**Desktop**
![](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/74557207/029e52e2-98f2-408f-98dd-a6da109569f9)

**Tablet**
![](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/74557207/4fb340ce-df32-46bf-a44a-488c6abe3514)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-176)

**Comment by mmmavis** [comment]
Hi @nancyt1 thanks for reporting this. Do you mind adding a link to the page in the ticket description?

**Comment by data-sync-user** [comment]
➤ Kristina Shu commented:

We’re no longer using this footer style so we can close this ticket!
