### ISSUE TITLE
[Design Updates] Update hover state in footer to just an underline

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#10860]
Currently the links in our footer will turn purple with an underline on hover. After auditing for the design system, we wanted to change the hover state to just an underline and no color change for consistency with other hover states. 

[Figma Prototype](https://www.figma.com/proto/sOxNGYMzwZT0B9Fal2D4WT/%5BWIP%5D-Component-Library?page-id=601%3A5447&type=design&node-id=1691-22340&viewport=600%2C112%2C0.13&t=zeffSPYSnMUb7W8K-1&scaling=scale-down-width&mode=design)

**Current footer:**
<img width="1122" alt="Screenshot 2023-07-11 at 11 13 58 AM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/74557207/48f701d3-805d-40a3-bb74-366c460a2169">

**Comment by mmmavis** [comment]
Hi @nancyt1 currently there are different kinds of links in the footer with their own styling treatments (e.g., privacy notice, read more, Donate, Careers etc). Do you mind clarifying which links you were referring to?

**Comment by nancyt1** [comment]
@mmmavis yeah, it's just the links in the right 2 columns like Donate, Careers, Participation Guidelines. Everything else works as expected.

**Comment by nancyt1** [comment]
@danielfmiranda I think everything looks good!
