### ISSUE TITLE
Decrease spacing between checkboxes on FA Petition form

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#10863]
Can we decrease the spacing between the 2 checkboxes to ~1 rem and decrease spacing between the form fields and the checkboxes to ~2 rem? The spacing between the form and checkboxes should be the same as between the checkboxes and the button, if that makes sense. Something similar to this [figma mockup ](https://www.figma.com/file/sOxNGYMzwZT0B9Fal2D4WT/%5BWIP%5D-Component-Library?type=design&node-id=1519%3A13734&mode=design&t=BDaxvyEVVY7wlXU2-1)under petition form. 

I highlighted the spacing I'm referring to.

<img width="463" alt="Screenshot 2023-07-11 at 5 27 45 PM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/74557207/884c5010-5db3-4985-aaa1-2b4266e9dcf6">

I've also noticed this really tiny down arrow for the country field, could we increase the size to the height of the text?

<img width="1395" alt="Screenshot 2023-07-11 at 5 30 24 PM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/74557207/691ac045-b61e-4ac1-ad05-248125db52cb">

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Browser: Firefox

# Acceptance Criteria

On campaign page's petition form,

- [ ] Update the spacing in between the two checkboxes to ~1rem 
- [ ] Update the spacing in between the last input box and the privacy checkbox to ~2rem (roughly the same as the spacing in between the email subscription checkbox and submit button)

**Comment by mmmavis** [comment]
Done grooming the ticket. This is a small one so I'm just gonna file a quick PR to fix the spacing issue.

**Comment by mmmavis** [comment]
@nancyt1 do you mind QAing this on staging? :) https://foundation.mofostaging.net/en/campaigns/tell-slack-make-dms-safe/
