### ISSUE TITLE
[RCC] How To Wagtail Documentation

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#10867]
**To Do:**
_Add some quick documentation to 'How To Wagtail' regarding:_

- [x] Existing libraries
- [x] What should go in the libraries
- [x] How categories/taxonomies work
- [x] Snippets
- [x] Profiles (shared between Research Hub and RCC, so be careful what you delete)
- [x] Categories
- [x] Creating articles in the libraries

**Comment by beccaklam** [comment]
Note: Unrelated to RCC but related to documentation, add 'Permissions' to the 'How To Wagtail' documentation

**Comment by beccaklam** [comment]
Started a doc here for brain/content dump: https://docs.google.com/document/d/1-5KAp70G-Y4SPJgCGagBrihGGJsrb4UKf_nT0aZE_jY/edit?usp=sharing

**Comment by beccaklam** [comment]
@kristinashu This page has been created here: https://foundation.mozilla.org/en/docs/how-do-i-wagtail/specific-pages/libraries/ Please edit as you see fit!

**Comment by beccaklam** [comment]
@kristinashu I also added a quick ['Permissions' page](https://foundation.mozilla.org/en/docs/how-do-i-wagtail/permissions/). I wasn't sure if I should add descriptions for each permission but I figured the titles themselves are already a good start?

**Comment by kristinashu** [comment]
This is great, thank you!
