### ISSUE TITLE
FormAssembly doesn't include asterisks for required fields in their embed code

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#10874]
Stakeholder: Christina Hug

Original request:

> Looking for a way to indicate that fields are required in Form Assembly. Right now there is no indication and you get errors if you missed one - want that indicator up front? And if not can we just add a text asterisk beside the field names?

Let's go ahead and add asterisks to the embed code in the petition forms along with an indicator of what the asterisks mean.

Mock-up:
![requiredfield](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/41487159/ce135864-97a0-4d74-bde2-4727a5226f7f)

The embed code for the form lives in [`network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/formassembly_body.html`](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/39c38dcf3f1477273dbd5d11fc0a14aa0428c40f/network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/formassembly_body.html#L4)

### Dev Tasks
- [ ] Add `*` to the following fields: `First Name`, `Last Name`, `Email`, `I’m okay with Mozilla handling my info as explained in this Privacy Policy`
- [ ] Add `* indicates a required field` above all fields at the top of the form
- [ ] Style all text to match the current text within the form

### Acceptance Criteria
- [ ] As a user, I see asterisks on the labels of the required fields on page load for all languages of a campaign page with a petition CTA.
- [ ] As a user, I see `* indicates a required field` above the fields on page load for all languages of a campaign page with a petition CTA. The text is presented in the corresponding language.

**Comment by kristinashu** [comment]
Note, talk around the design is happening in the PR https://github.com/MozillaFoundation/foundation.mozilla.org/pull/10875

**Comment by danielfmiranda** [comment]
Hi @mtdenton @Gbaldassano! 

The PR for this ticket has now been merged into main and is ready for QA on staging. 

A test page can be found here: https://foundation.mofostaging.net/en/campaigns/tell-slack-make-dms-safe/

Thanks!

**Comment by mtdenton** [comment]
Checked on three languages, also saw `aria-required`. Looks good!
