### ISSUE TITLE
SPIKE:  Adjusting Petition Form Fields/Moving Petition CTA Above the Fold

### ISSUE THREAD

**Issue by Gbaldassano** [MozillaFoundation/foundation.mozilla.org#10896]
### Context
Optimizing the Petition forms to maximize conversions is a priority for the Engagement team. As a result, they would like us to:

1) Move the petition form/CTA up so it appears above the fold on mobile (similar to what was done for donate forms)
2) Condense form fields/copy so that copy lives in the form field box (similar to the old Petition form) rather than above it.

![Screen Shot 2023-06-29 at 11.01.21 AM (2).png](https://images.zenhubusercontent.com/640f8c755e71df27c4397000/7c90c34b-d24e-427a-9acc-7ef057a1e704)

However, there are some considerations to take into account. 
1) For instance, screen readers would have a different experience on desktop sizes if paragraphs were kept to the left, which means it would start reading the petition side first.
2) Also, we're limited to what is available to us in the FormAssembly settings unless we want to hack up their code and we're aware customizations like that could cause issues down the road if we ever need to change the form code in any way.

### Request
The goal of this ticket is to investigate if/how we can make these changes petitions and answer questions like:

- What can we do out of the box? 
- What would involve more customization, and what effects will changing it have?
- What are the ramifications are of making core changes like this?
- How, if at all, can we increase our ability to optimize the form, without causing issues down the line?

**Comment by mtdenton** [comment]
Thanks for building this out @Gbaldassano! Concerning the field labels, I want to highlight a few things from W3C's [Web Accessibility Initiative Docs](https://www.w3.org/WAI/tutorials/forms/instructions/#placeholder-text)

> While placeholder text provides valuable guidance for many users, placeholder text is not a replacement for labels. Assistive technologies, such as screen readers, do not treat placeholder text as labels. Moreover, at the time of writing this tutorial, placeholder text is not broadly supported across assistive technologies and not displayed in older web browsers.

Further, we could implement hidden labels or rely on `aria-label` to do the heavy lifting for the form (which may already be implemented?) to help users with screen readers, but another caveat that needs to be considered:

> Note: Section [Hidden labels](https://www.w3.org/WAI/tutorials/forms/instructions/labels.html#hidden) of this tutorial describes how to hide information visually but keep it available to assistive technology. This same approach can be used to avoid visual redundancy of displaying both labels and placeholder text. **Be aware that this makes it very hard for users to review the form**. To avoid this problem, **JavaScript can be used to make labels appear visually (in the associated label element) above or beside the input that has focus**.

Which would likely mean that we would have to add a ton more custom code to the form that would need to be refactored if the form code ever changed on the FA side, plus there would be design time involved to figure out where that pop-up labeling should exist.

Given the effort vs. value of this, I'd like to suggest that we avoid implementing a solution here. I know we had it like this previously, but doing the above research indicates that the previous way has its own issues as well.

**Comment by kristinashu** [comment]
Thanks for pinging me on this @mtdenton! 

This feels like two separate requests so I'd recommend separating this into two tickets. 

For Moving Petition CTA Above the Fold, note that we should remove the current sticky Take Action button. We could make it appear once a user has scrolled past it but I'm guessing that will be pretty buggy. 

<img width="300" alt="Screenshot 2023-07-20 at 8 29 21 AM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/e9e45aa8-f218-4576-8b6f-a9281635b6c1">


For Adjusting Petition Form Fields, if we can re-frame this as a more general ask to make the form more condensed while adhering to accessibility best practices, then I'm sure we can find a few possible solutions (although I can't speak to the affects of overriding Form Assembly). 

I'd recommend we get this work on our roadmap and give Nancy and Mavis time to work on it - Nancy can mock up a few different options, we discuss as a team, share with stakeholders and have them approve of the design before dev does the work.

**Comment by Gbaldassano** [comment]
@mtdenton @kristinashu thank you both for taking a look at this so quickly! This is definitely something we can take a beat on and chat through more in depth to make sure I'm asking the right questions/info is laid out correctly. 

I know we've been chatting about the potential issues of changing petitions in this way so my goal with this ticket was just to officially pose the question so we have a firm answer on what's possible to share with the Engagement team as I know this is on the top of their list. 

Don't feel pressured to pick this up immediately/happy to chat through this more in sprint planning!

**Comment by kristinashu** [comment]
Tyler's link to time machine was helpful to confirm that the placeholder move turn into a label as a user starts to type https://web.archive.org/web/20190423222628/https://foundation.mozilla.org/en/campaigns/facebook/

(although the label text is probably too small and light grey to pass AAA accessibility)
<img width="431" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/6814e927-5994-4567-bd0a-911b6ca4aa97">

**Comment by mtdenton** [comment]
Thanks @kristinashu! Agree on splitting the ticket out here, I'll rearrange this ticket to be specific to the field labels and create another for moving the CTA
