### ISSUE TITLE
Add iFrame to OAT Landing Page

### ISSUE THREAD

**Issue by Gbaldassano** [MozillaFoundation/foundation.mozilla.org#10894]
### Context
One of the stakeholders for the OAT project has asked us to help integrate this [visualization](rbsteed.com/oat-landscape/embed.html) into the [OAT landing page ](https://foundation.mozilla.org/en/open-source-audit-tooling/database/) we helped them build via iFrame.

Ryan has a working iframe version of the site ready for testing at rbsteed.com/oat-landscape/embed.html. It's working in a test iframe at rbsteed.com/oat-landscape/embed-test.html and it works when  changing the URL of the example Streamfield iframe [here](https://foundation.mozilla.org/en/docs/how-do-i-wagtail/streamfield-blocks/#iframe).

### Request
Can we try adding it to an iFrame at https://foundation.mozilla.org/en/open-source-audit-tooling/database/? 
Can we replace the embedded Airtable and adapt the header text from the full version of the site into a caption?

Once this is added, we should let the stakeholder know so they can experiment more with breakpoints etc.

**Comment by Gbaldassano** [comment]
@kristinashu just FYI I put in a ticket for this - let me know if there's enough info!

**Comment by kristinashu** [comment]
Nice, looks like that worked https://foundation.mozilla.org/en/open-source-audit-tooling/database/!
