### ISSUE TITLE
[FA] Replace source url hotfix with a more future proof solution

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#10901]
Context: https://mozilla.slack.com/archives/C98GW3P7X/p1689799680306349

I will update ticket with more info

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-90)

**Comment by simont-cr** [comment]
Closed per 2024 ticket purge.
