### ISSUE TITLE
Move petition CTA above the fold on campaign page mobile views

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#10920]
via @Gbaldassano, split from #10896 
Stakeholder: ***needs grooming***

### Context
Optimizing the Petition forms to maximize conversions is a priority for the Engagement team. As a result, they would like us to move the petition form/CTA up so it appears above the fold on mobile (similar to what was done for donate forms)

![Screen Shot 2023-06-29 at 11.01.21 AM (2).png](https://images.zenhubusercontent.com/640f8c755e71df27c4397000/7c90c34b-d24e-427a-9acc-7ef057a1e704)

However, there are some considerations to take into account: 

- Screen readers would have a different experience on desktop sizes if paragraphs were kept to the left, which means it would start reading the petition side first. While not optimal to give these users a different experience, it seems like we don't have an option here without radically rearranging or redesigning this page.
- We will have to rearrange the DOM through the template and make it respond to different viewport sizes with `order` sort of like we did in [donate-wagtail #1755](https://github.com/MozillaFoundation/donate-wagtail/issues/1755). The `h1` page title will need to be independent of the current top paragraph `div` and always remain at the top of the page despite the order of the other elements.
- The compactness of the form doesn't improve on mobile sizes. We may want to consider any other ticket coming from #10896 addressing this as a requirement as well.

I've mocked up what this could look like but omitted needed input from the design team on arrangement, margin/padding, etc. (cc @kristinashu):

![mocked](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/41487159/2d5d3774-ad06-47c5-a91a-55ded665bc20)

This takes the liberty of removing a few elements that were causing spacing issues:
- The gray bar to be removed in #10919 (consider making this a blocking issues)
- The form footer `div`s, we'll need input on what to do with these as well:
![supportInfo](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/41487159/8e525027-55b7-4eee-9e88-18b14cb11f84)

**Comment by mtdenton** [comment]
We might consider splitting this as well, maybe assigning to an overarching petition page improvements epic. Suggested ticket ideas:

- make `h1` page title independent of the `campaign-page-content` parent div
- set visibility of `wFormFooter` and `supportInfo` elements to hidden if there is no content to be displayed

**Comment by kristinashu** [comment]
Also noting we need to decide next steps for the sticky CTA button https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10896#issuecomment-1644156024 

<img width="300" alt="Screenshot 2023-07-20 at 8 29 21 AM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/e9e45aa8-f218-4576-8b6f-a9281635b6c1">

And make sure this won't affect the newsletter sign up snippet position? Particularly on mozfest site (if any changes happen, we need approval from Marc). Keeping in mind that ideally, our UX patterns are as consistent as possible.  

<img width="300" alt="IMG_8466" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/546e23f9-3e5b-42d0-bf2e-e74ba772193f">

**Comment by kristinashu** [comment]
@Gbaldassano @mtdenton for the quick fix, can you please confirm both with the stakeholders and with the code re: [the comment above](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10920#issuecomment-1648344479) about the sticky button on mobile?

**Comment by kristinashu** [comment]
@nancyt1 had mocked up this version that is the same dev-wise as the original comment but she's suggesting stakeholders make use of the snippet copy to give supporters more context:

<img width="494" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/d058a260-d9ef-4dd3-b019-df41d71827b0">

**Comment by mtdenton** [comment]
>> @Gbaldassano @mtdenton for the quick fix, can you please confirm both with the stakeholders and with the code re: https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10920#issuecomment-1648344479 about the sticky button on mobile?

We could change the code in `sticky-cta.js` to only appear once the petition element leaves the top of the user's viewport and hiding the button again if the petition element comes back into view. This way, it will only take real estate from the long paragraphs below and still allow users a method to quickly get back to the form.

For posterity, the code I'm referring to is here-ish:
https://github.com/MozillaFoundation/foundation.mozilla.org/blob/6cd2796f6a3fc2bd161561ddd88c4f5d4be74801/source/js/common/template-js-handles/sticky-cta.js#L44

**Comment by kristinashu** [comment]
Thanks @mtdenton! And that won't be too buggy/glitchy? Will it only affect petitions and not newsletter sign up CTAs?

**Comment by mtdenton** [comment]
You bet! There shouldn't be any reason for it to behave strangely from my POV but we can evaluate. I'm also thinking that we can rewrite this JavaScript to determine if it's on a petition page or not and act accordingly so that newsletter sign up CTAs won't be affected.

**Comment by kristinashu** [comment]
Great! cc @mmmavis

**Comment by mtdenton** [comment]
Re-checking on staging for launch after un-reverting, looks good to go
