### ISSUE TITLE
Increase conversion on mobile petition pages

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#10925]
Followup ticket to: #10920 
Problem: Currently, form might be too low on mobile pages and affecting conversions

[Figma Doc](https://www.figma.com/file/JtSZjmp62ib13OVSqn2uGn/Petition-Page-Update?type=design&node-id=1%3A29&mode=design&t=rJuOABf01e84OEFA-1)

* [ ] Benchmark mobile petition pages
* [x] Wireframe potential solutions
* [ ] Get feedback with stakeholders and devs
* [ ] Create dev ticket for implementation

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-179)

**Comment by mmmavis** [comment]
This might be helpful: https://help.formassembly.com/help/340484-field-hints-contextual-help

**Comment by nancyt1** [comment]
I created a [Figjam](https://www.figma.com/file/eenl2O1NxmANbDv6qCxcrz/Petition-Page-Feedback?type=whiteboard&node-id=0%3A1&t=gzMumhhYknAnsSwg-1) to test if it's a good platform to collect feedback. @mmmavis Before I share with stakeholders, are you available to review these for feasibility but also give feedback if this was a good way to share potential designs?

**Comment by nancyt1** [comment]
Shared the figjam with Christian and Christina and currently waiting their feedback.

**Comment by Gbaldassano** [comment]
@nancyt1 hoping to check and see if these tickets are duplicative: https://app.zenhub.com/workspaces/mofo-web-platforms-team-585335eab729771d0736378d/issues/gh/mozillafoundation/foundation.mozilla.org/10920

Or is it alright if we link 10920 to this ticket for implementation?

**Comment by kristinashu** [comment]
@Gbaldassano #10920 has the quick fix for this. I think this ticket will still be useful for the longer-term solution. Also curious about what comes out of the petition workshop Monday.

**Comment by data-sync-user** [comment]
➤ Nancy Tran commented:

I feel like we should abandon this ticket for now until the need comes up again since this might get redesigned after rebrand anyway.
