### ISSUE TITLE
[PNI Privacy Index] Create and sign off on PRD

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#10924]
[Draft PRD Doc](https://docs.google.com/document/d/1tydN39iahB4RUwWZPgZazdY1b11dDoRiLDRX5Zp150g/edit#heading=h.e1hdva6khlbd)

- [x] Collab with Mavis to define requirements and scope
- [x] Get signoff from stakeholders

**Comment by kristinashu** [comment]
Done!
