### ISSUE TITLE
Add ability to add links to the body field in `GroupListingBlock` 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#10932]
Stakeholder/Reqestor: Miguel Morachimo

Currently, the only possible styling available in the Body field of `GroupListingBlock`is Bold. It should also allow staff to add links. 

Stakeholder: Miguel M via [request](https://airtable.com/appXJat3iETgLcZOH/tbl6aiXZqudFA60MS/viwo8I0OXw7nQ1epa/recuHAUWlB5ZVwA4t?blocks=hide) 

Screen cap of body:
<img width="400" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/193c32a5-cf90-46c0-85ca-a1f42349bc00">

Screen cap of paragraph showing a link option:
<img width="671" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/2257fbbe-8610-4f16-95b6-0492ead826ba">

### AC
- [ ] As an editor, I can add links to the Body field
- [ ] As a visitor, I can see there is a link and click on it
- [ ] Let the stakeholder know once this is live

cc @mtdenton @Gbaldassano

**Comment by mmmavis** [comment]
This should be a pretty quick fix. Assigning this to myself & will have a PR soon.

**Comment by Gbaldassano** [comment]
Hey @kristinashu @mmmavis is this a bug? Just curious - otherwise I think we should hold off on picking up this work until we've officially pulled it into a sprint.

**Comment by kristinashu** [comment]
Hey, it's not a bug but it sounds like it's a quick update and Mavis already has a PR for it!

**Comment by Gbaldassano** [comment]
@mmmavis no worries at all! Always appreciate the quick turnaround 😌, just want to make sure we go through sprints to help keep things organized/as a buffer so things don't get too overwhelming. Thank you for hopping on this!

**Comment by mmmavis** [comment]
@kristinashu could you help testing this? Sample test page on staging: https://foundation.mofostaging.net/cms/pages/1771/edit/

**Comment by kristinashu** [comment]
Yes, this is working well on staging! Thank you @mmmavis!
