### ISSUE TITLE
Footer newsletter sign-up button shifts when error message is triggered

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#10948]
When a user fails validation for the newsletter sign-up box in the footer of foundation.mozilla.org, this changes the size of the "Sign Up" button and causes "Up" to break to a new line.

### To Reproduce
1. Add email to newsletter sign up box
2. Hit 'sign up' without checking "I'm okay with Mozilla handling my info..."
3. See Sign up CTA changes shape/layout

### Expected behavior
"Sign Up" text does not break to a new line.

### Screenshots
![Screenshot 2023-08-01 at 9 25 19 AM](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/41487159/95d3fa6c-4844-43ed-b3d2-35da33af97af)

**Comment by tbrlpld** [comment]
Also noticed that the height of the button does not match the input, even when it's not breaking into multiple lines. 

<img width="735" alt="Screenshot 2024-01-03 at 12 59 18 PM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/24797493/002f1516-e4f7-4835-a6b3-36d82d1007ee">

**Comment by kristinashu** [comment]
cc @mmmavis @nancyt1 since I think you've been looking at sign ups

**Comment by mmmavis** [comment]
Thanks for flagging it. All the above issues have been addressed. Fixes are currently on a feature branch and will be merged into `main` soon.
