### ISSUE TITLE
[PNI Privacy Index] Explore and create visual assets

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#10954]
- [x] Start exploring character creation for site
- [x] Explore color palette
- [x] Define what is needed for site and marketing
- [ ] Get feedback

**Comment by nancyt1** [comment]
Started to gather some inspiration on a new [figma page](https://www.figma.com/file/idw7tpYbaRXCRqzk01poEX/Privacy-Index-Page?type=design&node-id=246%3A2351&mode=design&t=yzypTWJVjVF8S3Q4-1)

**Comment by nancyt1** [comment]
Presented some [art directions](https://www.figma.com/proto/idw7tpYbaRXCRqzk01poEX/Privacy-Index-Page?page-id=388%3A3846&type=design&node-id=416-5856&viewport=-103%2C551%2C0.09&t=njDicDeXHLTuk9ov-1&scaling=scale-down-width&starting-point-node-id=440%3A7075&mode=design) to stakeholders and they are leaning towards the retro art style.

**Comment by kristinashu** [comment]
Awesome, I'm also loving the retro / newspaper style!

**Comment by nancyt1** [comment]
Going to meet with Sabs and Tess this week to get consensus on styles and create a list of potential assets needed. Iterating on those assets will be another ticket.

**Comment by nancyt1** [comment]
Created a list of about 6 spot illustrations and a handful of emoji graphics for smaller cards. Will continue this work in #11075!
