### ISSUE TITLE
Update mzl.la/request URL to direct to new Jira Intake Form

### ISSUE THREAD

**Issue by Gbaldassano** [MozillaFoundation/foundation.mozilla.org#10958]
### Context
With the new intake form ready to use, we want to make sure we update the https://mzl.la/request URL to redirect to this new form (rather than https://mozillafoundation.typeform.com/to/fdvnq70t)

Please update https://mzl.la/request to redirect to https://mozilla-hub.atlassian.net/servicedesk/customer/portal/20

Timing wise, we're hoping to start letting stakeholders know about the new form by 8/11, so if we could update this before then that would be great.

**Comment by mtdenton** [comment]
@Gbaldassano @shing-mofo what's the go-live date for this?

**Comment by mtdenton** [comment]
Just updated the link, this is live @shing-mofo @Gbaldassano @kristinashu

**Comment by shing-mofo** [comment]
You're awesome, thank you!

**Comment by Gbaldassano** [comment]
@mtdenton thank you!!
