### ISSUE TITLE
JIRA for Sprint Management Evaluation

### ISSUE THREAD

**Issue by Gbaldassano** [MozillaFoundation/foundation.mozilla.org#10976]
### Context:
The goal of this ticket is to track work needed to evaluate JIRA for sprint management.

Please make a copy of this checklist as a new tab and rename with your name as you begin testing: [Jira Testing Checklist](https://docs.google.com/spreadsheets/d/1cOOfrPHg0QTEJb-99LOfZ6_EKtaFGknyhrJmEKiXVso/edit?usp=sharing)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-181)

**Comment by kristinashu** [comment]
Here's the PRD as well https://docs.google.com/document/d/1KDfd5KI7XQeKXE-5FvEM4KrgbFur48jjdyGDmcS9QIY/edit

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

As we are currently using our Jira project already for sprint planning, this is considered as done.
