### ISSUE TITLE
PNI - Increase character limit for 4 rich text fields

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#10983]
Vampire Killer: Jen Caltrider

Original request:

> Misha ran into a (smallish, but not exactly small) issue as we’ve started to enter the cars content into the CMS. Some of the reviews are a bit longer than normal (because we’re reviewing 6 or 7 privacy documents and lots more than usual other stuff) and we’re hitting a world limit on the “what could happen” blurbs. I believe the current word limit is 5000 and i think some of these might run upwards of 7500 or so. Is it possible/not too time consumer and difficult to increase the word limit for that section?

Additional from @TheoChevalier:
> Chiming in just to ask that we increase the word count limit that Jen needs by ~20% to avoid hitting the exact same issue once translations are ready

And from Misha
> To be on the safe side, I would increase all the limits for the 4 blurbs:
> - intro blurb,
> - 'what could go wrong',
> - 'how does it use data' (to 20000)
> - 'what control does user have'

Let's increase the character limit for the following field to 10,000 to give overhead.

### Dev Tasks
- [ ] Increase the `max_limit` for `blurb` to `10000`
- [ ] Increase the `max_limit` for `worst_case` to `10000`
- [ ] Increase the `max_limit` for `how_does_it_use_data_collected` to `20000`
- [ ] Increase the `max_limit` for `how_can_you_control_your_data` to `10000`

### Acceptance Criteria

For each of the 4 fields above,

- [ ] As an editor, I can publish PNI product pages when [the field] above is at or under 10,000 characters
- [ ] As an editor, I cannot publish PNI product pages when [the field] is above 10,000 characters

**Comment by mtdenton** [comment]
@mmmavis to groom in migration step

**Comment by mmmavis** [comment]
@mtdenton do you mind helping me QA this on staging? https://foundation.mofostaging.net/cms/pages/24630/edit/
