### ISSUE TITLE
Pull Campaign ID from Petitions URL

### ISSUE THREAD

**Issue by Gbaldassano** [MozillaFoundation/foundation.mozilla.org#11026]
### Context
As discussed with Christian last week, the Engagement team has flagged that setting up various parts of a Petition campaign can be very time consuming. From Christian:

> For the ads program, we're facing the challenge of accurately tracking ad performance (cost per acquisition, attribution etc). The only way around this is having a dedicated landing page for each ad we're running (if we wanted to be 100% accurate, we'd even need a dedicated page for each ad variation in creatives). The setup process involves several pieces (shareprogress, Wagtail campaign page, petition snippet, donation snippet) that all need to be set up manually for each page. That takes up 15-20 minutes per page overall, which doesn't exactly catalyze our ambitions to scale up this progress in the medium term.

As a way to cut down on this, one solution identified is to pull in the campaign ID from the petition URL and send to Salesforce.

mtdenton @jhonatan-lopes could you add more info here about what needs to be done?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-186)

**Comment by simont-cr** [comment]
@jhonatan-lopes Do you have any insight about this ticket based on the initial request?

**Comment by jhonatan-lopes** [comment]
@simont-cr, @mtdenton was working on this but I'm not sure where it was left off. The goal was to use `utm` parameters to pass the campaign id through the urls

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Tyler Denton Per Jhonatan’s comment, you were the one working on this issue previously. Do you feel that we need to groom in order to work on it, or we can actually remove altogether?

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Closing ticket for lack of context for grooming.
