### ISSUE TITLE
Mozilla.vc GA set up

### ISSUE THREAD

**Issue by Gbaldassano** [MozillaFoundation/foundation.mozilla.org#11025]
Mozilla.vc team has requested a GA4 property so that they can link it with their Consider job board. Before we do that, it may be good to ask someone like Nneka if this can live with Foundation GA properties or if it needs to live somewhere else.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-100)

**Comment by Gbaldassano** [comment]
@mtdenton can this be picked up this sprint?

**Comment by mtdenton** [comment]
Splitting this into two separate issues.

**Comment by simont-cr** [comment]
@shing-mofo Do you have any insights by any chance if this might be somewhat related to the GA4 issues that we just closed?

**Comment by shing-mofo** [comment]
@simont-cr No, this is different. I don't see a Mozilla VC GA4 property set up in our instance, I just sent an email to the stakeholder to see if I can get more info - but lets keep this open and I will circle back.

**Comment by abi-mofo** [comment]
@simont-cr  Adam from the VC team confirmed they are all set- we can close this one!
