### ISSUE TITLE
PNI - Increase char limit for 3 fields

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11033]
Related to #10983 

Upon request (via [Slack](https://mozilla.slack.com/archives/C04JFV09EDC/p1692987908441869)), we need to bump up max char limit again. 

This will need to land by Monday next week.

### Dev Tasks
- [ ] Increase the `max_limit` for `worst_case` to `20000`
- [ ] Increase the `max_limit` for `how_does_it_use_data_collected` to `40000`
- [ ] Increase the `max_limit` for `how_can_you_control_your_data` to `20000`

### Acceptance Criteria

For each of the 3 fields above,

- [ ] As an editor, I can publish PNI product pages when [the field] above is at or under [max limit] characters
- [ ] As an editor, I cannot publish PNI product pages when [the field] is above [max limit] characters

**Comment by jhonatan-lopes** [comment]
@mmmavis @mtdenton, on the previous work we also bumped the `max_limit` for `blurb` to `10000`. Could you please confirm that we do not need to bump this one as well?

**Comment by mtdenton** [comment]
@jhonatan-lopes Thanks for flagging, I have a question out to Jen about this, sit tight!

**Comment by mtdenton** [comment]
@jhonatan-lopes Just got word from Jen, no need to increase Intro Blurb limit. Thanks for checking!
