### ISSUE TITLE
Investigate Mozilla.vc Wordpress Password Reset Issues

### ISSUE THREAD

**Issue by Gbaldassano** [MozillaFoundation/foundation.mozilla.org#11068]
### Context:
There have been several issues with Mozilla.vc colleagues trying to reset their Wordpress passwords in the past few weeks. It seems like the password reset email is not getting sent to these users.

### Additional info:
It's possible nothing was put in place to send email out from the website with a @mozilla.vc email address.
Either Gmail is catching these and rejecting them or something is busted on the WPEngine side. 
We may had to set up  a pass-through email address because WordPress' default mail system can be unreliable

### Potential next steps:
* Confirm if the mozilla.vc google group is already set up. If not,
* Set up a Google Groups email account or using another SMTP mailer service like Mailgun (either would require MoCo help)
* Installing and configuring a WordPress plugin to utilize that mail account for outbound site mail. (The WP plugin is already approved for use.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-188)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Hey Tyler Denton , is there a way to confirm if this is still happening and would require to continue investigation on this matter or this might already be considered as Closed or Abandoned?
