### ISSUE TITLE
SPIKE - Baselines for Story Point Estimation

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#11071]
Timebox to 1 hour

Confluence page: https://mozilla-hub.atlassian.net/wiki/spaces/webplatforms/pages/340034569/Story+Points

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-191)

**Comment by simont-cr** [comment]
@mmmavis @danielfmiranda @jhonatan-lopes Can you take a look at this whenever you have a chance on your documentation specific day? I feel there's not much that's missing on this page to complete it and there might be better examples now. Thanks!

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

I think that we’re pretty much find with the current baselines used in the Confluence page. I will close this ticket for the time being and once we need some specific task on this, we can create another ticket or reopen.
