### ISSUE TITLE
[PNI Privacy Index] Development Prep & Handoff

### ISSUE THREAD

**Issue by tessheinricks** [MozillaFoundation/foundation.mozilla.org#11073]
Prepare designs for Dev hand-off

**Communication:**
- [x] Meet with Mavis

**Exports:**
- [x] Illustrations
- [x] Product Images

**File Preparation:**
- [x] Redline for dev
- [x] "Ready for dev" [Figma](https://www.figma.com/file/idw7tpYbaRXCRqzk01poEX/Privacy-Index-Page?type=design&node-id=1090%3A13156&mode=design&t=jWzA4lmQNMP4EksD-1) Page Completed

**Continued Support:**
- [x] Support dev
~Review dev tickets (Acceptance Criteria)~

**Comment by sabrinang** [comment]
Checked with Mavis that her dev tickets are good since she already started development so we will skip the AC checkbox for this project. Continued design support will be provided in corresponding PRs.
