### ISSUE TITLE
[Main Navigation Drop Down | Discovery] PRD Creation

### ISSUE THREAD

**Issue by tessheinricks** [MozillaFoundation/foundation.mozilla.org#11104]
Efforts towards defining project scope & creation of a PRD

**Comment by sabrinang** [comment]
Tess and I worked on drafting the PRD for the main navigation menu work and it is in google docs here: https://docs.google.com/document/d/1X7LCoOv5KtYRmmp0-SRjFRgHG7LWxt_nlskz8tQwZz8/edit?usp=sharing

@kristinashu ready for your feedback and review

**Comment by kristinashu** [comment]
This is very thorough and thoughtful! I left some comments and questions but it's looking really good. It would be great if you could share this with Gen tomorrow morning and ask if she can review it by the end of this week.

**Comment by sabrinang** [comment]
Thanks Kristina for the insightful comments and feedback. We incorporated and resolved the feedback to revise the document. @Gbaldassano has been tagged in the doc and slack messaged to give her feedback and input!

**Comment by tessheinricks** [comment]
The PRD has been created and will continue to evolve based on stakeholder feedback.
