### ISSUE TITLE
[PNI] Update press page

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11138]
Update info on [press page](https://foundation.mozilla.org/en/privacynotincluded/about/press/) (currently hardcoded and not on CMS).

Revised version is on https://docs.google.com/document/d/1InL0XlA1XuJsu-MoSkRk7acX-Ni-j0sb52OqTQ-mBt4/edit#heading=h.sa73c5locnym.

**Comment by kristinashu** [comment]
@Gbaldassano @mtdenton although this isn't a priority ticket, it is a small one and would be good to have done before the holiday launch.

**Comment by danielfmiranda** [comment]
Hi @zoe-PNI! 

The updated press page has made it to staging and is now ready for QA.

Whenever you find a free moment, can you please take a look at foundation.mofostaging.net/privacynotincluded/about/press and let me know if everything looks as expected? Thanks!

**Comment by danielfmiranda** [comment]
I have received verbal confirmation from stakeholders that everything looks OK :+1: moving to ready for prod!
