### ISSUE TITLE
[SPIKE] Increase code readability for template files

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11154]
Since Tailwind is an utility based framework and that we want to use as our primary way to style elements, our template files are starting to get crammed with long lists of Tailwind classes. These classes can be added in any random order which makes the initial development phase faster but worsens code readability and maintenance for any subsequent work.

Using the one-off PNI Consumer Creep-O-Meter custom page as an extreme example - in the template file, the majority of code is from the usage of Tailwind classes (from a quick scan, it seems 90% to me).

e.g., 
![](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/5047e6e6-9e41-4f70-be2c-4fb8c9cad6e5)

There are some things we should consider and research on

* best practice to organize Tailwind classes so they are added in the template in a meaningful, consistent way
* any linting / formatter available for us to use
* (please add your suggestions here)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-194)

**Comment by jhonatan-lopes** [comment]
We need to quickly re-establish a linter here for our templates. We currently only have `djhtml` which is only a spacing formatter. We have `djlint` installed, but it is disabled and has been giving us problems since an update. Wagtail core uses `curlylint` but the standard is using `djlint`.

Besides that, we could break up large templates into fragments/reusable components to make sure that code is not duplicated and that templates are more manageable.

https://tailwindcss.com/docs/reusing-styles

https://tailwindcss.com/docs/adding-custom-styles#adding-custom-utilities

**Comment by jhonatan-lopes** [comment]
Wagtail uses [`fragment` to separate class names from the HTML attribute](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/headers/slim_header.html#L2-L4):

```html
{% load wagtailadmin_tags i18n %}
{% fragment as nav_icon_classes %}w-w-4 w-h-4 group-hover:w-transform group-hover:w-scale-110{% endfragment %}
{% fragment as nav_icon_button_classes %}w-w-slim-header w-h-slim-header w-bg-transparent w-border-transparent w-box-border w-py-3 w-px-3 w-flex w-justify-center w-items-center w-outline-offset-inside w-text-text-meta w-transition w-group hover:w-text-text-label focus:w-text-text-label expanded:w-text-text-label expanded:w-border-y-2 expanded:w-border-b-current w-shrink-0{% endfragment %}
{% fragment as nav_icon_counter_classes %}-w-mr-3 w-py-0.5 w-px-[0.325rem] w-translate-y-[-8px] rtl:w-translate-x-[4px] w-translate-x-[-4px] w-text-[0.5625rem] w-font-bold w-text-text-button w-border w-border-surface-page w-rounded-[1rem]{% endfragment %}
{# Z index 99 to ensure header is always above  #}
<div class="w-sticky w-top-0 w-z-header">
    <header class="w-slim-header w-flex w-flex-col sm:w-flex-row w-items-center w-justify-between w-bg-surface-header w-border-b w-border-border-furniture w-px-0 w-py-0 w-mb-0 w-relative w-top-0 w-z-header sm:w-sticky w-min-h-slim-header">

        {# Padding left on mobile to give space for navigation toggle, #}
        <div class="w-pl-slim-header sm:w-pl-5 w-min-h-slim-header sm:w-pr-2 w-w-full w-flex-1 w-overflow-x-auto w-box-border">
            <div class="w-flex w-flex-1 w-items-center w-overflow-hidden">
                {% block header_content %}
                    {% if breadcrumbs_items %}
                        {% breadcrumbs breadcrumbs_items %}
                    {% endif %}
                {% endblock %}
            </div>
        </div>

        <div class="w-w-full sm:w-w-min w-flex sm:w-flex-nowrap sm:w-flex-row w-items-center w-p-0 sm:w-py-0 sm:w-pr-4 sm:w-justify-end">
            {% block actions %}
                {% if side_panels %}
                    {% include "wagtailadmin/shared/side_panel_toggles.html" %}
                {% endif %}
            {% endblock %}
        </div>
    </header>

    {% block side_panels %}
        {% if side_panels %}
            {% include "wagtailadmin/shared/side_panels.html" %}
        {% endif %}
    {% endblock %}
</div>
```

**Comment by mtdenton** [comment]
Yes but timebox.

**Comment by jhonatan-lopes** [comment]
Example of using `fragment` to increase code readability: https://github.com/MozillaFoundation/foundation.mozilla.org/pull/12146/files
