### ISSUE TITLE
[EOY] - Needs to be live by 11/16 - [Post Deploy] set up DonateHelpPage redirects

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11176]
Once the new DonateHelpPage has been deployed to production and is live, we are going to need to set up the following redirects:
- [x] https://donate.mozilla.org/help/ -> https://foundation.mozilla.org/en/donate/help/
- [x] https://donate.mozilla.org/faq/ -> https://foundation.mozilla.org/en/donate/help/#frequently-asked-questions

~https://foundation.mozilla.org/donate/  -> https://foundation.mozilla.org/?form=donate~

**Comment by kristinashu** [comment]
I've removed the redirect ask for https://foundation.mozilla.org/donate/  -> https://foundation.mozilla.org/?form=donate from the list since WE HAVE A DONATE PAGE and we should just show that!

![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/91a8416b-cd3b-4b36-a707-abcdfeb81c55)

**Comment by Gbaldassano** [comment]
@kristinashu do you mean show https://donate.mozilla.org/en-US/ when someone loads https://foundation.mozilla.org/donate/ instead?

I still don't see anything living on https://foundation.mozilla.org/donate/ so we would need a redirect to either

https://donate.mozilla.org/en-US/ 

or  

https://foundation.mozilla.org/?form=donate

correct?

cc: @mtdenton

**Comment by danielfmiranda** [comment]
Hi @Gbaldassano! with https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11386 being merged into main, we can now create a DonateLandingPage (pictured in @kristinashu 's comment), at the URL http://foundation.mozilla.org/donate, we just need to go into the CMS and create it. Heres a link to an example page set up on staging: https://foundation.mofostaging.net/en/donate/

All donate updates have made their way onto `main`, so once we push to prod tomorrow 11/14, we will be able to create the following:

- Donate Landing Page (which will have the URL of /donate/)
- Donate "ways to give" page (which will have the URL /donate/ways-to-give)
- Donate "help" page (which will have the URL /donate/help)

**Comment by mtdenton** [comment]
Yep, didn't realize that, the redirects are deleted.

**Comment by mtdenton** [comment]
Added correct blocker ticket
