### ISSUE TITLE
[PNI Privacy Index] Enhance a11y

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11171]
Before merging the work into `main`, we should do a final check to make the page more accessible.

Some things to look for and fix

- semantic HTML (especially for sections and headings)
- proper `alt` text for images
- add `aria-label" to links that are not descriptive on its own
- etc

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-113)

**Comment by simont-cr** [comment]
Closed per 2024 ticket purge.
