### ISSUE TITLE
[PNI Privacy Index] Cleanup & Final Edits

### ISSUE THREAD

**Issue by tessheinricks** [MozillaFoundation/foundation.mozilla.org#11185]
### This is a space to capture any final tweaking of the PNI Creep-O-Meter development

**Hero**
- [ ] **[P2]** Creep-O-Meter Emoji brought up to remain visible - top of speech bubble stem is brought more in line with top of emoji head
- [x] Speech bubble on mobile: Can be less wide for stem to be closer to left side of emoji face like mockup 
- [ ] Lead copy font weight: Appears to renders heavier than figma file (although inspector says it is using ExtraLight?)
- [ ] Asterisk illustration location between 768<1200 breakpoints: It gets obscured so perhaps placing it like mobile in upper left but larger
- [x] Swap current asterisk illustration with spot illo 1, the dark purple sad face one

**Quiz**
- [x] Add "Retake Quiz" icon in button
- [x]  **[P1]** Make scroll bar permanently visible (so users always know there is additional products to select)
- [x] **[P1]** Twitter share button links to Facebook
- [ ] **[P2]** Improve quiz result images load speed to be instant the first time (they have a bit of a delay on first load but once they have appeared they load instantly)
- [x] **[P2]** Share button icon disappears after clicking on the button
<img width="600" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/89d7a6f7-8f30-47ff-98db-c755a47489c1">

- [ ] Revise [See Results button module](https://www.figma.com/file/idw7tpYbaRXCRqzk01poEX/Privacy-Index-Page?type=design&node-id=2872%3A10272&mode=design&t=J3ZG0pJGyLNmsclS-1):
Adding a button for users who don't own any of the products or don't select any products. The see results button should be inactive until a user selects products, and if a user selects the "I don't own any" button they should continue through the flow.

![Quiz Addition - _I don't own any_](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/141766274/0ba29519-5108-4f5c-88a4-2b18f1c259f7)

**Stay in Control** 
- [ ] Refine shared colour gradient 
- [ ] Refine header & image relationship for mobile & smaller screen sizes
- [x] Within "Wield Your Pocketbook" Add [link](https://foundation.mozilla.org/en/blog/applause-for-apples-idfa-decision/) to "Apple" - Ensure page opens in a new tab
- [x] Within "Wield Your Pocketbook" Add [link](https://foundation.mozilla.org/en/blog/zoom-makes-right-call-encryption/) to "Zoom" - Ensure page opens in a new tab

**Our Approach**
- [x] **[P2]** Make “one research report” have an underline now that it is linked
- [x] Make “one research report” link black (instead of blue)
- [x] "our methodology" link should open in a new tab 

**Universal**
- [ ] Email subscription box revision - going to launch with pre-existing form but can revise to stack on mobile post launch.
- [x] **[P1]** Links opening on separate tabs instead of same page (if we want to keep users on the page to complete the other CTAs consider opening all links on new tabs)

**Comment by Gbaldassano** [comment]
Hey @tessheinricks @mmmavis  @mtdenton @danielfmiranda 

We've gotten some feedback from stakeholders on this link: [PNI Index Page (WIP)](https://foundation-s-feature-pn-12imga.mofostaging.net/en/privacynotincluded/articles/annual-consumer-creep-o-meter/)
Can these be addressed before we launch?

**From Kevin:**
- There’s some redundant text on the quiz responses. The headline is repeated in the first sentence of the paragraph. We can remove that first sentence.

**And a few questions From Christian:** I've already responded to these in [this slack thread](https://mozilla.slack.com/archives/C04JFV09EDC/p1696959840964549?thread_ts=1696863568.358089&cid=C04JFV09EDC)
- there's signup options for the newsletter as part of the quiz + in a separate frame right below (+1 at the bottom - love the many prompts!) - are those both signups for the MoFo News newletter?
- are we capturing if people join through those widgets? If not, could we implement that?
- There is only the our generic donation ask at the bottom of the page - would it be possible to make that donation ask a part of the design flow? We'd happily provide copy + a dedicated fundraise up campaign

**Comment by mmmavis** [comment]
I have a WIP PR #11242 that covers improvement for the quiz section (I addressed Kevin's feedback in the ticket). I will wrap up that PR after I get the Stay in Control section implemented.

**Comment by mtdenton** [comment]
Removed redundant privacynotincluded.org text and added a link to a report via Sabrina's feedback, [PR](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11252) is here

**Comment by kristinashu** [comment]
Thank you @mtdenton! I took a stab at prioritizing the items.

**Comment by tessheinricks** [comment]
Hi team! Just flagging a couple additional link edits for the **Stay in Control** & **Our Approach** sections. You can find them above but wanted to repeat them here as well. 

**Stay in Control**
- Within "Wield Your Pocketbook" Add [link](https://foundation.mozilla.org/en/blog/applause-for-apples-idfa-decision/) to "Apple" - Ensure page opens in a new tab
- Within "Wield Your Pocketbook" Add [link](https://foundation.mozilla.org/en/blog/zoom-makes-right-call-encryption/) to "Zoom" - Ensure page opens in a new tab

**Our Approach**
-  Make “one research report” link black (instead of blue)
- "our methodology" link should open in a new tab

Please let me know if you have any questions and thank you for all of your hard work and patience!

@mmmavis @mtdenton @danielfmiranda @sabrinang @kristinashu

**Comment by kristinashu** [comment]
@mtdenton will make the updates now to open links in a new tab

**Comment by kristinashu** [comment]
Adding Theo's ticket about removing /en from all links https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11253

**Comment by mtdenton** [comment]
There's a[ PR](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11272) to address several of these, looking to push out today.

**Comment by mtdenton** [comment]
PR is out, top ticket is updated!

**Comment by mtdenton** [comment]
Updated above with completed items from #11273 being pushed to prod

**Comment by kristinashu** [comment]
Thank you everyone who helped find and/or fix these! I'm going to go ahead and close this ticket since the critical ones are done. Please feel free to reopen or open individual tickets for items you feel are still important to complete.
