### ISSUE TITLE
(Launch 11/16) FE - Make the text and link on the Donate Banner into editable fields

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11180]
### Describe the feature request
Front-end work for #9823.

Design: Finalize design for donate alert banner #11247
[Figma file ](https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/Fundraising?type=design&node-id=1537%3A48&mode=design&t=QG5dHmnXxHXF9vIW-1), additional notes [here](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11180#issuecomment-1785918481)

Additional direction from Kristina:
Design is based on what is currently live on https://foundation.mofostaging.net/ but with these updates:

- Text is white
- Heading is H1 but I had to make it the bolder Semi bold weight (max character count 60)
- Body is Body Large but Semi bold weight (max character count 200)
- Remove the Cta text field in the CMS
- Close icon is white
- Red #FF4F5E background 
- No overlay
- Image scales and crops differently (I expect some back and forth between design and dev when QAing this)

Responsive image
- Please pin to the right side for desktop (image scales down as browser shrinks)
- Stack the image on top of the text at narrower widths

### Screen caps (note the blue outline shows the transparent png image area)

![Desktop Layout _ Dark mode _ 2023 Design](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/82d1e4ba-c27b-4dbb-8267-906eb24c76e5)

<img width="700" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/23834dbe-8e26-46b6-8a26-ad28a1feea30">

<img width="600" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/de0f44a2-b45b-453a-bba8-d133834ee7bc">

<img width="300" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/c4862f5c-f921-495f-b2af-143ebd6bef55">

Deadline: Aim to have everything merged by 11/16 to account for holidays/shortened bandwidth the following week. The first banner is planned to launch the Monday before for Giving Tuesday, 11/27th

Including Dev Tasks & Acceptance Criteria from BE ticket:
-As a CMS user, I want to be able to update the copy/link/imagery of the donate banner on the MoFo website without need for dev intervention.
Note:
-Text must be localizable

**Comment by mtdenton** [comment]
@danielfmiranda here's the existing ticket for the front-end work.

**Comment by kristinashu** [comment]
Hi @danielfmiranda the design done in https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11247 has been approved by the stakeholder! 


[Figma file ](https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/Fundraising?type=design&node-id=1537%3A48&mode=design&t=QG5dHmnXxHXF9vIW-1)


### A few design notes

Heading
- Left side is H1 but I had to make it the bolder Medium weight
- Giving a generous max character count 100

Body
- Right side is Body Large but Semi bold weight 
- Giving a generous max character count 200

Background image
- Please scale this from the center (top, bottom and sides get cropped as the image scales
- You can use this image to test with
![mozilla-donate-banner-blue](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/44b56919-f47b-4a7b-ab4d-7b066b53dc27)


### Screen caps

![Desktop Layout 3](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/f641afed-1fc9-404f-99d6-b9d2e240c89c)

<img width="300" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/06a4c9cc-8c27-4690-88ab-7bd0d93473c5">

<img width="700" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/897a34d8-983d-4cfc-b4f5-05dad8fb85ef">

**Comment by kristinashu** [comment]
Sorry but please hold off on this, there's some additional back and forth with the stakeholder and I'm not confident the design won't change. cc @Gbaldassano

**Comment by mtdenton** [comment]
@danielfmiranda just had a convo with @Gbaldassano and @kristinashu , let's keep going here today, they're about to have a convo with the stakeholder. I'll chat you on Slack for more details.

**Comment by kristinashu** [comment]
Although still not 100% approved by the stakeholder, here's the preferred direction. 

Design is based on what is currently live on https://foundation.mofostaging.net/ but with these updates:
- [ ] Text is white
- [ ] Heading is H1 but I had to make it the bolder Semi bold weight (max character count 100)
- [ ] Body is Body Large but Semi bold weight (max character count 200)
- [ ] Remove the Cta text field in the CMS
- [ ] Close icon is white
- [ ] Red #FF4F5E background 
- [ ] Red #FF4F5E transparent overlay (keep blur)
- [ ] Image scales and crops differently (I expect some back and forth between design and dev when QAing this)

Background image
- Please pin to the right side for desktop (left side, top, and bottom get cropped as the image scales)
- Stack the image on top of the text at narrower widths

Here is the [Figma file ](https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/Fundraising?type=design&node-id=1537%3A48&mode=design&t=QG5dHmnXxHXF9vIW-1)


### Screen caps (note the blue outline is just to show the bounding boxes)

![Desktop Layout 3](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/9f488dee-d5d2-436e-a21e-5c50e9594193)

<img width="300" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/5c959036-9c14-47e3-9de1-62dc9f91c6bc">

<img width="700" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/b878d9a9-97c8-44c2-aef5-31c463c14f39">

Thank you @sabrinang for doing the design review!

**Comment by Gbaldassano** [comment]
@danielfmiranda just confirming Michael has confirmed the crop/image scaling that @kristinashu outlined above is approved, so this should be 100% good to go.
cc: @mtdenton

**Comment by mtdenton** [comment]
Updated original ticket with @kristinashu 's notes for ease of use

**Comment by danielfmiranda** [comment]
Have updated the #2023-eoy-banners channel in slack, and they are all happy with whats on staging :+1: ready for prod!

**Comment by danielfmiranda** [comment]
This change has made it to prod. Closing!
