### ISSUE TITLE
Review Active Typeform Instances

### ISSUE THREAD

**Issue by Gbaldassano** [MozillaFoundation/foundation.mozilla.org#11186]
Context:
We are going to downgrade our Typeform account while we have legal review the terms of service, but the business account does not come with GDPR compliance which is a significant issue.

We should review any/all active Typeform instances and replace with Form Assembly while we figure out if this is a tool we can keep longer term. 

For reference, PNI consistently receives submissions from Typeform (300+ in the last month because of the cars editions)

Engagement team is using this form to collect feedback: https://mozillafoundation.typeform.com/to/xm6oqkYH
If Typeform is going away, we need to plan to transition this to Form Assembly. Jira ticket here: https://mozilla-hub.atlassian.net/browse/MOFOTP-25

If we need to build new Form Assembly forms, Plative may be able to help build them for us.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-115)

**Comment by Gbaldassano** [comment]
@kristinashu @mtdenton FYI - what's the best way to review these? Is there a dashboard we should look at?

**Comment by kristinashu** [comment]
Thank you for creating this ticket Gen! Design has not created themes in Form Assembly, we really haven't played around with it much at all. I can create a design ticket to do that - for reference, here was the one for Typeform https://github.com/MozillaFoundation/Design/issues/798. What is the timeline for templates? Our upcoming sprint is already looking pretty full with holidays, PTO, StratOps calls, and the already ongoing projects of blog newsletter signup and main nav drop down.

**Comment by Gbaldassano** [comment]
@kristinashu re: timeline, templates don't need to be created in the next sprint, just want to start reviewing now so we have an understanding of what needs to be replaced. We can talk timing during design sprint planning.
