### ISSUE TITLE
[Blog Newsletter] PRD Sign off

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#11208]
Get sign off from everyone on [PRD](https://docs.google.com/document/d/1WdT7hqRaXX1_8TjIyzfhkMYKxrThVckp9xkeJ5iUMnc/edit#heading=h.e1hdva6khlbd)

**Comment by kristinashu** [comment]
Gen is wrangling this so I think you can go ahead and close this ticket @nancyt1!
