### ISSUE TITLE
[Blog Newsletter] Gather baseline metrics

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#11206]
- [x] Chat with Dan
- [x] Get baseline metrics
- [x] Document in a slide deck or figma
- [ ] Optional: Build GA4 report to reflect this work

**Comment by nancyt1** [comment]
Added baseline metrics to this [slide](https://docs.google.com/presentation/d/15A57JqoAQMFmjDyRKa0eji9xvuq8sASNSq_kIS_iqwM/edit#slide=id.g28a2317c3ab_0_29), numbers were slightly different between GA4 reports and GA4 explore pages so everything is approximate. I'll probably calculate again closer to when it gets implemented!

**Comment by kristinashu** [comment]
So interesting, thank you for gathering that info!
