### ISSUE TITLE
Remove trailing slash from https://basket-dev.allizom.org/

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11220]
According to [Basket's doc](https://basket-client.readthedocs.io/en/latest/install.html):

> BASKET_URL
      URL to basket server, e.g. https://basket.mozilla.org
      Default: http://localhost:8000
      The URL must not end with /. Basket-client will add / if needed.

Currently, testing newsletter subscription is not possible locally and on review app because the BASKET_URL we set includes a trailing slash. Let's remove that!

<img width="868" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/aa8f18a6-2abe-4ddc-a4ce-ad71e2487752">

**Comment by mtdenton** [comment]
Running this to the top of the backlog, super easy fix.
