### ISSUE TITLE
[EPIC] Refactor newsletter signup front-end components

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11225]
We have so many variations of newsletter signup form on the site. Rough estimate would be 20+ including variations with slight UX/UI differences. It would be great if we can do an audit to see if we can cut down the set a bit so we can clean up the codebase to make things more streamlined.

For example, the React component [`join.jsx`](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/source/js/components/join/join.jsx) used for rendering the newsletter signup has become a monster to tame. 😱😱😱😱😱  We should really refactor it sooner than later. (Not to mention there are other components in the codebase that are doing the similar jobs for newsletter signups) 

### Some topics to talk about when we tackle this work

- Could we use browser's default form validation?
  - If not, do we wanna improve on the current validation logic? Specifically the regex for validating emails
- Create pre-defined styles for form fields and add them to Tailwind configs
- Revisit existing form related Tailwind styles in Tailwind configs 

### Pre-work

Now that we have created a new set of React Component using atomic approach, we should convert the existing newsletter modules away from `join.jsx`. Tickets will be filed and added to this epic.

Audit sheet: https://docs.google.com/spreadsheets/d/1EeWshn5N7f6eEZ8eBdMS_IEF1RtFuaXFeUrwLEX96js/edit#gid=0

**Comment by mtdenton** [comment]
To the top!

**Comment by mmmavis** [comment]
Here's my plan for creating a new set of React components, based on atomic design methodalogy, to render newsletter signup module

In `source/js/`:
```
├── components
│   ├── ...
│   │   └── ...
│   ├── join (existing, all existing signup variations are handled here, won't be touched in this ticket)
│   │   ├── join.jsx
│   │   ├── join.scss
│   │   └── language-select.jsx
│   ├── ...
│   ├── ...
│   ├── ...
│   ├── newsletter-signup (new, to be created)
│   │   ├── atoms
│   │   │   ├── heading.jsx
│   │   │   ├── description.jsx
│   │   │   ├── label.jsx
│   │   │   ├── validation-error.jsx
│   │   │   ├── input-text.jsx
│   │   │   ├── input-checkbox.jsx
│   │   │   ├── select.jsx
│   │   │   ├── button-submit.jsx
│   │   │   ├──
│   │   │   └──
│   │   ├── molecules (e.g., label + input + validation error message)
│   │   │   ├── input-text-field.jsx
│   │   │   ├── input-checkbox-field.jsx
│   │   │   ├── select-field.jsx
│   │   │   ├──
│   │   │   └──
│   │   ├── organisms
│   │   │   ├── form-variation-1.jsx (placeholder file name)
│   │   │   ├── form-variation-2.jsx (placeholder file name)
│   │   │   ├── form-variation-3.jsx (placeholder file name)
│   │   │   ├── form-validator.js (HOC)
│   │   │   └──
│   ├── ...

```

I don't love the file structures here as typically directories like `atoms`, `molecules` etc should be moved to higher level. Since this new newsletter box is the first component that we build using atomic design approach, I think it's okay to leave them under `newsletter-signup` dir for now to reduce confusion in codebase.

**Comment by mmmavis** [comment]
A note that we are thinking about changing how we do newsletters signup in general. Stay tuned for updates.

**Comment by mmmavis** [comment]
Just did an audit to find out how many variations of newsletter signup forms `join.jsx` is responsible of generating. Here's the [Google Sheet](https://docs.google.com/spreadsheets/d/1EeWshn5N7f6eEZ8eBdMS_IEF1RtFuaXFeUrwLEX96js/edit#gid=0). I will be creating tickets today based on it.

**Comment by mmmavis** [comment]
🎉 🎉 🎉 🎉 🎉  DONE  🎉 🎉 🎉 🎉 🎉
