### ISSUE TITLE
Refactor share buttons

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11243]
Similarly to [https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11225](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11225), we have so many variations of share buttons on the site. Some are backed with Shareprogress and some are not. Some are implemented in React and some are in the combo of plain HTML and vanilla JS.

## Dev Task
* Audit to see how many designs and code variants we have for the share buttons
* Based on the audit, streamline design and implementation so they are more maintainable.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-197)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/63629">image-20240527-174517.png</a>

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Per Kristina report, share buttons are slightly cut off at medium browser widths, as seen here ( https://foundation.mozilla.org/en/campaigns/demand-privacy-for-all-support-a-us-data-privacy-law-v1/?thank_you=true ).

!image-20240527-174517.png|width=719,height=529,alt="image-20240527-174517.png"!

**Comment by data-sync-user** [comment]
➤ Nancy Tran commented:

This is the link to the component ( https://www.figma.com/design/sOxNGYMzwZT0B9Fal2D4WT/%5BWIP%5D-Component-Library?node-id=788-6205&t=vcvMTcoZ45Du0rHM-1 ) in our design system.

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

We’ll start fresh for the new site. Since this is an improvement ticket for the current website, we can mark this ticket “abandoned”.
