### ISSUE TITLE
[Main Navigation Drop Down] Kick Off Preparation

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/foundation.mozilla.org#11250]
- [x] Kick off meeting prep
- [x] Create Slack channel
- [x] Agenda (discuss if we need slides, any framing from stakeholders)

**Comment by sabrinang** [comment]
We're doing some planning in the [notes doc](https://docs.google.com/document/d/1C9Yj5vHHrhz-2tEilQp_u8NyWPHANpQqjcY6_O2HinU/edit?usp=sharing)

**Comment by sabrinang** [comment]
- We created the [Agenda Notes doc](https://docs.google.com/document/d/1Fmq6hASEZTyv-RyMxLCj9r7zIt2KkHXQwId64nk5CU8/edit?usp=sharing) & [Kick Off slides](https://www.figma.com/file/BVh6wTOMI8WIVV3XOUQhwo/Main-Navigation-Drop-Down?type=design&node-id=304%3A1628&mode=design&t=rSaIPKzPuifclz0A-1)
- We did presentation planning and dry run yesterday 
- We created the [mofo-web-working-group](https://mozilla.slack.com/archives/C04DYP6T6VD) slack channel yesterday
- We had the Navigation Drop Down Kick Off meeting

**Comment by kristinashu** [comment]
Congrats on the kick-off, you both did an amazing job summarizing and presenting all the info!
