### ISSUE TITLE
Blog Newsletter Signup Implementation

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#11265]
Purpose: Create a new MVP newsletter sign up block that can be added to blog pages to increase email signups from blog posts.

This used to have a pretty aggressive due date, but expanding requirements and considerations means that the ball is in our court to estimate delivery.

## Overall Requirements
[Blog Newsletter PRD 2.0](https://docs.google.com/document/d/17VA5brmV3LIC4jhFLC_d78EwZ34-S4CKLXi7ZcOFR0M/edit#heading=h.e1hdva6khlbd)

## Front-End
[Figma File](https://www.figma.com/file/528nyaJFzvCXAiw2gglwzh/Blog-Improvements?type=design&node-id=3193%3A19466&mode=design&t=KMeRm1qrnXGz9565-1)

 - GA4 tracking should use a `data-` attribute for GTM to match on

## Back-End

- Implementation will be similar to the MozFest newsletter sign-up snippets
- A workflow needs to exist that prevents everyone but the web team from editing these snippets
- Fields needed:
    - Name (text) - CMS snippet identifier
    - Header (text) - Corresponds to "Reclaim the Internet" in the mock-up, need character limit
    - Description (rich text) - Corresponds to "Mozilla is fighting for a free..." in the mockup, need character limit
    - Nesletter(s) (text) - This is the CTMS newsletter subscription lists. Validation might be a little difficult, but it should 
allow one or more CTMS lists in the format of `newsletter-list-1`, or comma-separated multiples like `newsletter-list-1,newsletter-list-2` with no space in between. 
    - Submit button text (text): char limit TBD
- Editors should have a newsletter sign-up block to add to blog pages (not required, maximum of one for now)

## Open Questions
[Do we need to make submit button text CMS-editable?](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11265#issuecomment-1786205590)

**Comment by mmmavis** [comment]
@nancyt1 Do we need to make submit button text CMS-editable?

**Comment by nancyt1** [comment]
@mmmavis Ideally yes! But it's more of a p2 so if it adds a lot of time then it's ok.

**Comment by mmmavis** [comment]
@nancyt1 it shouldn't be a lot of work. I'll update the ticket description to reflect that. We'll also need to think about char limit for that field.

**Comment by mmmavis** [comment]
Launched! 🎉 🎉 🎉
