### ISSUE TITLE
[Main Navigation Drop Down] Research & Project Scope Sync

### ISSUE THREAD

**Issue by tessheinricks** [MozillaFoundation/foundation.mozilla.org#11266]
Connect with Genevieve (Kristina & Nancy as well if possible) to roadmap & align on how to tackle timeline, scope, and budget.

- [x] Discussed Calendar Holds/Office Hours
- [ ] ~Set up calendar holds~ moved to epic
- [x] PRD discussion
- [x] Scope / MVP, Long Term Plans

- How do we we future-proof and align with future work? 
- How are we going to manage scope without stifling future IA work?
- Does this project have space within the San Diego Work Week?

**Comment by sabrinang** [comment]
- sent out a calendar invite for Mon, Nov 6
- drafted meeting agenda here https://docs.google.com/document/d/1Fmq6hASEZTyv-RyMxLCj9r7zIt2KkHXQwId64nk5CU8/edit#bookmark=id.85vovyssi42y

**Comment by sabrinang** [comment]
[Notes](https://docs.google.com/document/d/1Fmq6hASEZTyv-RyMxLCj9r7zIt2KkHXQwId64nk5CU8/edit#bookmark=id.85vovyssi42y) captured Nov 6 meeting.

Setting up the calendar holds will continue in the epic https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11322
