### ISSUE TITLE
Add Documention for How Do I Wagtail for newsletter snippet block

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#11303]
After implementation is finalized, we should update our ["How Do I Wagtail?" Blog Post page](https://foundation.mozilla.org/en/docs/how-do-i-wagtail/specific-pages/blog-posts/) with instructions on how to select and insert a newsletter snippet block into blog pages.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-123)

**Comment by nancyt1** [comment]
I started some documentation [here](https://foundation.mozilla.org/en/docs/how-do-i-wagtail/specific-pages/blog-posts/#add-a-newsletter-signup-block), is there anything I'm missing?

**Comment by simont-cr** [comment]
@jhonatan-lopes Could you please take a look at what Nancy shared and check if there's anything missing that we need to focus on the next sprints or if this looks good?

**Comment by jhonatan-lopes** [comment]
LGTM :+1:
