### ISSUE TITLE
EOY Banner - Due 11/16 - Implement/QA Tracking

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#11304]
Goal of this ticket is to:

- Implement click tracking for the homepage banner & ensure all data flows to GA4
- QA donation data flow from banner and ensure donation data (and utms) are tracked in GA (probably our UA instance still), FRU, and Salesforce

Example UTM to test with:
?form=FUNXTSAQGHV&utm_medium=web&utm_source=eoy-banner&utm_campaign=23-EOY-Test&utm_content=banner_2023-eoy&utm_term=en

To confirm,

- Banner is not yet live so this needs to be tested on staging. How does staging enviroment impact what data is collected/sent over to FRU/GA/SF?
- How can we ensure data flow is tested on staging before going live?

**Comment by Gbaldassano** [comment]
@mtdenton can we add this to the current sprint/can this be finished up by next week?

**Comment by mtdenton** [comment]
@Gbaldassano this is implemented and live, but holding on closing this in case we want to verify through GA that these events are coming through. Event names are `donate_banner_cta_click` and `donate_banner_close`

**Comment by Gbaldassano** [comment]
@mtdenton would those names populate in GA4 now if the banner is still on staging?

**Comment by mtdenton** [comment]
@Gbaldassano yup:
![analytics](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/41487159/409b2839-60f2-4cd1-bca8-1b46f3f835e8)

`donate_banner_click` was renamed to `donate_banner_cta_click` to be more descriptive

**Comment by Gbaldassano** [comment]
@mtdenton - perfect, thank you! So is there more that we need to do here?

**Comment by mtdenton** [comment]
Normally I'd say yes so that we can take a follow-up look on prod, but there's no way for us to turn this on in prod just to take a look right now. We can trust that this works, but if we get to take a look at this while the banner is up later then we should.

**Comment by mtdenton** [comment]
Events are coming through, closing as complete
