### ISSUE TITLE
I cannot receive confirmation code when I tried to change my password at Mozilla account.

### ISSUE THREAD

**Issue by ReiNarumiya** [MozillaFoundation/foundation.mozilla.org#11307]
Hello, I would like your help with one thing.

I reset the password for "Mozilla Account". However, the email with the "confirmation code" that was supposed to arrive at the end has not arrived even now, from 8:00am to 2:30pm. I cannot find it in the SPAM folder. No matter how many times I reissue it, I never receive it. What should I do now?
If I made a mistake to post this issue here, please let me know where I should post this issue. 

Thank you.

![Snap_19](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/105433711/dde7dc01-6e76-47cd-b27f-ff681b92399b)

**Comment by kristinashu** [comment]
Hi @ReiNarumiya, thank you for reaching out. Have you tried going through the account support page https://support.mozilla.org/products/mozilla-account? This Github repo is for work related to https://foundation.mozilla.org/
