### ISSUE TITLE
[Main Navigation Drop Down] Wireframe Explorations

### ISSUE THREAD

**Issue by tessheinricks** [MozillaFoundation/foundation.mozilla.org#11325]
Initial design explorations for the Main Navigation Drop Down project to better evaluate design and development considerations and opportunities

Explorations can be found within [Figma](https://www.figma.com/file/BVh6wTOMI8WIVV3XOUQhwo/Main-Navigation-Drop-Down?type=design&node-id=475%3A295&mode=design&t=do0hN9Y4XeXrPLOG-1)

**Comment by tessheinricks** [comment]
This design process is continuing into the next sprint with the consideration that there is a work week from December 4th to 8th

**Comment by tessheinricks** [comment]
Wireframe and design explorations will continue post winter shutdown break. 

Currently the team is working towards design decisions using a card sorting / information structure documented in [Miro](https://miro.com/app/board/uXjVNDiDd-w=/?moveToWidget=3458764573859334251&cot=14) and the resulting design explorations in [figma](https://www.figma.com/file/BVh6wTOMI8WIVV3XOUQhwo/Main-Navigation-Drop-Down?type=design&node-id=475%3A295&mode=design&t=OqHQlaHsKx7ClPDi-1) 

Following the break there will be further refinement based on Dev discussions and further stakeholder feedback

**Comment by kristinashu** [comment]
LOTS of amazing exploration here! I'm going to close this ticket and we will start refining tomorrow in https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11674
