### ISSUE TITLE
[Blog Newsletter] Setup metrics and document block

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#11330]
- [x] Setup report or dashboard for metric collecting
- [x] Draft [documentation copy](https://docs.google.com/document/d/1FVNN_4amPicLeEZmlKouc4dIPhfljm4fKVoUFqP4A70/edit#heading=h.tkwri8bf6f6q)
- [x] Gather images
- [x] Update How-to-Wagtail

**Comment by kristinashu** [comment]
@nancyt1 I suspect building the block will take devs a couple sprints. Are you blocked until it's closer to launch, if so then perhaps move this to backlog?

**Comment by nancyt1** [comment]
@kristinashu That might be a good idea. I can pull in some other documentation work

**Comment by nancyt1** [comment]
Updated [wagtail](https://foundation.mozilla.org/en/docs/how-do-i-wagtail/specific-pages/blog-posts/) with documentation

**Comment by nancyt1** [comment]
Mavis added a "blog-body" to form location field so no additional work is needed from me but I setup a small area in this [dashboard](https://lookerstudio.google.com/s/n_YwzcpOcWs) to look at how signups are coming in in general. I will measure metrics again in a couple months to compare against the baselines I documented [here](https://docs.google.com/presentation/d/15A57JqoAQMFmjDyRKa0eji9xvuq8sASNSq_kIS_iqwM/edit#slide=id.g28a2317c3ab_0_29).
