### ISSUE TITLE
[Newsletter] Localization

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11351]
Make sure localization and localized strings are set up properly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-200)

**Comment by mmmavis** [comment]
Hello @TheoChevalier ,

There's something we are hoping to learn from your expertise 

TL;DR - 

I've implemented a new set of React Components to render the newsletter signup forms (mostly for cleaner implementation sake). For now I'm re-using [all the translation](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/source/js/components/petition/locale-strings.jsx) we have been using for petition/newsletter forms. We are curious what the process would be to get a new string translated? In particular we are hoping to have the submit button text set to something other than `Sign Up`. (e.g., `Join Now`)

**Comment by mmmavis** [comment]
I'm also wondering instead of storing the hardcoded translation in a file, will it work if we expose the string in the template and wrap them in appropriate tags to get the translation?

e.g., 

```

<div class="newsletter-signup-module" data-submit-button-text="{% trans "Join Now" %}">
  // note: this is where the React component will be inserted
</div>
```

And in the React component, we can use the value coming from `data-submit-button-text` to set the button text.

**Comment by TheoChevalier** [comment]
Hey @mmmavis,

Your proposal is very clever, and yes that should work. It’s way better than the current `locale-strings.jsx` hack. I suggest to:
- Use your solution for all new React string
- If/When time permits, migrate the existing strings from `locale-strings.jsx` as well.

If we’re able to wrap the strings as suggested, you won’t have to worry about the translation process, in the sense that they can be added at any time and will be deployed with the next production push.

**Comment by mmmavis** [comment]
@TheoChevalier That's very awesome to know! Thanks! I can't wait to get rid of hardcoded translation strings in the codebase 😁

**Comment by simont-cr** [comment]
@mmmavis The related EPIC is now closed, but is this ticket still valid in the context of work expected? If so, would it be enough for it to be a P3 or should we push for a P2 instead?

**Comment by mmmavis** [comment]
@simont-cr I would say P3 since the strings don't get changed often, there's no urgency to complete this ticket.

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

This is an enhancement ticket regarding our approach to displaying localized strings in React components. While the current solution works, there’s room for improvement. Since we’ll soon be shifting focus to building the new site, it might make more sense to turn this ticket into a “new site consideration” rather than something to complete for our current site.
