### ISSUE TITLE
[Main Navigation Drop Down] Internal Staff Survey via Google Forms | Implimentation & Initial Synthesis

### ISSUE THREAD

**Issue by tessheinricks** [MozillaFoundation/foundation.mozilla.org#11381]
This is part of a larger qualitative research epic https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11326

Tasks

- [x] Review within Design Crit
- [x] Distribute survey to Working group (Friday, November 10th)
- [x] Finalize survey based on feedback
- [x] Initial Synthesis efforts ahead of November Shareback 

Additional revisions will take place before distributing the survey to all MoFo Staff

**Comment by sabrinang** [comment]
- Reached out to Paul for feedback via slack, received feedback and scheduled quick call with him tomorrow
