### ISSUE TITLE
RCC Landing page links to Figma instead of the real playbook

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#11385]
### Describe the bug
RCC Landing page links to Figma instead of the real playbook

### To Reproduce
1. Go to https://foundation.mozilla.org/en/responsible-computing-challenge/
2. Click on "See the RCC playbook"
4. See that this opens a Figma file instead of the real playbook.

### Expected behavior

Navigate to the real playbook.

### Screenshots

<img width="300" alt="Screenshot 2023-11-07 at 19 37 49" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/24797493/73c1244a-639e-4a7e-9cb2-710e1f63387f">

**Comment by tbrlpld** [comment]
Just came across this. Thought I'd leave a note 😅

**Comment by mtdenton** [comment]
Thanks for the heads-up @tbrlpld!

**Comment by mtdenton** [comment]
cc @Gbaldassano, this is not a code fix.

**Comment by kristinashu** [comment]
Wow good catch Tibor, thank you! I've just updated the link in the CMS.
