### ISSUE TITLE
[Post Deploy] - Add "Thank you" message instead of redirecting to form assembly

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11391]
# Description
At the moment, a successful submission of the FormAssembly donate help form will redirect the user to a FormAssembly hosted page, that shows a unstyled "thank you" message.

<img width="1919" alt="Screenshot 2023-11-13 at 5 28 48 PM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/18314510/72cdae3b-ffbc-4c84-9910-523837492a14">

We can make the user experience better by instead rendering the thank you message on the donate help page, once the user successfully submits their inquiry.

Something similar has already been achieved for FormAssembly petition submissions in PR #10617

# Dev Tasks
Using that PR for reference, we can implement a thank you screen on the donate help page by doing the following :
- Have the FormAssembly form redirect to `foundation.mozilla.org/donate/help/?thank_you=true`
- Have the DonateHelpPage check if the URL param `?thank_you=true` is present.
  - If present, render the thank you message (to be styled)
  - If not present, render the form assembly form
 

# Acceptance Criteria

- [ ] As a user, if I successfully submit the form found on the DonateHelpPage, I am redirected to the donate help page, this time rendering a "Thank you" message where the form used to be.

**Comment by danielfmiranda** [comment]
Hi @kristinashu!

I was wondering if the design team could please help me out by mocking up a "thank you" message that will render once a user submits the donate help form?

I am thinking that the best place to render it would probably be here:

![Screenshot 2023-11-13 at 17-31-04 Donate Help](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/18314510/0c65ab50-1d3f-4301-abab-8537dfe22dbf)


Please let me know if you need anything from my end! For example, should I reach out to stakeholders for copy?

Thanks in advance!

**Comment by kristinashu** [comment]
Hi @danielfmiranda, here's a quick mockup. Yes, please confirm the copy with the stakeholder. I don't think the "We'll be back shortly." is needed since it already says "we will be in touch shortly."

H4 `Thank you for contacting us.`
Body large `A case has been created for your issue and we will be in touch shortly. `
 
<img width="1108" alt="Screenshot 2023-11-14 at 7 56 01 AM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/74ccf159-2176-4271-8edd-df0a8a34b835">

**Comment by danielfmiranda** [comment]
Confirming that the copy above has been approved by stakeholders @miaatmozilla 👍

**Comment by danielfmiranda** [comment]
This has made it to prod and I have updated stakeholders. Closing!
