### ISSUE TITLE
[Post MVP] - Update banner backend implementation

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11392]
# Description
![Screenshot 2023-11-13 at 18-40-13 Donate Help](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/18314510/3b7982ce-c0dc-4cac-87cc-b1f0fbdf4fe7)

After some discussion with Miaatmozilla and @TheoChevalier, we found that while the current implementation of the DonateHelpPage's notice works, it also includes the following drawbacks:

* If users chooses to remove the DonateHelpPage's notice block, there is no record or revision history of what was set for the notice blocks text and image.
* Even if users created a new notice block with same data as the previously used one, the new notice block would have to go through the localization process again.

To resolve this, its been suggested to instead create a new wagtail snippet with the same fields as NoticeBlock. The user should then be able to select a notice snippet, when updating the donate help pages `notice` field. 

A good PR that we can use for reference regarding creating a new wagtail snippet would be https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11280

# Dev Tasks
(tbd)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-201)

**Comment by Gbaldassano** [comment]
If this were to go out, we would need to re-translate what is currently there - better to merge after EOY time period (early Jan 2024) to be safe.

**Comment by mtdenton** [comment]
There's an alternate way to see histories through page revisions, we should reevaluate taking this on @Gbaldassano, can give more details soon.

**Comment by simont-cr** [comment]
@danielfmiranda We already missed the deadline that @Gbaldassano had already mentioned previously, but do you think this is still something we can focus on this year?

**Comment by danielfmiranda** [comment]
Hi @simont-cr yes I would say we should focus on this this year. I am going to add the P2 label.
