### ISSUE TITLE
Add error handling to newsletter signup forms

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11406]
All of our existing newsletter signup forms **don't** have error handling set up for any server errors related to form submission (e.g., the server or Basket went down in the middle of the POST call etc). Currently the form doesn't change or show any user feedback when errors are encountered. 

# Current Form State

Form logic can be found in [`join.jsx`](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/source/js/components/join/join.jsx). 

I also wonder why we are only taking [http status `201`](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/source/js/components/join/join.jsx#L175-L177) and not all of the `2xx` as the "ok" response. (More on this [Slack thread](https://mozilla.slack.com/archives/C043Q45BBMF/p1699648412480669))

## Default State

<img width="1181" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/fae30a30-4843-41e3-adaa-b2f9bc36cffa">

<img width="1165" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/dd44ac7c-1a46-4863-9217-82ec0f788c65">

## Form Validation Errors

<img width="1162" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/0aa2d540-b66f-4f8b-91cb-fbff3894b44e">

## Form Submission Successfully Went Through

<img width="1163" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/f0254f55-0431-4132-90cd-5876d2b37fe3">

## Form Submission Did Not Go Through Due To Server/API Error

(Form stays the same. No feedback to users to indicate errors have occurred in our end.)
<img width="1187" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/24485751-f985-4aab-98fd-3833bd4aab05">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-203)

**Comment by robdivincenzo** [comment]
The error messaged mocked up. Design gave the thumbs up via Slack.
![Screenshot 2024-03-04 at 4 13 04 PM](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/3083419/9ef7ad92-b9d6-460d-82e2-f59a56393b12)
