### ISSUE TITLE
PNI "Holiday guide 2023" category is not translated in the menu

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#11426]
Hi,

I’ve translated the new PNI category in French, and the translation doesn’t show up everywhere, for instance on the homepage https://foundation.mozilla.org/fr/privacynotincluded/

But it does show up localized on a product page, though: https://foundation.mozilla.org/fr/privacynotincluded/sonos-sl-speakers/

<img width="530" alt="Capture d’écran 2023-11-15 à 10 22 18" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1294206/752d1b83-731f-49a9-ad02-07cd3a8f2981">

**Comment by jhonatan-lopes** [comment]
Hey @TheoChevalier, from what I can see locally and on prod, this seems to be working now. Could you please confirm if this bug is still showing up for you?
