### ISSUE TITLE
PNI Category OG images aren't showing up

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#11432]
PNI categories allow you to add a specific share image however these are no longer working.

Screen cap showing preview image for "Wearables" category:
![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/745c5365-a8f0-4d20-8895-00e6b8e7ddb9)

Screen cap showing that a unique image was added:
![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/1e6d4d27-c54a-40c1-9b56-807f5189ba81)

Expected behaviour:
- [ ] If no category image is set then the category shows the main PNI share image
- [ ] If a category image is set then the category page shows the unique category share image

Not that is not a critical bug.

**Comment by mmmavis** [comment]
Hi @kristinashu I wonder if this could be a cache thing? I visited [PNI Wearable page](https://foundation.mozilla.org/en/privacynotincluded/categories/wearables/) and viewed the source code. I can confirm that it is showing the right OG image now.

> `<meta property="og:image" content="https://assets.mofoprod.net/network/images/Wearables.original.png">`

**Comment by mmmavis** [comment]
It could also be a browser extension issue. Do you remember how you got to the PNI Wearable page? If it's from clicking the category link then depending on how the extension is implemented, it might not be able to pick up the OG image when you switched to the category view.

**Comment by kristinashu** [comment]
Thank you for looking into this @mmmavis! You're right, if I navigate to Wearables from the homepage than the extension shows the homepage image but if I go directly to Wearables then I see the wearables image.
