### ISSUE TITLE
[PNI] Remove `get_categories_for_locale` helper function

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11454]
Categories on PNI are currently being localized using the `get_categories_for_locale` utility function. This util is not performant and should be replaced by `localize_categories` on the same module.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-205)

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

Looks like this has already been done! Yay!
