### ISSUE TITLE
[Analytics] Remove GA related code from codebase if we no longer use GA

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11463]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-212)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Tyler Denton Do you know if with the recent GA changes, this might have already been completed or resolved in a different way? Or is still pending and good for us to keep?

**Comment by data-sync-user** [comment]
➤ Tyler Denton commented:

We can keep this as a follow-up for findings in  https://mozilla-hub.atlassian.net/browse/TP1-34 ( https://mozilla-hub.atlassian.net/browse/TP1-34|smart-link ) or create a new ticket altogether, your choice Simon Acosta Torres

**Comment by data-sync-user** [comment]
➤ diego commented:

Simon Acosta Torres I believe this is a duplicated ticket as GA related code was removed before with GTM migration.
