### ISSUE TITLE
[Main Navigation Drop Down] All MoFo Staff Internal Survey | Shareout & Follow Up

### ISSUE THREAD

**Issue by tessheinricks** [MozillaFoundation/foundation.mozilla.org#11474]
Share out of all MoFo Staff Internal Survey & follow up communication

- [x] Share out Survey (December 1st)
- [x] Follow up

**Comment by sabrinang** [comment]
**Share out**
- [survey](https://forms.gle/F3rGzt1VttXKNMvD7) [shareout](https://mozilla.slack.com/archives/G4TED39AS/p1701453550092189) to mofo internal staff shared in _mofo-staff_ slack on Dec 1 

**Follow ups**
 - [reminder](https://mozilla.slack.com/archives/G4TED39AS/p1702390939204469) sent on _mofo-staff_ slack on Dec 12
 - [reminder](https://miro.com/app/board/uXjVNDiDd-w=/?share_link_id=917818086045) in working group updates on miro board on Dec 12
 - [reminder](https://mozilla.slack.com/archives/C062ECCSQTC/p1702590789334369) in _mofo-web-working-group_ slack as follow up to workshop on Dec 14
 - [reminder](https://mozilla.slack.com/archives/C98GW3P7X/p1702590888696929) in _mofo-websites_ slack on Dec 14

_future reference: message drafts are in [notes doc](https://docs.google.com/document/d/1C9Yj5vHHrhz-2tEilQp_u8NyWPHANpQqjcY6_O2HinU/edit#bookmark=id.7oe1d6qz1eht)_
