### ISSUE TITLE
 [Main Navigation Drop Down] Working Group Workshop

### ISSUE THREAD

**Issue by tessheinricks** [MozillaFoundation/foundation.mozilla.org#11475]
Design & preparation for the Working Group Workshop of the main navigation drop down project taking place on December 13th, 2023

Collaborative Space
Agenda

**Comment by sabrinang** [comment]
- the workshop collborative space and agenda is in miro: https://miro.com/app/board/uXjVNDiDd-w=/
- additional meeting notes are in the [working group call agenda doc](https://docs.google.com/document/d/1Fmq6hASEZTyv-RyMxLCj9r7zIt2KkHXQwId64nk5CU8/edit#bookmark=id.30xn90ds3hr6)
- also debriefed afterwards and refined [working group workshop board](https://miro.com/app/board/uXjVNDiDd-w=/?moveToWidget=3458764573252241329&cot=14)

note: dev/seo convo prep to be done as well

**Comment by sabrinang** [comment]
closing this issue as dev/seo prep is tracked in this ticket #11573
