### ISSUE TITLE
[Main Navigation Drop Down] All MoFo Staff Internal Survey Synthesis

### ISSUE THREAD

**Issue by tessheinricks** [MozillaFoundation/foundation.mozilla.org#11473]
Synthesis of survey results

[Survey Link](https://docs.google.com/forms/d/1l_BcbXOcbmKgsF9P-mtPfP2cUtbOAytqDwcMRw-u9Fg/edit#responses)

**Comment by tessheinricks** [comment]
Synthesis has begun within [Figma](https://www.figma.com/file/BVh6wTOMI8WIVV3XOUQhwo/Main-Navigation-Drop-Down?type=design&node-id=1380%3A1355&mode=design&t=OqHQlaHsKx7ClPDi-1)

Insights will be captured within slides, and the results will inform the MVP design structure which can be previewed within [Miro](https://miro.com/app/board/uXjVNDiDd-w=/?share_link_id=122080771214), and initial wireframes can be viewed within [figma](https://www.figma.com/file/BVh6wTOMI8WIVV3XOUQhwo/Main-Navigation-Drop-Down?type=design&node-id=475%3A295&mode=design&t=OqHQlaHsKx7ClPDi-1). 

Sabrina and I have also booked time to meet with Paul on Wednesday, December 20th to further discuss synthesis and insights.

**Comment by tessheinricks** [comment]
**Winter Shutdown Update**

The team met with Paul to discuss how to best synthesize and communicate the research findings. 

- The synthesis work is being conducted within [figma](https://www.figma.com/file/BVh6wTOMI8WIVV3XOUQhwo/Main-Navigation-Drop-Down?type=design&node-id=1380%3A1355&mode=design&t=OqHQlaHsKx7ClPDi-1) using a card sorting method. Focusing on identifying patterns of pain points, user behaviors, and feature requests
- The insights are being captured within a [slide deck format](https://www.figma.com/file/BVh6wTOMI8WIVV3XOUQhwo/Main-Navigation-Drop-Down?type=design&node-id=1491%3A3124&mode=design&t=OqHQlaHsKx7ClPDi-1) which will continue to be developed in the new year in order to share back insights with stakeholders. Post winter shutdown this deck will be expanded in order to improve digestibility and further discussion/engagement  
- The findings from this process will inform the [wireframe](https://www.figma.com/file/BVh6wTOMI8WIVV3XOUQhwo/Main-Navigation-Drop-Down?type=design&node-id=475%3A295&mode=design&t=OqHQlaHsKx7ClPDi-1) and design process

**Comment by nancyt1** [comment]
I tried to group all the stickies and label them in a way that makes sense to me, which was organizing them around common complaints or common suggestions. Feel free to rename groups or move things around!

**Comment by tessheinricks** [comment]
Synthesis has been completed and formed into a [deck](https://www.figma.com/proto/BVh6wTOMI8WIVV3XOUQhwo/Main-Navigation-Drop-Down?page-id=1491%3A3124&type=design&node-id=1491-3263&viewport=556%2C380%2C0.02&t=A1kpOit7LoVkDnz0-1&scaling=scale-down&starting-point-node-id=1491%3A3263&mode=design) for sharing out with stakeholders.

**Comment by kristinashu** [comment]
Slide are looking amazing! Going to keep this ticket for this sprint since there has been some continued work on it.
