### ISSUE TITLE
[Main Navigation Drop Down] All MoFo Staff Internal Survey Creation

### ISSUE THREAD

**Issue by tessheinricks** [MozillaFoundation/foundation.mozilla.org#11472]
- [x] Revise the Internal Staff Survey
- [x] Meet with Paul

**Comment by sabrinang** [comment]
- draft work in progress for the survey in google forms [here](https://docs.google.com/forms/d/1l_BcbXOcbmKgsF9P-mtPfP2cUtbOAytqDwcMRw-u9Fg/edit)
- also in google docs [here](https://docs.google.com/document/d/1TZHlwsnQpt0Mbhkbo_VJe3dR6m7R9iWXWyEW4cloZbw/edit?usp=sharing) _(if we need it to collect comments)_
- updated screenshots in [figma](https://www.figma.com/file/BVh6wTOMI8WIVV3XOUQhwo/Main-Navigation-Drop-Down?type=design&node-id=1093-480&mode=design)
