### ISSUE TITLE
Create Donate "ways to give" page factory and add it to percy tests

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11497]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-216)

**Comment by simont-cr** [comment]
@danielfmiranda Please take a look and let us know if we should clean or continue working on this ticket. Thanks!

**Comment by danielfmiranda** [comment]
Hi @simont-cr confirming that we should continue to work on this ticket. Going to add it with a P1 since it has to do with donations

**Comment by danielfmiranda** [comment]
Closed via https://github.com/MozillaFoundation/foundation.mozilla.org/pull/12297!
