### ISSUE TITLE
Mozfest homepage & landing page - Add automated test

### ISSUE THREAD

**Issue by cdanfon** [MozillaFoundation/foundation.mozilla.org#11511]
This ticket covers adding automated tests to the updated homepage and new landing page for Mozfest.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-219)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

As we have already deployed Mozfest websites since this ticket was created, I will go ahead and close, till we find an use case on having to restore it.
