### ISSUE TITLE
Redirect CSV Upload returns Server 500 error

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#11559]
### Describe the bug
from @kristinashu:

> Hi, are [@Jhonatan](https://mozilla.slack.com/team/U04FC9TDRCN) or [@tbrlpld](https://mozilla.slack.com/team/U01ESFBJ7LH) around today? I need to do a bunch of redirects but am getting a Server 500 error when I import the csv file. Any chance one of you could please take a look and see what the problem is? I'm in this ticket https://github.com/MozillaFoundation/foundation.mozilla.org/issues/9988#issuecomment-1858294620

Log dump from Papertrail:
```
Dec 15 18:05:04 foundation-mozilla-org app/web.5 Internal Server Error: /cms/redirects/import/process/
Dec 15 18:05:04 foundation-mozilla-org app/web.5 Traceback (most recent call last):
Dec 15 18:05:04 foundation-mozilla-org app/web.5   File "/app/.heroku/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
Dec 15 18:05:04 foundation-mozilla-org app/web.5     response = get_response(request)
Dec 15 18:05:04 foundation-mozilla-org app/web.5   File "/app/.heroku/python/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
Dec 15 18:05:04 foundation-mozilla-org app/web.5     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Dec 15 18:05:04 foundation-mozilla-org app/web.5   File "/app/.heroku/python/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
Dec 15 18:05:04 foundation-mozilla-org app/web.5     return callback(request, *args, **kwargs)
Dec 15 18:05:04 foundation-mozilla-org app/web.5   File "/app/.heroku/python/lib/python3.9/contextlib.py", line 79, in inner
Dec 15 18:05:04 foundation-mozilla-org app/web.5     return func(*args, **kwds)
Dec 15 18:05:04 foundation-mozilla-org app/web.5   File "/app/.heroku/python/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
Dec 15 18:05:04 foundation-mozilla-org app/web.5     response = view_func(request, *args, **kwargs)
Dec 15 18:05:04 foundation-mozilla-org app/web.5   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/admin/urls/__init__.py", line 170, in wrapper
Dec 15 18:05:04 foundation-mozilla-org app/web.5     return view_func(request, *args, **kwargs)
Dec 15 18:05:04 foundation-mozilla-org app/web.5   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/admin/auth.py", line 184, in decorated_view
Dec 15 18:05:04 foundation-mozilla-org app/web.5     response = view_func(request, *args, **kwargs)
Dec 15 18:05:04 foundation-mozilla-org app/web.5   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/admin/auth.py", line 63, in wrapped_view_func
Dec 15 18:05:04 foundation-mozilla-org app/web.5     return view_func(request, *args, **kwargs)
Dec 15 18:05:04 foundation-mozilla-org app/web.5   File "/app/.heroku/python/lib/python3.9/site-packages/django/views/decorators/http.py", line 40, in inner
Dec 15 18:05:04 foundation-mozilla-org app/web.5     return func(request, *args, **kwargs)
Dec 15 18:05:04 foundation-mozilla-org app/web.5   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/contrib/redirects/views.py", line 304, in process_import
Dec 15 18:05:04 foundation-mozilla-org app/web.5     data = file_storage.read(input_format.get_read_mode())
Dec 15 18:05:04 foundation-mozilla-org app/web.5   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/contrib/redirects/tmp_storages.py", line 64, in read
Dec 15 18:05:04 foundation-mozilla-org app/web.5     with self.open(mode=mode) as file:
Dec 15 18:05:04 foundation-mozilla-org app/web.5   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/contrib/redirects/tmp_storages.py", line 53, in open
Dec 15 18:05:04 foundation-mozilla-org app/web.5     return open(self.get_full_path(), mode)
Dec 15 18:05:04 foundation-mozilla-org app/web.5 FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmphvt3lw0b'
```

### To Reproduce
1. Go to https://foundation.mozilla.org/cms/redirects
2. Upload a CSV using "Import redirects" on the top-right, CSV in question is [here](https://docs.google.com/spreadsheets/d/1dVBSAZAadpaokVsgLjLhcBzfNYoZW4zXvkmDqSpyFUk/edit#gid=0)

### Expected behavior
Redirects are uploaded and processed

**Comment by mmmavis** [comment]
@kristinashu could you QA this on staging to see if the issues you were experiencing on prod are now fixed? Thanks! https://foundation.mofostaging.net/cms/redirects/

**Comment by kristinashu** [comment]
@mmmavis I just tested it on staging now and it works but will need to test on prod as well since it was previously working on staging but not prod. 

Note:

There was a long thread in Slack about this https://mozilla.slack.com/archives/C04DYP6T6VD/p1702663958013809

It works on staging but not prod. Tibor said:

> It think the issue is that our hosting setup uses multiple servers/virtual machines (Heroku calls them Dynos). You first upload a file to a server and then receive this preview table that will show you what will be imported. The file is now on the server that first responded to your upload request. Once you check the table and click "confirm" the browser sends the "confirm" request to Heroku. This confirmation, though, might land on a different server, because Heroku just randomly selects one of the servers. So you might not get the server that you previously uploaded the file too (chances are something like 1:6). This means the server does not find the file - which is correct as the file is on a different server - and matches the error message in the logs. 

> I think it works on staging because we only run a single server. That means the server that handles the "confirm" also received the file and can find that file for the actual import.

> I will file and issue about this with Wagtail. This will probably affect more projects since Heroku is a fairly common hosting provider.

> Turns out Wagtail already has a setting. We just have not set it as needed. PR incoming to fix this for the future. https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11576

**Comment by mtdenton** [comment]
@mmmavis @kristinashu This fix is now on prod if we'd like to verify!

**Comment by kristinashu** [comment]
I'll test this next time I need to do a redirect. Will close this ticket for now and reopen if I have issues in the future. Ty!
