### ISSUE TITLE
Add tests for `get_content_related_by_tag` util

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#11557]
This util is central for functionality of the `BlogPage` but was not previously tested. While working on #11128 an initial test for this util was added. However, this is a fairly complex function and should be covered by more tests. Especially branch coverage seem crucial for a function with many if-statements.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-223)

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

This ticket is still valid and should be worked on.
