### ISSUE TITLE
[Main Navigation Drop Down] Techinical Discussions (Dev & SEO)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/foundation.mozilla.org#11573]
Prepare for Dev Sync meeting with developers _(Dec 19)_
- [Agenda](https://docs.google.com/document/d/1Fmq6hASEZTyv-RyMxLCj9r7zIt2KkHXQwId64nk5CU8/edit#bookmark=id.a6zpcpsphirk)

Prepare for SEO async discussion via slack
- Draft asynchronous communication for SEO
- Discuss when the next touchpoint is

**Comment by sabrinang** [comment]
- dev sync meeting complete (Dec 19)
- WIP drafting SEO async message in [notes](https://docs.google.com/document/d/1C9Yj5vHHrhz-2tEilQp_u8NyWPHANpQqjcY6_O2HinU/edit#bookmark=id.luypqtukxzre)

**Comment by tessheinricks** [comment]
Follow up meeting scheduled for Thursday, January 11th. SEO & Dev discussions will continue in the next sprint.
