### ISSUE TITLE
Refactor "2-column" version of newsletter signup form

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11584]
This is part of the refactoring work for newsletter signup form (epic #11225)

For the "2-column" version of newsletter signup form, extract the existing code from `join.jsx`, and create a similar component based on what we did for [the blog body streamfield block implementation](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/source/js/components/newsletter-signup/organisms/blog-body-signup.jsx).

For detailed audit report, see [this sheet](https://docs.google.com/spreadsheets/d/1EeWshn5N7f6eEZ8eBdMS_IEF1RtFuaXFeUrwLEX96js/edit#gid=0). Look for the "Blog Pages (callout box near footer)" column

Example: https://foundation.mozilla.org/en/blog/mozillas-responsible-computing-challenge-holds-its-first-student-unhackathon/

<img width="1146" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/ce2431df-52a6-40f0-bf27-ddb19a3bfbaf">

**Comment by danielfmiranda** [comment]
QA'd on staging. Ready for prod!

**Comment by mmmavis** [comment]
Live on prod! Closing! 🎉
