### ISSUE TITLE
Audio player controls alignment

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#11602]
While working with the audio player template I noticed the alignment of the controls seems to be slightly off.

I noticed the following:

* The elements are not using the same baseline (or are vertically centered). 
* The padding left of the play button is larger than on top and the bottom.

<img width="370" alt="Screenshot 2023-12-21 at 12 51 30 PM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/24797493/2239e4fb-c179-4c30-adfe-a7f544b45bb6">

<details>
<summary>
Larger screenshot
</summary>
<img width="1208" alt="Screenshot 2023-12-21 at 12 51 12 PM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/24797493/59b6fd9a-df12-4020-b64f-443fcf75a381">
</details>

See the player live here: https://foundation.mozilla.org/en/blog/

**Comment by mmmavis** [comment]
@kristinashu Could you help QA this on staging as I'm not sure what the expected style is: https://foundation.mofostaging.net/en/blog/ Thank you!

**Comment by kristinashu** [comment]
Yes, the player looks great!

**Comment by mmmavis** [comment]
Thanks, @kristinashu !
