### ISSUE TITLE
Refactor PNI sort dropdown

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#11607]
The [PNI sort dropdown](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/templates/fragments/buyersguide/pni_sort_dropdown.html) was flagged during HTML validation checks: https://validator.w3.org/nu/?doc=https%3A%2F%2Ffoundation.mozilla.org%2Fen%2Fprivacynotincluded%2F

The flagged issue is that it uses `<li role="button">` which is not valid: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li#technical_summary

Fixing the validation issue will likely require a full refactor of the entire component. We should probably use an actual `button` for `button` functionality. The currently used list in a list seems like a strange structure and is of questionable accessibility.

If possible, we should also make this progressively enhanced by starting with a `form`, `select`, `options` and a submit button.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-159)

**Comment by mmmavis** [comment]
tagging myself to QA on staging

**Comment by mmmavis** [comment]
Looks good on staging.

**Comment by mmmavis** [comment]
Done!
