### ISSUE TITLE
Refactor `generic_card` to be more generic

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#11600]
When creating new cards, it would be helpful to have a truly generic card template which can be reused in many ways. 

Currently, the "generic card" only works for internal links because it always requires a page to be passed. 

To make this more generic, we should enable the option to directly pass a URL as well and only use the page URL when not URL was passed. 

Similarly, the image should be possible to be passed and also only fall back to the page meta image if nothing else was provided. 

Also, the title should be passable. Basically everything that currently is pulled from the page should be possible to pass directly and only fallback to using the pages info. Passing a page should also be optional.

Something like this could achieve the above:
```django+html
{% load wagtailcore_tags wagtailimages_tags %}
{% if page %}
    {% if not url %}
        {% pageurl page as url %}
    {% endif %}
{% endif %}
{% with title=title|default:page.localized.title image=image|default:page.localized.specific.get_meta_image %}
<div
    class="
           tw-flex
           tw-flex-col
           tw-gap-6
           tw-w-full
           {% if horizontal %}
               medium:tw-flex-row
               medium:tw-gap-16
           {% endif %}
          "
>
    <div
        {% if horizontal %}
            class="medium:tw-max-w-xs large:tw-max-w-sm medium:tw-shrink-0"
        {% endif %}
    >
        <a href="{{ url }}">
            {% image image fill-1200x628 %}
        </a>
    </div>

    <div>
        <div class="tw-flex tw-flex-wrap">
            {% block tags %}{% endblock %}
            {% block published_date %}{% endblock %}
        </div>

        <a href="{{ url }}" class="tw-group tw-block hover:tw-no-underline">
            <p class="tw-h4-heading d-inline-block mt-1 mb-2 group-hover:tw-underline">{{ title }}</p>
            <div class="tw-body-small my-0">
                {% block description %}{% endblock %}
            </div>
        </a>
        {% block byline %}{% endblock %}
    </div>
</div>
{% endwith %}
```

This idea came up in: https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11585#discussion_r1434385666

**Comment by mmmavis** [comment]
@danielfmiranda do you mind QAing this on staging since you have more context?

**Comment by danielfmiranda** [comment]
No problem @mmmavis! I have just taken a look and can confirm everything is looking as expected 👍

**Comment by mmmavis** [comment]
Thanks @danielfmiranda @tbrlpld !
