### ISSUE TITLE
Upgrade `foundation-mozilla-org` Django to 4.2

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#11640]

**Comment by jhonatan-lopes** [comment]
`wagtail-footnotes` is using a fork of the main repo that hasn't been updated in a while (https://github.com/MozillaFoundation/wagtail-footnotes). This one does not allow Django > 3.2.

I'll port the changes in the fork upstream and get rid of the fork.
