### ISSUE TITLE
Refactor primary nav version of newsletter signup form

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11655]
This is part of the refactoring work for newsletter signup form (epic #11225)

For the primary nav version of newsletter signup form, extract the existing code from `join.jsx`, and create a similar component (or re-use one) based on what we did for [the blog body streamfield block implementation](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/source/js/components/newsletter-signup/organisms/blog-body-signup.jsx).

For detailed audit report, see [this sheet](https://docs.google.com/spreadsheets/d/1EeWshn5N7f6eEZ8eBdMS_IEF1RtFuaXFeUrwLEX96js/edit#gid=0). Look for the "Primary Nav" column

Example: https://foundation.mozilla.org/en/

<img width="1429" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/05775e15-e38f-4355-abfc-fec613185d23">

**Comment by danielfmiranda** [comment]
Just QA'd on staging. Ready for prod 👍

**Comment by mmmavis** [comment]
Live on prod! Closing! 🎉
