### ISSUE TITLE
[Main Navigation Drop Down] Create Prototypes

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#11675]
Create robust prototype to be used for user testing

**Comment by tessheinricks** [comment]
The team held an initial design shareout with the Web Working Group Stakeholders on January 18th using the [desktop](https://www.figma.com/proto/BVh6wTOMI8WIVV3XOUQhwo/Main-Navigation-Drop-Down?page-id=475%3A295&type=design&node-id=2245-22964&viewport=274%2C-957%2C0.03&t=KE7VphirJsSjVEGD-1&scaling=scale-down&starting-point-node-id=2245%3A22964&mode=design) and [mobile](https://www.figma.com/proto/BVh6wTOMI8WIVV3XOUQhwo/Main-Navigation-Drop-Down?page-id=2111%3A15901&type=design&node-id=2111-16777&viewport=858%2C475%2C0.13&t=M06tUdpBfBD34sob-1&scaling=scale-down&starting-point-node-id=2111%3A17530&mode=design) prototypes found within this [deck](https://www.figma.com/proto/BVh6wTOMI8WIVV3XOUQhwo/Main-Navigation-Drop-Down?page-id=2034%3A22284&type=design&node-id=2034-23015&viewport=1044%2C469%2C0.02&t=XL9WHa8r2UGVWJiS-1&scaling=scale-down&starting-point-node-id=2034%3A23015&mode=design)
