### ISSUE TITLE
Refactor "CTA Signup Snippet" version of newsletter signup form

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11670]
This is part of the refactoring work for newsletter signup form (epic #11225)

For the "CTA Signup Snippet" version of newsletter signup form, extract the existing code from `join.jsx`, and create a similar component (or re-use one) based on what we did for [the blog body streamfield block implementation](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/source/js/components/newsletter-signup/organisms/blog-body-signup.jsx).

For detailed audit report, see [this sheet](https://docs.google.com/spreadsheets/d/1EeWshn5N7f6eEZ8eBdMS_IEF1RtFuaXFeUrwLEX96js/edit#gid=0). Look for the "CTA Signup Snippet" column

**Comment by danielfmiranda** [comment]
Confirming this is working as expected :+1: moving to ready for prod!

**Comment by mmmavis** [comment]
Live on prod 🎉
