### ISSUE TITLE
Touchpoint with Adria

### ISSUE THREAD

**Issue by tessheinricks** [MozillaFoundation/foundation.mozilla.org#11684]
Preparation and meeting with Adria concerning SEO and other quantitative measurements for the main navigation project

- [x] Book meeting with Adria
- [x] Prepare Agenda
- [ ] Synthesize notes & next steps

**Comment by tessheinricks** [comment]
Notes from our discussion can be found within the notes document [here](https://docs.google.com/document/d/1C9Yj5vHHrhz-2tEilQp_u8NyWPHANpQqjcY6_O2HinU/edit#bookmark=id.auknsn9r3o2f)

**Comment by sabrinang** [comment]
I know we mentioned to include draft tickets in github projects but I wasn't sure if it belonged in main nav dropdown phase so I created a placeholder here capturing possible tasks for next steps: [[Epic] Information Architecture | SEO ](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11730) https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11730
