### ISSUE TITLE
[UserTesting] Plan & set up test for MVP designs

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/foundation.mozilla.org#11687]
- Create a script and plan for testing the prototype MVP website state to collec data on UserTesting.com
- Use this data to for comparison purposes with https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11682 previous test

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-174)

**Comment by kristinashu** [comment]
Tests have been launched https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11807#issuecomment-1967938628!
