### ISSUE TITLE
Shareout Wireframes Working Group [meeting - sync]

### ISSUE THREAD

**Issue by tessheinricks** [MozillaFoundation/foundation.mozilla.org#11686]
Shareout Wireframe Designs with the working group

- [x] Book meeting (within the week of January 15th to 18th) - Genevieve will assist
- [x] Hold meeting

**Comment by sabrinang** [comment]
The meeting was held today and designs were shareout with the working group. 

- [Working group agenda notes ](https://docs.google.com/document/d/1Fmq6hASEZTyv-RyMxLCj9r7zIt2KkHXQwId64nk5CU8/edit#bookmark=id.dhfineijvde3)
- [Meeting recording](https://mozilla.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=0259961b-3c22-428d-899b-b0fb01470e70)
