### ISSUE TITLE
Upgrade 'foundation-mozilla-org' Postgres 15

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#11691]
Heroku apps are running postgres 13 which will be EOL on Q3 2024 (on Heroku at least). Bump it to latest version available, which is v 15.

**Comment by jhonatan-lopes** [comment]
This PR bumps the images for local development, CI and Review Apps for the 15 version: https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11764

Once that is QA'd, a time must be scheduled to manually upgrade the DB instances on Heroku.
