### ISSUE TITLE
Implement Donate Help Form submission test

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11699]
Now that we have some integration tests in place for the Donate Help Page form via #11658, we should implement one more test that actually submits the form assembly form.

However, we do not want to flood form assembly with a bunch of dummy submissions, so we need to work with the donor care team in order to figure out how we can implement this without impeding on their reports.

For example, one suggestion is to agree on a "test email" with the donor care team so they can filter it out when running reports.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-230)

**Comment by simont-cr** [comment]
@danielfmiranda Should this be a P1 or P2 issue, based on your own estimation?

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Daniel Miranda How do you feel on keeping this task as a P2 or should we de prioritize to a P3 instead?
