### ISSUE TITLE
Shareout Final Design & Slides (async)

### ISSUE THREAD

**Issue by tessheinricks** [MozillaFoundation/foundation.mozilla.org#11692]
Final shareout of design & project deck

- [x] Create deck
- [x] Shareout

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-175)

**Comment by nancyt1** [comment]
Shareout was sent and slide deck is [here](https://www.figma.com/proto/BVh6wTOMI8WIVV3XOUQhwo/Main-Navigation-Drop-Down?page-id=3949%3A23401&type=design&node-id=3949-24904&viewport=7883%2C302%2C0.3&t=XuBtx1CrZNeHCdMB-1&scaling=contain&starting-point-node-id=3949%3A24904)!
