### ISSUE TITLE
HTML Validation Errors (Remaining Issues from 2023 EOY Branch)

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11705]
To make this ticket more digestible, I'm going to post one issue per comment below.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-231)

**Comment by mmmavis** [comment]
# PNI Product Page

Note this is a PNI site wide issue.

<img width="1865" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/a3c87528-0d1b-44d7-bfa6-1108b87e65d9">

**Comment by mmmavis** [comment]
# PNI Product Page

Note this is a PNI site wide issue.

<img width="1583" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/97beebb7-def4-4137-bd12-b08f89b614f9">

**Comment by mmmavis** [comment]
# PNI Homepage

<img width="1733" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/d95d8a63-36d0-452a-87c8-c2c3be14f2b8">

**Comment by mmmavis** [comment]
# PNI Article Page

Test page: https://foundation.mofostaging.net/en/privacynotincluded/articles/our-2023-nice-list-we-see-you-good-at-privacy-connected-products/

### Note that these issues are site-wide streamfield related, and *not* PNI specifc.

<img width="1881" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/8a64805d-04ae-43af-b431-5f7819a2a274">

**Comment by mmmavis** [comment]
@tbrlpld thanks for providing more insight. I didn't dive into the code and assumed it was coming from our streamfield implementation.

**Comment by simont-cr** [comment]
@mmmavis Should this be turned into an EPIC including all the tickets that you mentioned on here?

**Comment by mmmavis** [comment]
@simont-cr I think we can keep this as is. Some issues are already addressed in open PRs (pending reviews or deploy). The remaining work should be minimal.
