### ISSUE TITLE
[SPIKE] Investigate/Decide if we want to add more "FundraiseUp" supported languages to the foundation site

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11736]
There is a discrepency between the list of languages that are supported by FRU and supported on the Foundation site:

- English (supported on FoMo)
- Chinese
- Danish
- Dutch (supported on FoMo)
- Finnish
- French (supported on FoMo)
- German (supported on FoMo)
- Hungarian
- Italian
- Japanese
- Korean
- Norwegian
- Portuguese (supported on FoMo)
- Spanish (supported on FoMo)
- Swedish  

That means that if the user visits the donate landing page in a language that is supported by FRU but not by the foundation site, the page will render its content in English, but the donate form will render in the users preferred language.

The team and stakeholders need to decide if this functionality is OK as-is, or, if we would like to move forward with adding these other locales, considering things such as:
- if we have people who can preform the translations for the other languages above
- the negative performance implications that adding more languages may have

**Comment by danielfmiranda** [comment]
Hi @Gbaldassano @abi-mofo @mtdenton!

I was wondering if I could please get some help in deciding the best next steps for this ticket. 

At the moment, I can think of two options:

Option 1: Maintain the current list of supported languages on the foundation site. If a user visits the site with their browser's preferred language matching one from the list above, the donate modal will render in that language. However, the remaining site content will default to English (if the user's preferred language is not supported by the foundation site).

Option 2: Explore adding more FRU supported languages on the Foundation site. This would involve a bigger lift, as it would be a site-wide update. Collaboration with the localization team would be necessary, and we would have to consider that adding more supported languages on a content-heavy site such as the foundation site will have negative performance implications. The reason we were able to support so many languages on the original donate site compared to the foundation site, is because the donate site only included a handful of static templates. (tagging @TheoChevalier to see if I am missing anything!) However, if a large amount of our donations are coming from these locales, it may be worthwhile.


Thank you all in advance for the help!

**Comment by mtdenton** [comment]
I'm very heavily (like black hole heavy) leaning to Option 1. Option 2 is terribly complex and would require separate epic(s).

**Comment by danielfmiranda** [comment]
Thanks @mtdenton! I also am heavily leaning towards option 1, and agree that option 2 would be quite complex.

In that case, I am going to vote for sticking with the set up as-is, and closing this ticket as well as #10309, if there are no objections from @abi-mofo @Gbaldassano

**Comment by abi-mofo** [comment]
No objections- I totally agree on option 1!

**Comment by danielfmiranda** [comment]
Thanks Everyone! In that case, I will close this ticket and #10309.
