### ISSUE TITLE
[SPIKE] Plan out donate decommissioning

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#11757]
Here are the final steps for decommissioning the legacy donate stack:

1. Finish finalizing redirects via https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11739
2. Delete the legacy donate app on heroku
3. Update `mofo-redirector` heroku DNS settings to include donate.mozilla.org
4. In Route53 update the Hosted Zone record for redirected domain to point to the redirector heroku app.
5. Delete the legacy donate stack from Google Analytics / Google Tag manager
6. (TBD) delete repo and any related slack channels

**Comment by danielfmiranda** [comment]
Copied over these steps to #11740. Closing this spike ticket!
