### ISSUE TITLE
 [UserTesting] Plan & set up test for current state (part II)

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/foundation.mozilla.org#11758]
continuing from #11682

- [x] Translating user goals to tasks ahead of testing [here](https://www.figma.com/file/Grj496qYNpA3YtlJ98ONRg/Main-Navigation-%7C-User-Tasks-%2F-Goals?type=whiteboard&node-id=0%3A1&t=0v3qJK9WWABvE06C-1)
- [x] Review & Familiarize UserTesting tool
- [x] Set up test
- [x] Launch test

**Comment by tessheinricks** [comment]
The revised testing document can be found [here](https://docs.google.com/document/d/1DaDkG7eVh6punFGYbsjO_W7J8S7TTn-MABc8DiBewh4/edit?usp=sharing)

The UserTesting test can be found [here](?shared_via=link&share_id=eNCRID9fsZ)
