### ISSUE TITLE
Blog topic description not showing

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#11769]
Blog landing page https://foundation.mozilla.org/en/blog/ has generic intro text "Mozilla’s blog features guides to making your online life better, stories from the movement, and critical analysis of issues around internet health."
<img width="1241" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/e48baa90-3be8-4156-9edf-724d8d9c65c8">

Blog topic pages have a field to enter custom topic intro text. Example https://foundation.mozilla.org/cms/snippets/wagtailpages/blogpagetopic/edit/5/
<img width="1119" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/ae0aa8f6-d6af-40d5-8aa6-453ad988b6ad">

[Bug] However the blog topic pages are showing the generic text
<img width="1231" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/ede5725c-14ed-4250-a2d2-7619cf09ac6a">

[Expected behavior] It should show the custom topic text.

**Comment by danielfmiranda** [comment]
Hi @kristinashu! 

The fix for this ticket has been merged and is now live on staging. I was wondering if you could please give https://foundation.mofostaging.net/en/blog/topic/advocacy/ a look whenever you find a free moment, and leave a comment if everything looks as expected? 

Thank you!

**Comment by kristinashu** [comment]
Perfect, thank you Daniel!
