### ISSUE TITLE
[PNI] Product category sort order not respected in category nav

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#11770]
### Describe the bug
From @caltrider:

> This isn’t the hugest priority, but I do notice the the category sort order on the PNI nav page won’t like up with the order I’ve put the categories in. I tried to move Best Of back to the first spot and then cars and then move the holiday guide category down so it is lower/shows up in the drop down by the order I’ve put them in in the CMS doesn’t seem to be showing up for me on the website.

### To Reproduce
1. Go [here](https://foundation.mozilla.org/cms/snippets/wagtailpages/buyersguideproductcategory/) and try to edit sort order on product categories.
2. Go to any PNI page, category order does not reflect the current sort order of the Buyers Guide Product Category snippets.

### Expected behavior
Order of categories in the secondary nav on PNI pages should match the sort order of the product category snippets in the dashboard

### Screenshots
<img width="1348" alt="Screenshot 2024-01-25 at 3 21 48 PM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/41487159/d9ee2dae-0eb7-4430-905d-15be0af5fe8b">
<img width="1364" alt="Screenshot 2024-01-25 at 3 23 36 PM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/41487159/7485ba57-a09a-41df-bf03-31b2794065c8">

**Comment by danielfmiranda** [comment]
Confirming that I am able to update the PNI category nav bar on staging to match whats on production. Going to leave this screenshot of the navbar in production for reference, so we can update it accordingly when this update goes live! 



<img width="1228" alt="Screenshot 2024-02-12 at 11 37 28 AM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/18314510/7845f490-d225-48e1-a075-947f89c0ead0">
