### ISSUE TITLE
Refactor "PNI Creep Vote" version of newsletter signup form 

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11787]
(Just realized I didn't spot this version of signup form in the first place. I'm creating a ticket for it now)

---

This is part of the refactoring work for newsletter signup form (epic #11225)

For the "PNI Creep Vote" version of newsletter signup form, extract the existing code from `join.jsx`, and create a similar component (or re-use one) based on what we did for [the blog body streamfield block implementation](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/source/js/components/newsletter-signup/organisms/blog-body-signup.jsx).

For detailed audit report, see [this sheet](https://docs.google.com/spreadsheets/d/1EeWshn5N7f6eEZ8eBdMS_IEF1RtFuaXFeUrwLEX96js/edit#gid=0). Look for the **"PNI Creep Vote" column**

**Comment by mmmavis** [comment]
@mtdenton @abi-mofo This is something that didn't get caught when I did the initial audit work last year. I filed this ticket yesterday to capture the work and I'm adding this new ticket to my sprint as I'm really hoping to wrap up my newsletter refactor work hopefully by this sprint.

**Comment by danielfmiranda** [comment]
Just tested and confirming that this is ready for prod!

**Comment by mmmavis** [comment]
Live on prod 🎉
