### ISSUE TITLE
[Mozfest] White gap between hero and dark section

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11795]
### Describe the bug
After addressing the spacing issue on Mozfest (https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11756), there is now a white gap between the hero and dark sections that shouldn't exist.

> On the home and landing pages now it leaves a gap between the hero and the black section that should be able to sit directly linked.
https://www.mozillafestival.org/en/Test-landing/

![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/61277874/b75c6a9e-5512-45e0-85e8-d48265b1e04c)

### To Reproduce
1. Go to 'https://www.mozillafestival.org/en/Test-landing/'
2. Scroll down after "Heading Heading"
3. See error

### Expected behavior
White gap should not be visible (or should be dark).

**Comment by mmmavis** [comment]
Looks like we only need to [revert these changes](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11756/files#diff-5632e11459c8dca75fd1fd48f3ce59e88e90b3815cbc90d364d886fc3227124f) to get rid of the white gap. @jhonatan-lopes do you know why the changes were introduced in that PR? I could file a PR to revert the code but would like to make sure I don't create unwanted effects with that.

**Comment by jhonatan-lopes** [comment]
Hey @mmmavis, thanks for taking a look at this! It seems that the margin/padding between the blocks was not adequate as it can be seen on [this visual regression test](https://percy.io/Mozilla-Foundation/foundation.mozilla.org/builds/32400510/changed/1778962378?browser=firefox&browser_ids=48%2C49&subcategories=approved&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280). That PR was made to increase that gap.

If this feels like a simple task for you, I would appreciate you working on it, thanks

Please let me know if you need more details

**Comment by robdivincenzo** [comment]
Hey @jhonatan-lopes and @mmmavis- just to clarify, do we want to remove only the gap between the blocks and keep the gap between the content and footer sections which existed before https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11795?

![Screenshot 2024-02-08 at 11 50 40 AM](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/3083419/39ab5869-bf13-49b1-8353-b4deab07867c)

**Comment by jhonatan-lopes** [comment]
Hey @robdivincenzo, on that example both gaps should be removed since the hero banner/image is considered to be "dark".

For additional context, here is what the original ticket fixed (see the gap between the hero and the first paragraph):
![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/61277874/f7a3c4e6-5158-45b5-8c64-ec489a8b6f58)

We want to keep that fix in but without "white gaps" (sorry if that's a bit vague). The goal is to make the transition between consecutive dark sections to be smooth, without white breaks in between.
