### ISSUE TITLE
Page character counter does not display properly on dark theme

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11809]
### Describe the bug
On dark Wagtail theme, the character counter for the page title is displayed as black on dark, so it doesn't show up properly:
![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/61277874/39473e66-fe72-4ba4-866f-7bd9661dca2d)

### To Reproduce
1. Go to the CMS and login
2. Change your theme to "dark" on "account preferences"
3. Edit a page
4. Click on the page title
5. See the character counter bug

### Expected behavior
Character counter is visible on both light and dark themes

**Comment by jhonatan-lopes** [comment]
Hey @mmmavis, I think this character counter is actually a custom work from this repo so that's why it's not formatted properly. We can fix it with CSS on our end. Maybe a good ticket for Rob?

**Comment by danielfmiranda** [comment]
QA'd on staging. Moving to ready for prod!
