### ISSUE TITLE
[UserTesting] Run test for MVP designs

### ISSUE THREAD

**Issue by tessheinricks** [MozillaFoundation/foundation.mozilla.org#11807]
- [x] Launch test
- [ ] Synthesize findings

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-191)

**Comment by nancyt1** [comment]
Tests have been launched!

**Comment by kristinashu** [comment]
Tess has already summarize the [initial findings](https://docs.google.com/document/d/1c-toVus_Ypz-zBAQISi4bAi6nYrhfBG2m8kUOkLZ0tI/edit?usp=sharing). I'm going to close this ticket and opened https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11965 to turn this into a share out.
