### ISSUE TITLE
[Main Navigation Drop Down] Systemize designs and Figma file cleanup

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#11808]
- [x] Make sure all new styles are documented in library file and as tokens
- [x] Make sure all elements use tokens
- [x] Clean up components page
- [x] Move necessary components to design system file
- [x] (Optional) Add any necessary documentation to figma file
- [x] Publish new components
- [x] Delete extra pages/components

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-192)

**Comment by sabrinang** [comment]
Design System — progress updates

**[[WIP] Styles Library](https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/%5BWIP%5D-Styles-Library?type=design&node-id=0%3A1&mode=design&t=ejxVG0DVVFZLxbJR-1)**
- **Colors:** Added Gray 02 & Blue 03
    - Interpolated colors (used https://palettte.app/) to determine closes tint/shade for the system and named them accordingly
    - Added tokens via token studio, pushed changes, added documentation
    - Published library and used styles in nav file and removed local styles to use published styles instead
    - Influence on system: other colors do not have tints below 05
    - DS debt for future: add other lighter tints? Fix Shannon’s orange colors (not tokens, interpolate, a11y)

**[[WIP] Component Library](https://www.figma.com/file/sOxNGYMzwZT0B9Fal2D4WT/%5BWIP%5D-Component-Library?type=design&node-id=601%3A5415&mode=design&t=gNLsMHdvSgSNlEAe-1)** 
- **Dividers:** new divider variants
    - added “orientation” property to enable both Horizontal and Vertical styles to be present
    - Add “tertiary” to type property
    - Added component variants and added documentation
    - Published library and used components in nav file and removed local styles to use published styles instead
    - Influence on system: added additional divider options than needed as there are missing combinations
- **Iconography:** add 18px icons
    - Added arrow up right, arrow right & featured icons
    - Added variant states for arrows
    - Published library and used components in nav file and removed local styles to use published styles instead
    - DS debt for future: come up with naming conventions as I don’t think size is as intuitive, iconography in general hasn’t been worked on

**Comment by sabrinang** [comment]
Design System — progress updates

### **[[WIP] Component Library](https://www.figma.com/file/sOxNGYMzwZT0B9Fal2D4WT/%5BWIP%5D-Component-Library?type=design&node-id=0-1&mode=design)** 
- **.Dropdown Navigation Primary Link** to replace **.Primary Nav Link (to be Archived)**
   - uses 18px token (17px previous) 
   - included missing Donate active state
   - uses linkPrimary text style defined in [WIP] style library
- **.Dropdown Navigation Link Item**
   - uses defined text and colors from [WIP] style library
- **.base-placeholderSlot** for **Dropdown Navigation Column Slot**
   - uses defined text and colors from [WIP] style library and library components
- **.DropdownContainer**
   - mobile, tablet and desktop consolidated here
- **.DropdownElements**
   - contain default and opened elements separately for appropriate prototype animations (tablet/mobile)
   - desktop uses "default" page state as all the pages are grouped together for appropriate animation
   - These elements contain the String Variables so updating those will be reflected on these components
- **Primary Navigation**
   - This is the component that will be used assembled from other base/slot components

‼️**Note on Names:** Overall renamed "secondary" to "dropdown" as we already have a secondary nav however we also have "mobile nav dropdown" for how secondary nav appears on mobile so we should reconsider our names in the future with existing components

### **Other existing components updated/impacted:**
- **Buttons**
   - changed border align inside (improve alignment)
   - removed text property to enable ability to use string variables

- **Links**
   - updated right arrow to match feather icons and default text to 'Read more'
   - removed text property to enable ability to use string variables
   - moved any "Links" navigation used to live on the "Navigation" page instead for organization
   - DS debt for future consideration: if links should live in components or in styles library as typography 

- **Icons**
   - cleaned up color to use defined tokens
  
###  **Content**
- new **String Variables** for content alignment and easier updating
- text across mobile, tablet and desktop assigned string variables so when we make future updates we update the variable and it will update across all three where it is referenced
- if the column and link positions change, new strings can be added
- Naming suggestions? Any suggestions appreciated as I'm learning to use them so far I am using `p#c#l#` and `d` or `t` suffixes shorthand for primarynavlink (p), column (c), link (l), description (d), topic (t)
<img width="1366" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2492510/1bba92dd-04b0-40b9-84eb-8456bce6b540">
<img width="879" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2492510/a54a8b62-7855-4847-9564-949946821f4a">

###  **Documentation**
   - updated documentation to include new components and describe dropdown
   - removed zen mode documentation into archive

###  **Archive**
   - set aside some old documentation and components to be archived when all published and we resolve zen navigation mode in future sprint

**Comment by nancyt1** [comment]
All updates and documentation were reviewed and look really good! I would like to do more exploration on the active state so a new ticket will be made for that work.
