### ISSUE TITLE
Related Products not updating in preview mode

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11835]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-93)

**Comment by simont-cr** [comment]
@danielfmiranda Can you add some more details on the current status of this ticket?

**Comment by danielfmiranda** [comment]
Hi Everyone! It looks like the fix for this ticket was actually merged into the repo via: https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11799

Closing as complete!
