### ISSUE TITLE
[Main Navigation] Create Dev PRD

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11834]
- Design Brief Doc: https://docs.google.com/document/d/1X7LCoOv5KtYRmmp0-SRjFRgHG7LWxt_nlskz8tQwZz8/edit#heading=h.e1hdva6khlbd
- More notes about what to put on the "Dev PRD": [Design-Dev Alignment Meeting Notes](https://docs.google.com/document/d/1GGfXpHIh0PLrIeO4QOYxMg0o0O6AJ1P47vCBAI1Id-g/edit#bookmark=id.9bmpvzeivg1o)

From discussion during the Design-Dev Alignment call, our preference is to extend the existing PRD doc (aka the Design Brief Doc) by adding the Dev PRD content at the end of the doc so we can keep everything all in one place. However, if there's any concern with this approach, creating a new doc can also be an option.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-198)

**Comment by jhonatan-lopes** [comment]
Done: https://docs.google.com/document/d/1UVdu7rF58cWdvNEz72HDLfipLd1D_j2VPOy8xCcgZrY/edit
