### ISSUE TITLE
Clean up hardcoded URL on RSS feed

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11830]
The [RSS feed is defining the `link` and `feed_url` URLs hardcoded to the `https://foundation.mozilla.rog/` site](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/30dff3dd8133438f93fc1ada8e59fa83a1a6a7c3/network-api/networkapi/wagtailpages/rss.py#L11-L79). This is a bad practice. We should aim to provide relative urls within the codebase:

```
class RSSFeed(Feed):
    """
    Blog page RSS feed, using the content:encoded serializer above
    """

    title = "Mozilla Foundation Blog"
    link = "https://foundation.mozilla.org/blog/"
    feed_url = "https://foundation.mozilla.org/blog/rss/"
    description = "The Mozilla Foundation Blog"
```

Using relative URLs, the [syndication framework will construct an absolute URL for the feed using the current site](https://docs.djangoproject.com/en/4.2/ref/contrib/syndication/#urls).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-94)

**Comment by danielfmiranda** [comment]
Closing this issue as the fix has made it to prod vis #12228
