### ISSUE TITLE
List of Cookies by type (essential/non essential) 

### ISSUE THREAD

**Issue by abi-mofo** [MozillaFoundation/foundation.mozilla.org#11842]
Create a list of cookies sorted by essential and non essential for upcoming banner work.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-92)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Abigayle Fidler Let’s discuss this when we have our meeting, as I feel this will be important when setting up everything on OneTrust side. 😀
