### ISSUE TITLE
Check third-party integrations with `mofo-cron`

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11846]
Related PR/Issue: #11843 

As mentioned in #11843, we should utilize `mofo-cron` to periodically check third-party integrations on the foundation site, and set up an alert if one of them fail.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-91)

**Comment by jhonatan-lopes** [comment]
An alternative would be to use something like `checkly` with `playwright`: https://www.checklyhq.com/product/synthetic-monitoring/

**Comment by simont-cr** [comment]
@jhonatan-lopes @danielfmiranda I can see that the related PR/Issue has been merged. Is there any further work to be done as part of this ticket?

**Comment by jhonatan-lopes** [comment]
This hasn't been worked on yet. The related ticket was just a discussion. We need to formalise how to proceed here.

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Daniel Miranda and Tyler Denton , how do you feel about creating a follow up ticket on this? Should we close or discuss as a team?
