### ISSUE TITLE
[MozFest] Call to action block on MozFest doesn't allow for mailto links

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/foundation.mozilla.org#11875]
### Describe the bug
I'm creating a Sponsors page on the MozFest website where the CTA is to email the team.
When adding the 'Call to action' block and adding a mail to link (eg: mailto:sponsor@mozillafestival.org) I get a validation error saying that I need to 'enter a valid URL'

### To Reproduce
1. Use the Call to action block on the MozFest website
2. Add a mail to link in the Link URL field
3. Press Save/Publish
4. See validation error

### Expected behavior
I'm able to add a mailto link as a valid URL

### Additional context
This is the page I'm trying to add this to: https://www.mozillafestival.org/cms/pages/27424/edit/

Other blocks like buttons allow me to add mailto link

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-216)

**Comment by mmmavis** [comment]
I think updating the regex [here](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/constants.py) should solve the issue. I will bring this ticket to our next ticket triage session.
