### ISSUE TITLE
Compile a list of repos MoFo engineering team has worked on

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11897]
Compile a list of repos MoFo engineering team have worked on.

Documentation can be found on this [Confluence page](https://mozilla-hub.atlassian.net/wiki/spaces/webplatforms/pages/240615565/GitHub).

- - -
I'm creating a ticket for this work so I don't forget to complete this extensive list 🕵🏻 :mag:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-81)

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

Marking this as done! I've documented most of the repos our team has worked on. The list might not be comprehensive, as tracking down all of them is challenging.

**Comment by data-sync-user** [comment]
> **Simon Acosta Torres** commented from Jira:

[~accountid:712020:df1d02fe-5a82-4cf2-9e6c-62a9af785923] to verify if there’s anything actually missing from our documentation.
