### ISSUE TITLE
Audit and update CMS orderables to accurately reflect changes in wagtail preview panel

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11919]
Recently, we have received feedback from two stakeholders regarding an inconsistency observed within our CMS. Specifically, any modifications applied to the related items of a page, such as additions, deletions, or reordering, fail to be accurately reflected in the CMS's preview panel.

Example 1:  [PNI related products aren't updating and are in wrong order #11799 ](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11799)
Example 2: [RCC Detail Page related authors not reflecting changes in the preview panel #11918](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11918)

These examples lead me to believe that this problem affects any page utilizing orderables.

To address this, we should create a utility using the fix from https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11844 for reference.

By applying this utility across all pages that implement orderables, we can ensure that changes to orderables are consistently and accurately represented in the CMS preview panel.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-70)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Both tickets that were included as children for this EPIC have been closed. Proceeding to close this EPIC as well.
