### ISSUE TITLE
Investigate mofo-techops

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11924]
The team has reviewed this [list](https://docs.google.com/document/d/17ByHIC_vo_WK7j48x3VauW5LMO_yDK6qvrCE0uQ4IL8/edit) to evaluate AWS resources for potential decommissioning or removal. In the process, we've identified `mofo-techops` requires further examination. (Marked with a yellow dot on the google doc)

The purpose of this task is to look into `mofo-techops` and confirm whether it can be approved for decommissioning.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-66)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

There are files within the bucket that have been updated as recently as April 3rd, which means actively the bucket is being used and it would be safer to keep online.
