### ISSUE TITLE
Investigate foundation-site-copy

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11926]
The team has reviewed this [list](https://docs.google.com/document/d/17ByHIC_vo_WK7j48x3VauW5LMO_yDK6qvrCE0uQ4IL8/edit) to evaluate AWS resources for potential decommissioning or removal. In the process, we've identified `foundation-site-copy` requires further examination. (Marked with a yellow dot on the google doc)

The purpose of this task is to look into `foundation-site-copy` and confirm whether it can be approved for decommissioning.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-65)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Images from 2018 from the bucket are showing an Access Denied when trying to access them through their URL. This means that whenever they might be hosted they are no longer available and this bucket is safe to remove.
