### ISSUE TITLE
Investigate mozilla-foundation-research

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11929]
The team has reviewed this [list](https://docs.google.com/document/d/17ByHIC_vo_WK7j48x3VauW5LMO_yDK6qvrCE0uQ4IL8/edit) to evaluate AWS resources for potential decommissioning or removal. In the process, we've identified `mozilla-foundation-research` requires further examination. (Marked with a yellow dot on the google doc)

The purpose of this task is to look into `mozilla-foundation-research` and confirm whether it can be approved for decommissioning.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-44)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

This bucket includes Image assets from 2016/2017. If this is part of the MoFo Research Hub page, it’s important to note that the older projects that can be viewed in the platform are from 2018. Includes two folders:

  * 2016: 8 month folders (from Jan to Oct), each with photos ranging from 8 to 32.
  * 2017: 1 month folder (Jan), including one photo.

Considering that the same project went from using more than 100 pictures across 8 months for 2016 and using one single photo for January on 2017 means that this is no longer an active project and it’s safe to remove.
