### ISSUE TITLE
Investigate csa-hpcloud-backups

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11922]
The team has reviewed this [list](https://docs.google.com/document/d/17ByHIC_vo_WK7j48x3VauW5LMO_yDK6qvrCE0uQ4IL8/edit) to evaluate AWS resources for potential decommissioning or removal. In the process, we've identified `csa-hpcloud-backups` requires further examination. (Marked with a yellow dot on the google doc)

The purpose of this task is to look into `csa-hpcloud-backups` and confirm whether it can be approved for decommissioning.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-68)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Access on the SQL file included in this bucket, which is from 2014, is denied. Due to the time the bucket has been online and just having one single file, this bucket can be removed.
