### ISSUE TITLE
[Main Navigation Dropdown] Sync on copy with stakeholders

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#11920]
- [x] Share dev prototype to stakeholders
- [ ] Get sign-off on launch copy from Audrey, Lindsey, Shing, & Michael

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-53)

**Comment by sabrinang** [comment]
- Message drafted in [notes](https://docs.google.com/document/d/1C9Yj5vHHrhz-2tEilQp_u8NyWPHANpQqjcY6_O2HinU/edit#bookmark=id.7rh4bpwlqulu)
- Shared in mofo-web-working-group slack channel
- @ Audrey, Lindsey, Shing, & Michael in thread to ensure they've seen prototype and copy
