### ISSUE TITLE
Investigate hive-blog

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11937]
The team has reviewed this [list](https://docs.google.com/document/d/17ByHIC_vo_WK7j48x3VauW5LMO_yDK6qvrCE0uQ4IL8/edit) to evaluate AWS resources for potential decommissioning or removal. In the process, we've identified multiple components linked to "hive-blog" that require further examination. (Marked with yellow dots on the google doc)

The purpose of this task is to look into hive-blog and confirm whether the related resources can be approved for decommissioning.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-36)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

This bucket includes an archive going back to 2017. There are no references to this backup either in Slack or any other platform. We can safely remove from AWS.
