### ISSUE TITLE
Investigate strongercommunities.info

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11931]
The team has reviewed this [list](https://docs.google.com/document/d/17ByHIC_vo_WK7j48x3VauW5LMO_yDK6qvrCE0uQ4IL8/edit) to evaluate AWS resources for potential decommissioning or removal. In the process, we've identified `strongercommunities.info` requires further examination. (Marked with a yellow dot on the google doc)

The purpose of this task is to look into `strongercommunities.info` and confirm whether it can be approved for decommissioning.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-62)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Because this relates to an active site that has multiple buckets that will stay online, it would be best to keep this active.
