### ISSUE TITLE
Investigate paper-storm-tiles-production

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#11930]
The team has reviewed this [list](https://docs.google.com/document/d/17ByHIC_vo_WK7j48x3VauW5LMO_yDK6qvrCE0uQ4IL8/edit) to evaluate AWS resources for potential decommissioning or removal. In the process, we've identified `paper-storm-tiles-production` requires further examination. (Marked with a yellow dot on the google doc)

The purpose of this task is to look into `paper-storm-tiles-production` and confirm whether it can be approved for decommissioning.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-43)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

The images from this bucket are not being used in the Paper Storm website ( https://www.google.com/url?q=https://paperstorm.it/&sa=D&source=docs&ust=1711033137411887&usg=AOvVaw3atMX74XRe9FC9SX5sd2MH ). I found no requests from that site to the bucket to request any of the images included. Also, the Paper Storm site while active is no longer relevant. This bucket is save to remove.
