### ISSUE TITLE
Senior Full Stack Dev Hiring Process

### ISSUE THREAD

**Issue by data-sync-user** [MozillaFoundation/foundation.mozilla.org#11948]
Epic to track steps needed to fill Senior Full Stack developer position.

Full schedule for interview process outlined [here](https://docs.google.com/document/d/18JJRGXMTa1V_rt-9xe4S_OpVYEmZNns085LnQ3Sg6ck/edit?usp=sharing)

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/TP-14)

**Comment by simont-cr** [comment]
Closing issue created per JIRA integration.
