### ISSUE TITLE
Mavis creating a Task ticket with "To Do" status

### ISSUE THREAD

**Issue by data-sync-user** [MozillaFoundation/foundation.mozilla.org#11942]
I’m the description.

Updated - Hello there

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP-5)

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

commenting

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

See if this triggers notification

**Comment by simont-cr** [comment]
Closing issue created per JIRA integration.
