### ISSUE TITLE
Daniels Test Task

### ISSUE THREAD

**Issue by data-sync-user** [MozillaFoundation/foundation.mozilla.org#11945]
【 highlighted #0747a6 】Well this is quite 【 end highlighted 】【 highlighted #ff5630 】interesting 【 end highlighted 】:slightly_smiling_face:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP-11)

**Comment by simont-cr** [comment]
Closing issue created per JIRA integration.
