### ISSUE TITLE
Test Jira for sprint management

### ISSUE THREAD

**Issue by data-sync-user** [MozillaFoundation/foundation.mozilla.org#11940]
# Summary
The goal of this epic is to start testing using Jira for sprint management. Some of the ways we may want to test Jira include:

* Making tickets
* Making sprints
* Testing GitHub integration
* Testing slack integration
* Testing comment/feedback loop

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/TP-2)

**Comment by data-sync-user** [comment]
➤ Genevieve Baldassano commented:

Kristina Shu Tyler Denton anything else we want to test?  Feel free to add it to the list!

**Comment by simont-cr** [comment]
Closing issue created per JIRA integration.
