### ISSUE TITLE
Kristina to test creating an issue in Jira

### ISSUE THREAD

**Issue by data-sync-user** [MozillaFoundation/foundation.mozilla.org#11941]
Created a tab in [https://docs.google.com/spreadsheets/d/1cOOfrPHg0QTEJb-99LOfZ6_EKtaFGknyhrJmEKiXVso/edit#gid=712060603](https://docs.google.com/spreadsheets/d/1cOOfrPHg0QTEJb-99LOfZ6_EKtaFGknyhrJmEKiXVso/edit#gid=712060603|smart-link) and will fill out

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP-4)

**Comment by data-sync-user** [comment]
➤ Kristina Shu commented:

Adding a comment!

**Comment by data-sync-user** [comment]
➤ Kristina Shu commented:

Genevieve Baldassano can you please comment on this ticket so I can test my notifications? Ty!

**Comment by data-sync-user** [comment]
➤ Genevieve Baldassano commented:

Kristina Shu testing!

**Comment by simont-cr** [comment]
Closing issue created per JIRA integration.
