### ISSUE TITLE
[Main Navigation Dropdown] Cleanup tickets and roadmap

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#11959]
Reassess existing tickets and assess what is left to do

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-245)

**Comment by kristinashu** [comment]
We reviewed and updated the [project board ](https://github.com/orgs/MozillaFoundation/projects/15/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C70917062%2C70917103%5D), closed a couple epics (other epics should close this sprint), and opened a few new tickets.
