### ISSUE TITLE
[Main Navigation Dropdown] Support Devs

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#11958]
Support devs with any question or QA requirements they need.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP-244)

**Comment by sabrinang** [comment]
- nav wrap up meeting with Mavis (Mar 12)
- dev support in slack for Jhonatan (mofo-web-platfroms-team)

**Comment by sabrinang** [comment]
continuing in #11993
