### ISSUE TITLE
[Main Navigation Drop Down] Metrics Gathering

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#11994]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-45)

**Comment by data-sync-user** [comment]
➤ Nancy Tran commented:

Added baselines to the dashboard ( https://lookerstudio.google.com/u/0/reporting/244bba04-984b-481a-a833-1e9684e4b32b/page/p_w39qtudqgd )!
