### ISSUE TITLE
[Main Navigation Drop Down] Launch

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#11992]
Pre-Launch 

* [x] @kristinashu to send project transition note in working group (no longer needed)
* [ ] Check with devs
* [ ] Let stakeholders and staff know [(see message draft in notes doc)](https://docs.google.com/document/d/1C9Yj5vHHrhz-2tEilQp_u8NyWPHANpQqjcY6_O2HinU/edit)

Launch

* [ ] Add content
* [ ] QA on prod
* [ ] Let stakeholders and staff know (let us know if you see any bugs or have feedback)
* [ ] Check metrics

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-47)

**Comment by data-sync-user** [comment]
➤ Nancy Tran commented:

Created new ticket to review metrics https://mozilla-hub.atlassian.net/browse/TP1-700 ( https://mozilla-hub.atlassian.net/browse/TP1-700|smart-link )
