### ISSUE TITLE
Cleaning up our vaults in 1Password

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11991]
Context see: https://mozilla.slack.com/archives/C04DYP6T6VD/p1709564927533369

Details TBD. I'm creating this ticket to account for the upcoming work.

/cc @abi-mofo @simont-cr

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-48)

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

Migration is done.
