### ISSUE TITLE
[Main Navigation Dropdown] Zen Mode Navigation - Discovery

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/foundation.mozilla.org#11990]
**Consider the future of Zen Mode**

* what is it's current usage? pros/cons
* how do we want to use Zen mode moving forward when main nav dropdown launches?
* if sunset, where do we need to remove/archive the feature? _(figma DS, code, CMS)_
* how/who do we need to communicate the change to? 
* any documentation that needs to be updated?
* who needs to approve the change?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-49)

**Comment by data-sync-user** [comment]
➤ Kristina Shu commented:

I’ve started a brief https://docs.google.com/document/d/11mq0-blFvpz_ZGqysD3o7loPjocOgP0StZc9VOG4VHk/edit#heading=h.e1hdva6khlbd ( https://docs.google.com/document/d/11mq0-blFvpz_ZGqysD3o7loPjocOgP0StZc9VOG4VHk/edit#heading=h.e1hdva6khlbd|smart-link )  and have shared it for devs to review. Hoping this can go into our next sprint.

**Comment by data-sync-user** [comment]
➤ Kristina Shu commented:

Nancy Tran will review and update our Figma file next sprint https://mozilla-hub.atlassian.net/browse/TP1-638?atlOrigin=eyJpIjoiOWM0ZjM3YjY5MTMwNDY2NDliZmM3MGMwNWM5YTA5ZGUiLCJwIjoiaiJ9 ( https://mozilla-hub.atlassian.net/browse/TP1-638?atlOrigin=eyJpIjoiOWM0ZjM3YjY5MTMwNDY2NDliZmM3MGMwNWM5YTA5ZGUiLCJwIjoiaiJ9|smart-link ) 

Simon Acosta Torres will get the dev planning work into next sprint.
