### ISSUE TITLE
Dropdown colour is hard to see on CMS's block inventory page

### ISSUE THREAD

**Issue by data-sync-user** [MozillaFoundation/foundation.mozilla.org#12009]
**Step to reproduce:**

1. Log into the CMS
1. From the sidebar, go to Reports → Block inventory
1. Click on the dropdown. Notice the colour of the dropdown options are too light to be visible.

!image-20240305-210852.png|width=1208,height=628!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-36)

**Comment by mmmavis** [comment]
<img width="758" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/f1b73b9e-a221-416b-9ac8-5f14908bfc7b">
