### ISSUE TITLE
Add `PageChooser` field to `CampaignIndexPage`

### ISSUE THREAD

**Issue by data-sync-user** [MozillaFoundation/foundation.mozilla.org#12042]
Currently, [https://foundation.mozilla.org/en/campaigns/](https://foundation.mozilla.org/en/campaigns/|smart-link) populates it’s template with any page that lives under /campaigns in the [CMS](https://foundation.mozilla.org/cms/pages/791/). This can lead to the page being populated with duplicates of the same campaign page, as stakeholders sometimes create similar pages with different petitions for different purposes:

!Screenshot 2024-03-13 at 4.16.29 PM.png|width=1920,height=878!

!Screenshot 2024-03-13 at 4.12.13 PM.png|width=1920,height=878!

To resolve this issue, we would like to allow stakeholders to select which campaign pages to be rendered instead. 

This can be achieved by adding a new orderable relation of CampaignPages to the CampaignIndexPage model (we can use the [BuyersGuideArticlePageRelatedArticleRelation](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/3913257bd1b1f1fc1a8c56f2729eb68e394782ff/network-api/networkapi/wagtailpages/pagemodels/buyersguide/article_page.py#L206-L226) for reference.), and then using our existing HTML templates to render the selected pages.

## Acceptance Criteria:
* [ ] As a CMS editor, I can visit the CampaignIndexPage and select CampaignPages that I would like to be featured at [http://foundation.mozilla.org/campaigns](http://foundation.mozilla.org/campaigns|smart-link) 
* [ ] As a user, I can visit [http://foundation.mozilla.org/campaigns](http://foundation.mozilla.org/campaigns|smart-link)  and see that only the selected campaign pages are being rendered.

**Comment by danielfmiranda** [comment]
Closed via https://github.com/MozillaFoundation/foundation.mozilla.org/issues/12172!

**Comment by data-sync-user** [comment]
➤ Rob DiVincenzo commented:

Looks good Daniel Miranda! I think your follow-up items: https://mozilla-hub.atlassian.net/browse/TP1-541 ( https://mozilla-hub.atlassian.net/browse/TP1-541|smart-link ) and https://mozilla-hub.atlassian.net/browse/TP1-540 ( https://mozilla-hub.atlassian.net/browse/TP1-540|smart-link ) will make a big improvement for the editor experience.

Now that I’m seeing it on staging with 4 page size. I feel like we should have an option for 6 as well to better balance cards when there’s 3 per row. Perhaps a 3rd spin-off issue?
