### ISSUE TITLE
Remove unneeded donate.mozilla.org items from AWS

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#12077]
Now that the legacy donate stack has been decommissioned and http://donate.mozilla.org is now redirecting to https://foundation.mozilla.org/donate,our next step is to eliminate any unnecessary components from AWS.

According to the devops team, there’s a few donate-related S3 buckets and SQS queues that can be cleaned up, as well as the associated CloudFront distribution.

The objective of this ticket is to carry out the removal of these items from AWS.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-14)

**Comment by simont-cr** [comment]
Hi @tomusher , this is a request based on what you had discussed previously with Daniel. Can you please take a look and let us know if you need any further details on the ticket before starting to work on this? Thank you!

FYI: @cdanfon

**Comment by tomusher** [comment]
- CloudFront distribution deleted (E3GTOFU205EIHD)
- donate-wagtail-translations bucket deleted
- donate-maintenance bucket deleted
- SQS queues deleted

There is a cleanup of other items pending as part of a larger AWS account review, so anything not caught here will likely be cleaned up then. I've updated the associated audit document with the actions taken as part of this ticket.

**Comment by data-sync-user** [comment]
➤ Daniel Miranda commented:

Simon Acosta Torres Closing this ticket per our conversation in slack 👍
