### ISSUE TITLE
Remove tw-capitalize from localized article pages

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#12072]
Hi,

I noticed Wagtail is altering translations in the navbar menu of articles pages by capitalizing it following the English capitalization rules. The example below was taken from https://foundation.mozilla.org/fr/research/library/accelerating-progress-toward-trustworthy-ai/whitepaper/
![](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1294206/60fc25e7-eb46-4b47-b265-102f4cde85fc)
This capitalization is wrong in French and in most languages outside English. The correct capitalization is the one displayed below `Accélérer le développement d’une IA digne de confiance `

We need to add a conditional so that `tw-capitalize` is only added for the English page and removed from the other locales in https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/templates/fragments/article_subnav.html#L7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-16)

**Comment by mmmavis** [comment]
@TheoChevalier thanks for catching this!
