### ISSUE TITLE
Petition snippets are not translated

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#12133]
This ticket claims the issue has been fixed https://github.com/MozillaFoundation/foundation.mozilla.org/issues/7771 but unfortunately it’s still not working.
To be more precise, we can now start a translation, but Wagtail doesn’t use the translated content.

Example with the latest campaign launching today:
<img width="1170" alt="Capture d’écran 2024-04-02 à 08 55 58" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1294206/c428e4f3-f221-4918-a6e1-da6599785907">

The translation was added here, but it’s not used: https://github.com/mozilla-l10n/fomo-content/commit/5881366788a602b9bbcbed39f80a2b838e24d23b
<img width="1074" alt="Capture d’écran 2024-04-02 à 09 02 46" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1294206/7f2dd63e-3e38-4730-8a61-4bbdd0e0e7d6">

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-355)

**Comment by jhonatan-lopes** [comment]
Hey @TheoChevalier, you're absolutely right, thanks for reaching out! I'll flag this up with the engineering team

**Comment by jhonatan-lopes** [comment]
I'm going to close this ticket in favour of reopening #7771, since that ticket holds more context

**Comment by data-sync-user** [comment]
➤ diego commented:

Hi Simon Acosta Torres reading the issue on Github I saw this ticket was previosly closed when not clear solution was found, and then reopened becuase is still pending, but asking for more context to Théo, he tell me to check the status of the new petition platform, do you know where I can get more information about it?

**Comment by data-sync-user** [comment]
➤ diego commented:

Doing some further research about this issue, I have encountered couple of blockers that may caused the solution take longer than expected. As Theo mentioned on the issue  ( https://github.com/MozillaFoundation/foundation.mozilla.org/issues/7771 )couple years ago, it seems that wagtail has conflicts with the class inheritance inside of the Snippet class. 

Reading documentation ( https://docs.wagtail.org/en/stable/topics/snippets/registering.html ) about snippets registering, we can find currently two ways, using register_snippet as decorator or as function, currently we are using the function option. 

@register_snippet
class SnippetName:
  pass

class SnippetName:
  pass
register_snippet(SnippetName)Wagtail recommends the second option for separation of concern purposes where you can inherit the snippet with SnippetViewSet that will allow to custimize the snippet while having the data model separated in another class. 

In another hand, taking a look at the docs  ( https://docs.wagtail.org/en/stable/advanced_topics/i18n.html#translatable-snippets )about the transalation of snippets, it seems that right way to apply them is creating the model directly on the snippet registration in oder to apply TranslatableMixin inside and add the locale and translation_key fields to the model.

@register_snippet
class Advert(TranslatableMixin, models.Model):
    name = models.CharField(max_length=255)This would suggest significantly change the current structure of all snippet models, so I will continue with the research and also looking forward to updates about “new petition platform” that Theo mentioned before.
