### ISSUE TITLE
Syncing translations of certain Highlight snippets doesn’t work

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#12139]
When syncing this highlight snippet I get the following screen
https://foundation.mozilla.org/cms/localize/update/1114/?next=%2Fcms%2Fsnippets%2Fhighlights%2Fhighlight%2Fresults%2F

![](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1294206/4d084f7e-7f02-46f5-af27-2c0750410ad9)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-362)

**Comment by robdivincenzo** [comment]
Hey @TheoChevalier - traced through this a bit as part of grooming.

The form provides a `next_url` variable in the submit action to return to the snippet listing i.e. `cms/snippets/highlights/highlight/` but it seems to tack on a `/results/` path to the end (resulting in the broken admin page). I noticed this `next_url` variable comes from the `next` query parameter in the URL.

So in the case provided, we can see how `/results/` is added to the end. However, you submit the form from a URL without that in the query parameter, you would go to the correct page: https://foundation.mofostaging.net/cms/localize/update/1114/?next=%2Fcms%2Fsnippets%2Fhighlights%2Fhighlight

As a follow-up, where did you get the original URL with the `/results/` query parameter? That would help me continue the trace and check for how we might fix this.

**Comment by TheoChevalier** [comment]
Hi @robdivincenzo , thanks for looking into this!

Here are the steps to reproduce:

1. In the CMS admin, click on "Archived" in the nav menu
2. Click on Highlights
3. In the search box at the top, type "WhatsApp". You should see only one result
4. Click on the 3-dot button then select "Sync translated snippets"
5. Hit the Submit button


Given the info you provided above, it looks like the search field is altering the query

**Comment by data-sync-user** [comment]
➤ Rob DiVincenzo commented:

This appears to be a known wagtail core issue. Related issues and releases linked here: https://github.com/wagtail/wagtail/issues/11177 ( https://github.com/wagtail/wagtail/issues/11177|smart-link )
