### ISSUE TITLE
Update donation links

### ISSUE THREAD

**Issue by data-sync-user** [MozillaFoundation/foundation.mozilla.org#12130]
Request by Patrick Doherty on [https://mozilla-hub.atlassian.net/browse/MOFOTP-166](https://mozilla-hub.atlassian.net/browse/MOFOTP-166|smart-link) : 

We are updating donation links on our various sites to allow for better tracking/data insights. Please update the following links:

1. On the [donor care intake form page](https://foundation.mozilla.org/en/donate/help/) update “If you need help with a donation” to have “donation” link to: [https://foundation.mozilla.org/?form=donor-care-intake](https://foundation.mozilla.org/?form=donor-care-intake|smart-link) 
1. On the [PNI page](https://foundation.mozilla.org/en/privacynotincluded/), update the donate button to link to: [https://foundation.mozilla.org/?form=privacy-not-included](https://foundation.mozilla.org/?form=privacy-not-included|smart-link) 
1. On the [MozFest page](https://www.mozillafestival.org), update the donation link in the footer to: [https://foundation.mozilla.org/?form=mozfest-footer](https://foundation.mozilla.org/?form=mozfest-footer|smart-link) 

Timeline

Having this complete by mid-April would be ideal!

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-352)

**Comment by danielfmiranda** [comment]
Closed via https://github.com/MozillaFoundation/foundation.mozilla.org/pull/12149!
