### ISSUE TITLE
[Main Nav] Keyboard navigation

### ISSUE THREAD

**Issue by data-sync-user** [MozillaFoundation/foundation.mozilla.org#12229]
Properly setup keyboard navigation on dropdowns as it currently is not tab-able (is this a word?).

Also make sure that links on desktop respond to `click` events.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-543)

**Comment by danielfmiranda** [comment]
Closed as completed via https://github.com/MozillaFoundation/foundation.mozilla.org/pull/12314!
