### ISSUE TITLE
Nav misaligned on campaign pages

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#12290]
# Description

![Screenshot 2024-04-30 at 14-20-35 Demand Privacy for All Support a U S  Data Privacy Law](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/18314510/78204713-1cec-45e2-96a1-efe95b4bfd71)

The new nav looks great, however, I am noticing a visual regression when visiting campaign pages. The links look misaligned. This happens with or without Zen Nav enabled.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-607)

**Comment by mmmavis** [comment]
This has been fixed.
