### ISSUE TITLE
Snippet internal names shouldn't be translated

### ISSUE THREAD

**Issue by data-sync-user** [MozillaFoundation/foundation.mozilla.org#12344]
Reported by Theo [here](https://mozilla.slack.com/archives/C98GW3P7X/p1715877273231709?thread_ts=1715874601.265629&cid=C98GW3P7X). 

Also the snippet internal name shouldn’t be translated: [https://pontoon.mozilla.org/fr/foundation-website-content/snippets/nav.NavMenu/1-main-menu-2024.po/?string=305782](https://pontoon.mozilla.org/fr/foundation-website-content/snippets/nav.NavMenu/1-main-menu-2024.po/?string=305782|smart-link) 
and the `relative_url` fields should probably be just `synchronized` instead of `translated` [https://pontoon.mozilla.org/fr/foundation-website-content/snippets/nav.NavMenu/1-main-menu-2024.po/?string=305806](https://pontoon.mozilla.org/fr/foundation-website-content/snippets/nav.NavMenu/1-main-menu-2024.po/?string=305806|smart-link)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-666)

**Comment by data-sync-user** [comment]
➤ Daniel Miranda commented:

Hi Everyone!

While I was able to fix the first request via https://github.com/MozillaFoundation/foundation.mozilla.org/pull/12347 ( https://github.com/MozillaFoundation/foundation.mozilla.org/pull/12347|smart-link ) , it appears that the second request (updating “relative_url” to a synchronized field) may be a bigger lift than I thought.

To give some context, we are populating the NavMenu model with instances of StructBlocks (the NavMenuItem block), and after some research I found that at the moment StructBlocks are *not* able to define translatablefields/synchronized fields (wagtail-localize issue #307 ( https://github.com/wagtail/wagtail-localize/issues/307 )).

However, there is a nearly completed wagtail-localize PR ( https://github.com/wagtail/wagtail-localize/issues/307 ) in progress with some fairly recent activity (Mar 8th 2024) which introduces a solution.

I can think of two routes to go about this, and was wondering which route the team thinks would be best.

Option 1 : We bring the PR back to the attention of the wagtail-localize team, and wait for / assist them to add it to the package. We can then update our wagtail-localize package to the latest version, and define which fields are to be synced vs translated with relative ease.

Option 2: If the translation team would like a fix ASAP, we can use the PR for reference, and add a custom logic to our codebase in order to define translatable/synchronized fields for StructBlocks. We would need to add tests for this as well, and then have to remember to update it once the fix for wagtail-localize issue #307 ( https://github.com/wagtail/wagtail-localize/issues/307 ) has been merged into their repo.

If I understand the bug correctly, this is not breaking anything, but instead an annoyance for the translation team. 

@theo, could you please let us know how urgent this fix is for the team? Your input will help us decide the best course of action.

Thanks!

**Comment by TheoChevalier** [comment]
Hi,

> If I understand the bug correctly, this is not breaking anything, but instead an annoyance for the translation team.

Correct, but note there’s a risk some translators mistakenly translate those URLs, and then it will break things. I’m doing my best monitoring this and will try to add notes in Pontoon every time we update these fields. Looking at the 4 current URLs, **I assume we won’t update/change them anytime soon**, so it will greatly reduce this risk.


So I think option 1 should be fine, with the assumption outlined above

**Comment by danielfmiranda** [comment]
Thanks @TheoChevalier! 

I've left a comment on the WIP PR to see if we can get an estimate on when the work may be done or if there is anything we can help with to move the PR forward. 

Going to mark this ticket as "blocked" for now in Jira 👍
