### ISSUE TITLE
“Article links” on Research detail pages link to English pages

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#12471]
Hi,

I’ve noticed the button on research detail pages was linking to English pages:

<img width="931" alt="Capture d’écran 2024-06-11 à 10 20 48" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1294206/dffda6d5-ffc3-4d94-aa7e-173557f839d3">

https://foundation.mozilla.org/pt-BR/research/library/accelerating-progress-toward-trustworthy-ai/

Note: For this particular paper, since it is linked in the Main Nav and translated into French, German & Spanish, I’ve manually overridden the links for those languages as an immediate fix:
<img width="1007" alt="Capture d’écran 2024-06-11 à 09 56 55" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1294206/536caad2-60f9-4d0e-aaaf-f86c866dcd74">

But you can reproduce the behavior on the Polish or Portuguese pages

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-795)

**Comment by AdalbertoMoz** [comment]
Just merged the PR #12556 that adds localization to the articles linked to another Wagtail Page. To simplify the testing process, here are a few examples of `Research Details Pages` that are linked to Wagtail Pages (feel free to switch languages, it should work for all of them):

- https://foundation.mofostaging.net/pl/research/library/accelerating-progress-toward-trustworthy-ai/
- https://foundation.mofostaging.net/de/responsible-computing-challenge-playbook/curriculum/learning-outcomes-and-assessments/
- https://foundation.mofostaging.net/fr/responsible-computing-challenge-playbook/curriculum/service-learning/
- https://foundation.mofostaging.net/es/responsible-computing-challenge-playbook/curriculum/effective-talking-points-for-different-audiences/
- https://foundation.mofostaging.net/pt-BR/responsible-computing-challenge-playbook/curriculum/managing-resistance/

Could you please confirm that is working as expected in Staging environment? @TheoChevalier
