### ISSUE TITLE
CSP contains invalid URL for img-src

### ISSUE THREAD

**Issue by janbrasna** [MozillaFoundation/foundation.mozilla.org#12558]
### Describe the bug

CSP policy header includes invalid entry (that is therefore ignored and not allowed):

### Screenshots

![Screen Shot 2024-06-28 at 13 24 33](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1784648/a0df14ae-0f0b-412e-839e-e4b8ce4cabe9)

### To Reproduce

Inspect response headers. There's `https://https://ucarecdn.com` entry.

### Expected behavior

Correct directive URL to allow `ucarecdn.com` source.

### Additional context

It is correct here in all the env files https://github.com/MozillaFoundation/foundation.mozilla.org/blob/b2928689c6946646d1ba5d3d95673b64f40b8eb2/env.default#L57
so it is probably only set elsewhere in the deployment setting/env itself.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-888)

**Comment by simont-cr** [comment]
Fix has been applied to the production environment.
