### ISSUE TITLE
[MVP MoFo Website] CSS System Planning

### ISSUE THREAD

**Issue by data-sync-user** [MozillaFoundation/foundation.mozilla.org#12924]
After years of development and a lack of proper maintenance, Our current website's CSS ecosystem has become really messy. We have

* Bootstrap v4.6 with our own MoFo Bootstrap overrides
* Custom SCSS
* Tailwind (our own config, plugins, and a bunch of one-off arbitrary classes)

We should start new for the website instead of trying to adapt to any existing code.

Some ideas to explore further

* framework (e.g, Bootstrap, Foundation) vs utility-based approach (e.g., Taiwlind, WindiCSS, etc)
* naming convention
* atomic design principles
* design system
* code splitting

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-1289)

**Comment by GuntreddyHemanth** [comment]
Hi, can you explain with some more context that you actual want to rebuild your website or CSS styles?

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

Simon Acosta Torres since this is also part of the discovery work, are there any particular questions I should address on this ticket?

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Mavis Ou For this ticket in particular, I think that we would need to focus on which framework should we use, what the guidelines on naming conventions would be, and any best practices that can be documented to take in account once we start.

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

For framework 

Utility-based frameworks like Tailwind CSS are not the kind of framework we want to adopt because they can make template files quite hard to read, and can complicate styling adjustments and debugging.

I then compared the two popular non-utility based frameworks, +Bootstrap+ ( https://getbootstrap.com/ ) and +Foundation Framework+ ( https://get.foundation/ ). 

After taking different aspects into consideration, my preference is to use Foundation Framework because it is built with semantic markup and accessibility in mind and is generally easier to customize compared to Bootstrap. With Foundation, we can have more control over components and the grid system. Foundation is more modular, which allows us to include only the components we need. 

However, one downside with Foundation is that it doesn’t provide an official design kit like Bootstrap does. We’ll need to check with the designers to see if this might be a deal breaker.

For naming methodologies

For our current website, we didn’t incorporate any naming methodology for CSS. For the new website, it would be preferred that we adopt +BEM+ ( https://getbem.com/ ) because it helps promote modularity and will increase code readability and maintainability. We should also work with the designers to ensure that our naming convention aligns with their design files and components, making the development process smoother and more consistent.

Other notes

  * We should only import the components we need from the Foundation framework to keep SCSS code in the project lightweight.
  * We should modularize our SCSS code as much as possible. This will make the code more readable and reusable, and it can improve compile time.
  * Try to organize our SCSS into partial files where appropriate (e.g., _buttons.scss or _headings.scss) because it can also improve recompile time.
  * We should continue using PostCSS + Node scripts to compile the SCSS.
  * Linting is important and should continue to be part of our workflow.
  * Look into using PurgeCSS and see if we can utilize it to remove unused CSS code.
  * Establish common naming conventions between the design files and code to ensure consistency and increase productivity for both designers and developers.
