### ISSUE TITLE
Provide full text in RSS feed

### ISSUE THREAD

**Issue by sbaack** [MozillaFoundation/foundation.mozilla.org#5232]
### Describe the feature request

Different to the RSS feed of https://blog.mozilla.org/, the blog on the Foundation's homepage (https://foundation.mozilla.org/en/blog/) only provides a preview of the blogposts, not the full text. Please provide the full text for each blogpost, just like https://blog.mozilla.org/.

### Additional context

I guess RSS readers are used by a niche, but an elite niche. Making the RSS feed full text is a small change that makes following news around the Mozilla Foundation more convenient.

### Dev Tasks

- [ ] Update [this line](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/rss.py#L67) from the page's meta description, to the page's body. We can use [this](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/7914) PR for reference.
- [ ] Verify that RSS feeds are then returning the full text of each blog post, similar to what is being returned on blog.mozilla.org

## Acceptance Criteria

- [ ] On RSS Readers, the foundation site is returning the full text for each blog post, similar to blog.mozilla.org.

**Comment by Pomax** [comment]
The RSS feed is generated automatically by Django, and already generates the full body for blog posts. https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/rss.py#L38

**Comment by sbaack** [comment]
It's been a while since I reported this and it had been fixed, but unfortunately it seems some other updated reversed that fix and now the RSS feed is not full text again

**Comment by Pomax** [comment]
I no longer work on this project, so it's probably better to file a new issue and link to this one as example of when we fixed it, rather than reopening an closed issue.

**Comment by mtdenton** [comment]
@danielfmiranda to groom here

**Comment by danielfmiranda** [comment]
It looks like this is due to an update from https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10514, where we have changed the field "description" from an HTML rendition of the page body,  to the page's meta description instead. 

The change seems simple enough as all we need to do is update this line.

**Comment by danielfmiranda** [comment]
Hi @mtdenton this has been merged into main and is ready for testing on staging! 

I was wondering if you could please help QA this by loading the foundation blog on a RSS reader and confirming that it now renders the page's body instead of meta description?

Thanks in advance!

**Comment by mtdenton** [comment]
@danielfmiranda Confirming that full blog posts now pull from staging:

![rssfeed](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/41487159/c20ba38d-0eef-4df2-91ad-15754050e2aa)
