### ISSUE TITLE
Roadmap and Prioritize Site Improvement Recommendations

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/foundation.mozilla.org#6557]
following up issue #6303 

The recommendations from the IA refresh has been labeled and categorized on a spreadsheet https://docs.google.com/spreadsheets/d/14XlcxPYT5qJFPnMUsPmDk512lMzTuLx0OJeSwGbmAQM/edit?usp=sharing

These will need be prioritized so 'complexity for implementation' and 'impact' need to be scoped. The action items can then be roadmapped to plan when/where it fits in with the rest of the foundation site work.

**Comment by sabrinang** [comment]
**Note:** I surfaced that we have language/strat comms related foundation.mozilla.org recommendations on the strategic comms working group call. Carys would like to be looped in as she would be the point person for the team to coordinate the outputs/deliverables and she can inform the broader team. This way we can also coordinate and be informed by both our timelines and expectations.

**Comment by Pomax** [comment]
@kristinashu is this still ongoing work, or does it make sense to close for now and open a new issue when a new site improvement pass is done?

**Comment by kristinashu** [comment]
I've moved the spreadsheet to our new shared drive folder so it's easier to find but will close this ticket
