### ISSUE TITLE
Create fake_data for articles, and make sure we have tests covering those

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/foundation.mozilla.org#6845]
With the additional of articlepage as child for more pages, we need to make sure we create articles pages in all the places where we now allow them, so that we can test that they perform as expected and don't break things like the old submenu generation code, index filtering, etc.

- [ ] update load_fake_data to generate as many fake article pages as we allow nestings (making sure that we set the correct parent for each generated fake article page)
- [ ] update the unit tests to include these article pages
- [ ] update the percy/visual tests to make sure we don't run into visual regression later

**Comment by kristinashu** [comment]
Closing this since it is old and Tyler added the `Purge` label.
