### ISSUE TITLE
Consider installing `django-rename-app` to FINALLY rename our django app

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/foundation.mozilla.org#6857]
The "Network API" hasn't exists for over five years, even predating the use of Mezzanine, which was in place before used Wagtail. It would be _fantastic_ if we could _finally_ do some renaming of projects/apps to actually reflect the code's true identity.

link: [django-rename-app on PyPI](https://pypi.org/project/django-rename-app)

**Comment by tbrlpld** [comment]
Nobody is working on this. Removing from active sprint.

**Comment by Pomax** [comment]
Always a shame to see this die. I still hope one day this code has nothing to do with the long-dead Learning Network API.

**Comment by tbrlpld** [comment]
We should definitely working on restructuring the repo/apps.
