### ISSUE TITLE
MoFo Design System

### ISSUE THREAD

**Issue by benhohner** [MozillaFoundation/foundation.mozilla.org#6952]

**Comment by Pomax** [comment]
@kristinashu @fessehaye is this work still ongoing or did it stall? (if the latter, is it work we're still looking to complete?)

**Comment by kristinashu** [comment]
Design-wise this is still happening and @sabrinang is doing a big push on it right now.

**Comment by mtdenton** [comment]
Not sure if this issue needs to be open since it doesn't relate to the repo in any meaningful way and has no information present. Marking for purge.

**Comment by mtdenton** [comment]
Had a question if we needed to close this, but I guess what I really need is to be brought up to speed on this.

**Comment by simont-cr** [comment]
@kristinashu Could you please let us know if this ticket should remain open as the work detailed on this might have moved to another issue or should we keep this available?

**Comment by kristinashu** [comment]
I think this is an ongoing things. Let's close and open specific tickets as needed!
