### ISSUE TITLE
2 - Design system in Figma

### ISSUE THREAD

**Issue by fessehaye** [MozillaFoundation/foundation.mozilla.org#6985]
- Migrate from Sketch to Figma
- Implement updated design tokens
- Make sure all atoms and molecules are well defined

**Comment by mtdenton** [comment]
@fessehaye @sabrinang can this be closed?

**Comment by cdanfon** [comment]
Hey @kristinashu @sabrinang is this ticket still relevant or can we close it? Thanks!
