### ISSUE TITLE
5 - Create separate directory in repo for design system

### ISSUE THREAD

**Issue by fessehaye** [MozillaFoundation/foundation.mozilla.org#6988]
* Find all styles on foundation that are design system specific (make sure there are no or minimal overrides included in the design system)
* Move them to separate directory

**Comment by mtdenton** [comment]
@fessehaye can this be closed?

**Comment by simont-cr** [comment]
@kristinashu Do you still need a separate repo to handle everything for the design system or there is no longer a need for it?
