### ISSUE TITLE
Usability/firefighting issue: we can't unpublish a page + all localized copies

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/foundation.mozilla.org#7372]
With the wagtail-localize approach, we can no longer just unpublish "a page" and have all associated localized versions be unpublished too, which makes firefighting exponentially harder: we need some way to say "this page, and all its localized copies/aliases/etc, should (temporarily) be made unavailable".

As concrete use case, we had someone abuse our donate help submission form, which has many localizations, and unpublishing each of those pages would have been an intractable action. Instead we pushed a code change that emptied the page template so that we knew it would affect every page instance, which we then had to roll back once we had submission hardening in place. This is not an ideal solution

**Comment by benhohner** [comment]
- [ ] Add this to Theo's localization issue list

**Comment by Pomax** [comment]
This is still a concern that needs to be addressed (probably in collaboration with TB/Wagtail folks)

**Comment by mtdenton** [comment]
@cdanfon can't believe this isn't a thing for us, I feel like we need to resurface this.

**Comment by tbrlpld** [comment]
This is solved in Wagtail 4.0: https://github.com/wagtail/wagtail/commit/4cc10322a1c86c1137f5042a13d94d8017498bf7

**Comment by simont-cr** [comment]
Per Tibor latest comment on 2022, this has already been resolved after Wagtail's update on 4.0. Closing as no longer an issue for the team.
