### ISSUE TITLE
Improve blog category default title

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#7464]
Currently blog category titles are built by:
- concatenating the category name ("advocacy", "common voice"…) with the main blog title ("Blog")
- then applying English capitalization rules to the result.

This causes some localization issues:
- The "Blog" translation is reused in a different context (translators may want two distinct translations)
- The concatenation makes it impossible to move "Blog" at the beginning of the title
- Capitalization mostly only works for English

We now have a dedicated "Title" field in Wagtail to set a completely custom title, but we should find a different solution when there’s no custom title set.

Maybe we could just use the category name?
Or make the title field required and set "Advocacy Blog" etc for all existing categories?
Something else?

**Comment by Pomax** [comment]
@nancyt1 is this something to take into consideration for the blog redesign related to categories?

**Comment by nancyt1** [comment]
@TheoChevalier Can you confirm if this is still an ongoing issue?

**Comment by simont-cr** [comment]
Closing as obsolete issue as part of 2024 Clean-up.
