### ISSUE TITLE
Profile blocks don't seem to respect low max numbers

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/foundation.mozilla.org#7580]
From slack: to produce this bug, create a page that has:

* a Profile By Id block,
* a Profile Listing block, and
* a Profile Directory block

then:

* set the max number of results to for the "profile by id" block and "profile listing" block to 4
* this limit seems to get ignored when the "profile directory"block is on the same page.

The solution here would require both a test case and of course the code fix that makes things work properly again =)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-249)

**Comment by tbrlpld** [comment]
Am I understanding correctly, that all three block types are added to the the same `StreamField` and the block count limits are set with the `block_count` argument to the `StreamField`?

**Comment by Pomax** [comment]
Yes to the first, but no to the latter, it uses a `max_num` in the struct options: https://github.com/mozilla/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/pagemodels/customblocks/profile_directory.py#L74-L80

**Comment by jamilasnell** [comment]
@Pomax you are assigned to improve steps to reproduce! Have a great day

**Comment by Pomax** [comment]
@tbrlpld I have updated the initial comment to better describe the problem as it was encountered

**Comment by tbrlpld** [comment]
Thanks @Pomax. This looks clear enough. 

Any recommendation on how to test Pulse? Are there examples where Pulse is mocked out?
