### ISSUE TITLE
[PNI] - product_criterion.html should sense whether or not its using rich text

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#7755]
Instead of sending a "rich_text_value" or "rich_helptext" flag, the product_criterion.html template should be able to determine whether or not its richtext. 

That way we dont need to worry about hardcoding it through the template and add fields/update fields as we would like.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-251)

**Comment by eleensmathew** [comment]
Hi I am interested to work on this. Since this is my first project please guide me.
