### ISSUE TITLE
[PNI] PNI specific error pages

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#7872]
Currently if I go to a broken PNI link e.g. https://foundation.mozilla.org/en/privacynotincluded/netatmo-smar - I see the foundation site 404 page. Would it be possible to show one that is custom to PNI? For example, can it:
- Show the PNI main nav
- Show PNI sub nav
- "Go to home page" button links to https://foundation.mozilla.org/privacynotincluded 

Screen cap from production:
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/1068783/142043274-0c2f3ab4-331e-42d1-b569-1f9d5df3ea13.png">

**Comment by jamilasnell** [comment]
@kristinashu is this something that is needed for this iteration? Or can this be done at a later date this year?

**Comment by kristinashu** [comment]
Later is totally fine!

**Comment by Pomax** [comment]
Let's investigate whether we can have multiple 404s on the same site based on URL path prefix

**Comment by Pomax** [comment]
Marking the investigation as good first bug, not necessarily the work itself as that will require a PNI specific 404 page to be designed.
