### ISSUE TITLE
[PNI] Design About pages that can be edited in the CMS

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#7958]
Currently all the PNI about pages need a dev to update the copy. We should talk to devs about making these editable and then design the pages in a way that matches the rest of fo'mo.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-253)

**Comment by kristinashu** [comment]
@Pomax how much work will it be to make the PNI About pages editable in the CMS?

**Comment by TheoChevalier** [comment]
@kristinashu  I’ve filed #7963 to handle the translation migration work, so we can coordinate those tasks

**Comment by simont-cr** [comment]
@kristinashu Could you let us know if this is something we're still planning on doing for this year or it's safe to close?
