### ISSUE TITLE
[PNI] Migrate About page translations

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#7963]
#7958 will move the content from templates to Wagtail, we should sync these tasks and plan ~ half a day to manually migrate all translations in French, German & Spanish.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-254)

**Comment by mtdenton** [comment]
@TheoChevalier is it safe to close this issue?

**Comment by TheoChevalier** [comment]
@mtdenton Only if we don’t plan on doing https://github.com/mozilla/foundation.mozilla.org/issues/7958 anymore
