### ISSUE TITLE
PNI - Clean up search filter code

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/foundation.mozilla.org#8015]
Follow-up to https://github.com/mozilla/foundation.mozilla.org/issues/7988 

With the refactor complete, we should consolidate/optimize the search filter code as much as possible.

## Dev tasks: 
* [ ] Consolidate mobile and desktop
* [ ] Renaming 

(to be groomed after the team has the opp to discuss and agree on approach)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-257)

**Comment by tbrlpld** [comment]
This is 100% necessary. I find it extremely hard to understand the search code.

**Comment by tbrlpld** [comment]
Also follow up to #9553

**Comment by tbrlpld** [comment]
I would like to propose to make the search a individual template fragment that can be included multiple times on a page (e.g. for mobile and desktop). We can pass an id into the fragment. 

Similarly, all JS should be generic and only need the id used for the fragment to instantiate a new search bar.

**Comment by mtdenton** [comment]
This should belong to a PNI refactor epic.
