### ISSUE TITLE
Add (almost) streamfield blocks to Page Types where they are missing

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#8017]
Currently, [not all streamfield blocks are available on all Page Types](https://foundation.mozilla.org/en/docs/how-do-i-wagtail/streamfield-blocks/). This is mostly because at the time we did not feel it was pertinent to take the extra step to add them to new Page Types. With more staff creating pages, however, now feels like a good time to make all streamfield blocks available on all Page Types. Looking at the the streamfield blocks that are missing from certain Page Types in this [spreadsheet](https://docs.google.com/spreadsheets/d/10zm-TMKQNJtvdYqO5_Dj-UvsF_I8vbO8H7uAxpC48zA/edit?usp=sharing), it doesn't seem like this would be a detrimental step. 

**Exceptions:**

- The Paragraph block probably does not need to be added to the Article Page Type since the Content block appears to fulfill the same function
- Related to that, could the Content block replace the Paragraph block on all other Page Types since it is essentially a more robust version of the Paragraph block?
- The Publication Page Type currently does not appear to support streamfield blocks, so perhaps it can remain the way it is? Will need to look more into this.

cc: @kristinashu

**Comment by kristinashu** [comment]
Closing this ticket but we plan to tackle this in more detail this upcoming quarter
