### ISSUE TITLE
Blog RSS feed resets timestamp on each new article published

### ISSUE THREAD

**Issue by bunnybooboo** [MozillaFoundation/foundation.mozilla.org#8067]
### Describe the bug
Each time a new article is published a set of older articles also get pushed as though new. This broadcasts a longer list of new items instead of simply the new item. This results in higher list maintenance needs for the reader when trying to read only new items.

This list also redirects to ES language URLs. In my case I hope to read EN-US or EN-GB.

### To Reproduce

1. Open RSS reader (Thunderbird used in this example)
1. Add news feed pointing to https://foundation.mozilla.org/en/blog/rss/

What happens:

A batch of 10 article items are pushed to the RSS reader. The URLs contained within them are redirected to an incorrect localized version.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-258)

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Clearing ticket as initial report was done in 2021 and we haven’t had any further updates on this regard.
