### ISSUE TITLE
Block inventory improvements

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8126]
Using the block inventroy has become a bit clunky. 

https://github.com/cfpb/wagtail-inventory

E.g. it is hard to identify different block types due to their naming. Is it possible to change how they are displayed to make it easier to find them? 

Also, when looking for pages that contain the blocks, we have the issue that the list of pages is too long. Especially, we would like to filter the list by locale. Is it possible to override the query to just be the (en) locale? Or can we make this our selves (might be a significant pull).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-259)

**Comment by tbrlpld** [comment]
@sabrinang Can you have a look at my description up top to see if this makes sense to you? Are those the main points you would like to be addressed?

**Comment by sabrinang** [comment]
@tbrlpld Yes, those are the main pain points using block inventory I had!

**Comment by simont-cr** [comment]
Hi @sabrinang , is this something that's still happening in the platform and we would need to address or it's safe to close?

**Comment by data-sync-user** [comment]
➤ Daniel Miranda commented:

After reading the description of this ticket I feel that it should be updated to a spike, so we can see what options are available to us when updating the inventory page, and if we are able to implement the requests such as filtering results to just return the english locale. I feel that should definitely be doable, its just a matter of figuring out how to override the results 👍
