### ISSUE TITLE
All external links should open in a new tab

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8214]
We have added "target='_blank'" to any external links within a rich text block in #8195

However, since external links in other blocks such as link buttons and video/image captions still open themselves in the same tab vs a new one like the rich-text external links, it is providing an inconsistent user experience.

The ask of this ticket is to make sure that **any** external link on the site opens in a new tab.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-260)

**Comment by simont-cr** [comment]
@danielfmiranda Is this still something that needs to be corrected in the platform and if so, would you say we could just keep it with a P3 status?

**Comment by danielfmiranda** [comment]
Hi @simont-cr I would say yes and that this can keep the P3 status. I have updated the labels to reflect this 👍
