### ISSUE TITLE
New highlights can’t be translated

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#8254]
A few days ago, a new highlight has been added to the [What you can do](https://foundation.mozilla.org/cms/pages/168/edit/) page.
I’ve synced the page with translations, but Wagtail didn’t automatically start the translation of the new highlight.
It had a “Translate” button in front of it, so I tried to manually start the translation. The translation did start (and went through Pontoon etc, [example in French](https://github.com/mozilla-l10n/fomo-content/blob/main/locales/fr/snippets/highlights.Highlight/134-add-your-name-tell-slack-to-blockabuse.po)), but the content remain in English on [the live page](https://foundation.mozilla.org/fr/what-you-can-do/) (Look for the Slack campaign).

I wonder if this is related to #7771?

[Here’s an example on staging](https://foundation.mofostaging.net/cms/pages/3785/edit/), I’ve added the Ring highlight and after syncing the page it appears untranslated (as in the translation is not automatically started/enabled):
<img width="766" alt="Capture d’écran 2022-02-16 à 16 20 10" src="https://user-images.githubusercontent.com/1294206/154296218-fd6af1d5-75c1-4e92-b67f-1524d1f730d9.png">

**Comment by simont-cr** [comment]
Closing as obsolete issue as part of 2024 Clean-up.
