### ISSUE TITLE
[RH] Author index page - search/filter

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8317]
Add a search or filter functionality for the research author index page. 

The exact implementation of the search/filter functionality is still under discussion. The goal of the feature would be to be able to discover new researchers. 

The array of letters (as in the design) has been criticized because it is not easy to cover all localisation situations. We have also discussed the option of a search bar. The search bar might be problematic because you need to know what to search for. Search is more a find feature, not a discovery feature. 

**THIS FEATURE NEEDS DISCUSSION AND SCOPING**

<img width="416" alt="image" src="https://user-images.githubusercontent.com/24797493/162296282-2c2707e0-6897-4743-9a0e-51ecef91d5c6.png">

<img width="481" alt="image" src="https://user-images.githubusercontent.com/24797493/156827676-6cdf8ba4-54fd-4d18-9b64-4856e958679d.png">

See also:
- [Designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration)

# Acceptance criteria

- [ ] The feature is fleshed out. 
- [ ] When the author index is loaded, it displays all authors (which are the `Profiles` associated with "research detail pages").
- [ ] A search or filter feature allows reduction of the number of displayed authors and aids discovery. 
- [ ] ....

**Comment by beccaklam** [comment]
@tbrlpld If we're changing this to search I don't know if removing the filter via a "View All" button makes sense. Wondering if the wording should be "Remove Filter" or "Clear Filter" or simply "Clear". Alternatively, perhaps we could make "View All" work by adding "Authors" so, "View All Authors". I feel that having the label reflect the action happening (the filter being removed) may make more sense though?

**Comment by tbrlpld** [comment]
@beccaklam Yea, that makes sense. Since the action says "search" I guess "clear search" or "reset search" would be most consistent (over introducing the word "filter" as synonym for "search" -- even though it is correct in this case as the search if basically a filter).

**Comment by tbrlpld** [comment]
Good points @beccaklam 

Looks like there is no option reset the search on the library. 
<img width="609" alt="image" src="https://user-images.githubusercontent.com/24797493/162263694-44c35632-ad3d-4d8f-8e7e-c839ba37f19d.png">


Also just noticed that the "view all" was in the original design for the author index.
<img width="607" alt="image" src="https://user-images.githubusercontent.com/24797493/162263847-0ed09a1e-509d-4e48-97b4-7b2ef890c0f3.png">

**Comment by beccaklam** [comment]
@tbrlpld Yes, the 'view all' makes sense in the above context since it's referring to all the letters. I feel like it makes less sense now that we've switched the design to a search box. 

A quick search of the internet yields this search and clear benchmark but it would be good to have Nick have a design pass at this:
![Screen Shot 2022-04-07 at 10 47 22 AM](https://user-images.githubusercontent.com/20977376/162265193-b7743876-9a15-4d0c-9dc4-8cd013598db0.png)

**Comment by tbrlpld** [comment]
@beccaklam Sounds good. Not sure about the accessibility implications here. Yea, would be good to get input from Nick, but I am not sure he will be available any time soon. 

Is that maybe something you could take on? 

cc @bheasman

**Comment by tbrlpld** [comment]
@beccaklam Would the "clear search" button be keyboard accessible? I feel like it's a common pattern to type the search and then tab to the submit button. I would be afraid that one would not see the miss button, type the keyword, tab, enter and then the bar would be emptied... which I don't think is what we would want. 

 I guess the clear button should not be tab reachable or after the search/submit button. I guess the keyboard accessible way to reset the search is just deleting the keyword and submitting... although that feels somewhat hidden. Maybe... 
 
 Sorry about the back and forth.

**Comment by beccaklam** [comment]
@tbrlpld Good questions and no worries about the back and forth. I'm actually going to tag @nancyt1 here to give input since she's designed a search bar with clear functionality for the blog which we could use here? It would make sense for the Foundation website to have a mostly consistent search bar UI/UX anyways esp for the same functionality. @nancyt1 do you mind dropping your design here, providing assets, and answering the accessibility question above if it's still applicable to your design?

**Comment by bheasman** [comment]
Thanks for the helpful discussion her. I think it's going to be tricky to get Nick's time before the end of the month on this - but if we can use the search bar from @nancyt1 that feels like a good solution - especially to allow consistency across the site.

**Comment by tbrlpld** [comment]
@bheasman I have updated the ticket based on today's discussion. Except for styling, the page is already working as expected for MVP... It really only lists the authors without pagination. 

I move this ticket to "needs discussion" because we can not start work on this until we know what search/filter feature we want.
