### ISSUE TITLE
[RH] Research detail page - related research

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8318]
![image.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/1e875176-bcde-4824-96f1-52fd3e1b414b)

Display related research on each "research detail page". 

The exact weighing and calculation to define "related" research still needs to be defined, but it should be based on taxonomies. E.g. they are similar when they share topic, year, author and region. 

***

- [ ] On each "research detail page" two cards are displayed linking to two other "research detail pages" that are deemed "related". 

***

See also:
- [Research hub models](https://docs.google.com/document/d/19WoZxJvisMsHnXqA4GDX3Te6t9JnqAI2NG5jE9J4LP4/edit#)
- [Designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration)

**Comment by kristinashu** [comment]
Same for this ticket, going to close it since I don't see it being a priority anytime soon. 

cc @beccaklam @tbrlpld in case you disagree :)
