### ISSUE TITLE
[RH] Research detail page  - related news and events

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8319]
![image.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/fae4c334-c422-43a4-8f99-56a1e715d445)

Enable display of related news and events links on the "research detail page". These are basically just links (internal or external) with some meta information. 

This is can be very simple to start with. E.g. an orderable inline model with the following fields:
- Page
    - Parental key [Research detail page]
- Title
- Date / Meta info
    - Plain text
    - Max 50 char
    - Use help text to say this should be “date for publication, date range for event” …
- Target description
    - Plain text
    - Max 50 char
    - Just some additional text to say something about the page linked to (e.g. “News” or the host of the linked page)
- Link (external, internal)
- Intro

***

**Acceptance criteria**

- [ ] Editors can create "related news and event" links on "research detail pages"
- [ ] The links can be internal or external
- [ ] External links show a little icon
- [ ] Editors can fill a meta data field that is e.g for publication dates or date ranges.
- [ ] Editors have to provide the title
- [ ] Editors have to provide a short introduction text for the link
- [ ] Factories for the "research detail pages" need to be adjusted to create mock data for these fields
- [ ] When no "related news and events" links are defined, the whole section should be hidden
- [ ] A maximum of 3 entries can be added

***

See also:
- [Research hub models](https://docs.google.com/document/d/19WoZxJvisMsHnXqA4GDX3Te6t9JnqAI2NG5jE9J4LP4/edit#)
- [Designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration)

**Comment by kristinashu** [comment]
Going to close this since I don't see it being a priority anytime soon. 

cc @beccaklam @tbrlpld in case you disagree!
