### ISSUE TITLE
[RH] Landing page - featured authors

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8320]
![image.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/483f5aac-a31a-4960-9f99-34716ca6db07)

Display up to 4 featured research authors on the research landing page. 

There  is some discussion around how this is to be managed, which researchers are displayed. Double check that that discussion has been resolved. 

***

**Acceptance criteria**

- [ ] Editors can select up to 4 research author "profiles" to be displayed on the "research landing page". 
- [ ] A research author "profile" can only be selected if it is associated with at least one "research detail page".
- [ ] The author card links to the "research author page/view". 
- [ ] If no research authors are selected the section should be hidden.

***

See also:
- [Research hub models](https://docs.google.com/document/d/19WoZxJvisMsHnXqA4GDX3Te6t9JnqAI2NG5jE9J4LP4/edit#)
- [Designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration)

**Comment by kristinashu** [comment]
@beccaklam @tbrlpld is this at all a priority for the RCC playbook? If it's only beneficial for the research hub then I think we can close it since it won't be a priority anytime soon.

**Comment by tbrlpld** [comment]
@kristinashu Yes, this came up recently for RCC too to highlight orgs (Universities). I mentioned this ticket to @beccaklam and I think she wanted to explore this as a solution
