### ISSUE TITLE
[RH] Research newsletter signup

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8323]
![image.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/6c9ea9c5-1853-45ad-9066-41659618455b)

- Element in the bottom of every page type in the research hub.
- Discuss if needed/desired.
- Can be added to the base template if static.

See also:
- [Research hub models](https://docs.google.com/document/d/19WoZxJvisMsHnXqA4GDX3Te6t9JnqAI2NG5jE9J4LP4/edit#)
- [Designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration)

**Comment by kristinashu** [comment]
I'm going to close this since I don't think there are any real plans for a research newsletter and it is not a priority.
