### ISSUE TITLE
[RH] Library page - filter feature [complex]

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8324]
- Update the list of available filter values for all filter categories based on the already selected filters. E.g. when year filter 2020 is selected, the author filter values list is updated to only show authors with publications from 2020.
- This needs some more scoping.
- This might need a totally different approach then the simple version
- There is not really a sensible way around hitting the server on every filter setting
- I might make sense to just let the server render this filter feature and then do DOM diff and update on the frontend to keep focus etc.
- See [discussions on the designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc?node-id=21:275#156809501) for more info
- I would ignore the count values here for a moment

See also:
- [Research hub models](https://docs.google.com/document/d/19WoZxJvisMsHnXqA4GDX3Te6t9JnqAI2NG5jE9J4LP4/edit#)
- [Designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration)

**Comment by kristinashu** [comment]
@tbrlpld is this still relevant, how important is this, would it be ok to close it a "won't fix"?
