### ISSUE TITLE
Cleanup source\sass\components\select-dropdown.scss

### ISSUE THREAD

**Issue by fessehaye** [MozillaFoundation/foundation.mozilla.org#8335]
We already have `tw-form-control` and `tw-form-control-lg` so we just need to remove this file and replace the dropdowns with the new classes

**Comment by mmmavis** [comment]
@fessehaye can you verify on staging that there's no regression on `select.tw-form-control`

### To QA 
- Go to https://foundation.mofostaging.net/en/campaigns/unknown-influence/ and check
There are three forms on the page 1) Nav bar via "Newsletter" button 2) in page petition form 3) footer newsletter sign up
- Go to https://foundation.mofostaging.net/en/blog/ and check the big "Subscribe to our newsletter" form

Thanks!

**Comment by danielfmiranda** [comment]
Thanks for the fix @mmmavis!

I have taken a look and can confirm that there is no regression. Moving this to ready for prod.

**Comment by mmmavis** [comment]
@kristinashu taking for QAing this. Basically we just need to make sure the forms mentioned above are still looking the same as what's on prod.

**Comment by kristinashu** [comment]
Looks good!
