### ISSUE TITLE
cleanup source\sass\views\participate.scss

### ISSUE THREAD

**Issue by fessehaye** [MozillaFoundation/foundation.mozilla.org#8343]
`network-api\networkapi\wagtailpages\templates\wagtailpages\static\participate_page2.html` will be affected but just worry about removing `#participate-hero` and `.bottom-line` and we will cleanup the rest of the HTML in a different ticket!

SASS File should be removed!

**Comment by tbrlpld** [comment]
Nobody is working on this. Removing from active sprint.

**Comment by simont-cr** [comment]
Closing per issue clean-up on EPICS.
