### ISSUE TITLE
cleanup source\sass\views\shared\sticky-cta.scss

### ISSUE THREAD

**Issue by fessehaye** [MozillaFoundation/foundation.mozilla.org#8345]
Double check with `source\js\foundation\template-js-handler\window\sticky-cta.js` to see what classes are needed but I think you can delete the sass file and replace it with just tw-classes.

Files affected:
* `networkapi\wagtailpages\templates\wagtailpages\campaign_page.html`
* `network-api\networkapi\wagtailpages\templates\wagtailpages\bannered_campaign_page.html`
* `network-api\networkapi\mozfest\templates\partials\signup.html`

**Comment by simont-cr** [comment]
Closing per issue clean-up on EPICS.
