### ISSUE TITLE
cleanup source\sass\wagtail\blocks\looping-video.scss

### ISSUE THREAD

**Issue by fessehaye** [MozillaFoundation/foundation.mozilla.org#8349]
* Will involve renaming classes in `network-api\networkapi\wagtailpages\templates\wagtailpages\blocks\looping_video_block.html`
* Should be possible to remove sass file all together and replace with tw classes on the wagtail template

**Comment by mmmavis** [comment]
Deprioritizing this ticket as the "looping video" block doesn't seem to be used often & it isn't being used currently on any prod pages.

**Comment by simont-cr** [comment]
Closing per issue clean-up on EPICS.
