### ISSUE TITLE
update makes.org redirect to point to the correct artifacts page

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/foundation.mozilla.org#8451]
The ancient and long-retired makes.org domain currently points to https://foundation.mozilla.org/en/artifacts/thimble, which isn't a real page anymore. We should update this to point to the `webmaker-thimble`, rather than `thimble` page.

**Comment by simont-cr** [comment]
This will already be tackled with #11484 epic, so we can safely close.
