### ISSUE TITLE
Localize the `profile` snippet

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#8452]
This is a follow-up from https://github.com/mozilla/foundation.mozilla.org/pull/8424 to allow translation of the `tagline` and `introduction` fields.

We need to make the following class localizable:  `PublicationAuthors`, `ArticleAuthors` and `BlogAuthors`.

See discussion in https://github.com/mozilla/foundation.mozilla.org/pull/8431 for full context

**Comment by Pomax** [comment]
might be a good pair programming opportunity

**Comment by simont-cr** [comment]
Issue was mentioned on a follow up ticket and PR, proceeding to close this one per duplicate item.
