### ISSUE TITLE
Create link-de-englisher management command.

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/foundation.mozilla.org#8503]
Followup to https://github.com/mozilla/foundation.mozilla.org/issues/5981, we should:

* write a management command that can run through all `Page` instances
* for each Page, check for a `body` property
* iterate the `body` streamfield looking for blocks that may contain either richt text or have explicit URL fields
* in each, check for links with the `/en/` infix in them, and replace that with `/` instead, so that URLs localize properly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-270)

**Comment by mtdenton** [comment]
Stumbled upon this and it's a fantastic idea, @cdanfon @victoriachan adding this to the project to disucuss, let me know if there are timing/feasibility issues for our timeline.

**Comment by cdanfon** [comment]
Hey @victoriachan when you have a bit of time, can you estimate this one please? Thanks

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Tyler Denton We never got this estimated, but do you still feel that this would be a good idea? We could set up some time and have a member of the team to groom and estimate.
