### ISSUE TITLE
[RH] Library page - load more

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8532]
### Describe the feature request

Progressively enhance the library page with a "load more" functionality. 

Previously the library should have been create with normal pagination in place (see #8316). The original design idea was a "load more" feature.  This ticket is meant to progressively enhance the library page with the "load more" functionality. 

### Screenshots / mock-ups

<img width="296" alt="image" src="https://user-images.githubusercontent.com/24797493/162258542-ba13de70-20c8-43fe-aa41-d880252c1c1f.png">

### Acceptance criteria

- [ ] When visiting the page with Javascript deactivated it shows the previously implemented pagination
- [ ] When visiting the page with Javascript active it uses the "load more" feature
- [ ] Clicking the "load more" button retrieves the next page (e.g. 10) of "research detail pages" and adds them to the bottom of the existing list.
- [ ] The URL should reflect the updated loaded page in the URL.
- [ ] Visiting a link with a page number in it (e.g. `research/library/?page=2`) displays all results up to and including the page defined in the URL. 
- [ ] Visiting a link with a page number in it (e.g. `research/library/?page=2`) scrolls to the place in the page where the results for that page are starting. 
- [ ] The "load more" button shows the total number of available, not yet displayed results.

**Comment by kristinashu** [comment]
I think the current pagination is enough. Closing this ticket but @beccaklam @tbrlpld please reopen if you disagree.
