### ISSUE TITLE
[RH] Library page - dynamic search, filter and sort

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8533]
### Design team contact

@beccaklam 

### Final Designs

https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration?node-id=4%3A2

<img width="355" alt="image" src="https://user-images.githubusercontent.com/24797493/162260175-56bf42af-c6ba-4f81-8baa-cd5eff82c884.png">

### Details

Apply search, filter and sort dynamically. 

Previously, the library page was setup to with search, filter and sort features. Changing any one of those filters required a page refresh to update the list of results (research detail pages). 

The goal of this ticket is to progressively enhance the library page with dynamic updates to the results list based on the search, filter and sort values. 

### Acceptance criteria

- [ ] When visiting the page with JS disabled, the previously implemented functionality based on full page reloads still works.
- [ ] When visiting the page with JS enabled, the results list is dynamically refreshed updated to reflect the used search, filter and sort order. 

### Implementation Checklist

(Feel free to remove items that are not applicable.)

**Before creating ticket**:

- [ ] Business requirements are verified (make sure the suggested solution will meet stakeholder’s needs)

**Ticket-Creation**:

- [ ] Make sure you have acceptance criteria in the ticket (in a checklist)
- [ ] List of all tasks that need to be completed to meet the acceptance criteria
- [ ] Ticket structured well

**Pre-Merge**:
- [ ] Code follows our code style guide [documentation WIP]
- [ ] Code is documented according to our documentation standards [Need to create]
- [ ] Unit Test Coverage [need to create coverage target and tooling]
- [ ] Integration Test Coverage [need to create guide]
- [ ] Any technical debt is documented (todo/fixme => needs an issue linked in comments)
- [ ] Any follow-up tasks are created before a PR is merged
- [ ] Code peer-reviewed by at least one other developer

**If the work had design-dev handoff, also signed off by a designer**:
- [ ] Code has error handling with clear error messages
- [ ] Incomplete features are hidden behind feature flags (for features without Update or Delete DB migrations)
- [ ] Secrets (github actions + heroku) are up to date for CI, review apps, and staging

**Post-Merge, Pre-Production Deploy**:
- [ ] Code is deployed to Staging
- [ ] Code is manually verified to work on staging (rare, but important)
- [ ] Test management commands that may need to be run
- [ ] Release scripts are up to date (rare, but important)

**Production Deploy**:
- [ ] Production deploy successful
- [ ] Notify Stakeholders

**Comment by bheasman** [comment]
@tbrlpld should this cover the 'load more' feature replacing pagination too?

**Comment by tbrlpld** [comment]
@bheasman I have #8532 for the load more functionality. They are similar in ways, but ultimately unrelated. Changing any of the search, filter or sort will destroy the whole displayed list and render a new one. This tickets goal is just to do so without the page reload. 

The load more will extend the existing list with out destroying what's already there. It should therefore be separate.

**Comment by kristinashu** [comment]
Closing this since it is low priority.
