### ISSUE TITLE
[RH] Author index page - pagination

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8538]
Add pagination to the author index page. 

In the design, the author index page does not have any pagination. This can be problematic when looking at the unfiltered index as it can contain many authors. 

Goal of this ticket is to add basic pagination to the author index. 

# Acceptance criteria

- [ ] The author index page does not show more than 20 results per page.
- [ ] A next an previous link are displayed to navigate to the respective page.
- [ ] On the first page there is no previous link.
- [ ] On the last page there is no next link.
- [ ] The page navigation is implemented with full page refresh (dynamic behavior can be added later/with a separate ticket). 
- [ ] Change the search filter will reset the page selection to 1.
- [ ] Change the page will keep the same search in place.

# Dev tasks

- [ ] Add page setting (not on the content panel) to define page size. Default 10. 
- [ ] Add test to check different pages of results can be requested via URL parameters. To make the test simpler to set up, it is helpful to set the page size to a lower value (e.g. 3). 
- [ ] Add pagination to the results queryset/list in the `get_context` method. This should make the test pass. 
- [ ] Add navigation links below the results list. Use link style with arrows.

**Comment by tbrlpld** [comment]
@bheasman Sorry, I had to create a new ticket for the MVP. This is something I totally missed because it was not in the original design.

**Comment by bheasman** [comment]
No probs - good spot. Ok to add an estimate on here please? Presumably we can reuse the pagination component from the library page @tbrlpld ?

**Comment by tbrlpld** [comment]
@bheasman Yes, we should be able to reuse the pagination from the library. 

Also moved this to "nice to have" based on todays discussion.

**Comment by kristinashu** [comment]
I don't think too many authors on the page will be an issue anytime soon https://foundation.mozilla.org/research/browse-authors/. Closing this for now and we can address it if/when it becomes an issue.

cc @beccaklam
