### ISSUE TITLE
Visual issues with the publication menu on translated pages

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#8557]
Looks like the menu was not designed to handle multi-line labels, and so when "SHOW ALL" translation results in a longer string, it’s wrapping on a second line and causing a couple visual issues.

This is currently affecting French, German, Polish, Dutch and Frisian.

### When opening the menu, there’s a weird “bump”

https://user-images.githubusercontent.com/1294206/163192396-04fdfe29-a2de-4d99-9c0c-c192aca743a1.mov

### The menu is visible below the site header

When opening a publication page in one of the affected locales, e.g. https://foundation.mozilla.org/fr/insights/trustworthy-ai-whitepaper/path-forward/introduction-theory-change/ you will notice the lower part of the menu is visible below the site header

<img width="1352" alt="Capture d’écran 2022-04-13 à 15 35 33" src="https://user-images.githubusercontent.com/1294206/163194549-69de0d42-7b2e-45c9-b9c1-8db69ccbec60.png">

**Comment by kristinashu** [comment]
@TheoChevalier are you still seeing this issue? Both issues **_seem_** to be fixed 
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/1068783/228388285-7b0ec9d7-3756-43e7-a5b2-d77e357b806a.png">

**Comment by kristinashu** [comment]
I'm going to close this but please reopen it if you still notice the issues.
