### ISSUE TITLE
History is still inaccurate when hidden categories are included

### ISSUE THREAD

**Issue by fessehaye** [MozillaFoundation/foundation.mozilla.org#8606]
Go to the hidden category https://foundation.mofostaging.net/en/privacynotincluded/categories/mental-health-apps/
Click on a category like "Best of"
Hit your back button to go back to Mental Health Apps page
Click on Mental Health Apps title and see how the URL change to the previous category - best of

![image](https://user-images.githubusercontent.com/2374073/165635218-cbb031cb-3bae-4455-9d1f-ac6ef898ab8c.png)

**Comment by mtdenton** [comment]
@fessehaye is this still relevant after the PNI relaunch?

**Comment by kristinashu** [comment]
Just tested this and it seems to be working as expected now!
