### ISSUE TITLE
SPIKE - Map Out Holistic view of all groups & relative permissions on Wagtail

### ISSUE THREAD

**Issue by cdanfon** [MozillaFoundation/foundation.mozilla.org#8609]
@kristinashu Mentioned it would be useful to have an understanding of the different types of groups and relative permissions on Wagtail. 

Creating this ticket to produce a report that gives us that holistic vision.

Once the report has been created we would use it to amend/update permissions within groups to avoid having to manually update them for individuals depending on the work they need to do on the Wagtail backend.

**Comment by tbrlpld** [comment]
@cdanfon Is this supposed to be a one-time report or a screen in Wagtail that shows this information dynamically? 

Also can you specify what exactly the report should show? Do you want an overview of which group has which permission?

**Comment by kristinashu** [comment]
It would be a one-time report to help us better understand the different roles (which groups have which permissions) and then we can figure out how to simplify and streamline them. I'm picturing a spreadsheet...

**Comment by tbrlpld** [comment]
@kristinashu Thanks for clarifying. Would it be possible to get a sketch of the spreadsheet you are picturing? I have a hard time right now coming up with a good grouping and structure, eg. what are columns, what are rows, etc.

**Comment by kristinashu** [comment]
I'm glad you asked this because I'm now realizing I had started [a spreadsheet](https://docs.google.com/spreadsheets/d/1AwLF6dw05Jn2WZu-xvxUgm8VQ4udriZW6d_NfdVI9ns/edit?usp=sharing) about this a while ago (4th tab called "Permissions").

I understand how to given staff permission to certain roles but I really don't know what the roles do, how they're controlled, or what it looks like so I'm hoping devs can help clarify that under the "What does it control" column.

**Comment by tbrlpld** [comment]
Yea, I am not sure why we have so many groups either. It almost feels like we have a single group for every possible permission. 

You can view (and as an admin edit) the permissions that are given to each group: https://foundation.mozilla.org/cms/groups/63/

I wonder if we need a discussion with the wider org as to why we need this fine grained control. In the end I feel like we give permission to staff who ask for it anyhow 🤔 Maybe there is some process I am missing?

**Comment by kristinashu** [comment]
Oh wow this is very helpful to see and it does seem overly complex! 

I agree, we need to have a wider convo about how granular we should (or more likely should not) be. I suspect the granularity wasn't necessarily intentional. I'll assign this ticket to myself and @mtdenton for now.

**Comment by mtdenton** [comment]
I'm taking this on to map this out as a first step. Once we have the facts of how we're doing it now, we'll follow up with tickets on how to streamline these permissions and integrate workflow functionality introduced into Wagtail in the newer versions.

**Comment by kristinashu** [comment]
Thank you Tyler! In general, I believe all the different content editor roles should be grouped together as a single role and then some of the snippets should be more granular (only a few people can edit Blog Page Topics, Research topics, and Research regions).

**Comment by tbrlpld** [comment]
@kristinashu Can you add some context why we need more granularity for the snippets? Just wondering why we don't trust editors there to only touch what they are should while we do for pages.

**Comment by kristinashu** [comment]
I think most snippets are fine for anyone to edit but we want to be strict about Blog Page Topics so we don't end up with an unhelpful amount of them. Based on past experiences, staff don't immediately see anything wrong with adding more and more topics so, if they could, I think they would go ahead and add more and more.

The Research and soon to be RCC libraries should also be restricted to just the product owners for similar reasons.

**Comment by kristinashu** [comment]
Rebecca did this as part of the CMS clean up work!
