### ISSUE TITLE
[EPIC] Updating Github issue templates

### ISSUE THREAD

**Issue by cdanfon** [MozillaFoundation/foundation.mozilla.org#8620]
From the back of our 'Maintain digital services' roadmap session we agreed on _Updating Github issue templates_ as one of the low hanging fruit to _Maintain & improve our codebase & tech stack to ensure our digital products serve our supporters/internal teams efficiently, speedily, in a secure way_

Link to the Miro board - https://miro.com/app/board/uXjVO_AWfbg=/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-272)

**Comment by simont-cr** [comment]
Issue represents an epic with only one missing ticket, #8626. Keeping open so we can close when the related ticket is done.

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

As we no longer adding issues directly on GH, this is safe to complete.
