### ISSUE TITLE
Private pages are returning 500 error

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8652]
### Describe the bug
Stakeholders are experiencing 500 errors when trying to visit a page that is set to private.
The page that was used to reproduce the bug is https://foundation.mozilla.org/en/blog/regretsreporter-user-controls-study-1/

### To Reproduce
1. Go to https://foundation.mozilla.org/en/blog/regretsreporter-user-controls-study-1/
2. Make page private
3. Visit again and note the 500 error

### Expected behavior
This depends on what the privacy can be set to. For example, if i set it to private with a password, there should be a text box to enter the password to view the page. 

On prod, we instead get a 500 error. And on localhost we get this error:
![Screenshot 2022-05-11 at 10-16-26 AttributeError at _en_blog_initial-test-blog-post-with-fixed-title_](https://user-images.githubusercontent.com/18314510/167908781-7be8e71e-77bf-493e-bb60-953afee9e471.png)

### Additional context
The line that is producing the error can be found on [blog.py line 222](https://github.com/mozilla/foundation.mozilla.org/blob/fcafac3057cb4defe4a683ec97a3844dd88fc106/network-api/networkapi/wagtailpages/pagemodels/blog/blog.py#L222)

**Comment by tbrlpld** [comment]
Nobody is working on this. Removing from active sprint.
