### ISSUE TITLE
[Blog] - Blog Updates

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8682]
This is an epic made to cover the Blog Page improvements for the foundation site. 

[Link to Figma Designs](https://www.figma.com/file/528nyaJFzvCXAiw2gglwzh/Blog-Improvements)

[Link to Google Doc outlining work/requirements](https://docs.google.com/document/d/1dCYTWdtnt0RtDz7hSRs5eGTkXRF0_aPeuQ4D4mhwjJc/edit)

[Meeting recording
](https://torchbox.zoom.us/rec/share/yaK9uw_iJO27f_75iVNnrHlP-vFZHPeCoVBKChZsiAIU0SUCs5a0bKRzQp0PBtal.Ed9YOgox0lffsciD?startTime=1652722477000)Passcode: SL7?8Qz.

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/TP1-274)

**Comment by tbrlpld** [comment]
Nobody is working on this. Removing from active sprint.

**Comment by kristinashu** [comment]
@jhonatan-lopes @Gbaldassano @mtdenton hi, @nancyt1 and I quickly reviewed the remaining blog tickets. We've added priority labels to some tickets and epics to help re-prioritize this work.

The only P1 is https://github.com/MozillaFoundation/foundation.mozilla.org/issues/8788
P2 would be https://github.com/MozillaFoundation/foundation.mozilla.org/issues/8790 and the tickets within https://github.com/MozillaFoundation/foundation.mozilla.org/issues/8795
The other tickets feel lower priority.

**Comment by mtdenton** [comment]
Per SD Workweek, let's take a look at this and figure out how to prioiritize what's inside this epic.
