### ISSUE TITLE
[Blog] - [Search] - Search Page Styling

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8696]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/18314510/169925501-aa7760df-bb06-402d-8841-701c41ad19b8.png">

[Link to Figma Design](https://www.figma.com/file/528nyaJFzvCXAiw2gglwzh/Blog-Improvements?node-id=627%3A22440)
This ticket is to bring all search page components together and to style the page based on the design above using tailwind as much as we can.

Dev Steps
---

- [ ] Take the components from the other tickets in this epic, and add them to this template
- [ ] Using Tailwind as much as possible, arrange and style the page to match the design above as close as possible.

Acceptance Criteria:
---

- [ ] The layout of components follow the figma design as close as possible

**Comment by kristinashu** [comment]
Aside from the filter drop down (which is low priority) it seems to me like this ticket is complete. @nancyt1 @danielfmiranda could you please confirm and close the ticket if it is done? The page https://foundation.mozilla.org/en/blog/search/?q=privacy+not+included looks pretty amazing to me!

**Comment by nancyt1** [comment]
There's a few small design details missing like:
- "Showing X results for" label
- swapping the search field font from nunito sans to zilla
- adding 1.5rem top padding to the page title
Is that small enough stuff to address here or could I open a ticket for blog QA after big work is done?
