### ISSUE TITLE
Update source\js\components\join\language-select.jsx

### ISSUE THREAD

**Issue by fessehaye** [MozillaFoundation/foundation.mozilla.org#8704]
See [[EPIC] React Components Stylings](https://github.com/mozilla/foundation.mozilla.org/issues/7042) for more details.

## Dev Work

- [x] Make sure there is no bootstrap classes remaining on the JSX file
- [x] If there are CSS classes that are from a local SASS file, refactor them on the JSX file using tailwind classes
- [x] After refactoring the classes from SASS files, delete the previous SCSS file
- [x] Might be needed to create a plugin if we are replacing a reused bootstrap class

## Acceptance Criteria

- [x]  Component should be able to work without a dependency from bootstrap
- [x]  Component should be able to work without a dependency from existing SASS files

**Comment by mmmavis** [comment]
@fessehaye can you verify on staging that there's no regression?

### To QA 
- Go to https://foundation.mofostaging.net/en/campaigns/unknown-influence/ and check
There are three forms on the page 1) Nav bar via "Newsletter" button 2) in page petition form 3) footer newsletter sign up
- Go to https://foundation.mofostaging.net/en/blog/ and check the big "Subscribe to our newsletter" form

Thanks!

**Comment by mmmavis** [comment]
@kristinashu taking for QAing this. Basically we just need to make sure the forms mentioned above are still looking the same as what's on prod.
