### ISSUE TITLE
Update source\js\components\petition\donation-modal.jsx

### ISSUE THREAD

**Issue by fessehaye** [MozillaFoundation/foundation.mozilla.org#8706]
See [[EPIC] React Components Stylings](https://github.com/mozilla/foundation.mozilla.org/issues/7042) for more details.

## Dev Work

- [x] Make sure there is no bootstrap classes remaining on the JSX file
- [x] If there are CSS classes that are from a local SASS file, refactor them on the JSX file using tailwind classes
- [x] After refactoring the classes from SASS files, delete the previous SCSS file
- [x] Might be needed to create a plugin if we are replacing a reused bootstrap class

## Acceptance Criteria

- [x]  Component should be able to work without a dependency from bootstrap
- [x]  Component should be able to work without a dependency from existing SASS files

**Comment by mmmavis** [comment]
@danielfmiranda do you mind QAing this on staging for me? Thank you in advance!

- staging: https://foundation.mofostaging.net/en/campaigns/tell-slack-make-dms-safe/?thank_you=true
- prod: https://foundation.mozilla.org/en/campaigns/tell-slack-make-dms-safe/?thank_you=true

**Comment by danielfmiranda** [comment]
Hi @mmmavis! Looks good to me 👍

**Comment by mmmavis** [comment]
Done!
