### ISSUE TITLE
Clean up source/sass/views/youtube-regrets-reporter.scss

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8732]
The goal of this ticket is to take all references of the scss in the youtube-regrets-reporter.scss file, and instead update the related HTML templates to use tailwind classes to achieve the same design.

Some of the HTML templates that may need to be updated include:

- [ ] youtube_regrets_base.html
- [ ] youtube_regrets_reporter_page.html

**Comment by simont-cr** [comment]
Closing per issue clean-up on EPICS.
