### ISSUE TITLE
Clean up source/sass/buyers-guide/_colors.scss

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8745]
Since we have updated the tailwind config to now include the PNI colors, I believe that it is safe to remove this file **once** we update/remove all scss files referencing these variable, and instead use the tailwind classes in the html templates.

TODO: Make this ticket blocked by all other cleanup scss tickets

**Comment by simont-cr** [comment]
Closing per issue clean-up on EPICS.
