### ISSUE TITLE
Remove variables.scss

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8751]
Once we are finished cleaning up the scss in primary-nav.scss, we can remove delete this file and remove it from "bg-main.scss"

--- 
### Dev Steps:

1. Delete this file
2. Remove the import from bg-main.scss

**Comment by ArshErgon** [comment]
Hey @danielfmiranda  just to be clear remove the `primary-nav.scss` and its import from the `bg-main.scss`?

**Comment by simont-cr** [comment]
Closing per issue clean-up on EPICS.
