### ISSUE TITLE
Clean up buyers-guide/mixins.scss

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8752]
The goal of this ticket is to remove the need for this file. However, since these mixins are being referenced in scss files that are going to be removed, I think its best we wait until that work is done as that would make this ticket as simple as "Delete file and push"

---
### Dev Steps:
- [ ] Once mixins are no longer used, we can delete the file
- [ ] Once deleted, we can then remove the reference to this file in "bg-main.scss"

**Comment by simont-cr** [comment]
Closing per issue clean-up on EPICS.
