### ISSUE TITLE
[Blog] - [Blog Page] - CTA Block Component

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8788]
<img width="832" alt="image" src="https://user-images.githubusercontent.com/18314510/171538373-547d521c-7553-4238-ae2b-ff5e3b3a7360.png">

The goal of this ticket is to create a new block for blog posts, called a "CTA block".

This new component should be able to be left aligned, right aligned, and full width. Similar to the blocks in publications.

It can be styled one of 3 ways:

Pop:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/18314510/171538861-434d5f5a-6523-40c1-a378-9908a070c2cf.png">

Outline:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/18314510/171540744-ef22c2da-6894-4b7c-89ce-bb5db7d6f961.png">

Filled:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/18314510/171540795-f333be04-1267-4742-8a4d-48bd0f7f8b7b.png">

Full width:
![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/61277874/50ff44b2-a343-429c-bc7f-2beede005fd3)

Optional button or image:
![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/61277874/a577711f-74ec-459d-b346-4e91baf25386)

It should have the following fields:

- [ ] Image - optional
- [ ] Body (rich text) - required
- [ ] Link Button (choice of primary or secondary) - Optional
- [ ] Link URL - Optional

Dev Steps:
---

 Note: We already have images with the same "left/right" with text wrapping around it styling on PublicationPages, so we can probably use that for reference on this ticket.

- [ ] Create a new streamfield block for use on the BlogPage, with the following fields above
- [ ] Make sure that this new block works as expected, with the other body text wrapping around it.

**Comment by mtdenton** [comment]
Hey @nancyt1 ! When you get a sec, could you take a look here? Thanks!
