### ISSUE TITLE
Research Hub implementation phase 2

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8800]
Implement features for phase 2 of the Research Hub.

[Design](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research-Hub?node-id=4%3A2)

[Delivery plan](https://miro.com/app/board/uXjVO-LT3a8=/?moveToWidget=3458764522850233162&cot=14)

**Comment by kristinashu** [comment]
@tbrlpld is this epic still useful for you or can it be closed?

**Comment by tbrlpld** [comment]
@kristinashu Looking at it in Zenhub still groups the related tickets: https://app.zenhub.com/workspaces/mofo-web-platforms-team-585335eab729771d0736378d/issues/gh/mozillafoundation/foundation.mozilla.org/8800

But, I don't think there is Phase 2 planned, and most certainly not with the feature set we defined over a year ago. 

So I guess yea, we can close this.
