### ISSUE TITLE
Research Hub implementation phase 3

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8801]
Implement features for phase 2 of the Research Hub.

[Design](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research-Hub?node-id=4%3A2)

[Delivery plan](https://miro.com/app/board/uXjVO-LT3a8=/?moveToWidget=3458764522850233175&cot=14)

**Comment by kristinashu** [comment]
@tbrlpld is this epic still useful for you or can it be closed?

**Comment by tbrlpld** [comment]
Related tickets only visible in Zenhub: https://app.zenhub.com/workspaces/mofo-web-platforms-team-585335eab729771d0736378d/issues/gh/mozillafoundation/foundation.mozilla.org/8801


But, no plan to do phases 2 and 3 for now. 

If we ever do another phase of development, we probably want to redefine what is being build in that phase anyhow. So, yes, we can close this.
