### ISSUE TITLE
Confirm profile images are using reduced size when hi-res is not necessary 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#8805]
We would like to be able to upload high-resolution profile images to the CMS and for the images to be loaded/displayed to users at high-res when needed but lo-res when the image is small. In other words, when a page (e.g. https://foundation.mozilla.org/en/blog/) displays small profile images, we should be loading them at the appropriate lower resolution (even if the photo was uploaded to the CMS at a large high-resolution). 

[via Slack](https://mozilla.slack.com/archives/CG07HH4G5/p1653419964938569) from tbrlpld

> Wagtail can create renditions at lower resolutions where they are needed. This allows more flexibility for the use of the images.

> That's a standard feature of Wagtail. We would only need to check pages with many images and make sure they are pulling the reduced size images.

### Todo
* [ ] Investigate if we are using the Wagtail feature
* [ ] If we are not then open necessary ticket(s) to add the Wagtail feature

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-287)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/67650">image-20240803-203841.png</a>

**Comment by tbrlpld** [comment]
Nobody is working on this. Removing from active sprint.

**Comment by simont-cr** [comment]
Hey @kristinashu , could you let me know if this is still something that we should worry about for this year work, maybe with a P2 or P3, or we should be okay with closing for now?

**Comment by kristinashu** [comment]
P2 sounds good, we _might_ work on profiles this year

**Comment by data-sync-user** [comment]
➤ diego commented:

Reviewing the code and the templates where author profile images are included on pages, we can confirm we are properly and correctly making use of wagtail renditions, displaying the smaller images according its size, and creating a rendition with proper transformations. 

How to test
  * We can consult this renditions on the following template: network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/blog_authors_intros.html
  * We are correctly importing wagtail image tags allowing the built-in renditions functionality: {% wagtailimages_tags %}
  * Inside of the template previously mentioned the follwing line  ( https://github.com/MozillaFoundation/foundation.mozilla.org/blob/087d3914a85a07fc2b4e09253de223b6ae472869/network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/blog_authors_intros.html#L11 )can be reviewed to confirm profile renditions {% image_url author.image "fill-100x100" %}
  * blog_authors_intros.html template is reused in different pages, making sure renditions also apply in: spotlight_posts.html, news_you_can_use.html, and blog_card.html
  * Another way to quickly test images are rendered by the browser with correct transformations is right-clicking the image > Inspect. Take a look at the source code element highlighted. (See image attached)

!image-20240803-203841.png|width=1270,height=472,alt="image-20240803-203841.png"!

Other observations:Also for Blog featured images rendition is applied on them, reducing the size from it original from 4000x1350 to 1200x628. 

Docs:Wagtail images ( https://docs.wagtail.org/en/v6.2/topics/images.html )
