### ISSUE TITLE
[RH] Show only month and year for the publication date

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8808]
# Description
During demo of the Research Hub, kaodro mentioned that it would be desirable to only show the year and month instead of the exact date of the `ResearchDetailPage.origininal_pulication_date`. This would be for all places that the date is shown in the Research Hub. 

See also https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#date.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-288)

**Comment by bheasman** [comment]
@cdanfon - be good to get an idea of size on this one if poss please?

**Comment by tbrlpld** [comment]
@bheasman This is a small one. We only need to change the templates of the different locations. 

One question I have is how this might affect internationalisation. @TheoChevalier are dates in the form of "Month Year" (e.g. `Feb 2020`) acceptable for all locales we support?

**Comment by TheoChevalier** [comment]
@tbrlpld Yup, should work well, the only thing I would pay attention to is using a capitalized format (`M` of `F` from the Django docs)

Example in French, the month is not capitalized when the day is specified, but becomes capitalized when it’s not specified:
`3 février 2022`
`Février 2022`

**Comment by cdanfon** [comment]
Thanks guys! 

@bheasman we can look at adding this to a sprint once the PNI work has been completed
