### ISSUE TITLE
[RH] Add link from landing page to author index

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8809]
# Description

Currently, there is not really any way to reach the author index page (except through the breadcrumbs on the author detail page). 

To make it easier to find the author index page, we should add a link to it on the landing page. E.g. change the "browse all" button (which links to the library) to primary style and use the secondary style for a link to the author index page. 

This might need input/feedback from design. 

This link is particularly important until we make a decision about the "featured authors" section that is still under discussion #8320.

**Comment by kristinashu** [comment]
Added the `RCC` label to this since it might become relevant. cc @beccaklam

**Comment by beccaklam** [comment]
If we implement #8320 then we can probably close this ticket?

**Comment by tbrlpld** [comment]
Yup. 

Closing in favor of #8320
