### ISSUE TITLE
Allow manual curation of featured research on landing page

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8810]
# Description
During demo of the Research Hub kaodro mentioned that it might be good to be able to manually curate the research listed on the landing page.

Currently the landing page shows the last three (by "original publication date") research detail pages. 

We might need to gather more feedback after the team had time to use the Research Hub.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-289)

**Comment by kristinashu** [comment]
RCC would also like to have this feature
