### ISSUE TITLE
[RH] Add concept of teams

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8811]
# Description

During demo of the Research Hub @kaodro mentioned that we there might be need to implement the concept of teams in the Research Hub. Currently, we have proposed to create "profiles" for teams and add the team as an author to a research detail page. 

This still needs discussion how teams should be used and how they would be displayed in the Research Hub.

**Comment by tbrlpld** [comment]
It seems questionable if this is still desired. Profiles have be used for teams and other orgs.

**Comment by kristinashu** [comment]
I think using the team's name as an author is working.
