### ISSUE TITLE
Allow alphabetical sorting of localized querysets (e.g. filter options and author index)

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8813]
# Description

It is currently not possible to combine a localized queryset with custom sorting. 

Localizing the queryset means that for each item, we check if there is a version of it in the active locale. If it exists, then we use that one. 
If not, then we fallback to the items equivalent in the default locale.

In the end, there is only one version of each item, either from the current or the default locale. 
Items are considered the same when they have the same `translation_key`.

The current solution to localize a queryset (`wagtailpages.utils.localize_queryset`) is relying on ordering of items based on them belonging to the current locale or not (the all items except for the first are removed from the query set, which results in the behaviour described above - use item of current locale if possible, fallback to default locale).

## Why do we need to localize querysets? 

We are using custom models that are translatable, e.g. research topics, regions and authors / profiles. 
While these can be translated, there is no guarantee that a translated version of that model exists. 
This becomes important on pages that list the any models of such nature (e.g. the author index or the libary page). 
We needs pages to still list all the options (e.g. all authors) even if not all instances of that model have been translated. 
That is what the localization of the queryset does. 

An alternative solution to what is implemented in `wagtailpages.utils.localize_queryset` would be to just get all the instances of a model in the default locale and then for each instance get the localized version (this is a feature in Wagtail with the `.localized` property).

But, this is the classical 1 + n database query problem. 
This will become a performance burden really fast, especially on pages that list multiple localized querysets (like on the library page). 

## What could be better?

The current implementation in `wagtailpages.utils.localize_queryset` allows to retrieve the localized queryset of any size with 3 queries, 2 or which are for the active and the default locale. 

But, the problem is that, as described above, this solution relies on ordering and distinctness of the results. This prevents the queryset to be ordered otherwise. 

Goal of this ticket is to find a solution that allows a localized queryset to have a custom ordering while still retrieving the data with less than 1 + n queries. 

## What are possible approaches? 

I believe there should be a possible solution by combining two querysets. 
The first one should be retrieving all instances of a given model for the active locale. 
The second would be all instances of the default locale, but exclude those that have a `translation_key` that is present in the first queryset. 

It should be possible to combine the querysets into a single queryset using the [`.union` method](https://docs.djangoproject.com/en/4.0/ref/models/querysets/#union)

# Acceptance criteria

- [x] Filter options on the library page are listed alphabetically.
- [x] Authors on the author index page are listed alphabetically.

**Comment by jhonatan-lopes** [comment]
After fixing #10395, `localize_queryset` now has two distinct queries (one for the active locale) and one for the fallback items that are not available in the active locale (only in the default locale). These are put together [using the OR (`|`) operator](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/3e6ac2a2d0d58fd9083200147ed868c65ea42bf6/network-api/networkapi/wagtailpages/utils.py#L371) (i.e. `queryset | translated_instances`).

While doing this work, I tried using `.union` to get those two querysets together and while it works in this function, it raises some issues downstream as `.union` querysets need to be final, i.e. we cannot apply `filter`, `exclude` etc. on them.

I would suggest trying to order the queryset as it is (without using union).
