### ISSUE TITLE
SEO | Put "Mozilla Foundation" at the end of the `<title>`

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#8839]
Based on #8839 

Update the title in the base template to add "Mozilla Foundation" to the end of the title rather than the beginning. 

Make sure this is the case for all `<title>` elements in the repo.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-853)

**Comment by simont-cr** [comment]
Closing as obsolete issue as part of 2024 Clean-up.
