### ISSUE TITLE
Landing page - Some links are always redirecting to English

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#8932]
Something I couldn’t tackle in #8928 for the Research Hub, currently some links are redirecting to the /en/ version of the site even though you’re on a different locale.

For example, when visiting the French version of the page (https://foundation.mozilla.org/fr/research/), 3 links are redirecting to the English version:

<img width="1284" alt="Capture d’écran 2022-06-09 à 16 57 11" src="https://user-images.githubusercontent.com/1294206/172878773-9a2acdd5-0e42-4888-8679-3b54d0cae948.png">

I think this can be solved using the `localizedroutablepageurl` tag in https://github.com/mozilla/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/templatetags/localization.py#L75

Here’s a code example where it’s been used to fix a similar issue https://github.com/mozilla/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/blog_card.html#L20

## Acceptance criteria

- [ ] As a visitor, when I visit the library page in non-default locale (e.g. "french" -> https://foundation.mozilla.org/fr/research/), I can follow all links on the page (in particular the ones to the library page) and remain in the same locale (i.e. I see `/fr/` in the URL).

**Comment by tbrlpld** [comment]
@TheoChevalier This is ready for QA on staging now: https://foundation.mofostaging.net/fr/research/

**Comment by danielfmiranda** [comment]
Hi @tbrlpld thanks for taking this work on, I gave it a test and it looks good to go! Moving to "ready for prod"

**Comment by TheoChevalier** [comment]
Sorry, only seeing this now — just wanted to say thank you for fixing this, and confirm it looks good to me as well!
