### ISSUE TITLE
Componentize blog card topics

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#8980]
![](https://user-images.githubusercontent.com/18314510/173961789-297a74d0-6dc3-4d20-98ad-b52dc7add45d.png)

I noticed that the topic section for things such as the new featured video post and blog cards have pretty much the exact same format to display the topics, I think we can probably turn this into a component and have them share the template.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-297)

**Comment by cdanfon** [comment]
Hey @danielfmiranda Is this new issue part of the Blog Updates EPIC or just something we can re-use from the work we're doing for that epic?
