### ISSUE TITLE
Detail page - Add a page chooser option to Research Links

### ISSUE THREAD

**Issue by bheasman** [MozillaFoundation/foundation.mozilla.org#9033]
### Describe the feature request
As there will be a lot of internal content that is being surfaced in the research hub, it'd be good to add a page chooser option to the 'Research links' section of the research detail page. This will then give editors the option of adding a file, an external URL or choosing an existing page. The key benefit of this is that if the internal page moves within the page tree, the links will remain intact.

### Acceptance Criteria

- [x] As an editor, I can use a page chooser to select an internal page as a research link

**Comment by tbrlpld** [comment]
@kristinashu @beccaklam  Would  either of you mind doing the QA on this one? It would be greatly appreciated 🙏

**Comment by kristinashu** [comment]
The page chooser is working well!
