### ISSUE TITLE
[PNI] - Editorial Content Index Page - Filter by Content category

### ISSUE THREAD

**Issue by fessehaye** [MozillaFoundation/foundation.mozilla.org#9107]
https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=2303%3A126762

Content Filter Types names are All, Articles, Advice, Petition, and In the Press (which is visually separated and will not show up in "All")

Dev Tasks:

* [ ] Style Filter Component
* [ ] Add JS to filter articles by tag

Acceptance Criteria:

* [ ] Should be able to filter PNI articles/campaigns by page type or tag

![Article Index Page - All](https://user-images.githubusercontent.com/74557207/187467012-0fbc62c9-3d68-4096-85b7-269806d02079.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-300)

**Comment by tbrlpld** [comment]
@fessehaye Are you sure you want to do this in JS? We have very similar functionality already on the backend and the index page from which we are going to build the index page.

**Comment by cdanfon** [comment]
@nancyt1 to update design, @fessehaye to update the description

**Comment by tbrlpld** [comment]
Functionality is outlined in the dev notes: https://docs.google.com/document/d/12AmWzlOVll6hHBPL-lu3E4rAtOM9vX6wgO6U8uOxCxk/edit#heading=h.qedu6bgm180y

**Comment by beccaklam** [comment]
Nancy has updated the design. @fessehaye as Tibor mentioned in the comment above we have notes on the filtering functionality in the dev notes (see under 'Content index page'). Copying part of the notes here:

> - "All articles" lists all non-categorized articles, all advice-category (or otherwise categorized) articles and all campaign pages. It should NOT show the news updates!
> - Filter index by content category, there already is similar functionality on the index page. Show a filtering label for each content category (in the beginning there will only be one) that filters the list of entries to only those that belong to the content category. 
> - Filter index to show only campaign pages (this can be done based on the page type)
> - Show list news updates (these were not shown before)

**Comment by tbrlpld** [comment]
Removing from this sprint since it's p3.
