### ISSUE TITLE
[Blog] Author slug contains `-none` instead of id

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#9122]
# Description

Whenever a `Profile` is created (through Wagtail or the `inv new-db` script) the profiles have a slug ending with `-none` instead of their id. 

This should be because of the `save` method override. When the save method runs the first time, the profile does not have an id yet. This leads to `None` being used in the string conversion. 

Subsequent saves of the same profile will fix this issues, because the profile will have an id then. 

The logic needs to be changed so that the slug contains the id and not `none` even on the first save. My hunch would be to use `if self.id: self.slug = ...` in the save method override and use the `post_save` signal to set the slug only when it does not yet exist `if self.id and not self.slug: self.slug ...`.

Since we need the slug in two places, it might be good to just extract that into a method `get_slug` (which does something like `return self.slug or sluggify(...)`

See also: https://docs.djangoproject.com/en/4.0/ref/models/instances/#what-happens-when-you-save

# Acceptance criteria

- [ ] Whenever a new profile is saved, it's slug is set to the sluggified name of the profile and it's id.
- [ ] The slug uses the id even on the first save instead of `-none`.

**Comment by jhonatan-lopes** [comment]
This has been fixed already.
