### ISSUE TITLE
Tweet Block / Embedded Tweets

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#9232]
### Describe the feature request
Users are requesting the ability to embed a tweet on blog pages. 

More details to follow

**Comment by cdanfon** [comment]
[Discussion](https://torchbox.slack.com/archives/C98GW3P7X/p1659615409168239) on the #mofo-wagtail channel

**Comment by kristinashu** [comment]
Closing this as "won't do" - particularly given the state of twitter.
