### ISSUE TITLE
Detail page - Update which fields are required

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#9266]
### Describe the bug
I need to create a detail page before I can create a Publication under it but the Landing page requires a link the Publication in order to create it, which I can't create until I have the Landing page.

### To Reproduce
1. Go to add a new Child page new in the Research Library https://foundation.mofostaging.net/cms/pages/18267/
2. Fill out the info that you can (no link to the Publication because it doesn't exist yet)
3. Publish the page
4. Can't Publish 

### Expected behavior
I understand that these fields should be required but unfortunately they shouldn't be required if it isn't possible.

### Screen cap
<img width="1176" alt="Screen Shot 2022-08-24 at 3 10 01 PM" src="https://user-images.githubusercontent.com/1068783/186713141-7ea736a9-b7ec-40a7-ad20-8456c8b44f9b.png">

**Comment by tbrlpld** [comment]
@kristinashu This is ready for testing on staging: https://foundation.mofostaging.net/cms/pages/add/wagtailpages/researchdetailpage/18267/

**Comment by kristinashu** [comment]
Looks good, thank you!
