### ISSUE TITLE
DFL 2022 | Async loading of tab content

### ISSUE THREAD

**Issue by kevinhowbrook** [MozillaFoundation/foundation.mozilla.org#9391]
### Describe the feature request

**Banner Page Navigation** 
Async loading of the tab content without page refresh (e.g. with HTMX). The point of the async content loading is to get around the need to always scroll past the top banner section (which is the same across the banner pages nested below a banner page). 

### Screenshots / mock-ups

N/A

### Additional context

This can be implemented using this https://pypi.org/project/django-htmx/

---

**Dev Tasks:** 
* [ ] Re-configure tab loading in template to be asynchronous with django htmx
* [ ] Ensure that and anchor tag `#` is applied to the URL when a tab is clicked

**Acceptance Criteria:**
- [ ] Design to stay the same
- [ ] As a user, when I click a banner page tab the page does not reload
- [ ] As a user I can bookmark or link to a banner page tab using and anchor `#`

**Comment by cdanfon** [comment]
@kevinhowbrook Can we break this ticket down into smaller tasks?

**Comment by kevinhowbrook** [comment]
@cdanfon 
Yea I think that's a good idea.
The following breakdown would make sense:
- Install django htmx (which would include the spike element of this to ensure it will do what we want)
- Confiugre banner page type templates to use HTMX for tab loading
- Configure/ensure link bookmarking with the use of `#` anchor tags in the URL once tabs are clicked

**Comment by cdanfon** [comment]
@kevinhowbrook Nice one, would you like to add the tasks to the ticket as 'subitems' or split it into 3 new tickets?

**Comment by cdanfon** [comment]
@kevinhowbrook @tbrlpld FE or BE?

**Comment by tbrlpld** [comment]
@cdanfon Both

**Comment by simont-cr** [comment]
Several tickets have already been created, with some of them resolved, based on the same initial request. Closing this ticket as it seems no other work needs to be tracked here.
