### ISSUE TITLE
PNI - Refactor primary_active_nav for PNI Usage

### ISSUE THREAD

**Issue by fessehaye** [MozillaFoundation/foundation.mozilla.org#9420]
Subpages do not get proper underline squiggle on PNI. This is a good opportunity to rewrite the `primary_active_nav.py` so we can use it for `buyersguide\pni_nav_links.html`

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-301)

**Comment by data-sync-user** [comment]
➤ Rob DiVincenzo commented:

Resolved via TP1-192 ( https://mozilla-hub.atlassian.net/browse/TP1-192 )
