### ISSUE TITLE
[PNI] Preserve product sort order between full page reload

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#9441]
> > I also noticed that when navigating between pages with a full page reload (e.g. from category page to homepage) then the sort order is not preserved. Have you considered storing it in local storage?
> 
> Tibor, I tested this and could not replicate this issue even after reloading. Please make a separate ticket with repro for this issue if this still happens to you.

@fessehaye Just double checking we are talking about the same thing. When navigating as in the following video you still have "alphabetical" sort when you are back on the homepage? 

https://user-images.githubusercontent.com/24797493/193091850-c2f2386c-3df8-44ea-a6b8-0db53439c7cd.mov

_Originally posted by @tbrlpld in https://github.com/mozilla/foundation.mozilla.org/issues/9416#issuecomment-1262547700_
      

*** 

@tbrlpld 
I understand, this also does not preserve the search text or privacy ding as well with this repro since the logo link will always refresh the page. I think it was discussed last year of how the history management works when we click on the home logo or any link that causes a refresh/reload.

Since this is outside of our history management(navigate forward/backward, refreshing on the same page), I would consider this something we would discuss with the designers and probably a revisit to how we implement browser history. This is a good catch but at the moment, not worth the time sink. If we did the localstorage route we would have to do the same with privacy ding and search text. I am against this at the moment because we have our PNI frontend tests disabled. So any larger rewrite for the search-filter related files, I would encourage after our tests get fixed.

_Originally posted by @fessehaye in https://github.com/mozilla/foundation.mozilla.org/issues/9416#issuecomment-1262760194_
      

***

**Comment by simont-cr** [comment]
Closing as obsolete issue as part of 2024 Clean-up.
