### ISSUE TITLE
Refactor invalid `disabled` attribute on `a` elements to class

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#9484]
# Description

The [`disabled` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled) is only valid on form elements such as `<button>` and `<input>`. [We are using it on `<a>` elements](https://foundation.mofostaging.net/en/style-guide/#buttons), on which it is not officially supported , for styling purposes. Mainly, we are using it to display button style links as grayed out.  

We should refactor this to valid HTML by using a `disabled` class for styling of `<a>` elements. 

[`pointer-events: none;`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) is probably going to be useful here. 

References:
* https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled
* [`pointer-events: none;`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events)

# Dev tasks

- [ ] Create a class that applies the styles for disabled buttons but with a class instead of the `disabled` attribute.
- [ ] Replace all use cases of the `disabled` attribute with the class.
- [ ] Ensure typical link events (like hover and click) have not effect on disabled links.

# Acceptance criteria

- [ ] As a user, I can see no difference between a disabled button element and a link that is disabled with a class.
- [ ] As a user, when hovering a disabled link, the cursor does not turn into a pointer (the little hand).
- [ ] As a user, when clicking on a disabled link, I am **not** navigate to a new page.

**Comment by mtdenton** [comment]
Linked to #9875
