### ISSUE TITLE
UI backend improvements - Localize editor experience

### ISSUE THREAD

**Issue by cdanfon** [MozillaFoundation/foundation.mozilla.org#9520]
Having used the back end of the foundation site for a while doing testing I've noticed a couple of things affecting Localize that make the editor experience quite tricky.

1) Snippets don't define the locale. In the below screenshot you can see 'Mozfest' as a CTA used for different locales, but there's not a way of easily identify the language unless opening it. This makes the adding snippets to different parts of the site (even if using the search function) fairly time-consuming.

![Screenshot 2022-10-21 at 12.00.53.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/fe119fc8-54b8-4c1d-b860-7c0855f8e086)

Although I'm not sure if this is happening because these snippets have been added manually in different languages instead of using localize.

Something similar happens when using the search bar in the back end to add articles to a page for example. The search bar won't automatically filter by locale (neither by relevant path), making the available choice immense:

![Screenshot 2022-10-21 at 12.08.23.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/10f5a727-a79b-4e2d-846c-dc3992c39181)

**Comment by tbrlpld** [comment]
Valid points @cdanfon. Have you checked the Wagtail release notes for 3 and 4 if this might be improved in them? Otherwise, these are going to require heave overrides. It might also be helpful to provide this feedback to the Wagtail team.
