### ISSUE TITLE
[PNI QA] Product Reviews page loads too low on the screen

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#9552]
Currently when one clicks "Product Reviews" in the menu it jumps to the part of the page right above the privacy ding and 'sort by creepiness' filter:
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/67de65f9-b5ca-45e0-9986-f909310725c6)

The expected behaviour is that the page would load at the top of the page, including the navigation:
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/9b30d57e-9b09-43e3-911f-af9db7b69633)

**Comment by tbrlpld** [comment]
The title and the description don't seem to match @beccaklam

**Comment by tbrlpld** [comment]
I feel like I have raised that before somewhere... 🤔
