### ISSUE TITLE
Improve CSS build in development

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#9556]
It takes pretty long after starting the stack with `docker compose up` until the styles are working properly. There might be a bunch of reasons, but I think we should definitely not run css optimization while in local dev. That's something for deployments, but not something we should be doing for local development. 

```
...
foundationmozillaorg-watch-static-files-1  | > @ build:sass /app
foundationmozillaorg-watch-static-files-1  | > run-s build:sass:clean && run-p build:sass:main build:sass:bg && run-s optimize:css
...
```

**Comment by tbrlpld** [comment]
When the frontend container starts, it runs `npm run watch`.

`"watch": "wait-on [http://backend:8000/cms](http://backend:8000/cms) && run-s build:clean && run-p build:js:dev build:common watch:**"`

- `wait-on` - Waits till the backend container can be reached
- `build:clean`
    - `shx rm -rf network-api/networkapi/frontend && shx mkdir -p network-api/networkapi/frontend/_js` — Deletes a directory and creates a child directory below the previously deleted one
- `build:js:dev`
    - `node esbuild.config.js -- --node-env development` — Runs the esbuild build script in development mode. In development mode, it enters into a watch mode in the end. ESBuild watch mode uses polling.
- `build:common`
    - `run-p build:images build:sass build:tailwind build:contribute` - Runs a couple commands in parallel. `build:sass` is running PostCSS which can build Tailwind and also triggers the CSS optimizations which are running on the output directory, but this is not waiting for the Tailwind CLI to finish.
        - `build:images`
            - `shx rm -rf network-api/networkapi/frontend/_images && shx cp -r source/images network-api/networkapi/frontend/_images` — Deletes a directory of images and then copies back a directory of images from the source directory to that location.
        - `build:sass`
            - `run-s build:sass:clean && run-p build:sass:main build:sass:bg && run-s optimize:css`
                - `build:sass:clean`
                    - `shx mkdir -p network-api/networkapi/frontend/_css` — Creates the css directory? That is weird. Clean seems like it would delete something.
                - `build:sass:main`
                    - `sass source/sass/main.scss network-api/networkapi/frontend/_css/main.compiled.css` — Builds the main css file into the previously created directory
                - `build:sass:bg`
                    - `sass source/sass/buyers-guide/bg-main.scss network-api/networkapi/frontend/_css/buyers-guide.compiled.css` — Builds the buyer’s guide css file into the previously created directory
                - `optimize:css`
                    - `run-s optimize:css:*` — Runs all the optimize css subscripts, but not subsubscripts
                        - `optimize:css:run`
                            - `postcss network-api/networkapi/frontend/_css/*.css --dir network-api/networkapi/frontend/_css/temp` — Runs postcss over the previously build css into a temp directory
                        - `optimize:css:copy`
                            - `shx mv network-api/networkapi/frontend/_css/temp/* network-api/networkapi/frontend/_css` — Move the processed files from the temp directory to the css directory where they came from.
                        - `optimize:css:clean`
                            - `shx rm -rf network-api/networkapi/frontend/_css/temp` — Delete the temp directory
        - `build:tailwind`
            - `tailwindcss -i source/postcss/tailwind.css -o network-api/networkapi/frontend/_css/tailwind.compiled.css` — Builds Tailwind from the basically empty `tailwind.css` file into the CSS output directory. This is running in parallel with the `build:sass`  which also triggers the `optimize:css` which runs on that CSS output directory.
        - `build:contribute`
- `watch:**`
    - `watch:images`
        - `chokidar \"source/images/**/*\" -c \"npm run build:images\"` — when ever the images directory changes, it runs the image build
            - `build:images`
                - `shx rm -rf network-api/networkapi/frontend/_images && shx cp -r source/images network-api/networkapi/frontend/_images` — Copies the images from the source directory to the output
    - `watch:sass`
        - `chokidar \"source//*.scss\" **\"**/*.html\" -c \"npm run build:sass\"` — Runs the SASS build when ever a SCSS or HTML file changes.
            - `build:sass`
                - `run-s build:sass:clean && run-p build:sass:main build:sass:bg && run-s optimize:css`
                    - … same as above

**Comment by tbrlpld** [comment]
Some other notes: 

- Should we split build and clean steps / scripts. Maybe have a shorthand command to clean and then build? Or maybe it’s not that bad that the build script automatically cleans, but the individual build commands should be reachable separately. I think the clean scripts should also be separately and run during the clean step.

- PostCSS uses the Tailwind plugin  while we also run the Tailwind CLI. Do we need this?
    - Turns out we are running the Tailwind CLI in dev to make the utility classes available faster.
    - So this seems to be already a measure to combat the long build times.
- Searching for `@apply` I find that a bunch of `scss` files are using that Tailwind directive. That is weird. We should probably be splitting this out and clearly separate that stuff. This seems to be only in place because of the transition from SASS to Tailwind and when some classes are removed they are being replaced with `@apply` rules. I wonder if it would be more effective to work on the SASS to Tailwind transition on a HTML file basis, rather than an SCSS file basis. That would avoid this mixing too. And it should help working toward splitting the HTML templates into reusable fragments.
- I guess this is the reason we need to run PostCSS with the Tailwind plugin, so that all these `@apply` rules are expanded…
- So to get a real watch mode going we need SASS to rebuild on HTML changes, because SASS is now building the css files with the Tailwind classes.
- It seems like the build is running multiple times when the container first comes up.
- We are not using the native SASS watch mode and not the native PostCSS watch mode. We just rebuild the whole thing when ever an SCSS file changes. I wonder if this could be faster if we used the proper watch modes of the build tools

**Comment by fessehaye** [comment]
Thanks for documenting this @tbrlpld !

**Comment by mmmavis** [comment]
Related to https://github.com/MozillaFoundation/foundation.mozilla.org/issues/9556

**Comment by mmmavis** [comment]
Not sure if I will be able to finish this task completely by the end of the sprint. But I should be able to get some improvement in.

**Comment by mmmavis** [comment]
PR #10809 has been merged. I think we can close this ticket now.

### Key changes:

- Removed `optimize:css:**` scripts as they were buggy and problematic
- Added two new scripts
  - `postcss:build` (for prod/staging): process compiled CSS filed using PostCSS
  - and `postcss:watch` (for dev): basically is like `postcss:build` but with the watch and rebuild ability
- Removed `tailwind` and `tailwind:watch` scripts because their jobs are now covered by the new `postcss:**` scripts
- Updated `watch` script to make sure tasks are run in the correct order

Note that I'm using utilizing PostCSS (with its Tailwind plugin)'s watch mode instead of SASS's [because](https://sass-lang.com/documentation/cli/dart-sass/#watch)
> Sass watches only the directories that you pass as-is on the command line, parent directories of filenames you pass on the command line, and load paths. It does not watch additional directories based on a file’s @import/@use/ @forward rules.
