### ISSUE TITLE
PNI Article index body text preview cut off

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#9569]
https://foundation.mozilla.org/en/privacynotincluded/articles/

<img width="300" src="https://user-images.githubusercontent.com/24797493/198412392-03772e39-c96c-4fbd-928a-34180bac5844.jpeg"> 

### Smartphone (please complete the following information):
 - Device: iPhone6 or iPhone14 Pro
 - Browser: Safari
 - Version: 16

**Comment by mmmavis** [comment]
@tbrlpld can you verify if this is still occurring? It looks fine on my phone.

**Comment by tbrlpld** [comment]
Yes I can still see this. 

<img width="300" src="https://user-images.githubusercontent.com/24797493/219815155-79864c1a-becb-49f5-99d3-e2c7233ef64c.PNG">

<img width="300" src="https://user-images.githubusercontent.com/24797493/219815167-e40ada4c-7c8e-4895-8f23-738d8dedaed6.PNG">

**Comment by simont-cr** [comment]
Just took a look on my phone and the issue seems to be resolved already.
