### ISSUE TITLE
PNI Tool Tip Adjustments

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#9575]
Making this ticket to continue a conversation around the PNI tool tip from ticket #9524:
- Should we adjust the tool tip wording "privacy not included in this product" for the privacy ding filter
- Can the tool tip be activated also when the cursor hovers over any part of the filter (not just the words "privacy not included")

**Comment by tbrlpld** [comment]
> Can the tool tip be activated also when the cursor hovers over any part of the filter (not just the words "privacy not included")

@beccaklam Yes, that is possible.
