### ISSUE TITLE
PULSE | CSP Updates for Google Tag Manager

### ISSUE THREAD

**Issue by cdanfon** [MozillaFoundation/foundation.mozilla.org#9587]
### Overview
Content Security Policies are a common security device to prevent unintended content from being loaded into a website. Coincidentally, the whole purpose of Google Tag Manager is to load assets into a website.

In order to use Google Tag Manager in sites with a CSP in place, we need to make some slight changes to the GTM code added to sites, as well as add a few lines to the site security policy.

### Dev tasks
* [ ] Update GTM code following instructions in [this](https://docs.google.com/document/d/1IbfNfn0HUoJ94qDTWiwZjxWmy8ZzisyilGtxOhR5xNc/edit
) document
* [ ] Update Content Security Policy following instructions in this document
* [ ] Updates to be made both in staging and prod sites

**Cointainer ID**

Pulse - GTM-KHLX47C

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-305)

**Comment by cdanfon** [comment]
Hey @mtdenton One for the support duty, we would need you (eng team) to make CSP updates for Pulse as part of the work that TBX is doing on GA4.

I'm aware Daniel has been dealing with these kind of request in the past but he's not back until Wednesday - as we haven't got anything on his sprint at the moment, could he pick this up as one of the first things he does please?

**Comment by mmmavis** [comment]
It seems like builds on Pulse staging has been broken at least since March 24. I'm gonna investigate why and fix the issues. Until then, we won't be able to push changes live for Pulse.

![image.png](https://images.zenhubusercontent.com/568fffb1638e718c995fe96d/db30baed-672b-4f00-9399-3aa117b25ee5)

**Comment by cdanfon** [comment]
Thanks for the heads up @mmmavis and thanks for raising the builds issue and jumping straight into it! Is great to have you back in the team :)

**Comment by cdanfon** [comment]
We've decided that @mmmavis will put together a google doc with the next steps/options. But is not something we will be sorting asap.

This means Pulse GA4 tracking won't work until the CSP issue is fixed on Pulse

@bheasman @kristinashu

**Comment by mmmavis** [comment]
Created this Google Doc: https://docs.google.com/document/d/1QKrysAt-HVInh46P3VZGSUU5DJlVltiEYLEvN7_tIRk/edit#

I will revert changes I landed in [this PR](https://github.com/mozilla/network-pulse/pull/1661) as it won't work properly until we decide what the next step should be (see Google Doc for details).

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Tyler Denton We have had this ticket for a while now and while it was included as part of our P2 for this year, I don’t see this becoming a priority still. Do you feel that might change (we should keep) or should we abandon?

**Comment by data-sync-user** [comment]
➤ Tyler Denton commented:

Simon Acosta Torres Let’s scrap this for now, Pulse may have some changes coming down the pipe. Thanks!
