### ISSUE TITLE
Refactor `primary_heroguts` template

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#9605]
The [primary heroguts template (`templates/wagtailpages/fragments/primary_heroguts.html`)](https://github.com/mozilla/foundation.mozilla.org/blob/c3c5eeeced094e6a94b27e6d580631b25378d76a/network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/primary_heroguts.html) is used by 

* `wagtailpages/homepage.html`
* `wagtailpages/primary_page.html`
* `wagtailpages/bannered_campaign_page.html`

But all there are bunch of if statements to check if its actually used in the homepage. The remaining code that is shared between the not-hompage cases and the homepage. I don't think this still warrants being in the same template, given the complexity this has created in the template. 

We should just create two separate template for the different use cases. If there are sub sections that are shared, split those into their own fragments and include them.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-307)

**Comment by Ankitchaudharyy** [comment]
Can you assign this issue to me? I can work on this.
