### ISSUE TITLE
[PNI QA] Clearing search on homepage leaves user with no results - Firefox and Chrome mobile on iOS

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#9607]
# Description
To replicate:

1. Open https://foundation.mofostaging.net/en/privacynotincluded/ 
1. Click the magnifying glass to begin a search
1. Type in something to search
1. Hit return
1. After search results have appeared, clear the search by clicking the "x" icon
1. See bug (no results and no category selected even if "All Reviews" was previously selected prior to running the search)

Note: This bug does not seem to appear on Firefox mobile.

![](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/cd2aa02b-6ea2-4bb1-af25-07f8d0ec5dac)

# Expected behavior / acceptance criteria
* [ ] As a site visitor on a mobile size Firefox or Chrome browser, I am able to visit the PNI homepage and use the search in the menu to filter the number of items displayed and when I clear the search with the little "x" button all results appear again. 

# Dev notes
* It is curious that the issue only occurs on mobile. This may be related to the fact the mobile and desktop search bar are implemented with independent templates and that the JS also contains some duplication. 
* mtdenton Is working on getting Browserstack to allow dev testing with the right device.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-308)

**Comment by kristinashu** [comment]
I was able to reproduce this on my desktop FF at a narrow browser width

**Comment by tbrlpld** [comment]
@beccaklam @kristinashu Could you provide a screen grab? I am not able to reproduce this. I have tried iOS directly as well as small viewport on desktop Firefox and Chrome.

**Comment by tbrlpld** [comment]
What I do experience on iOS though is that the little "x" button does nothing unless the cursor if in the input field. Once that is the case it clears the field and removes the search filter.

**Comment by kristinashu** [comment]
[Here's a recording of the bug](https://www.loom.com/share/24334348aa2e4dbf9f0f9c5217febe07) on my desktop however in trying to get the recording the issue wasn't happening consistently. I did it several times and sometimes it would work as expected and sometimes I would see the bug. I don't think I'm doing anything differently each time!?

**Comment by tbrlpld** [comment]
Weird. Thnanks @kristinashu. I have tried several times but it's still not happening for me. Very odd 🤔

**Comment by cdanfon** [comment]
This is a stretch goal for Simon this sprint

**Comment by fessehaye** [comment]
Hey! I have got this once in like 15 attempts and even then there weren't any errors on the console that gave it away. There is not really enough for me to make a fix on this problem so maybe this should be removed from the sprint or given lower priority? @cdanfon @beccaklam

**Comment by beccaklam** [comment]
@fessehaye @cdanfon That's fine with me!

**Comment by cdanfon** [comment]
Moving this to the backlog as currently is not easy to reproduce

**Comment by cdanfon** [comment]
Closing as can't be reproduced

**Comment by cdanfon** [comment]
Claudia to test this on her iPhone and see if can be reproduced

**Comment by sabrinang** [comment]
@mmmavis Did some testing on my phone and browsers

**Device:** Pixel 7
**Android Version:** 13

**Chrome** 109.0.5414.85
https://user-images.githubusercontent.com/2492510/214447905-caa2394a-11cd-4bac-82ac-9cf7399e252f.mp4
(no results after clearing)

**DuckDuckGo** 5.146.0
https://user-images.githubusercontent.com/2492510/214447951-f90c73d7-0822-4b30-9f0b-4a52afd0762d.mp4
(no results after clearing)

**Firefox Focus** 109.1.1
https://user-images.githubusercontent.com/2492510/214447998-e650a7f6-eb8d-4927-902c-59ae41ea88d1.mp4

**Firefox Browser** 109.1.1
https://user-images.githubusercontent.com/2492510/214448060-992b67e8-5e50-472c-8d55-86161964ef4d.mp4

**Comment by mmmavis** [comment]
I found a few issues as I dived into the code. However, I wasn't able to pin point what exactly is causing the bug in this ticket. Complication partly comes from many functions being called multiple times and likely unintentionally. For example, `sortProductCards` is called twice on page load, one time for search, and three times when user clicks the 'x' icon to clear the keywords. This is just one example. We might want to put a hold on this ticket as I think a refactor is needed in order to solve the root problem.

**Comment by mmmavis** [comment]
I'm moving this back to the backlog.

I spent more time last week on this ticket. Because this bug is getting harder and harder to reproduce + there are multiple issues  indirectly contribute to the bug. I'm worried there's no quick fix for this ticket. Moving this back to backlog as it has eaten up too much of the dev's time to find "the solution". This should be fixed as we clean up the codebase.

**Comment by data-sync-user** [comment]
➤ Mavis Ou commented:

Just tested on iOS Chrome and Firefox. This bug is no longer existed! Yay!
