### ISSUE TITLE
[PNI] Squiggly line in nav bars are too pointy/look cut off

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#9610]
The squiggly line underlining selected items in all nav bars looks too "pointy" and upon closer inspection it looks like it might be partially cut off:

![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/e2a4d806-b80f-4962-9c83-92126181776f)

The squiggle should look like this:
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/7e576884-cfc9-47da-8db9-dbcaff2dac7b)

**Comment by tbrlpld** [comment]
Custom underlines are quite the task: https://medium.design/crafting-link-underlines-on-medium-7c03a9274f9

**Comment by tbrlpld** [comment]
We are currently using normal CSS underline styling: https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style

**Comment by beccaklam** [comment]
Ahh I see, okay I'll take this back to the design team to discuss!

**Comment by beccaklam** [comment]
Hi @tbrlpld! Sorry for the delay. So after discussing with the design team, a quick fix we'd like to implement is minimizing the size of the underline from 2rem to 1.2rem. We will think about longer term solutions in https://github.com/MozillaFoundation/Design/issues/1116

**Comment by tbrlpld** [comment]
@beccaklam Which dimension are you talking about that you would like to reduce from 2rem to 1.2rem? The only dimension we can control is the thickness, which is currently 2px, which also dictates the height of the wave.

The issue on Safari might be caused by the missing support for the line thickness in the shorthand: https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration#browser_compatibility

**Comment by tbrlpld** [comment]
One thing to note, even when we fix the Safari issue, the underline style will vary, based on the Browser implementation

**Comment by beccaklam** [comment]
I think I'm talking about the text-decoration for :hover? But also whatever affects the selected state.
<img width="1512" alt="Screenshot 2022-12-01 at 1 31 38 PM" src="https://user-images.githubusercontent.com/20977376/205163617-c207c9f2-7c87-4aee-82ce-c888205e80c6.png">

**Comment by beccaklam** [comment]
> One thing to note, even when we fix the Safari issue, the underline style will vary, based on the Browser implementation

Variation is okay and expected as long as it's not too off from what's intended. Would it be hard to implement the Safari fix? I wouldn't say the underline is a high priority.

**Comment by mmmavis** [comment]
Apparently Safari doesn't recognize we combine everything text decoration related to just one CSS declaration `text-decoration: wavy #595cf3 2px underline`. If we split this into four individual declarations then the squiggly line will show up.

![image.png](https://images.zenhubusercontent.com/568fffb1638e718c995fe96d/bafd3ca8-50ee-400a-897f-915b4c3c24e4)

**Comment by mmmavis** [comment]
Sorry nvm. I read Becca's message wrong 😂  I accidentally read her message `I wouldn't say the underline is a high priority.` as `I would say the underline is a high priority.`
