### ISSUE TITLE
Document the use of emoji's on the banner page

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#9615]
We use emoji's on the banner page in the sub navigation to signify the status of these pages (e.g. 🙈 - login restricted, 🐣 - draft). We should document these in the "How do I Wagtail" guide, because it leads to confusion for editors. 

See https://mozilla.slack.com/archives/C98GW3P7X/p1667480230096119

**Comment by nox1134** [comment]
Hi @tbrlpld! I'd like to work on this issue. How do I get started?
Also, if there's any other helpful information that could be provided for solving this issue, please let me know.

**Comment by tbrlpld** [comment]
@nox1134 Thanks for the offer, but please refer to the README regarding contribution support. Thanks.
