### ISSUE TITLE
[PNI] Refactor PNI Category Call to Mixin

### ISSUE THREAD

**Issue by fessehaye** [MozillaFoundation/foundation.mozilla.org#9622]
```
language_code = get_language_from_request(request)
context['categories'] = get_categories_for_locale(language_code)
```

This snippet is repeated a few times on the buyerguide page models. Suggestion is to move this to a BuyersGuideMixin that can be applied to all PNI Page models and add tests for this.

**Comment by mtdenton** [comment]
@fessehaye can this be closed?

**Comment by simont-cr** [comment]
Closing ticket as no follow up was provided.
