### ISSUE TITLE
[PNI] Content category links should link to filtered editorial content index

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#9624]
We already display the content categories of articles as links, but these links go straight to the editorial content index page and don't apply any filtering. 

![Screen Shot 2022-11-04 at 17.22.30.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/e84669e8-5eb2-43ef-814b-10ebc9ccd882)

Of course this is only possible after the content index filtering is created.

**Comment by cdanfon** [comment]
This need to be re-checked once the functionality is in place
