### ISSUE TITLE
Set up `django-pattern-library` for easier template development

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#9665]
# Description

> The [django-pattern-library](https://pypi.org/project/django-pattern-library/) package automates the maintenance of UI pattern libraries or styleguides for Django projects, and allows developers to experiment with Django templates without having to create Django views and models.
> * Create reusable patterns by creating Django templates files as usual.
> * All patterns automatically show up in the pattern library’s interface.
> * Define data as YAML files for the templates to render with the relevant Django context.
> * Override Django templates tags as needed to mock the template’s dependencies.
> * Document your patterns with Markdown.

This allows us to decouple the development of frontend and backend. It supports us in keeping the templates structured and organized. It also serves as a library of existing template components, which should improve the reuse of templates.

Also:
> As we discussed in chapter 1, the benefits of pattern libraries are many:
> 
> They promote consistency and cohesion across the entire experience.
> They speed up your team’s workflow, saving time and money.
> They establish a more collaborative workflow between all disciplines involved in a project.
> They establish a shared vocabulary between everyone in an organization, including outside vendors.
> They provide helpful documentation to help educate stakeholders, colleagues, and even third parties.
> They make cross-browser/device, performance, and accessibility testing easier.
> They serve as a future-friendly foundation for teams to modify, extend, and improve on over time.
>  
— [Brad Frost, Atomic Design](https://atomicdesign.bradfrost.com/chapter-3/)

# Acceptance criteria

- [ ] Django pattern library is installed and configured in the project. 
- [ ] A couple of templates are added as examples to the pattern library. 
- [ ] The dev team had a small workshop to get introduced to working with the pattern library.

**Comment by victoriachan** [comment]
As discussed in meeting with @jhonatan-lopes and @cdanfon:

- Currently though there could be template files within each app, the definitive place for them should be in the `network-api/networkapi/templates` directory.
- I can move this or rename this to suit the django-pattern-library implementation. This is likely going to be a new app, e.g. `project_styleguide`.
- Note that there could still be ongoing dev that involves templates, I should make sure my branch is regularly updated or consider using a feature branch if more than one MR.
- django-pattern-library should not be used on production site. As the project only has one settings file and uses the same settings file for dev, it might need splitting up into a separate file for dev.

**Comment by cdanfon** [comment]
Hey @victoriachan any updates on this one please?

**Comment by victoriachan** [comment]
This is taking longer than I expected. I am currently adapting the templates for pattern library (e.g. add yaml files for them). I was hoping to just adapt one template as an example, and we can tackle the rest later or let the team handle it in due time.

However even for just the article page, there are a number of elements to fix, e.g. the 'get_page_authors' custom tag, and various includes, so it takes time. This is where I am at currently. I am adapting the article page and tackling these errors one by one.

**Comment by victoriachan** [comment]
I've added a draft [PR](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/10808) for this. There are still issues rendering the template, but the pattern library itself is installed here. This PR is backwards compatible and should not break existing functionalities.

**Comment by victoriachan** [comment]
I'm currently working on getting Pattern Librray to work for at least one template, so the team can have at least one reference of a working page. It should not affect existing website functionality and can be enabled only on local dev as required, and so could be safely merged in the main branch, and progressively enhanced in future.

**Comment by victoriachan** [comment]
Hi, I've updated the [PR](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/10808) with more changes. You should be able to code review it. 

The existing code should not have side effects on the usual workings of the website. The pattern library is only enabled when the debug is on, and when `PATTERN_LIBRARY_ENABLE=1` is set in the environment variable.

There is one issue I'm having, which I'm not sure if it's just cache. I seem to get duplicate links on the Pattern Library left hand nav. 

Also I haven't added documentation for this yet as I am not sure if you want to actively promote it yet. The template context still needs adding for most of the templates to make it useful.

**Comment by cdanfon** [comment]
@jhonatan-lopes FYI

**Comment by cdanfon** [comment]
Hey @mtdenton please see the above comment from Victoria on this ticket. Any issues let me know!
