### ISSUE TITLE
[PNI] Fix font size of drop down menu

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#9666]
Follow up ticket from #9528

The drop down nav font-size is .875rem which equals to 14px I think (is the base rem 16px?). This should be updated to match the rest of the category nav font size which is 16px. Right now there is a slight difference between the two which looks a little odd.

![Screenshot 2022-11-10 at 9.53.44 AM.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/b4c005d2-2d4b-4cc8-9589-967b5421a275) 

## Acceptance criteria:

- [ ] The menu item font size is 1 rem
- [ ] Design team have been updated we've done the changes so that they can reflect it on their designs

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-310)

**Comment by mmmavis** [comment]
@beccaklam I will pick up the dev work and update category nav link font size to 1rem/16px. I'm wondering what line height should they be? And if the links in the dropdown should have the same line height.

**Comment by simont-cr** [comment]
@mmmavis Do you think that we could still be able to apply this update or is no longer relevant with the current state of the site and design?

**Comment by mmmavis** [comment]
This is still valid. I can file a PR to fix this today.

**Comment by simont-cr** [comment]
If it's not going to take you too long to PR this, then that would be amazing, thank you!

**Comment by mmmavis** [comment]
@kristinashu Would [this Figma file](https://www.figma.com/file/4QFUwtwPN88j74no526S3y/Privacy-Not-Included-Master-File?type=design&node-id=1%3A15&mode=dev) be the place to refer to PNI design?

**Comment by kristinashu** [comment]
@mmmavis yes, that looks like the right file. To clarify, is the ask for this ticket is to update the "More Categories" text and drop down text in it from 14 to 15px so it matches the other nav items?

**Comment by mmmavis** [comment]
> To clarify, is the ask for this ticket is to update the "More Categories" text and drop down text in it from 14 to 15px so it matches the other nav items?

Yup!
