### ISSUE TITLE
[PNI QA] Editorial section shown for too long before hiding for search results (all browsers)

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#9695]
When you go to search for something from a page other than the home page (i.e. about page or article page), after you enter your search query the editorial section of the homepage shows for quite a while before being hidden. Is there a way for the search results appear more seamlessly?

https://images.zenhubusercontent.com/76596293/21fc4cdf-c3bb-482e-ba42-63f51fb24960/screen_recording_2022_11_14_at_1_13_03_pm.mov

**Comment by mtdenton** [comment]
related to #9709

**Comment by cdanfon** [comment]
Once #9709 has been completed we can revisit this one and see if it is still a problem
