### ISSUE TITLE
[PNI] Make Typeform a lightbox

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#9724]
Follow up ticket to #9722

Goal: Make the "Submit a product" typeform link a light box so people don't have to leave our site to submit a product review recommendation. 

Tyler found information on implementation [here](https://www.typeform.com/help/a/embed-your-typeform-360029249212/#h_01FKFTT9N3YHW4C6VEWT7R9C48) under "Popup". 

`<button data-tf-popup="oWfci8Ee" data-tf-iframe-props="title=PNI Product Submission" data-tf-medium="snippet" style="all:unset;font-family:Helvetica,Arial,sans-serif;display:inline-block;max-width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;background-color:#0445AF;color:#FFFFFF;font-size:20px;border-radius:25px;padding:0 33px;font-weight:bold;height:50px;cursor:pointer;line-height:50px;text-align:center;margin:0;text-decoration:none;">Submit a product<script src="//embed.typeform.com/next/embed.js"></script>`

**Acceptance Crtieria:**
- [ ] As a user I am able to fill out the "Submit a product" typeform on the same page/tab I found the link so that I don't have to navigate to a new page/tab.
- [ ] CSP is updated so that the form works both in staging and production

**Comment by cdanfon** [comment]
The design team would need to create the form in Typeform before the engineering team can implement it. @beccaklam can you provide the embed code please?

**Comment by beccaklam** [comment]
So I think this is it:
<button data-tf-popup="oWfci8Ee" data-tf-iframe-props="title=PNI Product Submission" data-tf-medium="snippet" style="all:unset;font-family:Helvetica,Arial,sans-serif;display:inline-block;max-width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;background-color:#0445AF;color:#FFFFFF;font-size:20px;border-radius:25px;padding:0 33px;font-weight:bold;height:50px;cursor:pointer;line-height:50px;text-align:center;margin:0;text-decoration:none;">Launch me</button><script src="//embed.typeform.com/next/embed.js"></script>

If not, the developer working on this can go to this link: https://admin.typeform.com/form/oWfci8Ee/share#/ and there are different embed options and ways to generate the code.

**Comment by cdanfon** [comment]
<buttondata-tf-popup="oWfci8Ee" data-tf-iframe-props="title=PNI Product Submission" data-tf-medium="snippet" style="all:unset;font-family:Helvetica,Arial,sans-serif;display:inline-block;max-width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;background-color:#0445AF;color:#FFFFFF;font-size:20px;border-radius:25px;padding:0 33px;font-weight:bold;height:50px;cursor:pointer;line-height:50px;text-align:center;margin:0;text-decoration:none;">Launch me<script src="//embed.typeform.com/next/embed.js"></script>

**Comment by kristinashu** [comment]
Closing this since we will most likely eventually update this to Form Assembly.
