### ISSUE TITLE
[Epic] Responsible Computing 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#9752]
After an initial meeting with the stakeholder Joycelyn, I outlined [these options](https://docs.google.com/presentation/d/1KubVG6xo7YNMntah75x9JwfCgdbHlGVeOlFLAhGwkVY/edit#slide=id.p). She is happy to use our existing CMS capabilities to create the Program hHub and then to make a copy the Research Hub for the Library (aka Playbook Curriculum). 

### Preliminary Timeline
- Project kick-off  in January  with stakeholders (Joycelyn, Alex, Crystal) and design/dev (Chris, Kristina, @mtdenton , @tbrlpld , a designer)
- Soft-launch the Program Hub by March
- Soft-launch the "Library" by June
- Promote the pages it in the Summer and Fall

### Proposed Todos for the Program Hub
- Project kick-off with stakeholders in Jan
- Design to write a Design brief
- Design to work with stakeholders on gathering copy
- Design to work with stakeholders to create pages in CMS
- Design to help with page IA and determine the best CMS blocks to use
- Design to create necessary graphics
- Design/dev/stakeholder to determine if any new blocks are needed (e.g. embedding a social feed)

### Initial Proposed Todos for the Library 
_(update this list after project kick-off)_
- The same project kick-off with stakeholders in Jan
- Design to write a Design brief
- Design to create Figma case study template deck
- Design to work with stakeholders to get a good sense of the different types of content
- Design/dev/stakeholders to determine nomenclature/taxonomies (name of library, topics, regions, etc)  
- Design/dev/stakeholders to determine types of sub-pages (Articles, Publications, but possibly other existing page types)
- Design to prototype the Library and stakeholders to circulate for feedback and buyin (test)
- Devs to build
- Design to create necessary graphics
- Design to work with stakeholders to create pages in CMS

**Comment by tbrlpld** [comment]
Been thinking about this a little now. If the second instance of the "Hub" can use the same set of taxonomy types, I think the "medium dev effort" is fair. Taxonomy type here means "region" and "topic". The taxonomy values (e.g. for the taxonomy type "region, a value could be "North America") that are relevant in each hub / library can be determined from the actual content. 

If however we want to use completely different taxonomy types on the different hubs, then the effort would be larger, because of the added flexibility.

**Comment by kristinashu** [comment]
@beccaklam now that the design side of this work is almost done and a dev Epic has been made https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10339, is this still useful or can it be closed?

**Comment by kristinashu** [comment]
Done https://foundation.mozilla.org/en/responsible-computing-challenge-playbook/! Content entry is underway.
