### ISSUE TITLE
[PNI] Show editorial content below product grid on homepage

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#9758]
Original design ticket: #9614
[Figma File](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=5289%3A99562&t=hQFivFXMHL7fbSR2-1)

Context: We are adding back in the editorial content that was hidden during the launch of PNI. The content was originally hidden as a quick fix to move the product reviews up on the home page. We want to add the content back in because we still want to feature the CTA call out box, Ask Jen section, and more editorial content. We are moving this section to the bottom of the page and will continue to monitor how these sections perform.

**Acceptance Criteria:**
- [ ] As an user I see that the product grid is truncated to 26 products
- [ ] As an user I see that I can click a "Load More Products" button which would extend the product grid and reveal 28 more product reviews each time I press the button. The "Load More Products" button remains until all products are shown
- [ ] As an user I see the editorial content below remains accessible and visible to me at all times on the homepage
- [ ] As an user I can see the "Ask Jen", "Popular", "News You Can Use" and CTA call out card at the bottom of the page as it is displayed in the figma file
- [ ] As a user, I am taken to the top of the list when changing categories

**Design**
![Homepage Update 8](https://user-images.githubusercontent.com/20977376/204884010-47b0305f-a46a-4afa-9a24-aa87777bf01f.jpg)

**Comment by tbrlpld** [comment]
@beccaklam What is the intended behaviour when clicking on the "load more reviews" button? Should the existing grid be extended or am I redirected to a different page? 

If the grid is extended: does the editorial content remain visible?

**Comment by beccaklam** [comment]
@tbrlpld The grid will be extended and the editorial content will remain visible. Do you foresee problems with that design?

**Comment by tbrlpld** [comment]
@beccaklam No, no problems. We just to be explicit in the AC what the expectations are.

**Comment by mtdenton** [comment]
Removing this from the current sprint

**Comment by fessehaye** [comment]
Progress: Of ticket is on branch `9758-pni`

**Comment by mmmavis** [comment]
I wasn't around when the editorial content work was taken place. From what I remember, the section was included in the page but at some point we decided to take it off. If we no longer need the editorial content section, it would be good if we close all the related GitHub tickets and file a new ticket to remove the relevant code.

/cc @kristinashu @simont-cr
