### ISSUE TITLE
BE - Make the text and link on the Donate Banner into editable fields

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#9823]
There's a need for the donate banner that appears at the very top of the page to have editable fields in the Wagtail dashboard.

![donatebanner](https://user-images.githubusercontent.com/41487159/206560876-7f7ff046-c727-4a39-b1bb-0f419558703a.jpg)

1. Title
2. Subtitle
3. CTA Text Line 1
4. CTA Text Line 2
5. CTA Button Text
6. CTA Link (didn't label that above but part of 5)

Ideally, each has a character limit that keeps in mind the various sizes of how this banner is displayed. Front-end functionality should stay exactly the same.

Dev Tasks & Acceptance Criteria:
As a CMS user, I want to be able to update the copy/text/imagery of the donate banner without need for dev intervention.

**Comment by kristinashu** [comment]
@mtdenton given that FRU will most likely be used for banners in the future, is it worth investing in this block?

**Comment by mtdenton** [comment]
I haven't seen top-of-page banner functionality like this for FRU, is that a thing?

**Comment by kristinashu** [comment]
idk but that's the sense I got from Chris?

**Comment by mtdenton** [comment]
Blocking this until clarification

**Comment by cdanfon** [comment]
Next steps: @victoriachan to refine this ticket and provide dev approach (including where in the CMS this would be editable)

**Comment by jhonatan-lopes** [comment]
The banner needs to be activated via settings. It's a feature flag under Settings -> Feature flags.

**Comment by kristinashu** [comment]
If you need the Figma file for the mockup shown above, it's here https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/Fundraising?type=design&node-id=115%3A271&mode=design&t=XKsMiqQrMHed3ywa-1

**Comment by victoriachan** [comment]
A new `DonateBanner` model can be added either as a _snippet_ or as _site settings_. Here are the considerations for each proposal:

### Adding as a Snippet:

- Pros:
	- Supports Revision / history
	- Can have multiple banners, and not to have delete previous banners, so it is easy to switch between them. This can be managed by having a 'is default' boolean flag which will have a custom code to ensure only one banner has this flag enabled.
	- Can preview banner before making it live (using `PreviewableMixin`).
- Cons:
	- Can be confusing / hacky to know which is the banner item that will be displayed on the site. This isn't the regular behavior / use case for Snippets.
	- Admin page for this buried among other site snippets such as News, Areas of focus, CTA, etc. (You could customise the admin view and location in Wagtail 5, but not in 4.1.6).
	- The 'hack' to impose only one default banner adds complications to the backend code.

### Adding as site setting:

- Pros:
	- Behave similarly to the existing feature flag, both live in site settings section.
	- Can only have one banner defined, clear about what will be displayed.
	- Simple and straightforward to implement and use.
- Cons:
	- No revision history
	- If need to temporarily put up a new banner, the old banner will be lost. Can't easily switch between versions.
	- Cannot preview banner, and can only see it by making it live, or create an identical one on staging for preview.
	
@jhonatan-lopes will bring this up at standup later for discussion.

**Comment by Gbaldassano** [comment]
@victoriachan @jhonatan-lopes @mtdenton Regarding implementation/to answer the question above, is there a solution (snippet or as site setting) that is more user friendly for non-developers? The ability to preview as a snippet seems like good benefit.

In addition to making the text/link editable, we would also like the make the background image of the appeal editable. @victoriachan would it be helpful to create that request as a separate ticket or include it here?

Lastly, I want to call out that the goal of this is to allow stakeholders to update the appeal without need for dev intervention.  I've updated the acceptance criteria to reflect this but are there any other considerations we'll need to keep in mind to do so?

cc: @kristinashu

**Comment by kristinashu** [comment]
Two points that came up during huddle were:
- Text must be localizable
- Image file size should be compressed but not so much so that the image quality looks poor


Also, is this ticket for both front and back end? For front end, I would love input from the stakeholder on if they think the dark background or light background will suite their creative direction best:
![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/7a4ce6f1-6779-4d16-b0a7-76469fca4d25)
![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/35263e49-f3f0-436f-a4d6-689ba2bba79b)

**Comment by jhonatan-lopes** [comment]
Hi @victoriachan, after giving this some thought, I think the best course of action would be to have a snippet to hold the banners (as we discussed) and then a setting to define which banner should be active (and if there should be an active banner or not).

I believe we can use a [Foreign Key to the snippet in the setting](https://docs.wagtail.org/en/stable/reference/contrib/settings.html#edit-handlers). Something like:

```python
@register_setting
class DonationBanner(BaseGenericSetting):
    select_related = ["donation_banner_snippet"]

    donation_banner_snippet = models.ForeignKey(
        'path.to.donation.banner.snippet', null=True, on_delete=models.SET_NULL, related_name='+'
    )

    panels = [
        FieldPanel('donation_banner_snippet'),
    ]
```

Being a nullable-field makes it so that if it's not selected means it's not active. We can make that more clear in the `help_text`.

The only pain point I can see with the code above is:

1. We need to display only English versions of the snippet to editors so that they choose the "original" (untranslated) banner snippet
2. When rendering the template, we need to display the localized version.

**Comment by victoriachan** [comment]
@jhonatan-lopes Sounds good!

**Comment by jhonatan-lopes** [comment]
Hey @victoriachan, let's nuke the backend code for the current banner settings but keep the styles and the template, as they will be reused once we implement the FE ticket.

**Comment by jhonatan-lopes** [comment]
Front-end ticket: #11180

**Comment by victoriachan** [comment]
@jhonatan-lopes I'm afraid I spoke too soon and this isn't ready yet.

I am still having issues with limiting the list of snippets in the admin snippet chooser to English ones. I found [this previous issue](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/9187) and have implemented a similar fix with `limit_choices_to`. 

Unfortunately though that does validate the form to ensure only English banners can be selected, it does not remove/hide the illegal choices from the chooser, and hence can still be confusing for Editors. 

Your suggestion of using `base_queryset` didn't quite work as it is for querying AbstractSetting type objects, and does not affect the list of snippets in the chooser.

Another issue I'm having is the weird caching regarding the background image. It doesn't seem to show up on the template, but if I hardcode it on the template instead, e.g. `tw-bg-[url(/media/images/9039_10710192_IMG_24_0000.2e16d0ba.fill-1305x720.jpg)]`, it then shows up. And if I then revert to the way it was before, i.e. `tw-bg-[url("|add:background_image.url|add:")]`, it still continues to show up. 

I'm marking the [PR](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11195) as draft for now. 

Will continue on Monday.

**Comment by victoriachan** [comment]
CI has passed, and I've fixed the issue with Locale. Just going to add some tests.

**Comment by cdanfon** [comment]
Hey @victoriachan can you update the ticket at the end of the day as a wrap-up of the work on it? Thanks

**Comment by victoriachan** [comment]
@jhonatan-lopes Sorry for the delay. The PR is ready for review: https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11195

**Comment by victoriachan** [comment]
@jhonatan-lopes Thanks for the review. I've made the code review changes now. Please review again: https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11195

**Comment by Gbaldassano** [comment]
@mtdenton @jhonatan-lopes Just curious about the linking functionality here since I know it's come up before - are there any restrictions on what we can link to? Can we make sure that all works as expected In the event that the team wants to link to an external URL vs a modal just in case?

**Comment by jhonatan-lopes** [comment]
@Gbaldassano The CTA link is defined now as either a valid URL (starting with `http://` or `https://`) or a valid query string (such as `?form=donate`). What do you mean by a modal?

**Comment by Gbaldassano** [comment]
@jhonatan-lopes great! By modal I just meant the donate form pop up - sounds like it will work for everything, thank you!

**Comment by victoriachan** [comment]
@Gbaldassano I followed the way that the validation works for the link target url field in Buyers Guide Call To Action and the donate url field in the Donation Modal snippet. It should work the same way.
