### ISSUE TITLE
[PNI] Tabbing through PNI Product Review page breaks the tab group

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#9839]
### Describe the bug
Tabbing through PNI Product Review page breaks the tab group

### To Reproduce
1. Go to PNI Product Review page. eg., https://foundation.mozilla.org/en/privacynotincluded/euki/
2. Use the tab key to tab through the page
3. See content being shifted improperly from the tab group and below

### Expected behavior
- [x] Heading of each tab (privacy, security, AI) is tabbable
- [x] Link in a hidden tab should not be tabbable

### Screenshots

[If applicable, add screenshots to help explain your problem.](https://user-images.githubusercontent.com/2896608/207453123-3d8c2704-9764-43df-a401-4cdf8a867514.mov)

**Comment by danielfmiranda** [comment]
Looks good to me! Thanks Mavis :+1:

**Comment by mmmavis** [comment]
Done!
