### ISSUE TITLE
[PNI] Washed out images on homepage

### ISSUE THREAD

**Issue by tbrlpld** [MozillaFoundation/foundation.mozilla.org#9863]
## Description

Some of the design images on the PNI homepage look washed out.

We are currently not showing these, but we will once #9758 is implemented. 

We should use SVG where possible and high-res images when using bitmap images. 

## Acceptance criteria

- [ ] When visiting the PNI homepage with a high resolution device, all styling images appear sharp and crisp

## Screenshots

The screenshots where taken at 100% resolution but are displayed larger here. 

![Screen Shot 2022-12-16 at 14.36.11.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/c132111d-ada1-4200-aefe-79b5ce1fd4f0)
![Screen Shot 2022-12-16 at 14.36.15.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/7ec63951-7165-497c-8516-2c196f7098fa)

**Comment by cdanfon** [comment]
@nancyt1 Hey could you please provide with SVG or high res versions of the images in the homepage? Thanks!

**Comment by nancyt1** [comment]
I [exported](https://drive.google.com/drive/u/0/folders/1ZQ9dWN2zqZ7hvs_zb0uAmKSHc-LOAz5N) both PNG and SVG, let me know if these still don't work.

**Comment by tbrlpld** [comment]
Actually just realizing there is currently no way to QA this ticket 🤔

**Comment by cdanfon** [comment]
Hey @tbrlpld thanks for pointing this out, could we add these sections as 'draft' on the staging version of the site to see if they've improved?

**Comment by tbrlpld** [comment]
@cdanfon These sections are currently not rendered. The template code is commented out. The plan is to reactive the sections with #9758. I have marked this ticket as "blocked by". I have pulled #10081 into the sprint because that came up yesterday instead and pushed this ticket back to the backlog.

**Comment by simont-cr** [comment]
Closed per 2024 ticket purge.
