### ISSUE TITLE
[PNI] Expand dropdown box and search bar to fit length of text

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#9870]
Follow up from ticket #9640 where translated text is getting cut off or doesn't visually fit into container
[Figma Designs](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=5609%3A102175&t=UCOqvUJixeY29Pqv-1)

![image](https://user-images.githubusercontent.com/74557207/208771372-28e47387-d51f-4cc7-86f1-82434c595666.png)

**Acceptance Criteria:**
- [x] search bar container should expand to fit text with a max width of 250px
- [x] On mobile, dropdown text should not run off screen but should stack underneath "Sort by" label if too long. Text should be allowed to wrap too.
- [x] Dropdown text should wrap to next line if it doesn't fit in the width
- [x] Arrow icon should not overlap with text in any screen size
- [x] Dropdown should match spacing specs in figma file

**Comment by fessehaye** [comment]
@nancyt1 try checking this on staging with different locales

**Comment by nancyt1** [comment]
It would be great if we could adjust the width of the dropdown to fit the text so there aren't any large gaps like this.

<img width="542" alt="Screen Shot 2023-01-26 at 2 27 43 PM" src="https://user-images.githubusercontent.com/74557207/214970445-ce9e2bd8-af7c-43d8-813d-9e79dde2798d.png">

**Comment by kristinashu** [comment]
@fessehaye is this on staging https://foundation.mofostaging.net/de/privacynotincluded/, I don't see the changes?

**Comment by nancyt1** [comment]
Updated the AC for this ticket and mocked up what the dropdown would look like with wrapped text in [Figma](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Archive-2022?node-id=5985%3A106189&t=EUWxYDUxIGrHywvn-1).

**Comment by fessehaye** [comment]
`DE` example: 

![image](https://user-images.githubusercontent.com/2374073/222837909-8820f2df-6d13-4eca-b55b-241de5013953.png)

**Comment by fessehaye** [comment]
@nancyt1 can you review this on staging to see if this is good to go?

**Comment by nancyt1** [comment]
Opening the dropdown covers up the label which results in an awkward UX, going to create another ticket for this issue! 

![Screen Shot 2023-03-08 at 12 26 02 PM](https://user-images.githubusercontent.com/74557207/223801907-e9bdda30-3387-4d9b-b8b2-88fe80b6df50.png)

**Comment by mmmavis** [comment]
Hi @nancyt1 this is ready for QA on staging: https://foundation.mofostaging.net/en/privacynotincluded/

**Comment by nancyt1** [comment]
@mmmavis Looks good and ACs have been met!
I think this has been an existing issue but I'll open up another ticket for this issue where dropdown isn't aligned to the category tags. 

<img width="646" alt="SCR-20230321-ndgs" src="https://user-images.githubusercontent.com/74557207/226724656-dbd82ece-b111-412d-82e7-d06cd898aec9.png">

**Comment by mmmavis** [comment]
@nancyt1 Awesome! Thanks for the QAing this!
