### ISSUE TITLE
Make a list of images to update in the code base for retina screens

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#9918]
Related Issues: #9901 

As mentioned in ticket #9901, there are some places on the site where rendered images appear blurry or "washed out" even if the image uploaded is of a high resolution. 

We should probably take a look at the code base for any images that need to be updated, and update them using a similar solution like the one used in #9765 

### Acceptance Criteria:
Dev:

* [ ] Create a list of image so update in the code base for retina screens.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-319)

**Comment by kristinashu** [comment]
Based on Tibor's comment https://github.com/mozilla/foundation.mozilla.org/issues/9901#issuecomment-1399104433, I've turned this into an epic.

Thank you for the [list above](https://github.com/mozilla/foundation.mozilla.org/issues/9918#issuecomment-1385832911). I'm curious what the code says but here are a few places where I feel I'm seeing this issue:


## Cards on What You Can Do page
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/1068783/214089641-2a45b321-e30f-49d2-9ae6-cc6b1e99ea17.png">


## Block with Aside block
<img width="775" alt="image" src="https://user-images.githubusercontent.com/1068783/214092119-226b680b-5daa-40f0-ab9f-dab955a574e7.png">


## Take Action section on our homepage
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/1068783/214089160-71603854-5981-47af-9e7c-388d519696ff.png">

## Listing block
<img width="909" alt="image" src="https://user-images.githubusercontent.com/1068783/214155137-fba243ff-cbe3-4163-9e1a-aa4fa2bd8fe9.png">
