### ISSUE TITLE
Optimize PNGs

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#9930]
Many PNGs in the codebase can be optimized through the `inv npm "run optimize:png"` command. Let's do that. We should also pay attention to Percy flags in the PR in case any image quality gets messed up during the optimization process. 

# Acceptance Criteria

- [ ] Run `inv npm "run optimize:png"` and commit the optimized png files to repo
- [ ] Update PR template to include a checkbox `[ ] images/css have been optimize`

**Comment by mtdenton** [comment]
Two questions here:

- How do we QA this?
- Should we be doing this task at a regular interval?

**Comment by mmmavis** [comment]
> How do we QA this?

The npm package ([optipng-bin](https://www.npmjs.com/package/optipng-bin)) we use for optimizing png is pretty popular and should be fairly reliable. I don't think there's really a need to QA the processed image. I mentioned Percy just to be extra safe.

> Should we be doing this task at a regular interval?

Haha you meant an optimization duty? I'm thinking we can update the PR ticket template to include a checkbox `[ ] images/css have been optimized` so that devs get into the habit of running the optimization tasks before they submit a PR.  In addition to png, we also have a few other tasks set up for [optimizing css, jpg, and svg](https://github.com/mozilla/foundation.mozilla.org/blob/main/package.json#L37-L44). It seems like some of them are broken and need fixing, though.

**Comment by mmmavis** [comment]
Ticket description updated with AC.

**Comment by mtdenton** [comment]
Purging this to maybe reopen later in another form.
