### ISSUE TITLE
Update FundraiseUp Script to disable "live mode" in staging

### ISSUE THREAD

**Issue by danielfmiranda** [MozillaFoundation/foundation.mozilla.org#9932]
### Details

At the moment, the FundraiseUp modal found at https://foundation.mofostaging.net/en/?form=donate is being rendered in "Live Mode".

This means that when trying to make a donation with a test credit card, the following error gets returned to the user:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/18314510/211726232-0be2a4c9-e350-4cab-b0da-0ba4c7a67beb.png">

We can render the modal in "test mode" by adding the following JS globally:

```javascript
<script>
window.fundraiseup_livemode = false;
</script>
```

We can achieve this by adding a new environment variable `FRU_ENABLE_LIVE_MODE`, which will tell the codebase whether or not to include the JS snippet above for both production and staging.

### Acceptance Criteria

**Dev Criteria:**
- [ ] As a dev, I can edit an environment variable `FRU_ENABLE_LIVE_MODE` in heroku, which will tell the site whether or not to render the FundraiseUp modal in "Live Mode" or "Test Mode".

**User Criteria:**
- [ ] As a user, when visiting https://foundation.mofostaging.net/en/?form=donate, the FundraiseUp modal is rendered in "test mode" and allows me to use a testing credit card.

**Comment by mtdenton** [comment]
We can do this through query parameters turns out, closing this
