### ISSUE TITLE
FRU | Bug in "Donate monthly" prompt button (after a one single donation has been completed)

### ISSUE THREAD

**Issue by cdanfon** [MozillaFoundation/foundation.mozilla.org#9938]
### Describe the bug
When a user makes a single donation, there is a CTA that prompts them to make a monthly donation (1st screenshot). This 'Yes, I'll give monthly' CTA takes the user to the same confirmation page as if the user would've clicked on "Not at this time' (2nd screenshot).

### Steps to reproduce the behavior:
1. Go to
'https://foundation.mofostaging.net/en/?form=donate&fundraiseupLivemode=no' (Prod) 'https://foundation.mofostaging.net/en/?form=donate&fundraiseupLivemode=no' (Staging)
2. Click on 'Donate' (give once option)
3. Fill out details using a test card
4. Skip employer contribution step
5. Click on 'Yes, I'll give monthly'
6. See error> Donation confirmation page appears instead of taking the user to the start of the monthly donation funnel. 

### Expected behavior
When a user clicks on 'Yes, I'll give monthly' is taken to the start of the Monthly donation funnel.

### Screenshots

![Screenshot 2023-01-11 at 14 56 15](https://user-images.githubusercontent.com/102978346/212058753-ec79caea-3a80-4be8-b07f-9ebbacafcfa6.png)

![Screenshot 2023-01-11 at 14 58 41](https://user-images.githubusercontent.com/102978346/212058752-13321731-1f5e-4cf9-9ef8-cdec5419f844.png)

**Comment by cdanfon** [comment]
Hey @mtdenton another bug related to FRU

**Comment by mtdenton** [comment]
Are we sure that this isn't actually the "funnel"? As in it doesn't just take the current user and CC info and charges the original one-time donation as well as signs the user up for monthly donations? Seems like "Would you like to become a monthly supporter starting 11 Feb?" alludes to that.

**Comment by cdanfon** [comment]
Oh right! I see what you mean. If that's the case the confirmation screen should probs indicate that the donor will be charged £12 a month moving forward?

**Comment by kristinashu** [comment]
Thank you for QAing this Claudia! For sure the thank you screen after agreeing to a monthly donation of £12/month should say that instead of the original £64 one time donation.

**Comment by mtdenton** [comment]
My guess is that we would have to submit this as feedback to the Fundraise Up team since we have no control over this iframed modal.

**Comment by cdanfon** [comment]
Fair enough @mtdenton. Could you submit this as feedback from the Moz FRU account?

**Comment by mtdenton** [comment]
Heading this up to talk to FRU.

Additional note, @mmmavis brought up that there's a push to audit our linking to social media platforms and we need to investigate what we can control in this modal.
