### ISSUE TITLE
Links aren't visible in heading styles

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#9966]
Staff use heading styles to highlight sections of text. This does not follow best practices and becomes an issue when they add a link to the text because there is nothing to signify that it is a link.

Screen cap from prod for [a blog post](https://foundation.mozilla.org/en/blog/what-would-movement-building-lose-if-it-lost-twitter/) with with heading text used to highlight key info:
![](https://user-images.githubusercontent.com/1068783/212761270-abb35a39-8d58-4f74-81d2-6f7438b8ecba.png)

Screen cap of the link that is only visible on hover:
![](https://user-images.githubusercontent.com/1068783/212761311-fa2ae518-3b1e-401b-8730-3cae30b48a75.png)

We have been reluctant to make links in heading blue or underlined because it would mean all card titles would be blue or underlined which might start to look overwhelming. For this blog example, perhaps is more about creating a new paragraph style that staff can use to highlight key text. 

### Todo
* Consider different possible solutions and mock them up
* 
* Consider both desktop and mobile versions
* Get feedback from design and dev
* Get feedback from Audrey as she raised this issue recently and uses the cms a lot
* Work with devs to open implementation tickets 
* Update all Figma and style guide documentation

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-322)

**Comment by kristinashu** [comment]
Designers chatted about this during our jam time, here are our notes about next steps:
- Add [documentation](https://foundation.mozilla.org/en/docs/design/websites/accessibility-guidelines/) for staff about when to use paragraph vs headings (particularly around a11y with screen readers, mobile, etc. and seo)
- Add a Lead paragraph style for when body large just doesn’t stand out enough
- Ask devs about best practices around having a different link treatment depending if the heading is used in a card or in body text
- Overall, we prefer the use of blue to indicate a link and underline for the hover state

**Comment by data-sync-user** [comment]
➤ Nancy Tran commented:

Decided on using blue as a compromise for link colors in heading. Created a new dev ticket for implementation!
