### ISSUE TITLE
URL Change - Responsible Computer Science -> Responsible Computing

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#9988]
Steve Azeka has requested that we change the URL for the Responsible Computing Challenge content to reflect the name change from "Responsible Computer Science Challenge". For instance:

https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge/

should now be:

https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computing-challenge/

We also need to ensure that all sub content reflects this change in URL structure.

We should also ensure that any links that contain `/responsible-computer-science-challenge/` are redirected to their equivalent `/responsible-computing-challenge/` link

Per @kristinashu, this work could be accelerated by the work to be done in #9961 , so I'm adding that as a dependency. 

### Dev Tasks:
- [ ] Change the subfolder of `/responsible-computer-science-challenge/` to `/responsible-computing-challenge/`
- [ ] Create redirects that point users from the old URL structure to their equivalent new URL structure

### Acceptance Criteria
 - [ ] All Responsible Computing Challenge content is now under the `/responsible-computing-challenge/` subfolder in the URL
 - [ ] All links containing `/responsible-computer-science-challenge/` should now redirect to their `/responsible-computing-challenge` equivalent

**Comment by tbrlpld** [comment]
We can set up redirects in Wagtail. With the version we are running this should happen automatically when pages are moved to slugs changed (this is what should happen here). There is a bug field regarding the automatic redirects not working. This is being worked on. 

We don't need any dev work to fulfill the request from Steve. Redirects from a given URL can be redirected to a selected page already here: https://foundation.mozilla.org/cms/redirects/ 

Once the automatic redirect creation fix is in, the redirects would also be created for all child pages of the page that is moved / has the slug changed.

**Comment by kristinashu** [comment]
Note: we will most likely move towards https://foundation.mozilla.org/responsible-computing-challenge/. @beccaklam will check with stakeholders and then create the new and improved pages at the new url. Once they are made then we can do the redirects in the CMS.

**Comment by danielfmiranda** [comment]
After reaching out to Steve Azeka, a go-live date is still being decided for this change. Moving this ticket to my sprint backlog in case we are asked to make the change this sprint, and if not I will update this ticket accordingly. 

Thanks!

**Comment by danielfmiranda** [comment]
Hi Everyone! After reaching back out to the stakeholder, they let me know that they were still looking for a "go-live" date, and I do not believe that they will announce it before the end of this sprint. 

Going to move this ticket back into the backlog for now, and will let the team know when a go live date has been confirmed.

**Comment by mtdenton** [comment]
Still delaying this until we get the word, not to be included on 7/10 sprint

**Comment by mtdenton** [comment]
Still waiting for input from Steve or Joycelin

**Comment by kristinashu** [comment]
It's been almost a year later but the team is ready for the redirects! I will do these via https://foundation.mozilla.org/cms/redirects/. I'll do no language and with /en but won't bother with other languages. 

Without language:

- [ ] https://foundation.mozilla.org/what-we-fund/awards/responsible-computer-science-challenge/ to https://foundation.mozilla.org/responsible-computing-challenge/
- [ ] https://foundation.mozilla.org/what-we-fund/awards/responsible-computer-science-challenge/application/ to https://foundation.mozilla.org/en/responsible-computing-challenge/grant-opportunities/
- [ ]  https://foundation.mozilla.org/what-we-fund/awards/responsible-computer-science-challenge/resources/ to https://foundation.mozilla.org/responsible-computing-challenge/resources/
- [ ] https://foundation.mozilla.org/what-we-fund/awards/responsible-computer-science-challenge/advisors/ to https://foundation.mozilla.org/responsible-computing-challenge/advisors-judges/#advisors
- [ ] https://foundation.mozilla.org/what-we-fund/awards/responsible-computer-science-challenge/judges/ to https://foundation.mozilla.org/responsible-computing-challenge/advisors-judges/#judges
- [ ] https://foundation.mozilla.org/what-we-fund/awards/responsible-computer-science-challenge/industry-support/ to https://foundation.mozilla.org/responsible-computing-challenge/industry-support/
- [ ] https://foundation.mozilla.org/what-we-fund/awards/responsible-computer-science-challenge/winners/ to https://foundation.mozilla.org/responsible-computing-challenge/awardees/

With /en:
- [ ] https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge/ to https://foundation.mozilla.org/responsible-computing-challenge/
- [ ] https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge/application/ to https://foundation.mozilla.org/responsible-computing-challenge/grant-opportunities/
- [ ]  https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge/resources/ to https://foundation.mozilla.org/responsible-computing-challenge/resources/
- [ ] https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge/advisors/ to https://foundation.mozilla.org/responsible-computing-challenge/advisors-judges/#advisors
- [ ] https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge/judges/ to https://foundation.mozilla.org/responsible-computing-challenge/advisors-judges/#judges
- [ ] https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge/industry-support/ to https://foundation.mozilla.org/responsible-computing-challenge/industry-support/
- [ ] https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge/winners/ to https://foundation.mozilla.org/responsible-computing-challenge/awardees/

@jhonatan-lopes @mtdenton I'll do this later this week but please let me know if there's an better/easier way to do this!

**Comment by jhonatan-lopes** [comment]
Hey @kristinashu, they only simpler way that I can see is to upload a csv file with the redirects so that you don't have to do them manually one-by-one:

![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/61277874/fd6e3583-fd41-47dc-8723-5a9a7943a90f)

You can export them first to get the template that is used and alter to fit the data that you have.

**Comment by kristinashu** [comment]
Oooh thank you, importing will be much easier. I've made[ this csv fil](https://drive.google.com/file/d/1ZGuVxN-SyAeZTwmvHPUSyuzgMTQmA76A/view?pli=1)e (based on [this spreadsheet](https://docs.google.com/spreadsheets/d/1dVBSAZAadpaokVsgLjLhcBzfNYoZW4zXvkmDqSpyFUk/edit#gid=0)) and will imported after my meetings.

**Comment by kristinashu** [comment]
I've tried importing the csv file three times now and everytime I hit "Confirm" I then get a Server 500 error.

<img width="1883" alt="Screenshot 2023-12-15 at 10 04 58 AM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/c305a4aa-6f59-4d73-9347-febe5ec8eb76">
<img width="326" alt="Screenshot 2023-12-15 at 10 01 53 AM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/3f346b30-ca95-47a8-b850-0b99170eb5b2">

**Comment by kristinashu** [comment]
Done!
