### ISSUE TITLE
[MAIT report] Design assets for blog and slides

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#9990]
Ramy has expressed a desire to reach a broader audience beyond builders and academics with this report. Design will be following Marketing's lead in this work. From Audrey:
- Tracy will be turning the executive summary into a blog post
- Audrey is hoping to create some slides to put on LinkedIn which will aim to be accessible to a wider audience
- Audrey also mentioned considered adding a blurb like at the top of this [publication](https://foundation.mozilla.org/en/data-futures-lab/data-for-empowerment/)

**Goals:**
- [ ] Support the blog post with any design assets needed
- [ ] Support the slides with any design assets needed

**Comment by nancyt1** [comment]
Might not need to do much for this ticket, Ramy had an illustrator create graphics that can be used across marketing. Audrey asked to refine/review the google slides to export for Linkedin when it's final. But that's all I'm aware of.

**Comment by nancyt1** [comment]
- OG image has been made and already on key pages
- Gave Tracy the link to the drive so she has all assets needed for PR and blog post
- The slideshow for LinkedIn was dependant on Ramy finishing the deck she had but I haven't heard anything and Audrey said she would ping Ramy about it.
