### ISSUE TITLE
[RCC] User Research Part 2

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#9994]
To understand the needs of the audience a bit more, we will reach out to past alumni and contributors of the RCC program and see what were their pain points in using the previous websites and also have them usability test the new prototype.

- [x] Contact alumni
- [x] Write user interview and usability test guide
- [x] Perform interviews
- [x] Perform thematic analysis
- [x] Write research report

**Comment by kristinashu** [comment]
This needs to be broken up into smaller tickets. One small one will go into this sprint.

**Comment by beccaklam** [comment]
Found this article on how to do thematic analysis for qualitative research and found it helpful: https://www.nngroup.com/articles/thematic-analysis/

**Comment by beccaklam** [comment]
Report links:
[Interview Notes](https://docs.google.com/document/d/1rnJ6dOP8H1Hompyvrwj62igbpv-eyou_sCDHGYeLcEI/edit?usp=sharing)
[Thematic Google Sheet Analysis](https://docs.google.com/spreadsheets/d/1NE2gIz-pqq1YOf02-3iarHb9PYD8J1xM7xFHJ1ahVDc/edit#gid=0)
[Report](https://docs.google.com/document/d/1nVN_j-S5F2-EtLgN7zrIc9SDLmttjVAdmFT1nE9Hjkc/edit?usp=sharing)
